### ISSUE TITLE
深色模式下图标看不见

### ISSUE THREAD

**Issue by Jerry-1984** [hcfyapp/crx-selection-translate#1002]
浏览器深色模式下工具栏图标不会自动变色，所以看不清！
Firefox与Chrome都是一样的情况

**Comment by lmk123** [comment]
我猜你指的“工具栏”应该是截图翻译和网页翻译那一排按钮。

我的 Chrome 是深色模式，但是我是看得清的：

![image](https://user-images.githubusercontent.com/5035625/115696126-f2dd2a80-a394-11eb-8168-589227df38c7.png)

但是我猜你的情况可能不是我这种，为了能重现你的问题，需要你再提供更多信息，比如你浏览器的版本、划词翻译的版本、你的操作系统，最好附带截图

**Comment by GH01** [comment]
我想楼主是指 扩展按钮。

**Comment by Jerry-1984** [comment]
我指的是浏览器工具栏图标

**Comment by lmk123** [comment]
是我理解错了，抱歉

我的 Firefox 确实有这个问题，不过我的 Chrome 是正常的，我的 Chrome 即使是在深色模式下，工具栏也是白色背景

![image](https://user-images.githubusercontent.com/5035625/116808645-891b0880-ab6c-11eb-9f71-008c78a7f649.png)

**Comment by lmk123** [comment]
我会在未来给划词翻译加个浅色的图标，深色背景时就切换成浅色的。

**Comment by lmk123** [comment]
加个白色描边也不错

**Comment by Jerry-1984** [comment]
这个问题还不打算解决吗？
我Firefox用CSS反转不会自动变色的图标，但发现本扩展的图标居然无法反转！！

**Comment by fiona1477** [comment]
这个问题解决了吗？我现在用的是9.9.0是还没解决，当网页的背景色是深色的时候，划词想翻译单词/句子，翻译按钮的图标完全找不到，看了一圈设置也没看到能改的地方，现在又那么多网页想搞科技感用的深色背景。。。。比如去midjourney官网划词试试

**Comment by lmk123** [comment]
@fiona1477 

这个 issue 只是将浏览器地址栏里的划词翻译图标给改成深色模式了，在网页里的翻译按钮本身没有做过任何变动。如果在深色模式下你觉得翻译按钮不够明显，那么你只需要在划词翻译设置 - 外观 - 深色模式里选择【关】，然后翻译按钮就会是白色的了，如下图：

<img width="570" alt="截屏2023-06-07 16 31 07" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/8a19db92-eced-4118-ad52-c0c271acf26f">

**Comment by fiona1477** [comment]
我去试了一下，没有像你截图这样的效果哦。是以下效果：
1、外观-深色模式-开，整个插件是深色模式了，icon在深色背景稍微能看到，但糊糊的，但整个插件都是深色背景了我又不想这样。
2、外观-深色模式-关/跟随系统，在深色网页划句划段落时，依然很难找到icon，智能根据经验去大概位置上看，费劲。
求改进～
