### ISSUE TITLE
加一个新的选项：固定状态下点击空白处也能关闭窗口

### ISSUE THREAD

**Issue by DogeFlow** [hcfyapp/crx-selection-translate#1086]
设置—网页划词面板—是否固定，默认为：“是”，但无法改变！希望进入加入选项！

**Comment by lmk123** [comment]
这个“选项”其实就是翻译窗口左上角的图钉按钮，点击图钉就可以切换固定状态。

**Comment by DogeFlow** [comment]
您好，我想设置“图钉”状态，不想每次都点击图钉以取消固定。目前设置中无法进行这个设置 @lmk123

**Comment by lmk123** [comment]
点击图钉来取消固定状态，比我把这个选项加入到快捷选项中更便捷吧？因为快捷选项还需要点击齿轮图标展开。

你的使用场景是什么，需要在选项里切换固定状态吗？

**Comment by DogeFlow** [comment]
您好，我希望这个图钉的默认状态可以设置为不固定，这样我就不需要每次点击 x 来关闭对话框，可以点击网页任意位置来关闭对话框。如果默认固定的话，会遮挡网页内容，很不方便。

**Comment by DogeFlow** [comment]
![image](https://user-images.githubusercontent.com/34650487/124203973-8313ba80-db10-11eb-9e88-3ad0c6093e2f.png)
希望这里可以进行默认设置，当前无法选择 @lmk123

**Comment by lmk123** [comment]
我懂你的意思了，你是希望翻译窗口能显示在右侧，但又希望能点击任意空白处来关闭窗口。

这个功能划词翻译目前还不支持，这跟“是否固定”的选项没有关系。“是否固定”这个选项就是图钉图标。

也许我可以加一个新的设置项来满足你的需求

**Comment by lmk123** [comment]
我准备加个新选项，拖动窗口后不默认改为 pin 的状态，这样一来点击空白处就能关闭窗口了。这个选项预计在下个版本中加入，后续进展见 #815

**Comment by GH01** [comment]
我感觉这个选项还是有必要的：
▲在固定位置使用，感觉更沉浸。（自动定位 太欢腾，查段时还会出界/消失）
▲随处点击就关闭 则比 Esc键/点x 更方便。

适合喜欢固定位置的懒人。

**Comment by lmk123** [comment]
我就是觉得现在选项太多了 :joy: 但确实这也是一种使用方式，我先 reopen 吧

**Comment by lmk123** [comment]
v10.3.0 在【划词翻译设置】-【网页划词翻译】-【网页划词面板】里加了一个选项“为固定模式添加默认行为”，取消勾选后即可取消掉固定模式的以下两个行为：

- 划词后立刻显示结果
- 点击空白处无法关闭面板
