### ISSUE TITLE
给翻译服务增加一些通用选项：字符数限制、语种限制等

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1117]
## 为什么你觉得需要（改进）这个功能？
有的用户可能只希望在翻译单词时才让有道翻译显示结果，针对这一情况，可以增加一个选项“字符数少于 10 个才显示翻译结果”。

有的用户可能只希望让彩云小译在翻译日语时才显示结果，可以增加一个语种限制，只在翻译日语时才启用某种翻译服务。

**Comment by oodzchen** [comment]
首先，不应该所有的选中操作都触发翻译，比如用户设置的是【英语】->【中文(简体)】，那么当用户选择中文的时候就不必弹窗。

其次，设置的时候，源语言应该可以多选，例如【英语、日语、韩语】-> 【中文(简体)】这样。最好是添加用户自定义，让用户可以自己写正则表达式匹配，或者让用户自己输入Unicode字符范围也行。

**Comment by lmk123** [comment]
也就是说要做两个部分的检查：

1. 查询翻译结果前，先检查一遍划选的文本是否满足要求，不满足则不触发翻译。可设置项包含：语种、字符长度、是否包含空格（这一点是有用户反馈有的专业名词特别长，光靠字符长度不能区分是句子还是词组，所以要额外添加是否包含空格来判断）
2. 如果划选的文本满足第一点中的要求，再给每个翻译服务单独做判断，是否满足要求。可设置项同第一点。如果不满足，则不查询此翻译服务的结果，并提示用户文本不满足要求。

但是我觉得第一点可能没有必要，因为划词翻译支持辅助键和快捷键，如果不想弹出翻译按钮，那么只需要设置成不弹出翻译按钮、通过辅助键和快捷键的形式弹出翻译结果就可以了（见[使用技巧 - 不想总是弹出翻译按钮](https://hcfy.limingkai.cn/docs/guides/nobtn)）。

@oodzchen 你觉得呢？

**Comment by oodzchen** [comment]
> 也就是说要做两个部分的检查：
> 
> 1. 查询翻译结果前，先检查一遍划选的文本是否满足要求，不满足则不触发翻译。可设置项包含：语种、字符长度、是否包含空格（这一点是有用户反馈有的专业名词特别长，光靠字符长度不能区分是句子还是词组，所以要额外添加是否包含空格来判断）
> 2. 如果划选的文本满足第一点中的要求，再给每个翻译服务单独做判断，是否满足要求。可设置项同第一点。如果不满足，则不查询此翻译服务的结果，并提示用户文本不满足要求。
> 
> 但是我觉得第一点可能没有必要，因为划词翻译支持辅助键和快捷键，如果不想弹出翻译按钮，那么只需要设置成不弹出翻译按钮、通过辅助键和快捷键的形式弹出翻译结果就可以了（见[使用技巧 - 不想总是弹出翻译按钮](https://hcfy.limingkai.cn/docs/guides/nobtn)）。
> 
> @oodzchen 你觉得呢？

第1点的目的不是“不想弹出翻译按钮”，而是只针对特定语言弹出翻译按钮，这种细节方面的体验我觉得还是很重要的，通过你给的链接目前并不能达到要求。
第2点你可能误会我的意思，我是说源语言可以多选而已，并不是说翻译服务多选，源语言的多选目的跟前一条“未设置的源语言不用触发翻译”是一致的。

举个例子：用户如果设置的翻译方向是把英语、日语、汉语都翻译成中文，那么只要在网页上选中的文本是这三种语言的任意一个，那么就触发翻译，如果网页上选中的是别的语言，如中文或者德语，这些不属于用户设置的源语言范围，所以不用触发翻译。
当然，这里举的例子都是单向翻译，而不是双向的。

**Comment by lmk123** [comment]
此 issue 已合并至 #1693
