### ISSUE TITLE
阿里翻译有时候会显示302

### ISSUE THREAD

**Issue by wisecrick** [hcfyapp/crx-selection-translate#1158]
## 基本信息

划词翻译版本：8.5.6
浏览器版本：Chrome/93.0.4577.63
操作系统：Linux 5.13.13-zen1-1-zen

## 重现问题的步骤

1.使用香港IP
2.使用阿里翻译句子或全文
3.出现302信息
4.国内IP就没有问题

我查了一下302是http重定向，是否阿里对海外IP有什么特别的处理？

### 预期行为
海外IP正常使用
### 实际行为
提示302错误

**Comment by lmk123** [comment]
你用的是自己申请的密钥还是划词翻译的翻译积分？

**Comment by wisecrick** [comment]
自己的密钥，这个问题也是时有时无
![Screenshot_20210911_022104](https://user-images.githubusercontent.com/1472179/132899668-000140e7-8f19-44b3-bcbd-4d99d8eeda67.png)

**Comment by lmk123** [comment]
活久见了……没想到有生之年能在浏览器里捕获到 302。我首先得确认一下什么情况下才能捕获到 302，今天太晚了，明天我再研究一下。

**Comment by wisecrick** [comment]
还是先把deepl的api接口做出来吧，这个比较有价值。我可以提供一个free api key

**Comment by lmk123** [comment]
我试了一下，测试不出来怎么重现阿里翻译 302。但是这个问题感觉不算是大问题，只要把阿里翻译加入到直连名单就可以了，所以这个问题我先搁置了。

> 我可以提供一个free api key

感谢，不过我还是自己申请吧，因为我得把申请步骤写成文档放在官网上

**Comment by lmk123** [comment]
由于无法稳定重现此问题，所以我就先关闭了。如果你之后有了新的信息，欢迎留言，我会继续跟进。
