### ISSUE TITLE
登录一直失败

### ISSUE THREAD

**Issue by wmlc** [hcfyapp/crx-selection-translate#1189]
![QQ20211006-170014](https://user-images.githubusercontent.com/12483202/136172654-46cb9f47-f2fd-43b2-99bd-83da90e67153.png)

**Comment by wmlc** [comment]
重新安装  好了

**Comment by lmk123** [comment]
我最近确实收到一些用户反馈会无法登录，但是我这边一直都是一切正常。有的用户排查后是发现证书会显示不正确，但刷新几次之后就好了。
