### ISSUE TITLE
使用 DeepL 进行网页全文翻译时在部分页面会出现翻译结果错位的情况

### ISSUE THREAD

**Issue by hmrg-grmh** [hcfyapp/crx-selection-translate#1210]
## 基本信息

划词翻译版本：8.6.2
浏览器版本：

![image](https://user-images.githubusercontent.com/68635334/139007710-35524a8d-89f7-4db2-9df1-c1a0b4621a94.png)

操作系统：WIN10

## 重现问题的步骤

1. site: `https://learnyousomeerlang.com/mnesia`
2. 全文翻译
3. 等

### 预期行为

翻译出现在正确位置

### 实际行为

这样：

![image](https://user-images.githubusercontent.com/68635334/139007867-6b0f2be9-4251-4363-9af3-dfdb27733498.png)

问题看着是从蓝框出现的。

调试下是这样：

![image](https://user-images.githubusercontent.com/68635334/139008050-3acc6120-1f62-4fd1-9c7b-9afcc917c877.png)

之后就一直都是错位的了，比如比较明显的：标题下面其实是第一自然段的翻译结果。

**Comment by hmrg-grmh** [comment]
在这页面也有错位：

`https://docs.openebs.io/docs/next/localpv.html`

![image](https://user-images.githubusercontent.com/68635334/141064652-4fc1bd1d-a010-475c-9d0a-ae8354bcd8a9.png)

并且在这个相同排版的页面则没错位：

`https://docs.openebs.io/docs/next/rwm.html`

![image](https://user-images.githubusercontent.com/68635334/141064713-51541c14-f3ff-4d3d-9432-fd78c47dad00.png)


----

在插件的 `8.6.3` 和 `8.6.4` 版本都有这问题。

**Comment by lmk123** [comment]
使用 v10.4.2 + DeepL 进行测试：

- https://learnyousomeerlang.com/mnesia 已经没有这个问题了
- 其它 openebs 的网址全都跳转到了 https://openebs.io/docs/ ，在这个新地址也没有这个问题

所以我倾向于判断 DeepL 已经没有这个问题了，所以 issue 我先关闭了。如果以后遇到了，欢迎继续留言
