### ISSUE TITLE
DeepL 全文翻译时没有将英文翻译为中文

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1285]
## 基本信息

划词翻译版本：v8.6.7.4、v8.6.8（应该跟划词翻译没关系，是 DeepL 官网做了改动）
浏览器版本：chrome 95
操作系统：macOS

## 重现问题的步骤

1. https://developer.mozilla.org/en-US/docs/Web/API/Event
2. 用 DeepL 进行全文翻译
3.

### 预期行为

所有英文段落都应该被翻译为中文

### 实际行为
大部分英文段落仍然被翻译成了英文，如下图：

<img width="1440" alt="截屏2021-12-27 下午9 03 24" src="https://user-images.githubusercontent.com/5035625/147474346-d2eb04c8-fdd1-4e36-8dfb-54677dda5701.png">

### 其它信息

尝试了多个网页之后，发现这个问题在有的网页是没有的，比如：

- https://developer.mozilla.org/en-US/docs/Web
- https://developer.mozilla.org/en-US/docs/Web/Guide

在有的网页大部分段落都是正常的但偶尔会有几个段落有这个问题，比如：

- https://developer.mozilla.org/en-US/docs/Web/Tutorials

另外，也试过在 https://deepl.com/ 直接粘贴网页全文翻译时发送的字符，发现 DeepL 自己确实把这些字符未经过翻译就原样输出了，如图：

<img width="1440" alt="截屏2021-12-27 下午9 06 51" src="https://user-images.githubusercontent.com/5035625/147474639-9f76d5e5-dec6-486c-a5dc-03bee2aef36a.png">

**Comment by lmk123** [comment]
尝试减少同时发送给 DeepL 的字符数，是有作用的，但还是偶尔会有这个问题，比如即使减少了同时发送的字符数到 500，https://developer.mozilla.org/en-US/docs/Web/API/Event 里的 `Many DOM elements can be set up to accept (or "listen" for) these events...` 这个段落输出的仍然是英文

**Comment by lmk123** [comment]
另外，可以确认以前是没有这个问题的，因为每次测全文翻译功能的时候我用的都是这个网页

**Comment by lmk123** [comment]
但是我又在 https://www.nytimes.com/ 试了下，是正常的……然后我仔细观察了一下 https://developer.mozilla.org/en-US/docs/Web/API/Event 全文翻译的情况，得出一个结论：这可能是 DeepL 的一个 bug

首先，前面提到 `Many DOM elements can be set up to accept (or "listen"...` 这个段落（下文称呼为“问题段落”）即使只把这一段文字输入 DeepL 网页版，也是原样返回的英文，这个无疑是 DeepL 的问题。

然后，我注意到 https://developer.mozilla.org/en-US/docs/Web/API/Event 出现英文的部分正好就是包含了问题段落的部分，而接下来其它部分的翻译情况是正常的，都正常由英文翻译成了中文。

我的猜测是，包含问题段落就会导致整个文本出问题，不包含问题段落就是正常的；减少同时发送的字符数之所以会生效，就是因为字符数少了，第一批文本不包含问题段落，就正常翻译了；第二批文本里又包含了这个段落，就不正常了；接下来的文本里不包含问题问题段落所以就又正常了。

公众号前天有个用户反馈说最近 DeepL 不好用了，但是没说原因，我猜就是因为这个。

**Comment by bobo521bobo** [comment]
![image](https://user-images.githubusercontent.com/878648/147715775-aeb219cc-87da-4a90-abc0-23ea9c970fa8.png)
这个应该跟网页语言有关系 ， 全文翻译应该增加 源语言→翻译语言 的选择！

**Comment by lmk123** [comment]
现在已经无法重现这个问题了，目测是 DeepL 自己的问题。
