### ISSUE TITLE
翻译文本背景颜色修改功能

### ISSUE THREAD

**Issue by chuwenhuang91** [hcfyapp/crx-selection-translate#1297]
## 现在已经有个框了，但是看起来还是不太舒服，没有很明显的区分，让用户能自己改变颜色的话也能视个人喜好来取舍

**Comment by lmk123** [comment]
好的

**Comment by lmk123** [comment]
v9.7.0 中将提供几种预定义的译文样式供用户选择，且还支持自定义 CSS。后续进展可关注 #1624
