### ISSUE TITLE
如果网页里面有中文，网页全文翻译无法把英文翻译为中文

### ISSUE THREAD

**Issue by freshcn** [hcfyapp/crx-selection-translate#1321]
## 基本信息

划词翻译版本：划词翻译 v8.6.10
浏览器版本：Microsoft Edge版本 98.0.1108.51 (官方内部版本) (arm64)
操作系统：macos 12.1 (21C52)

## 重现问题的步骤

1. 打开网页 https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/fbp-and-fbc
2. 启动“网页全文翻译”
3.

### 预期行为

都翻译为中文

### 实际行为
由于页面的顶部使用了中文，翻译被设置为了都翻译成英文
![image](https://user-images.githubusercontent.com/1764041/153991859-cc9bb144-2385-404b-a60f-ba89b071e26e.png)

**Comment by lmk123** [comment]
目前确实有这个问题。

后面会给网页全文翻译也加入设置源语种和目标语种的选项，这样当翻译中英文混合的页面时，可以自己设定目标语种，避免出现这种情况。

**Comment by lmk123** [comment]
后续进展将更新在 #943
