### ISSUE TITLE
希望支持火山翻译

### ISSUE THREAD

**Issue by Apostilize** [hcfyapp/crx-selection-translate#1322]
![1645062827(1)](https://user-images.githubusercontent.com/38352300/154389501-ad426be7-df3c-464b-b476-263e4a3ff456.jpg)

## 功能简介
https://translate.volcengine.com/api

**Comment by lmk123** [comment]
第一次听说这个翻译服务 :joy: 我会考虑看看的

**Comment by dingzhw** [comment]
支持，字节出品，在领域细分翻译方面做的挺好，而且反馈渠道畅通，解决问题效率很高

**Comment by lmk123** [comment]
v8.7.10 添加了对火山翻译的支持，已提交审核。
