### ISSUE TITLE
划词翻译打开的pdf字迹不清晰

### ISSUE THREAD

**Issue by shelllee** [hcfyapp/crx-selection-translate#1339]

**Comment by lmk123** [comment]
我这里试过的 pdf 都是清晰的，请提供一下能复现此问题的 pdf 文件。

当你提供能复现的 pdf 文件之后，我会重新打开此 issue

**Comment by shelllee** [comment]
上图是chrome中直接打开，下图是划词翻译

都用的100%缩放（划词中200%以上缩放会清晰，200%以内都感觉模糊）

![image](https://user-images.githubusercontent.com/11704124/157818417-f9141575-5a5a-47ea-a074-bc2933e1c7b0.png)

[vp.pdf](https://github.com/lmk123/crx-selection-translate/files/8229819/vp.pdf)

**Comment by lmk123** [comment]
在 macOS、Chrome 99 没有出现这个问题，如下图。方便提供一下你的操作系统以及浏览器版本吗？如果浏览器版本比较低的话，可以试试升级到最新版本。

<img width="699" alt="截屏2022-03-11 下午3 11 48" src="https://user-images.githubusercontent.com/5035625/157819863-bd2ddf44-5933-4cbb-a567-103b9373dde8.png">

**Comment by shelllee** [comment]
> 在 macOS、Chrome 99 没有出现这个问题，如下图。方便提供一下你的操作系统以及浏览器版本吗？如果浏览器版本比较低的话，可以试试升级到最新版本。
> 
> <img alt="截屏2022-03-11 下午3 11 48" width="699" src="https://user-images.githubusercontent.com/5035625/157819863-bd2ddf44-5933-4cbb-a567-103b9373dde8.png">

系统：Windows10
chrome版本：最新
屏幕分辨率：1920*1080

**Comment by shelllee** [comment]
系统：Windows10
chrome版本：最新
屏幕分辨率：1920*1080

**Comment by lmk123** [comment]
我手头目前没有 Windows 电脑 :joy: 等我有了之后我会再次确认此问题是否存在

**Comment by shelllee** [comment]
> 我手头目前没有 Windows 电脑 😂 等我有了之后我会再次确认此问题是否存在
😂😂😂

**Comment by lmk123** [comment]
我试了一下，确实有这个问题，但我没法修复 :joy:

内置 PDF 是基于网上的第三方 PDF 阅读器二次开发的，而文本渲染这个问题得由第三方 PDF 阅读器来修复，从划词翻译这边没法修复
