### ISSUE TITLE
增加翻译字符统计功能

### ISSUE THREAD

**Issue by yuanhepeng** [hcfyapp/crx-selection-translate#1343]
## 功能简介
希望可以展示选择的翻译源剩余的可以使用的翻译字符的数量
## 为什么你觉得需要（改进）这个功能？
因为很多翻译源都有最大的翻译字符的使用量，但是到期后又没有提示，很苦恼，每次用的时候总是担心不小心用的数量超过了上限

**Comment by lmk123** [comment]
各个翻译服务都没有提供“剩余免费翻译字符”的接口，所以你需要的功能实现不了。

但是，我可以给划词翻译做一个统计功能，也就是统计你通过密钥、翻译积分等渠道各使用了多少个字符

**Comment by yuanhepeng** [comment]
这个很nice。虽然没有接口，但是有明确的数量，可以直接把数量拿过来写死为常量，然后统计每个翻译源使用字符的数量，这个东西可以放redis，一个用户一个翻译源一个key，最基础的string结构就够用，然后有效期可以设置30天，一个月一清，这个可以有效的利用资源，避免空间的无效占用


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月11日(周五) 晚上7:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lmk123/crx-selection-translate] 剩余可用翻译字符 (Issue #1343)




 
各个翻译服务都没有提供“剩余免费翻译字符”的接口，所以你需要的功能实现不了。
 
但是，我可以给划词翻译做一个统计功能，也就是统计你通过密钥、翻译积分等渠道各使用了多少个字符
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lmk123** [comment]
此功能后续将在 #1435 更新进展
