### ISSUE TITLE
添加多个API密钥但是可选择是否启用

### ISSUE THREAD

**Issue by octigha** [hcfyapp/crx-selection-translate#1349]
## 功能简介

添加多个API密钥，但可选择哪个启用

## 为什么你觉得需要（改进）这个功能？

DeepL价格太贵了，只能添加多个密钥，但是额度又不多，翻译几个网页就没了，想着如果需要大量翻译网页就优先不使用API

**Comment by lmk123** [comment]
我似乎没明白这样做的必要性……

如果不想用密钥的话，那不要填写密钥就可以了。有什么场景会需要临时不用密钥吗？

**Comment by octigha** [comment]
主要是想节省一下额度，比如一些长网页翻译一下一个月的额度就没了，所以想在这些场景不使用API翻译
