### ISSUE TITLE
翻译无效BUG:https://www.mulesoft.com/exchange/org.mule.examples/netsuite-data-retrieval/

### ISSUE THREAD

**Issue by msghost** [hcfyapp/crx-selection-translate#1353]
## 基本信息

划词翻译版本：8.7.3
浏览器版本：FF98.0.1,CHROME99.0.4844.51
操作系统：Win10

## 重现问题的步骤

1.打开https://www.mulesoft.com/exchange/org.mule.examples/netsuite-data-retrieval/
2.选网页全文翻译
3.

### 预期行为
页面中间的主要内容部分会被翻译

### 实际行为

页面顶部的区域被翻译,中间区域的没有翻译

### 补充信息

![图片](https://user-images.githubusercontent.com/16555025/159481357-70cf20de-21d5-48a2-afc7-be1c459bc733.png)

**Comment by lmk123** [comment]
感谢反馈，已确认根本原因是因为 #1219

**Comment by lmk123** [comment]
你好 @msghost  ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
