### ISSUE TITLE
中文网页双语翻译显示异常

### ISSUE THREAD

**Issue by linuxscreen** [hcfyapp/crx-selection-translate#1354]
![截图_20224224014248](https://user-images.githubusercontent.com/51886573/159762639-f5621637-c165-4852-a43f-a23406e2218d.png)
还有就是网页全文翻译我希望英文页面一直翻译英文，中文页面不进行翻译

**Comment by lmk123** [comment]
我猜你想反馈的问题有三个：

## 1. 在百度首页原文和译文都是中文，但按照预期应该是不一样的

目前如果一个网页里同时包含中英文（`hao123` 可能被翻译服务识别为英语了）就可能会出现这个情况。未来的版本中会允许网页全文翻译指定源语种于目标语种。

## 2. 双语模式下页面布局混乱

双语模式是在网页原本的布局上“破坏性”的加入了本不应该存在的译文部分，所以不可避免的会破坏页面布局。有的网站布局简单的话可能看起来还行（例如大部分新闻网站是上下布局），但百度这种有左右布局的就会乱了。

也正因为如此，划词翻译还支持原文 / 译文 模式，这两种模式是不会破坏页面布局的。

## 3. 开启了“在当前窗口自动翻译”之后，想要避免自动翻译中文页面

我会在未来加入这个功能。但目前来说，推荐的使用方式是开两个浏览器窗口：

- 一个浏览器窗口 A 用来浏览**不需要**全文翻译的网站，例如百度；
- 另一个浏览器窗口 B 用来浏览器**需要**全文翻译的网站，并在此窗口中开启“自动翻译”。例如当你上 GitHub 或者看一些技术文档的时候

“在当前窗口自动翻译”开启后，只会对当前浏览器窗口有效，也就是说，只有浏览器窗口 B 中的标签页会被自动开启全文翻译，这样就能避免中文网页被翻译了。

**Comment by linuxscreen** [comment]
能不能根据url匹配，让用户选择哪些需要全文翻译，哪些不需要
或者通过读取<html lang="en">如果是en就翻译，如果是CN或其他不进行全文翻译

**Comment by linuxscreen** [comment]
\<html lang="en"\>

**Comment by lmk123** [comment]
> 能不能根据url匹配

之前也有用户提过，但是我觉得这样做的话显得太复杂了。目前这种分两个浏览器窗口来翻译我觉得是更简单的方式。

> 通过读取如果是en就翻译，如果是CN或其他不进行全文翻译

未来会添加此功能
