### ISSUE TITLE
部分页面带有小部分中文，导致划词翻译误以为我要“英译中”，大部分英文内容也翻译为英文

### ISSUE THREAD

**Issue by GF-Huang** [hcfyapp/crx-selection-translate#1355]
## 基本信息

划词翻译版本：v8.7.1
浏览器版本：Microsoft Edge 版本 99.0.1150.46 (正式版本) (64 位)
操作系统：Win10 21H2

## 重现问题的步骤

1. 以这个页面为例：https://groups.google.com/g/rl-list/c/rv92nGy0YRk?pli=1
2. 启用划词翻译的 “网页全文翻译” 功能。
3. 得到结果：
![image](https://user-images.githubusercontent.com/4510984/160272655-bb5ee19b-cdcb-4d90-a567-2cb5a2ad8222.png)

### 预期行为
忽略中文，只翻译英文部分。

### 实际行为
误解了我的意图，以为我要把中文翻译成英文。

**Comment by lmk123** [comment]
感谢反馈，这是已知问题，未来将优先解决 #943
