### ISSUE TITLE
百度翻译在翻译一段文本时报错

### ISSUE THREAD

**Issue by PGuardRing** [hcfyapp/crx-selection-translate#1356]
## 基本信息

划词翻译版本：8.7.3
浏览器版本：Firefox 98.0.2
操作系统：windows 10 

## 重现问题的步骤

1.打开网站https://diskanalyzer.com/download?ref=upgrade
2.使用申请的标准版百度翻译密钥，选中一段文本翻译

### 实际行为
出现报错，我没有登陆所以没有翻译积分
![图片](https://user-images.githubusercontent.com/102495819/160314488-47fe9e2c-6d95-4c17-9d60-4666371750a9.png)

### 补充信息

选其他或部分文本翻译都不会出现这个
![图片](https://user-images.githubusercontent.com/102495819/160314626-e436208d-1fba-4c1d-a126-96ef11ff2c17.png)

**Comment by lmk123** [comment]
重现了，但无法解决。

出现这个问题的原因是百度翻译接口对你划选的这段话（且正好是这段话，少了或者多了都没问题）没有返回任何内容，甚至没有报错信息（如下图），所以划词翻译在尝试读取错误码（也就是`error_code`）的时候就报错了。

这是百度翻译的问题，我没法解决，我能做的就是改进一下报错信息，当出现空返回的情况给一个比较人性化的错误信息例如“百度翻译对这段文本没有返回翻译结果”。

<img width="886" alt="截屏2022-03-28 下午2 17 06" src="https://user-images.githubusercontent.com/5035625/160337498-41e75166-8da9-4fdb-8991-c4c029175cd4.png">
