### ISSUE TITLE
这有问题吧

### ISSUE THREAD

**Issue by linuxscreen** [hcfyapp/crx-selection-translate#1357]
绑定百度翻译API没两天给我干到欠费33？？？
![截图_20223428023423](https://user-images.githubusercontent.com/51886573/160339748-6a1c9c86-1d32-4e90-b6b7-c6dbba0b9f8c.png)
我一个人不可能用者这么多啊
之前用了一个月也没多少字符

**Comment by lmk123** [comment]
从图上看，你的昨日使用字符有 260 万，这个数据肯定是有问题的。

你使用的划词翻译版本是多少？

划词翻译曾经有一个 bug 可能会导致这个情况，就是在翻译无意义的字符（例如 “pwage”）的时候会反复循环的触发查询，导致一天之内消耗大量字符数，但是这个 bug 在很早以前就已经修复了。

如果你使用的是最新版本的划词翻译，那么：

1. 联系一下客服，让他提供昨天你查询过的历史记录
2. 将记录上传到这个 issue 里，我来分析一下是否是由于上述 bug 导致的

如果确认是由划词翻译最新版本中的 bug 引起的，我会赔付给你这 33 元。

**Comment by linuxscreen** [comment]
哪里有客服联系方式



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 下午2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hcfyapp/crx-selection-translate] 这有问题吧 (Issue #1357)





 
从图上看，你的昨日使用字符有 260 万，这个数据肯定是有问题的。
 
你使用的划词翻译版本是多少？
 
划词翻译曾经有一个 bug 可能会导致这个情况，就是在翻译无意义的字符（例如 “pwage”）的时候会反复循环的触发查询，导致一天之内消耗大量字符数，但是这个 bug 在很早以前就已经修复了。
 
如果你使用的是最新版本的划词翻译，那么：
  
联系一下客服，让他提供昨天你查询过的历史记录
 
将记录上传到这个 issue 里，我来分析一下是否是由于上述 bug 导致的
  
如果确认是由划词翻译最新版本中的 bug 引起的，我会赔付给你这 33 元。

**Comment by lmk123** [comment]
https://fanyi-api.baidu.com/api/trans/product/desktop

右下角【咨询在线客服】

**Comment by lmk123** [comment]
另外，回想一下你没有把你的百度翻译密钥分享给其他人使用过或者不小心泄露过。

比如，我曾在一些翻译群里看到有人发过包含密钥信息的截图。

**Comment by linuxscreen** [comment]
我就在IDEA翻译插件里用过，用了很久出现什么问题
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hcfyapp/crx-selection-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hcfyapp/crx-selection-translate] 这有问题吧 (Issue #1357)





 
另外，回想一下你没有把你的百度翻译密钥分享给其他人使用过或者不小心泄露过。
 
比如，我曾在一些翻译群里看到有人发过包含密钥信息的截图。

**Comment by lmk123** [comment]
也就是说，你的密钥同时用在了划词翻译和其它翻译插件里。

从你的描述上看，你认为你用 IDEA 翻译插件很久了都没有出现问题，所以倾向于是划词翻译的问题；但从我的角度来看，划词翻译的新版本发布了近两年，只有阿里翻译曾经出现过这个问题，见 #1073

所以，先找客服拿到查询记录吧，你先自己看一下记录里的文本是你在哪个插件里用的。

**Comment by lmk123** [comment]
这件事情进展吗？如果你知道是什么原因引起的，可以告诉我一下吗？我会将这个作为案例写在文档里，帮助其他用户避免这个问题。

**Comment by linuxscreen** [comment]
联系了客服邮箱，她说只能查到使用了多少字符，不能查询具体哪些地方调用了API和具体查了哪些单词



---Original---
From: ***@***.***&gt;
Sent at: 2022年4月1日(Fri) Noon1:18
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hcfyapp/crx-selection-translate] 这有问题吧 (Issue #1357)




 
这件事情进展吗？如果你知道是什么原因引起的，可以告诉我一下吗？我会将这个作为案例写在文档里，帮助其他用户避免这个问题。

**Comment by lmk123** [comment]
我的建议：

- 立刻去 https://fanyi-api.baidu.com/api/trans/product/desktop 重置密钥
- 在接下来的一段时间内，只通过唯一一个软件使用新密钥。比如先只在划词翻译里用一个星期看看有没有问题，再只在别的软件里用一个星期看看。保险起见，最好时不时的去确认一下字符数有没有异常，毕竟百度翻译不会实时提醒字符数使用情况。

由于目前看起来一时半会儿不会有进展，所以这个 issue 我就先关闭了。一旦你有了新的进展，欢迎随时 reopen，我会继续跟进。

**Comment by linuxscreen** [comment]
只有在线人工弱智客服啊，醉了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hcfyapp/crx-selection-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hcfyapp/crx-selection-translate] 这有问题吧 (Issue #1357)





 
也就是说，你的密钥同时用在了划词翻译和其它翻译插件里。
 
从你的描述上看，你认为你用 IDEA 翻译插件很久了都没有出现问题，所以倾向于是划词翻译的问题；但从我的角度来看，划词翻译的新版本发布了近两年，只有阿里翻译曾经出现过这个问题，见 #1073
 
所以，先找客服拿到查询记录吧，你先自己看一下记录里的文本是你在哪个插件里用的。
