### ISSUE TITLE
鼠标悬浮取词 无法关闭

### ISSUE THREAD

**Issue by ningbowang** [hcfyapp/crx-selection-translate#1358]
## 基本信息

划词翻译版本：8.7.3
浏览器版本：chrome 99.0.4844.84（正式版本） （64 位）
操作系统：
![image](https://user-images.githubusercontent.com/47706456/160519997-b1defd25-d162-45eb-9ad3-f21e42daa969.png)

## 重现问题的步骤

1. 修改快捷键页面设置快捷键 -> 鼠标悬浮取词：  ALT+W 在chrome中
2. 觉得不好用，清除快捷键设置

### 预期行为

鼠标悬浮取词不再生效

### 实际行为

1. 所有网站（非chrome设置页），当鼠标悬浮到文本时，都会自动弹出悬浮取词的翻译框
2. 选中任意文本，也会自动弹出悬浮取词翻译框
3. 截图：
![3](https://user-images.githubusercontent.com/47706456/160521635-45e5b896-ae69-47dc-a3c9-372d11b78148.png)

### 补充信息
设置页：
![1](https://user-images.githubusercontent.com/47706456/160521368-cd58de5b-11f8-4b04-bc39-257884bc5e3e.png)

![2](https://user-images.githubusercontent.com/47706456/160521126-64f800ce-6955-41e2-9145-e86c1e965502.png)

已尝试：
重启电脑，无效

**Comment by lmk123** [comment]
“清除快捷键”不等于“关闭鼠标悬浮取词”。你需要在清除之前再按一次快捷键来关闭，或者如果你已经清除了快捷键，那么你可以点击翻译弹窗右上角的齿轮图标，然后取消勾选“鼠标悬浮取词”即可。

<img width="293" alt="截屏2022-03-29 下午1 59 27" src="https://user-images.githubusercontent.com/5035625/160543508-fa87713e-1d55-44c3-b6ff-ae2fcea19889.png">
