### ISSUE TITLE
网页全文翻译添加区域选择，只翻译正文部分或元素匹配

### ISSUE THREAD

**Issue by zero-coding** [hcfyapp/crx-selection-translate#1359]
**没有这个功能（改进）的时候，你遇到了什么问题？**
部分网站全文翻译后很乱，其实菜单目录之类的可以不用翻译，只翻译正文部分。

**你想要如何解决你的问题？**
可选择翻译区域，或元素匹配翻译。

划词翻译效果：[link](https://www.revitapidocs.com/2018/163d1fae-e9d8-e4de-7452-c3b140b6daad.htm)

![image](https://user-images.githubusercontent.com/55073865/160529296-bbfa5e94-b0b5-41ad-8fab-6420207eed62.png)

根据元素匹配效果：$(".summary")

![image](https://user-images.githubusercontent.com/55073865/160529250-8e0c9b38-a0d9-489f-97b8-587f4d23d7b2.png)

**补充信息**
减少翻译内容是否能加快翻译速度。

**Comment by lmk123** [comment]
这个功能是可以做的，我会在未来加入。

> 减少翻译内容是否能加快翻译速度。

不能 :joy:

**Comment by kingofotaku** [comment]
刚想提类似的建议，我的理由是因为某些网站（比如steam讨论区）适配了中文界面，但这会导致我看英文帖子的时候全文翻译会将网页识别为中文从而进行中译英，并且现阶段无法手动强制英译中。

**Comment by kingofotaku** [comment]
刚想提类似的建议，我的理由是因为某些网站（比如steam讨论区）适配了中文界面，但这会导致我看英文帖子的时候全文翻译会将网页识别为中文从而进行中译英，并且现阶段无法手动强制英译中。

**Comment by XHXIAIEIN** [comment]
+1
可以增加选择器白名单、黑名单规则，只翻译特定选择器的内容。

**Comment by lmk123** [comment]
此 issue 已合并至 #1406
