### ISSUE TITLE
最新的v8.7.3 chrome插件复制pdf文档中文字翻译，句子未去除换行，翻译后不是完整句子了

### ISSUE THREAD

**Issue by clawCa** [hcfyapp/crx-selection-translate#1361]
直接在pdf阅读中复制后ctrl+q翻译段落
例  Leaf Area Index (LAI) is an important biophysical variable for
monitoring maize growth and estimating yield (Su et al., 2019a).
不会别识别成一个完整句子，未规整化，
但是直接选中然后右键翻译整段文字就会自动规整成一个完整句子，希望能优化

**Comment by lmk123** [comment]
能提供一下具体的 pdf 文件、以及翻译哪段话会出现这个问题吗？我需要先重现问题

**Comment by clawCa** [comment]
> 
就是普通的英文pdf文献，在翻译器内置的阅读器中打开，复制后ctrl q翻译，就不是完整句子，点旁边小标弹出小窗是完整句子，文字复制到小窗中就又不是完整句子了

**Comment by lmk123** [comment]
**我需要能在我的电脑里重现你的问题才能解决你的问题**。并不是所有 pdf 都会有你这个问题存在，比如我电脑里的几个供我测试的 pdf 就没有这个问题。

**Comment by lmk123** [comment]
由于一直没有回应，所以我就先关闭了。当你提供重现所需的文件和信息之后，我会继续跟进。
