### ISSUE TITLE
网页划词面板丢失高度调整功能

### ISSUE THREAD

**Issue by Vanished-Rei** [hcfyapp/crx-selection-translate#1364]
## 基本信息

划词翻译版本：8.7.3
浏览器版本：CHROME 100.0.4896.75
操作系统：WINDOWS 10

## 问题
尊敬的开发者您好，本人升级浏览器至最新版本后，使用划词翻译发现：划词翻译面板似乎丢失了调整高度的功能，而独立翻译界面功能正常，希望开发者协助解惑，特此致谢~

**Comment by lmk123** [comment]
划词翻译在网页里的翻译框**从来没有**调整高度的功能，高度一直是根据翻译结果来动态调整的。

你能举一个具体的例子来对比说明浏览器版本升级前后的区别吗？

**Comment by Vanished-Rei** [comment]
感谢大佬回复！
刚才测试了下，老版本也确实不行，可能是因为我第一次用划词面板翻译长文，导致与之前用独立面板翻译的使用习惯记混了吧。
抱歉，打扰了。

**Comment by lmk123** [comment]
没事，有任何问题欢迎反馈
