### ISSUE TITLE
百度翻译出现58003，但是重新配一下id和密钥就又好了

### ISSUE THREAD

**Issue by xming521** [hcfyapp/crx-selection-translate#1366]
## 基本信息

划词翻译版本：v8.7.1
浏览器版本：Cent Browser版本 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
操作系统：win10

## 重现问题的步骤

1.在使用全局快捷键翻译时
2.
3.

### 实际行为
百度翻译出现58003，其他翻译没问题，重新配一下id和密钥就又好了

**Comment by lmk123** [comment]
58003 错误的原因见百度翻译文档：https://fanyi-api.baidu.com/doc/21

我也无法解决，恢复了就好 :joy:

**Comment by lmk123** [comment]
文档上说“如同一 IP 当日使用多个 APPID 发送翻译请求，则该IP将被封禁当日请求权限，次日解封。”

我猜测是你的出口 IP 里有很多人都申请了百度翻译密钥。

举个例子，可能整个公司的出口 IP 是同一个，然后公司内有很多人都申请了百度翻译的密钥，于是就满足了“同一 IP 当日使用多个 APPID 发送翻译请求”的情况。

**Comment by xming521** [comment]
可是我在划词翻译里面把appID和密钥重新设置一遍，还是和原来一模一样的就好了，这是为啥

**Comment by lmk123** [comment]
我也不清楚，这个风控是由百度翻译那边做的，他们的风控规则可能不止有这一条。

比如，可能过了一段时间百度发现你的 appid 是被误判了然后就又给解控了。

**Comment by lmk123** [comment]
划词翻译做的仅仅只是用你填写的 appid 调用了百度的接口，而百度如何控制接口就不在划词翻译的可控范围内了。

**Comment by Yalooo23** [comment]
我是学校里校园网连的，一直有58003的错误，看了大哥们的说法之后改了自己的手机热点就成功了。
