### ISSUE TITLE
提过一个免费获取通过 DeepL API 地址验证的方法

### ISSUE THREAD

**Issue by MSDNQ** [hcfyapp/crx-selection-translate#1367]
具体操作步骤已写在notion中，https://ani365.notion.site/DeepL-API-0348b1b42c2e45ee8bf116445cb72545

**Comment by cotagxrdhy** [comment]
感谢，但账号估计很快会被封掉吧

**Comment by MSDNQ** [comment]
> 感谢，但账号估计很快会被封掉吧

这个方法就是获取一张visa信用卡，deepl目前这方面验证不严格，0余额的也是可以过的。之前开的测试用的账户用的也是虚拟v/m卡过的，用了一年多也没事。
