### ISSUE TITLE
有无可能支持 Chrome 阅读器模式

### ISSUE THREAD

**Issue by ZeaKyX** [hcfyapp/crx-selection-translate#1369]
**没有这个功能（改进）的时候，你遇到了什么问题？**
现有 Chrome 自带阅读器模式不支持划词/全文翻译。

**补充信息**
支持的网站如（顺便是个打开隐藏阅读器模式的教程）：[How to Use Google Chrome’s Hidden Reader Mode](https://www.howtogeek.com/423643/how-to-use-google-chromes-hidden-reader-mode/)

**补充信息**
目前发现打开阅读器模式后进入了内置页面，看到 wiki 里说：

> 这是浏览器自身的安全策略限制，任何扩展都没有权限控制某些页面，包括但不限于：
> 
> - 浏览器的内置页面，即以 about://、chrome://、moz://、edge:// 等类似协议开头的网址。
> - 各浏览器的扩展商店页面，如 Chrome 不允许在 Chrome 扩展商店使用、Edge 不允许在 Edge 扩展商店使用。
> - 各浏览器自己的一些其它限制，目前已知的有 Firefox 不允许在 https://support.mozilla.org/ 里使用。

搞不了就算了吧😂

**Comment by lmk123** [comment]
如果是浏览器的内置页面，那确实没可能 :joy:

**Comment by lmk123** [comment]
我试了一下，阅读模式确实属于 Chrome 的内置页面的一种，即它不允许扩展程序的代码在里面执行，所以确实不行。

**Comment by lmk123** [comment]
顺带一提，这个内置页面的地址是 `chrome-distiller://63d969b7-e466-470c-943b-3c51bbcedaff_ba859c4d66f17c274b44597aca90d2fb15002c01d0a3127350c20d755f925b18/?title=<页面标题>&time=<时间戳>&url=<页面网址>`
