### ISSUE TITLE
检测网页中的 PDF功能载入文件错误

### ISSUE THREAD

**Issue by wtbsw** [hcfyapp/crx-selection-translate#1370]
## 基本信息

划词翻译版本：v8.7.3
浏览器版本：chrome版本 100.0.4896.127（正式版本） (x86_64)
操作系统：macos12.3.1

## 重现问题的步骤

1. 打开检测网页中的 PDF功能
2. 进入pdf页面，检测到网页中的 PDF，点击链接
<img width="496" alt="image" src="https://user-images.githubusercontent.com/14332504/164492443-b8bef5b8-63e0-4593-b4da-9841b50798f9.png">

3. 载入错误
<img width="293" alt="image" src="https://user-images.githubusercontent.com/14332504/164492726-a69ea1c3-124e-41ee-aeef-eea8a9a89cef.png">

### 预期行为
正常打开pdf文件
### 实际行为
载入错误
### 补充信息
无

**Comment by lmk123** [comment]
具体是进入到哪个网址的 pdf 页面？

**Comment by wtbsw** [comment]
https://arxiv.org/pdf/2203.03605v3.pdf
随便一个都行

**Comment by lmk123** [comment]
用 macOS 12.3.1 Chrome 版本 100.0.4896.127（正式版本） (arm64) 无法重现 :joy:

**Comment by lmk123** [comment]
附图

<img width="354" alt="截屏2022-04-22 14 39 32" src="https://user-images.githubusercontent.com/5035625/164618086-3a6e0930-4b5b-4c08-b7fd-96bfd4812363.png">

**Comment by lmk123** [comment]
我试着把所有插件都关闭了然后重启浏览器，还是没法重现。

由于我没法重现，所以我也没法解决你的问题。我猜测可能是外部因素造成了这个问题，你也可以试试把所有插件关了之后看看能不能恢复。

如果你能提供让我重现问题的步骤，可以继续留言，我会 reopen 并继续跟进。
