### ISSUE TITLE
在文本框中划词会导致页面出现横向滚动条(文本框处在页面最右边)

### ISSUE THREAD

**Issue by Leona-Li** [hcfyapp/crx-selection-translate#1372]
## 基本信息

划词翻译版本：8.7.3
浏览器版本：chrome 100.0.4896.127
操作系统：macos

## 重现问题的步骤
由于使用的是公司内部系统，外部无法访问，所以用codemirror官网模拟遇到的问题

1.打开 https://codemirror.net/index.html，
2. 打开开发者工具，并居右。调整开发者工具宽度，使codemirror页面的代码输入框靠近页面最右边（如下图）
3. 在代码编辑框里划一个单词

<img width="1889" alt="image" src="https://user-images.githubusercontent.com/21243549/164953216-1dad6ced-f8e8-4831-b5db-51594bbed960.png">

### 预期行为
页面宽度无变化

### 实际行为
页面出现了横向滚动条

**Comment by lmk123** [comment]
感谢反馈，已重现此问题，将在未来的版本中修复。

备注：需要划选文本框中一整行的代码（如 `var editor = CodeMirror.fromTextArea(myTextarea, {`）才会出现滚动条，如果只划选其中的一个单词（如 `editor`）就不会出现。

**Comment by Leona-Li** [comment]
如果文本框中的一行中文案很长，选中这个很长文案的任意位置就有可能出现滚动条
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/21243549/164957059-441ab550-3097-46a4-a3ff-8ab8331d4ddf.png">

**Comment by imReker** [comment]
@lmk123 有进展么？非常影响使用。如果网页里的文本框存在大量文字（比如github的代码编辑器，里面有大量代码），那整个网页瞬间就变得不可用了，会出现超长的滚动条，并且由于在BODY外面，导致网页的滚动行为完全无法预测。
已经关闭了划词翻译，也就是说在不翻译的情况下，只要选中了文本框里的文字，还是会出现在DOM里面
![image](https://github.com/hcfyapp/crx-selection-translate/assets/4949937/f85fd016-c11a-4740-a870-26c35a8003af)

**Comment by imReker** [comment]
@lmk123 2年了。。这个P1优先级的BUG有办法解决么？不想为了这么简单的事情直接反编译修改源码

**Comment by lmk123** [comment]
很抱歉这么久都没处理这个问题，此问题已在即将发布的 v10.8.0 里修复。

附注：由于时间过长，原重现步骤已失效，最新的重现步骤如下：

1. 打开此页面也就是 https://github.com/hcfyapp/crx-selection-translate/issues/1372
2. 将网页滚动到现在正在看的这条评论，点击编辑，让它变成输入框
3. 选中任意文本，无需翻译
4. 打开 chrome 的开发者工具，将它调整为靠右显示，然后将开发者工具的宽度尽可能拉长

此时就能看到左侧的网页区域出现了水平滚动条。macOS 上滚动条默认隐藏，但是左右滑动网页就能看到。

**Comment by imReker** [comment]
@lmk123 
问题依旧，div占据了与文本相同的空间，导致在BODY外占用了额外的横向和纵向空间
v10.10.0 on Edge
![image](https://github.com/hcfyapp/crx-selection-translate/assets/4949937/536dbcc4-7b12-48e3-9b89-2f836a2524c5)

**Comment by lmk123** [comment]
macOS 14.5、Edge 126.0.2592.61 (正式版本) (arm64)、划词翻译 v10.10.0 没有重现你的问题，见下方 gif 图。

我注意到你的控制台有一些别的报错，你可以试试把其它插件都关掉、只留划词翻译然后再试试。

如果你能提供一个稳定的重现步骤，麻烦新开一个 issue，我重现了就会解决。

![Kapture 2024-06-20 at 16 15 39](https://github.com/hcfyapp/crx-selection-translate/assets/5035625/f50928c4-dce8-4a7f-adf5-fdf06376b5fd)

**Comment by imReker** [comment]
> macOS 14.5、Edge 126.0.2592.61 (正式版本) (arm64)、划词翻译 v10.10.0 没有重现你的问题，见下方 gif 图。
> 
Windows 11, Edge 126.0.2592.56，其实跟浏览器无关。

你没复现是因为你输入的时候，文本框距离页面底部太远（请使用页面底部的回复框），或者说，文本长度还不够长，没有超出页面原有的范围。
只要打100个回车，然后拖动滚动条，让文本框底部超出屏幕范围，再选中文本，就能轻松复现。
特殊情况下，有些网页会在输入后隐藏输入框，此时就是灾难了。划词翻译认为文本框宽度是1，同样给这个隐藏DIV设置宽度为1，导致长度变得非常长，把整个网页拉到了几千像素高度。

![image](https://github.com/hcfyapp/crx-selection-translate/assets/4949937/69ec0f84-a0a0-4c0b-8ae7-af024c4d53e4)
![image](https://github.com/hcfyapp/crx-selection-translate/assets/4949937/98d76577-a4f3-4128-ae22-fd90e7be3844)


> 我注意到你的控制台有一些别的报错，你可以试试把其它插件都关掉、只留划词翻译然后再试试。
> 
> 如果你能提供一个稳定的重现步骤，麻烦新开一个 issue，我重现了就会解决。
@lmk123 
试过了，只关闭划词翻译就正常了。因为这个div是划词翻译创建的。

**Comment by lmk123** [comment]
已重现，后续会更新在新开的 issue #2033
