### ISSUE TITLE
DeepL翻译有时候会出现漏翻情况

### ISSUE THREAD

**Issue by cotagxrdhy** [hcfyapp/crx-selection-translate#1373]
划词翻译版本：8.7.1
浏览器版本：Chrome 100.0.4896.127
操作系统：WIN11

DeepL翻译会出现漏翻情况

![QQ截图20220424144247](https://user-images.githubusercontent.com/80959178/164960456-f602c32c-b1a8-4cd3-b694-9408ff6bac38.png)

**Comment by cotagxrdhy** [comment]
原文 ：Every decision you make on a daily basis has an impact on your future.Thatmeans you get an abundance of opportunities to take actions that align with yourvalues.Often,when we get down to it,how much of our time is spent working onour values?Is scrolling through social media aligning with my values?Is gettingplastered on the weekend aligning with my values?Is bringing up somethingpetty with a partner aligning with my values?

**Comment by lmk123** [comment]
这是 DeepL 的问题，跟划词翻译没有关系

<img width="1187" alt="截屏2022-04-24 14 50 22" src="https://user-images.githubusercontent.com/5035625/164960599-2c86de45-eeac-42ba-933b-edb6f1ed1f94.png">

**Comment by cotagxrdhy** [comment]
我发现问题所在了

直接选中翻译就没这个情况

只有截图识别后翻译才会出现漏翻的情况，有些扫描的pdf只能截图翻译

你可以多截图几个长段落试试 @lmk123

**Comment by lmk123** [comment]
>直接选中翻译就没这个情况

直接选中翻译仍然没有完整的翻译结果

<img width="764" alt="截屏2022-04-24 14 56 28" src="https://user-images.githubusercontent.com/5035625/164960801-8b543c5a-555d-4b25-b4ea-d20d9641f32c.png">

**Comment by cotagxrdhy** [comment]
![image](https://user-images.githubusercontent.com/80959178/164960864-c4192011-e6ad-4451-a5ec-16808fc47e4f.png)
我在这里选中翻译没问题。。。。好奇怪 @lmk123

**Comment by cotagxrdhy** [comment]
明白了截图识别句子之间标点没有空格，所以影响了DeeepL翻译。。。果然是他们的问题 @lmk123
