### ISSUE TITLE
查词面板高度调节

### ISSUE THREAD

**Issue by chenlidar** [hcfyapp/crx-selection-translate#1374]
OS：ubuntu20.04
![2022-04-24 21-20-58 的屏幕截图.png](https://s2.loli.net/2022/04/24/rkPm1ZHFeboliVJ.png)
您好，请问查词面板的高度是否可调，好像每次调出都是固定高度并下端挨着任务栏，当查词面板中内容很少时会有大量空白

**Comment by lmk123** [comment]
:joy: 你走错片场了，你这个截图不是划词翻译，划词翻译是这样子的：

<img width="561" alt="截屏2022-04-24 21 27 02" src="https://user-images.githubusercontent.com/5035625/164978793-4770b808-5089-4a39-b916-4ec5e062b84c.png">

**Comment by chenlidar** [comment]
确实，抱歉:joy:
