### ISSUE TITLE
English translation of the extension?

### ISSUE THREAD

**Issue by younyokel** [hcfyapp/crx-selection-translate#1376]
Hi. I just found this extension and am amazed at how handy it is! Is there, or will there be, a full translation of the extension itself or at least, its settings into English?

**Comment by lmk123** [comment]
I plan to do that, but it may take a while.

This is because my own English is very poor (otherwise there wouldn't be this software) and there is a lot of text that needs to be translated (settings, documents, etc.)

**Comment by tobiasdiez** [comment]
You can also outsource it to other people by using something like https://crowdin.com. The hardest part in the setup is to extract all the strings you want to translate, but after this initial work its pretty easy for others to contribute new translations.

**Comment by tobiasdiez** [comment]
@younyokel @lmk123 where can one find the option to change the language of the extension? I couldn't find it.

**Comment by lmk123** [comment]
@tobiasdiez I haven't added an English interface yet :joy:

**Comment by tobiasdiez** [comment]
Oh, could this issue then please be reopened? I, and probably a few other people, would appreciate an english interface. This extension is the best and most flexible one for translating chinese to english, so having the option to switch the interface to english would be very helpful.

**Comment by younyokel** [comment]
When the English translation is ready, I can translate it into Russian if needed.

**Comment by lmk123** [comment]
Hi guys, I made a schedule to track the translation progress. I'm currently extracting the Chinese text, you can follow #1770  to see the latest progress.
