### ISSUE TITLE
chrome商店中，右键选则翻译按钮无法弹出独立翻译窗口

### ISSUE THREAD

**Issue by shinesky** [hcfyapp/crx-selection-translate#1377]
## 基本信息

划词翻译版本：8.7.3
浏览器版本：Cent Browser(Chromium 86.0.4240.198) 64位
操作系统：win10 专业版 21H2

## 重现问题的步骤
在chrome商店中，随便选中一段文字，选则右键翻译按钮无法弹出独立翻译窗口。
必须得手动禁用划词翻译扩展，然后再重新开启，才可以右键弹出独立翻译窗口。
如果chrome商店界面刷新或者进入其他扩展窗口，仍然得再次重新开关闭划词翻译，才能使用右键翻译按钮。

![bug演示2](https://user-images.githubusercontent.com/26346923/167066253-0a0c7a5a-697f-47fe-b9c0-1ec260de7463.gif)

### 预期行为
会弹出独立翻译窗口
### 实际行为
不会弹出，需要手动开关闭一次划词翻译，再使用该功能才会弹出。

**Comment by lmk123** [comment]
感谢反馈，经确认在 Chrome 版本 101.0.4951.54（正式版本） (arm64) 里也可以重现

**Comment by lmk123** [comment]
备注：考虑到这一块的代码逻辑从来没有变动过，所以我出初步判断这是浏览器自己的限制，毕竟扩展商店页面属于扩展程序无权访问的页面，但这没法解释为何开关一次划词翻译之后就又能弹出来了，所以仍然需要确认一下问题到底出在哪里。
