### ISSUE TITLE
当 class 里有 `notranslate` 时不要翻译

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1378]
> 来自 Firefox 商店页面的评论区

希望像谷歌一样当 class 有 notranslate 时不翻译

**Comment by 1352love** [comment]
赞同，如果这个功能有了 我就付费终身会员

**Comment by lmk123** [comment]
原本在 v8.7.5 里做了简单的支持，但实际尝试后发现这个功能没有这么简单。

目前我只能做到对整个节点有效，即如果是这种情况：

```html
<p class="notranslate">点击“我知道了”即可隐藏弹窗。</p>
```

那么我能做到将 _p_ 元素忽略掉不翻译，但如果是下面这种情况：

```html
<p>点击“<span class="notranslate">我知道了</span>”即可隐藏弹窗。</p>
```

那么我做不到将`我知道了`原样输出在翻译结果里——然而 `notranslate` 基本都是用在这种情况下的。

这个功能实际上跟 #1036 是同一件事。

**Comment by KairuiLiu** [comment]
是否有相关DOM节点不翻译的标准呢? 目前看 notranslate 这些 css 属性并不是标准文档中的一部分

**Comment by lmk123** [comment]
此 issue 已合并至 #1406
