### ISSUE TITLE
firefox 100 使用 deepl 免费试用时加载超时

### ISSUE THREAD

**Issue by yuukh** [hcfyapp/crx-selection-translate#1379]
## 基本信息
deepl免费试用翻译超时,切换ip不能解决。打开deepl官网可以正常翻译，无遮挡。
![图片](https://user-images.githubusercontent.com/84430227/167278943-2e500071-015f-457b-8bf9-185e5eeb9e10.png)

划词翻译版本：8.7.3
浏览器版本：firefox 100.0
操作系统：win10

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
感谢反馈，已确认这是在 Firefox 升级到 100 之后才会出现的问题，在 Firefox 99 及以下版本和其它浏览器中均没有这个问题。

我会检查一下看看是什么原因导致的。

**Comment by lmk123** [comment]
已在官网中更新对于此问题的说明 https://hcfy.app/docs/services/free#deepl

>Firefox 在升级到 v100 之后，DeepL 会出现“加载超时”的错误。由于在其它浏览器及 Firefox v99 以下版本均没有此问题，所以初步判断这是属于 Firefox 的问题，可能会被 Firefox 在未来的版本中修复。
>
>我会试试能不能从划词翻译这边解决此问题，如果不能的话，大概只能等 Firefox 自己修复这个问题了。在问题修复之前，请在其它浏览器中使用 DeepL。

**Comment by IzualYang** [comment]
> 感谢反馈，已确认这是在 Firefox 升级到 100 之后才会出现的问题，在 Firefox 99 及以下版本和其它浏览器中均没有这个问题。
> 
> 我会检查一下看看是什么原因导致的。

可以理解，但建议提供临时的workaround。

现在的行为逻辑明显是有问题的：用户需要等待出现“加载超时”提示之后，才能够点击deepl区域右上的“显示详细结果”图标，以跳转到deepl翻译页面。而且用户必须要先后点击“查看解决方案”和“DeepL 的常见问题”，才会知道这个问题是firefox导致。

建议改成：如果检测到用户使用firefox100+（且这个问题未得到firefox修复），在等待加载deepl翻译结果过程中，直接提示“由于firefox版本原因可能无法正常显示翻译结果”，并enable右上角的“显示详细结果”图标以便用户跳转。

**Comment by listenerri** [comment]
只知道大概是 firefox 100 的原因么，没有找到更具体的原因么？等 firefox 修复，也得知道要修复的是什么吧？

**Comment by linkwanggo** [comment]
原因可能是很多网站会截取header中UA的版本号，但只截取两位 所以100+就变成了10.0或00.0，然后网站发现version为10 < 某个版本 例如48 ，就不让使用服务。
解决方案就是修改浏览器的header中的版本号 firefox是打开about:config 添加或修改general.useragent.override = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0（或者查看自己的浏览器UA）  改为只要小于100的都可以，但别太小，有限制。
chrome我不用，不清楚如何修改
实测解决了deepl的超时问题

**Comment by lmk123** [comment]
@linkwanggo 感谢提供解决方案。这个问题只在 firefox 里有 :joy:

**Comment by lmk123** [comment]
从 v8.7.9 开始，火狐里的 deepl 已经能正常使用了。
