### ISSUE TITLE
增加小牛翻译

### ISSUE THREAD

**Issue by wtbsw** [hcfyapp/crx-selection-translate#1380]
**没有这个功能（改进）的时候，你遇到了什么问题？**
目前我自己使用谷歌翻译和百度翻译配合使用，但是百度翻译API经常出现无法连接服务器的问题。

**你想要如何解决你的问题？**
添加小牛翻译的接口。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
建议增加

**补充信息**
因为我经常使用小牛翻译，感觉它的翻译质量挺高的，建议增加。

**Comment by lmk123** [comment]
好的，等我开发完桌面端后会添加小牛翻译。后续进展可以关注 #1019
