### ISSUE TITLE
截图翻译报错 An unexpected error occurred

### ISSUE THREAD

**Issue by Dunky-Z** [hcfyapp/crx-selection-translate#1381]
## 基本信息
从图片中提取文字时发生了一个错误：An unexpected error occurred

划词翻译版本：v8.7.3
浏览器版本： 91.0.4472.77（正式版本） （64 位）
操作系统：win 10 

## 重现问题的步骤

1. 截图翻译
2. 没有超过当日免费上限（第一次使用）
3. 无法翻译

**Comment by lmk123** [comment]
这个报错信息是第一次见，所以我只能猜测出现此问题的原因。

我觉得有可能是 Tessearct OCR 下载语言检测包的过程中报了错，你点一下下面这个链接，如果网络正常的话，你的浏览器会把 chi_sim.traineddata.gz 下载下来，如果没有开始下载或者在下载过程中失败了，那说明你得确认一下你的网络是否正常了。

http://tessdata.projectnaptha.com/4.0.0_best/chi_sim.traineddata.gz

**Comment by lmk123** [comment]
如果不是这个问题的话，那你试试把 Chrome 升级到最新版本然后重启下电脑试试。

**Comment by Dunky-Z** [comment]
>

**Comment by Dunky-Z** [comment]
无法下载，网络出错。这个功能必须要经过这一步吗？因为是内网，应该没法在线下载这个包。

**Comment by lmk123** [comment]
> 这个功能必须要经过这一步吗？

是。

或者你可以改为使用百度的文字识别——但是这也是要用到网络的。

**Comment by Dunky-Z** [comment]
已解决，谢谢，开个会员支持一下
