### ISSUE TITLE
划词翻译的永久会员，是否有第三方翻译服务使用次数的限制？如果有，扣费的时候会有提醒吗？

### ISSUE THREAD

**Issue by Stephen-Albert** [hcfyapp/crx-selection-translate#1382]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，现有 PDF 不支持标记功能，导致我无法在 pdf 上标记内容。

**你想要如何解决你的问题？**
比如，添加 PDF 标记功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
比如，如果划词翻译无法添加 PDF 标记功能，那么至少允许我在别的 PDF 软件里进行划词翻译。

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。

**Comment by lmk123** [comment]
划词翻译的会员和第三方服务就好比汽车和汽油的关系，会员服务就是汽车，你自行申请的第三方服务就是汽油。在申请第三方服务的文档里也提醒过了，你使用的第三方服务扣费都是在第三方平台进行的，除非你用“翻译积分”。

**Comment by lmk123** [comment]
每个第三方服务的免费额度以及超出额度之后各平台的收费标准都标注在文档里了，划词翻译只是调用了这些平台的服务，而服务如何计费、何时扣费、是否有提醒、何时提醒是由第三方平台决定的，这就好比你开着汽车去加油站加油一样，收你油钱的是加油站，不是卖汽车的 4S 店。

我在每个服务的申请文档里都标注了各平台是如何计费、何时扣费以及是否会超额扣费的，以百度翻译为例：

> 百度翻译是按天计费的，目前还不确定超过 200 万字符后会不会给出提示，强烈建议选择标准版使用。如果你一定要使用高级版，那么建议在百度翻译开放平台里充值 1 元，然后在[财务总览](https://fanyi-api.baidu.com/api/trans/product/desktop?req=account)页面设置余额低于 1 元就短信提醒。但是请注意，按天计费意味着在一天之内无论产生了多少使用量都不会有实时提醒，只会在每天结算的时候（一般是凌晨一点）才会有提醒

总的来说：划词翻译的会员解除了使用划词翻译内各个功能的限制，但是划词翻译用到的第三方服务是由各个平台提供、定价并收费的。

为什么这些第三方服务会收费的原因也写过了：https://hcfy.app/docs/faq/#why-apply

你理解为划词翻译是 4S 店、第三方服务是加油站就能明白了。4S 店卖了汽车给你，但是以后加油还是要你去加油站加的，加油的钱当然也是加油站收的、扣了多少钱当然也是加油站告诉你的。

**Comment by Stephen-Albert** [comment]
> 每个第三方服务的免费额度以及超出额度之后各平台的收费标准都标注在文档里了，划词翻译只是调用了这些平台的服务，而服务如何计费、何时扣费、是否有提醒、何时提醒是由第三方平台决定的，这就好比你开着汽车去加油站加油一样，收你油钱的是加油站，不是卖汽车的 4S 店。
> 
> 我在每个服务的申请文档里都标注了各平台是如何计费、何时扣费以及是否会超额扣费的，以百度翻译为例：
> 
> > 百度翻译是按天计费的，目前还不确定超过 200 万字符后会不会给出提示，强烈建议选择标准版使用。如果你一定要使用高级版，那么建议在百度翻译开放平台里充值 1 元，然后在[财务总览](https://fanyi-api.baidu.com/api/trans/product/desktop?req=account)页面设置余额低于 1 元就短信提醒。但是请注意，按天计费意味着在一天之内无论产生了多少使用量都不会有实时提醒，只会在每天结算的时候（一般是凌晨一点）才会有提醒
> 
> 总的来说：划词翻译的会员解除了使用划词翻译内各个功能的限制，但是划词翻译用到的第三方服务是由各个平台提供、定价并收费的。
> 
> 为什么这些第三方服务会收费的原因也写过了：https://hcfy.app/docs/faq/#why-apply
> 
> 你理解为划词翻译是 4S 店、第三方服务是加油站就能明白了。4S 店卖了汽车给你，但是以后加油还是要你去加油站加的，加油的钱当然也是加油站收的、扣了多少钱当然也是加油站告诉你的。

很生动形象的比喻。感谢解答！
