### ISSUE TITLE
电脑关机后，划词翻译需要重新输入密码登录，有点麻烦，希望改进下~

### ISSUE THREAD

**Issue by Stephen-Albert** [hcfyapp/crx-selection-translate#1383]
我是划词翻译终身会员。使用的是 Windows 10 Chrome 浏览器，隔了一天，我重新打开电脑，浏览网页，要启用划词网页翻译时，它提示我非会员每天只能免费试用三次，我就不得不再去划词翻译那重新登陆我的会员，希望能改进下这个功能。btw我在其他网页输入密码，谷歌都会提示我是否记住密码，但划词翻译没有，导致每次都得手输密码，也比较麻烦，这个也可以解决吗？

**Comment by lmk123** [comment]
划词翻译的账号只会在 7 天未使用划词翻译的情况下才会下线。你出现这个问题可能有以下原因：

1. 账号限制了同时最多登录 4 个浏览器，所以当你登录第 5 个浏览器的时候，第一次登录的浏览器账号会下线；
2. 如果不是上面这个原因，那么说明登录状态没有正确的保存在浏览器里。我猜测可能是由于别的插件阻止或者清除了划词翻译的 cookies，你可以试一试关掉其它所有插件，然后登录划词翻译账号后再重启电脑，看看账号还会不会掉线。

> 每次都得手输密码

不能解决，因为登录划词翻译的页面是在扩展程序内部而不是一个普通的网页，所以谷歌浏览器不会提示你记住密码。这是谷歌浏览器自己不愿意提示的，不是划词翻译不让它提示的。如果你用火狐的话，火狐是会提示的。

**Comment by Stephen-Albert** [comment]
> 划词翻译的账号只会在 7 天未使用划词翻译的情况下才会下线。你出现这个问题可能有以下原因：
> 
> 1. 账号限制了同时最多登录 4 个浏览器，所以当你登录第 5 个浏览器的时候，第一次登录的浏览器账号会下线；
> 2. 如果不是上面这个原因，那么说明登录状态没有正确的保存在浏览器里。我猜测可能是由于别的插件阻止或者清除了划词翻译的 cookies，你可以试一试关掉其它所有插件，然后登录划词翻译账号后再重启电脑，看看账号还会不会掉线。
> 
> > 每次都得手输密码
> 
> 不能解决，因为登录划词翻译的页面是在扩展程序内部而不是一个普通的网页，所以谷歌浏览器不会提示你记住密码。这是谷歌浏览器自己不愿意提示的，不是划词翻译不让它提示的。如果你用火狐的话，火狐是会提示的。

**Comment by Stephen-Albert** [comment]
> > 划词翻译的账号只会在 7 天未使用划词翻译的情况下才会下线。你出现这个问题可能有以下原因：
> > 
> > 1. 账号限制了同时最多登录 4 个浏览器，所以当你登录第 5 个浏览器的时候，第一次登录的浏览器账号会下线；
> > 2. 如果不是上面这个原因，那么说明登录状态没有正确的保存在浏览器里。我猜测可能是由于别的插件阻止或者清除了划词翻译的 cookies，你可以试一试关掉其它所有插件，然后登录划词翻译账号后再重启电脑，看看账号还会不会掉线。
> > 
> > > 每次都得手输密码
> > 
> > 
> > 不能解决，因为登录划词翻译的页面是在扩展程序内部而不是一个普通的网页，所以谷歌浏览器不会提示你记住密码。这是谷歌浏览器自己不愿意提示的，不是划词翻译不让它提示的。如果你用火狐的话，火狐是会提示的。

1.我知道了，是因为我清理了cookie；
2.嗯嗯好的，感谢及时解答,并提出第二解决方案。
