### ISSUE TITLE
能否在不同的电脑上登录同一用户

### ISSUE THREAD

**Issue by 945716994** [hcfyapp/crx-selection-translate#1384]
**没有这个功能（改进）的时候，你遇到了什么问题？**
我每一次从笔记本换成台式，都得重新登录一遍。

**你想要如何解决你的问题？**
同一个用户可以在多台电脑上登录。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
可以限制登录设备数量。

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。

**Comment by lmk123** [comment]
账号是可以在不同电脑上同时登录的。划词翻译的账号不是根据设备来区分的，而是根据登录进去的浏览器来区分的。账号最多同时登录四个浏览器，当你登录第五个浏览器的时候，你第一次登录的浏览器就会下线。

所以，出现这个问题的原因可能有：

1. 你在笔记本上 + 台式机上登录的浏览器超过了 4 个
2. 可能是你安装的其它插件清除了浏览器内的 cookies

**Comment by lmk123** [comment]
如果你确认不是上面两点造成的，那么你可以继续留言，我会持续跟进。
