### ISSUE TITLE
在chrome里，是否能在划词翻译内置的PDF阅读器内使用CrxMouse这个扩展插件

### ISSUE THREAD

**Issue by zhangjiakouzf** [hcfyapp/crx-selection-translate#1385]
**没有这个功能（改进）的时候，你遇到了什么问题？**
CrxMouse是一个鼠标手势扩展插件，我在里面定制了一些其他功能，在pdf阅读器里无法使用crxmouse的话，我需要再打开其他页面才能实现那些功能

**你想要如何解决你的问题？**
能在内置pdf阅读器内使用crxmouse插件

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
暂时想不到

**补充信息**

**Comment by lmk123** [comment]
不能，因为划词翻译内置的 PDF 阅读器属于划词翻译扩展内部（你应该注意到了浏览器地址栏左侧写着“划词翻译”），而扩展之间是没有办法对其它扩展的内部产生效果的。
