### ISSUE TITLE
想请教一下 让插件固定在这个页面是怎么实现的呢

### ISSUE THREAD

**Issue by 987603843** [hcfyapp/crx-selection-translate#1386]
想请教一下 让插件固定在这个页面是怎么实现的呢
![image](https://user-images.githubusercontent.com/49261839/168606893-a61c69b5-6c1a-4061-a5ea-060c23334ea7.png)

**Comment by lmk123** [comment]
如果你说的“固定”是指左上角的图标点了之后不随网页滚动的话，那就是 CSS 的 `position: fixed`

**Comment by 987603843** [comment]
不是的 我想请教的是 怎么让插件 出现的时候像这个图片里面一样是一个可拖拽的窗口，点击页面空白的地方不会让插件收起来，还是保持窗口

**Comment by lmk123** [comment]
从你的这个提问来看，我猜测（只是猜测 :joy:）你可能对 HTML、CSS 和 DOM 方面的 API 了解比较少。

要实现这一系列功能，你至少要了解一下几点：

- CSS 中的 display（控制显示 / 隐藏）
- mouse event + CSS 中的 position（拖拽功能）

如果你了解上面这两点，那么你就知道怎么实现了。
