### ISSUE TITLE
网页全文翻译的按钮在某些网站的交互问题

### ISSUE THREAD

**Issue by iFHiGM** [hcfyapp/crx-selection-translate#1388]
**没有这个功能（改进）的时候，你遇到了什么问题？**
- 功能：网页全文翻译
- 问题：在Firefox上使用此插件的网页全文翻译功能，在某些网站上，翻译设置按钮停靠在屏幕右下侧边后无法被触发（无法通过鼠标扫过的方式使设置弹出，而且停靠显示面积比正常情况下小），同时鼠标也无法将其触发，如果点击，则又会触发浏览器的滚动条导致无法点击到插件的设置按钮。
- 正常场景/网站：medium article([example url](https://omarzahran.medium.com/a-final-farewell-to-the-ipod-32aea71846d1)), conan doc([example url](https://docs.conan.io/en/latest/)), etc.
- 问题场景/网站：github([example url](https://github.com/deb0ch/emacs-winum))
- 图片信息：
  1. 正常网站的按钮大小：
![image](https://user-images.githubusercontent.com/44024833/169230417-e12c2f57-557e-4d15-8eab-00e130c5d6df.png)

  2. 问题网站的按钮大小：
![image](https://user-images.githubusercontent.com/44024833/169230511-8f106176-8d22-4f2a-939d-c4e0e7c89cf1.png)

  3. 在问题网站的场景下，如果我要点击这个按钮，那么浏览器的滚动条会遮挡操作：
![image](https://user-images.githubusercontent.com/44024833/169230779-41421627-dd89-43bb-ae0f-25cc085d3444.png)

**你想要如何解决你的问题？**
最好是跟正常的网站一样。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
使用快捷键强行唤出按钮设置。

**环境信息**
- 操作系统：windows11 22H2 (25115.1000)
- 浏览器：Firefox Nightly 102.0a1 (2022-05-15) (64-bit)
- 插件版本：v8.7.3

**其他信息**
另外，我尝试在Edge(Version 103.0.1260.0 (Official build) canary (64-bit))中安装同版本插件并打开问题网站，发现显示和触发正常。

**Comment by lmk123** [comment]
我的 macOS 用 Firefox 100 在你提供的问题网站 https://github.com/deb0ch/emacs-winum 上没有重现这个问题。我用 Chrome 也试过了，没有重现。

我猜测的可能的解决方案：

- 用正式版本的 Firefox 试试。Nightly 版本不在划词翻译的支持范围之内。
- 把其它所有扩展都关闭、只保留划词翻译然后试试

**Comment by iFHiGM** [comment]
- 正式版本的Firefox（Windows）：没有重现
- 关掉其他所有扩展：可以重现
- 在linux（我是arch）上尝试最新的Firefox-nightly（102.0a1）：没有复现

我觉得可能是我的环境有什么问题，这个单子我就先关掉？

**Comment by lmk123** [comment]
有可能是 Firefox Nightly 的问题，毕竟不是稳定版本。

这个 单子我先关了，如果未来 Firefox 的稳定版本出现了这个问题，你可以重新打开，我会修复。
