### ISSUE TITLE
网页全页翻译，使用deepl、百度翻译专业版等出现意外

### ISSUE THREAD

**Issue by hekai123** [hcfyapp/crx-selection-translate#1390]
## 基本信息

划词翻译版本：8.73
浏览器版本：猎豹浏览器V8.0.0.21634
操作系统：win10

## 重现问题的步骤

1.
翻译错误，显示如下结果：
翻译结果时出错。错误信息：找不到source的语种下拉框
### ![搜狗截图20220520154157](https://user-images.githubusercontent.com/12723848/169480683-4b237e87-fe0a-4098-b901-10b1777bcf56.png)

2.
3.

**Comment by lmk123** [comment]
猎豹浏览器不在支持范围内。我使用 Chrome 版本 101.0.4951.64（正式版本） (arm64)、用 DeepL 全文翻译了本页面，没有问题：

<img width="579" alt="截屏2022-05-20 16 34 19" src="https://user-images.githubusercontent.com/5035625/169488622-e5f1f252-4215-48c2-86e8-6ea0b9a91d00.png">

麻烦用最新版本的 Chrome 浏览器试一下，如果还是不行，请提供出现此问题的网址，我再试一下

**Comment by lmk123** [comment]
由于长时间无反馈，所以我先关闭了，但你仍然可以继续留言。当你提供我需要的信息后，我会重新打开此 issue 并继续更进
