### ISSUE TITLE
生词本或者扩展外发结果

### ISSUE THREAD

**Issue by ixqbar** [hcfyapp/crx-selection-translate#1391]
**没有这个功能（改进）的时候，你遇到了什么问题？**
能不能提供收纳生词本的功能，或者提供接口用户选择后可以通过配置的接口单次结果外发出来

**你想要如何解决你的问题？**
我想本地搭建一个服务，能够拿到每次翻译想收纳的单词及对应翻译结果

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
生词本
**补充信息**
期待

**Comment by lmk123** [comment]
> 生词本

现在的收藏夹其实充当了“生词本”，不过功能很少。未来会尝试多增加一些生词本相关的功能。

> 提供接口用户选择后可以通过配置的接口单次结果外发出来

这是划词翻译在未来准备推出的功能“Webhook”，可以在触发特定事件时通知服务器（比如获取到翻译结果时将翻译结果发送给你的服务器）
