### ISSUE TITLE
独立翻译窗口无法打开

### ISSUE THREAD

**Issue by DH455** [hcfyapp/crx-selection-translate#1392]
## 基本信息
划词翻译版本：v8.7.3
浏览器版本：Microsoft Edge  版本 103.0.1255.0 (正式版本) dev (64 位)
操作系统：Windows 11 家庭中文版 21H2

## 重现问题的步骤
1.笔记本电脑外接显示屏的情况下使用“独立翻译窗口”
2.将独立翻译窗口拖至副屏并改变窗口大小

### 预期行为
后续仍能正常使用独立翻译窗口
### 实际行为
无法使用独立窗口，显示：“打开独立窗口时发生了一个错误：Invalid value for bounds. Bounds must be at least 50% within visible screen space.”

### 补充信息
此问题与浏览器插件“unblock origin”无关，断开副显示器的连接情况亦无变化。
上月通过重装插件的方法解决了此问题，但无多时再次出现此问题

**Comment by lmk123** [comment]
确实会有这个问题。我一直都没有用过副屏，所以没有针对副屏做过适配。

等我整个显示器了修复这个问题 :joy:

**Comment by Orienser** [comment]
我也出现了一样的问题，但不是在副屏上。
显示屏是4K，Windows文字缩放为150%，打不开独立窗口，但把文字缩放改为100%后可正常打开。

**Comment by helloLT** [comment]
#  相同的问题，但出现在同步设置后

#### 我也出现了相同的问题以及相同的报错，我这里提供而外的信息：错误出现在了同步了设置后。怀疑是同步后的独立窗口位置数值出现异常，我在设置中查看到的参数如下。
-------------------------------
```
独立翻译窗口
位置和宽高
上边距：-32000px 左边距：-32000px
宽度：160px 高度：28px
```
------------------------------

#### 是否有什么办法重置独立窗口的数值来解决我的问题？

**Comment by lmk123** [comment]
@helloLT 目前只能通过在控制台输入代码的方式改变数值，步骤如下：

1. 打开划词翻译的设置页
2. 鼠标右键 -> 选择【检查】，浏览器底部应该会弹出一个窗口
3. 将窗口切换到 `Console`
4. 输入下面的代码

```js
chrome.storage.local.set({panelPos:{
    width: 270,
    height: 500,
    left: 100,
    top: 100,
}})
```

示例图如下：

<img width="432" alt="image" src="https://user-images.githubusercontent.com/5035625/172118752-d4c04194-ba71-4d34-b804-b2aeb0f1c8ae.png">

**Comment by lmk123** [comment]
在划词翻译 v8.7.5 中，我在设置页里给独立翻译窗口添加了一个“重置窗口位置与大小”的按钮，之后如果遇到双屏幕导致独立窗口不可见的话，就可以使用这个按钮。

对双屏幕的支持可以跟进 #1081

**Comment by DH455** [comment]
> 在划词翻译 v8.7.5 中，我在设置页里给独立翻译窗口添加了一个“重置窗口位置与大小”的按钮，之后如果遇到双屏幕导致独立窗口不可见的话，就可以使用这个按钮。
> 
> 对双屏幕的支持可以跟进 #1081

问题得到了解决，感谢您迅速而有效的改进
