### ISSUE TITLE
希望增加全局默认是否启动划词翻译开关

### ISSUE THREAD

**Issue by hnboy2005** [hcfyapp/crx-selection-translate#1393]
**没有这个功能（改进）的时候，你遇到了什么问题？**
每次重新打开浏览器 默认划词开关是启动的 但是并不是所有的场景都需要默认打开划词翻译功能 所以每次我都要按快捷键关闭划词翻译

**你想要如何解决你的问题？**
希望有一个全局快关 可以默认关闭划词翻译功能. 需要的时候再打开.

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
暂无

**补充信息**
暂无

**Comment by lmk123** [comment]
这个开关是有的，即【设置】-【网页划词翻译】-【网址筛选】的【在所有网站中禁用网页划词】选项，勾选之后，在任何网站内划词都不会弹出按钮，而快捷键其实就是在切换这个开关。

根据你的描述，我猜测你的需求是以下两点之一：

- 如果你勾选了这个选项，但重启浏览器后划词仍然会弹出按钮，那这就是一个 bug。如果是这样的情况，麻烦提供更多信息，比如你的浏览器、操作系统、划词翻译版本，我会在能重现此 bug 之后修复它。
- 如果你是希望在每次浏览器关闭后都自动勾选上这个选项，那么目前确实没有这个功能。不过，我个人认为此功能似乎没有必要？如果你不常用话此功能，那么当你不需要的时候，按一下快捷键关闭即可。

请告诉我你想表达的是哪一点，然后我们可以继续讨论。

**Comment by lmk123** [comment]
由于长时间无回复，这个 issue 我就先关闭了，但你可以随时留言，届时我会继续跟进。
