### ISSUE TITLE
deepl 多用几次就这样了

### ISSUE THREAD

**Issue by yyy33** [hcfyapp/crx-selection-translate#1394]
## 基本信息

划词翻译版本：v8.7.3
浏览器版本：Chromium 100.0.4896.88 Arch Linux
操作系统：Linux x550vc-yyy 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux

## 重现问题的步骤

1.打开deep网页翻译
2.开始几次可以用
3.多用几次就提示这样了

### 预期行为
不提示超时
### 实际行为
提示超时
### 补充信息

![2022-05-23_21-22](https://user-images.githubusercontent.com/51548147/169829886-376ff0b5-1df4-48e9-a346-6bc77fe18029.png)

**Comment by lmk123** [comment]
请先按照文档排查问题：https://hcfy.app/docs/services/free#deepl

如果按照文档仍然没有排查出问题，欢迎继续留言，我会跟进。
