### ISSUE TITLE
每次翻译的网站里包含中文时，就不翻译了。

### ISSUE THREAD

**Issue by Aaron009** [hcfyapp/crx-selection-translate#1396]
翻译网址：
https://www.linkedin.com/company/supabase

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/3838050/171099543-52a66b8c-92fb-4211-a7fb-bf6565305319.png">

没有翻译，直接显示原文了。

**Comment by lmk123** [comment]
感谢反馈，这是一个已知问题，将在之后的版本中改进。你可以在 #943 查看进度。
