### ISSUE TITLE
能否加入网站屏蔽功能

### ISSUE THREAD

**Issue by yygcom** [hcfyapp/crx-selection-translate#1397]
有的网站会莫名报错150.js，而且不需要进行划词翻译，能否设置不在那个域名下使用呢

**Comment by lmk123** [comment]
我更好奇你说的 150.js 的错具体是什么。

如果有 bug，应该优先解决 bug，而不是用另一个功能来掩盖这个 bug。

**Comment by yygcom** [comment]
就是提示的是这个插件下的150.js错误，也不知道是怎么的，吧插件关闭就没报错了

**Comment by yygcom** [comment]
因为这个站点是加了端口的http，不知道是不是和什么有冲突

**Comment by lmk123** [comment]
> 就是提示的是这个插件下的150.js错误

仅凭这一句话我没法重现你的问题 😂

你先看一下 https://hcfy.app/docs/issues/#bug 按照格式提供一个我能重现你的问题的步骤，一旦我能重现，我就会修复你的问题

**Comment by yygcom** [comment]
这个是内部测试用的站点，其他的页面我也刷新看了没遇到过

**Comment by lmk123** [comment]
那就麻烦了。如果不能重现问题，那我也就没法解决这个问题。

回到你所说的“能否设置不在那个域名下使用”，虽然技术上是可以做到的但我认为这样做性价比不高。

技术上确实可以做到在特定的页面完全不注入划词翻译的任何代码，这样一来，当然也就不会出现由划词翻译引起的错误了，但同时，在这个页面上，划词翻译的**所有功能**都将失效——划词、截图、网页全文、快捷键、右键菜单等等——但在我看来，这么做就好比为了解决房子里的一只老鼠而把整个房子都烧了一样，可以但没必要。所以，我还是倾向于直接解决 bug。

就算是内部网站也是能提供重现步骤的，比如你自己建一个新的项目运行你的前端代码，然后一点点删除代码，直至确定是哪部分代码导致了划词翻译的这个问题，然后你就可以整理一个重现步骤了。

所以，这个 issue 我就先关闭了，如果你能提供重现步骤，欢迎新开一个 issue
