### ISSUE TITLE
希望增加一个把音标显示的功能

### ISSUE THREAD

**Issue by lulu002** [hcfyapp/crx-selection-translate#1400]
**没有这个功能（改进）的时候，你遇到了什么问题？**
当我选中一个词的时候，我只看到这个词的中文翻译，我想知道这个单词是如何念的，但是我又没有办法把声音放出来，要是有音标显示就好了。

**你想要如何解决你的问题？**
在翻译界面的设计页面增加一个是否显示音标的设置，如果勾选了，则选中一个单词的时候，音标随着中文一起显示，参考有道PC版的作法

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
无
**补充信息**
可以参考有道词典的做法，显示音标。

**Comment by lmk123** [comment]
即使没有提供音标，你也是可以点击翻译服务名称右边的喇叭按钮来朗读它的：

<img width="171" alt="截屏2022-05-31 17 34 19" src="https://user-images.githubusercontent.com/5035625/171142777-222be103-c60c-4504-b6f8-b0edc3581dfe.png">

至于音标的话，谷歌翻译是提供拼音 / 音标的，有道、必应也是有的，但如果翻译服务自己不提供音标，那么我也无法“变”出来 😂
