### ISSUE TITLE
希望收藏夹能够有背单词的功能和收藏夹导出的功能

### ISSUE THREAD

**Issue by whuib** [hcfyapp/crx-selection-translate#1402]
1. 收藏夹中收藏的都是单词，收藏的单词过多的话每次打开收藏夹背诵记忆起来不是很方便，希望能添加背单词的功能。可以参考记忆曲线，设置成单词卡片的形式，每次记忆有三个选项：忘记、模糊、熟练。按照艾宾浩斯曲线来设置每天的记忆内容。
2. 收藏夹添加目录，每次收藏可以选择默认的收藏夹或者某个新建的收藏夹
3. 收藏夹可以导出，如果能把收藏夹内容导出，方便放到一些记忆软件里进行学习（如果不准备开发背单词功能的话）

**Comment by lmk123** [comment]
抱歉，忘记回复你了 :joy:

这三点之前也有用户提过了，不过收藏夹这一块在我这里优先级比较低，所以一直没有安排优化。我目前的重心仍然在划词、网页全文翻译等功能，以及最近正在开发桌面端的划词翻译。

单词本我应该不会做，不过导出以及收藏夹目录可能会做在桌面端划词翻译中。
