### ISSUE TITLE
希望能给翻译按钮设置关闭打开的选项

### ISSUE THREAD

**Issue by whuib** [hcfyapp/crx-selection-translate#1403]
我习惯先选中文本，然后使用快捷键翻译。
如果在网页上选中中文或者简单的英文的话，不需要翻译，但是鼠标的位置会出现翻译按钮，这样看起来不太美观。希望能设置关闭翻译按钮，这样使用快捷键翻译就会很美观

**Comment by lmk123** [comment]
在【设置】【网页划词翻译】【网址筛选】中勾选【在所有网站中禁用网页划词】即可。
