### ISSUE TITLE
希望增加自动翻译指定网站的功能

### ISSUE THREAD

**Issue by ooeooo** [hcfyapp/crx-selection-translate#1404]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如twitter.com，目前需要手动去点击全文翻译

**你想要如何解决你的问题？**
可以添加一个列表，访问列表内网站时会自动翻译

**补充信息**
参考实现：https://github.com/FilipePS/Traduzir-paginas-web

如果更高级一点，可以自定义翻译HTML标签就更好了！
比如增加一个编辑框，可以自定义要翻译的内容Xpath
我想翻译twitter网页内的评论内容，只需要添加 //*[@id]/span 就可以了

**Comment by lmk123** [comment]
> 希望增加自动翻译指定网站的功能

目前推荐的做法是开两个浏览器窗口，然后只在其中一个浏览器窗口中勾选“在当前窗口自动开启”。我觉得这种方法相比于通过网址来判断的话更灵活一些，因为：

- 无需维护一个网址列表
- 无需频繁添加 / 删除网址。在某些网站里，你可能有时候想自动打开，有时候又不想，而勾选了“在当前窗口自动开启”之后，此窗口内就会对所有网页自动开启，适合当你想要一直自动开启时使用。

> 比如增加一个编辑框，可以自定义要翻译的内容Xpath

这个点子不错，已新开了一个 issue，将在之后的版本中加入 https://github.com/hcfyapp/crx-selection-translate/issues/1406

**Comment by ooeooo** [comment]
目前我用快捷键翻译网页，ALT+Q，非常方便
