### ISSUE TITLE
Esc 取消选中优先级高于关闭面板

### ISSUE THREAD

**Issue by WhiverFichos** [hcfyapp/crx-selection-translate#1405]
**没有这个功能（改进）的时候，你遇到了什么问题？**
Esc 取消选中优先级高于关闭面板。

**你想要如何解决你的问题？**
修改 Esc 优先级，选中且面板打开时，Esc 先关闭面板。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
换个快捷键？

**补充信息**
Ubuntu 22.04 LTS
Firefox 91.9.1esr
划词翻译 v8.7.4

**Comment by WhiverFichos** [comment]
另外，我没有找到隐藏翻译按钮的选项。有一个选项勾选后隐藏翻译按钮，但选中文本会立刻翻译。
我现在的做法是改显示位置到看不见的地方，如 `99999, 99999`。

**Comment by lmk123** [comment]
> 另外，我没有找到隐藏翻译按钮的选项。有一个选项勾选后隐藏翻译按钮，但选中文本会立刻翻译。

你需要的其实是【在所有网址中禁用网页划词】

**Comment by lmk123** [comment]
> Esc 取消选中优先级高于关闭面板。

我手头没有 Ubuntu 环境，然后我用 macOS Firefox 101 没有重现这个问题。我的重现步骤是：

1. 打开 https://hcfy.app
2. 选中一个词，然后点击按钮弹出弹窗
3. 按下 Esc

然后，窗口就按照预期关闭了，并不是你所说的先取消了文字选中。

建议：

- 把 Firefox 升级到最新版 101 然后再试试看
- 如果还是不行，那我感觉像是 Firefox 在 Ubuntu 上的问题

**Comment by WhiverFichos** [comment]
已解决，原因为扩展冲突。感谢。不好意思给您添麻烦了。
