### ISSUE TITLE
划词翻译显示结果后如果鼠标动了浮窗应该自动关闭

### ISSUE THREAD

**Issue by xiaofang168** [hcfyapp/crx-selection-translate#1407]
**没有这个功能（改进）的时候，你遇到了什么问题？**
每次需要手动按esc或点击关闭，麻烦

**你想要如何解决你的问题？**
划词翻译后，鼠标离开选中的文本后就不需再显示了，自动关闭浮窗即可（鼠标不动就不关闭）

**Comment by xiaofang168** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/6174626/173169892-10a3fd72-ffca-4818-bd7e-f0c3af99e3b6.png">

**Comment by xiaofang168** [comment]
发现鼠标点一下空白处也可以关闭。。。。

**Comment by xiaofang168** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/6174626/173170056-c23a1632-c2bf-49d9-9f1f-4dca6ecc8de0.png">

**Comment by lmk123** [comment]
感觉是一个没必要添加的功能，就如你所说，点击空白处就能关闭的。

比起动一下鼠标就关闭，我觉得点一下空白处更合适，毕竟说不定用户还需要在面板上按一些按钮啥的
