### ISSUE TITLE
网页全文翻译无效

### ISSUE THREAD

**Issue by Liquidlkw** [hcfyapp/crx-selection-translate#1408]
## 基本信息

划词翻译版本：V8.7.4
浏览器版本：chrome
操作系统：windows 10

## 重现问题的步骤

https://www.youtube.com/watch?v=t5CIs0jDqC8&ab_channel=CrunchyrollCollection
或者Google搜索页面使用网页全文翻译

### 预期行为
有中文翻译结果

### 实际行为
翻译结果任然为英文原文

**Comment by lmk123** [comment]
对于中英混合的网页，全文翻译确实会出现这个问题。目前的目标语种是由翻译服务自行决定的，之后会通过添加源语种 / 目标语种的形式来确定翻译结果的语种，后续进展可以跟进 #943
