### ISSUE TITLE
独立窗口无法打开

### ISSUE THREAD

**Issue by Zawinzala** [hcfyapp/crx-selection-translate#1409]
## 基本信息

划词翻译版本：最新版874
浏览器版本：最新版Chrome
操作系统：windows10

## 重现问题的步骤
![image](https://user-images.githubusercontent.com/24386549/173182154-9584c293-fa10-49fd-9d6f-b51f73bb0a12.png)

1.无法打开翻译窗口
2.重装后可以打开
3.登录账号同步配置后无法打开

### 预期行为
打开独立翻译窗口
### 实际行为
浏览器无法打开，
### 补充信息
应该是窗口尺寸的配置问题，但是我无法修改它。

**Comment by lmk123** [comment]
已在 v8.7.5 中解决，见 https://github.com/hcfyapp/crx-selection-translate/issues/1392

v8.7.5 现在已经有离线安装包了，你可以用离线安装包升级之后看看还有没有问题

**Comment by Zawinzala** [comment]
哦好的，谷歌商店依然的之前的版本。谢谢你的解答。我去下载离线安装版了。
