### ISSUE TITLE
Vivaldi下"独立翻译窗口" 兼容性

### ISSUE THREAD

**Issue by maboloshi** [hcfyapp/crx-selection-translate#1410]
## 基本信息

划词翻译版本：8.7.5
浏览器版本：Vivaldi 5.3.2679.55 (Stable channel) （64 位） 
操作系统：Windows 10 Version 21H1 (Build 19043.1706)

## 重现问题的步骤

1. 独立翻译窗口

### 预期行为
打开一个特殊的窗口 特定窗口大小以及隐藏各个相关栏(如导航栏 标签栏 书签栏 侧边栏 状态栏)

### 实际行为
打开一个普通的窗口

**Comment by lmk123** [comment]
划词翻译目前仅保证兼容 Chrome、Edge 与 Firefox 浏览器。其它浏览器不在兼容范围，我也没有余力去兼容 :joy:

另外，我猜测这应该是由 Vivaldi 来修复的问题。在 Chrome 浏览器中，独立窗口就是你希望的那样隐藏了导航栏等的窗口。既然 Vivaldi 允许安装 Chrome 的扩展程序，那么它就应该负责兼容 Chrome 扩展程序代码，但显然在独立窗口这一情况上，它没有做到兼容。

建议将此问题反馈给 Vivaldi。

**Comment by maboloshi** [comment]
非常感谢 这个锅确实应该由 Vivaldi 背, 也不知为啥他们没有支持chrome.windows.create的 'type:popup' 参数 https://forum.vivaldi.net/topic/71837/extension-pop-ups-showing-all-ui
