### ISSUE TITLE
阿里翻译永远都是400错误！！！其他API用key都正常

### ISSUE THREAD

**Issue by kakushou** [hcfyapp/crx-selection-translate#1412]
## 基本信息
唯獨阿里翻译永远都是400错误！！！其他api用key都正常   Chrome和edge已是最新版本  卸載重裝劃詞翻譯也無用  請問該怎麼fix？？？

划词翻译版本：8.7.5.1 
浏览器版本：Chrome  版本 102.0.5005.115（正式版本） （64 位）
                      Microsoft Edge   版本 102.0.1245.41 (正式版本)    (64 位)
操作系统：win 11

## 重现问题的步骤

1.按部就班正常操作

### 补充信息
版本8.7.5.1   唯獨阿里翻译永远都是400错误    其他用key的接口都正常   Chrome和edge已是最新版本   卸載重裝劃詞翻譯也無用  請問該怎麼fix？？？

**Comment by lmk123** [comment]
我自己用阿里翻译试了一下，没有出现你这个问题。之前也有一两个用户反馈阿里翻译会出现 400 问题，但都是重装一下划词翻译就恢复正常了，然而我自己从来没有遇到过这个问题。

你可以尝试以下步骤：

1. 关闭其它所有插件，只保留划词翻译
2. 重新填写一遍密钥，确认密钥是正确的
3. 调整一下你的操作系统的时区，确保是北京时区
4. 重启一下电脑

完成以上步骤后，再用阿里翻译试试。

**Comment by ZuiXinK** [comment]
如果申请的密钥步骤没问题的话，大概率是在复制密钥的时候出问题了。我从阿里云那边复制的密钥粘贴过来莫名奇妙开头多了一个空格

**Comment by lmk123** [comment]
确实有这个可能性，我会在下个版本中自动去掉密钥的首尾空格，避免此问题的发生，见 https://github.com/hcfyapp/crx-selection-translate/issues/1560
