### ISSUE TITLE
全文翻译翻译跳转后页面

### ISSUE THREAD

**Issue by Quackgrass** [hcfyapp/crx-selection-translate#1413]
**没有这个功能（改进）的时候，你遇到了什么问题？**
从翻译后页面跳转到的其他页面也会被翻译。

**你想要如何解决你的问题？**
全文翻译不需要始终开启。

**Comment by lmk123** [comment]
我猜是因为你勾选了“在当前窗口自动启用”。

如果不是因为这个，那就是碰上 bug 了，你可以按照提交 bug 的格式重新开一个 issue。
