### ISSUE TITLE
我不登陆还能全文翻译，登录反而总显示反应超时，另外deepl登录后总也连不上了，大家有这样的吗？怎么修复

### ISSUE THREAD

**Issue by feizhibo** [hcfyapp/crx-selection-translate#1415]
chrome 版本 102.0.5005.115（正式版本）
划词翻译 v8.7.5

原来用免费版的时候，网页还都能翻译，deepl也可以划词翻译
成为会员后，反而都不能用了。
怎么修复？

**Comment by lmk123** [comment]
deepl响应超时的问题我发过公告了 https://hcfy.app/blog/2022/06/14/deepl
