### ISSUE TITLE
无法双击启动插件

### ISSUE THREAD

**Issue by Ushnidaye** [hcfyapp/crx-selection-translate#1416]
重装系统前可以双击自动启动插件进行翻译，现在重装以后在部分网站无法通过双击启动插件，例如YouTube和Twitter，原因不明

## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
请按照格式提供足够的信息。如果我没有足以重现你问题的信息，我就没法解决你的问题。
