### ISSUE TITLE
pdf文档翻译错误

### ISSUE THREAD

**Issue by YuHuanTin** [hcfyapp/crx-selection-translate#1418]
## 基本信息

划词翻译版本：8.7.5.1
浏览器版本：Chromium 86.0.4240.198
操作系统：Win10

## 重现问题的步骤

1.在划词翻译中打开pdf文档
2.使用网页全文翻译

### 预期行为
每行英文下对应中文

### 实际行为
中文被嵌入英文中

### 补充信息

![pic_2022-06-21_20-28-07](https://user-images.githubusercontent.com/51024916/174799012-dac6ab2c-b599-4d7d-9e2d-00b739cae45c.png)

**Comment by lmk123** [comment]
这是已知且无法解决的情况，官网中有对此说明：

> 由于 PDF 文件的结构比较特殊，所以网页全文翻译功能在[内置 PDF 阅读器](https://hcfy.app/docs/guides/pdf)里确实是无效的。

来自[网页全文翻译](https://hcfy.app/docs/guides/page)常见问题中的【在内置 PDF 阅读器中无效】
