### ISSUE TITLE
在网页全文翻译中谷歌翻译只是把中文翻译成英语，而不是翻译英语 

### ISSUE THREAD

**Issue by yuyangogo123** [hcfyapp/crx-selection-translate#1419]
## 基本信息

划词翻译版本：8.7.3
浏览器版本：edge
操作系统：win10

## 重现问题的步骤

1.
![image](https://user-images.githubusercontent.com/98162719/175077832-6241b455-b231-45c1-8a23-e9410b290652.png)

2.
![image](https://user-images.githubusercontent.com/98162719/175077954-4012513b-ea88-49d9-b878-788f2023fcd8.png)

3.

**Comment by lmk123** [comment]
麻烦提供一下截图中出现此问题的具体的网址

**Comment by lmk123** [comment]
你遇到的问题可能是因为这个：https://hcfy.app/docs/guides/page#yyy

如果不是的话，麻烦提供一下你截图中出现此问题的具体网址，我会重新打开此工单并继续跟进。
