### ISSUE TITLE
开通会员,付款时没有注意到备注栏

### ISSUE THREAD

**Issue by DD35P** [hcfyapp/crx-selection-translate#1421]
来自作者：为保护隐私，已隐藏订单截图

**Comment by lmk123** [comment]
麻烦提供给我你的划词翻译账号，我会在后台给你把会员加上。

**Comment by DD35P** [comment]
_为保护隐私，已隐藏账号信息_

**Comment by lmk123** [comment]
我已经在后台将你的账号设置为了永久会员，麻烦在【个人中心】确认一下。如有任何问题，欢迎继续留言。

**Comment by lmk123** [comment]
你是不是在 PayPal 里投诉过交易订单？现在我的 PayPal 账号因为你的这次交易订单被禁用了，你那边能撤销投诉吗？
