### ISSUE TITLE
希望做一个导出收藏单词的功能，这样我就可以把收藏的单词打印出来背了

### ISSUE THREAD

**Issue by gnu4cn** [hcfyapp/crx-selection-translate#1422]
**没有这个功能（改进）的时候，你遇到了什么问题？**
没有导出收藏单词功能，我没办法把那些不认识的单词打印出来背。

**你想要如何解决你的问题？**
能够把收藏的单词，导出成打印友好的格式（比如排版良好的 PDF, epub格式），方便打印。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
........

**补充信息**
..........

**Comment by lmk123** [comment]
好的，已提高此功能优先级，后续进展可以关注 #860
