### ISSUE TITLE
网页翻译之后无法点击链接，还原后链接内容消失

### ISSUE THREAD

**Issue by Pylogmon** [hcfyapp/crx-selection-translate#1424]
## 基本信息

划词翻译版本：8.7.5.1
浏览器版本：Firefox 101.0
操作系统：Archlinux 内核版本5.18.6

## 重现问题的步骤

1.打开任意英文网页
2.点击划词翻译进行网页翻译
3.出现问题

### 预期行为
翻译后的文本链接可以正常点击打开
显示原文之后链接正常显示
### 实际行为
翻译后文本链接变成常规文本，无法点击
显示原文之后文本链接部分消失，必须刷新网页才能恢复
#### 原网页：
![图片](https://user-images.githubusercontent.com/59004461/175804595-57b30f5d-d892-48a9-a41c-498e92b1012e.png)
#### 翻译之后：
![图片](https://user-images.githubusercontent.com/59004461/175804697-4748086a-596c-4e9a-be9d-06f653618a64.png)
#### 显示原文之后：
![图片](https://user-images.githubusercontent.com/59004461/175804639-9933180d-8ffd-402d-b94f-163285f2ade4.png)

### 补充信息

无

**Comment by lmk123** [comment]
> 翻译后文本链接变成常规文本，无法点击

在这个网页中，这个行为是符合预期的，原因见[网页全文翻译介绍](https://hcfy.app/docs/guides/page)里常见问题的“译文没有保留原文里的链接”部分

> 显示原文之后文本链接部分消失，必须刷新网页才能恢复

我在 https://github.com/emilk/egui 试了一下，是没有这个问题的，但在你的截图内的应该是另一个网站。麻烦提供一下你出现此问题的具体的网址，之后我会重新打开此 issue。

**Comment by Pylogmon** [comment]
> 我在 [emilk/egui](https://github.com/emilk/egui) 试了一下，是没有这个问题的，但在你的截图内的应该是另一个网站。麻烦提供一下你出现此问题的具体的网址，之后我会重新打开此 issue。

我也试了一下你这个链接，github的readme里边效果是非常完美的，我是在这个网站测试的，而且我上面描述的情况不止是在这个网站出现过。
链接：[https://crates.io/crates/egui](https://crates.io/crates/egui)

**Comment by Pylogmon** [comment]
比如说还有这个网站也有这种问题：

[https://gtk-rs.org/gtk4-rs/stable/latest/book/](https://gtk-rs.org/gtk4-rs/stable/latest/book/)

**Comment by lmk123** [comment]
我在 macOS Firefox 101.0.1 (64 位)  https://crates.io/crates/egui 试了一下，没有出现"链接消失"的问题，如下图：

<details>
<summary>点击查看截图</summary>

<img width="955" alt="截屏2022-06-27 21 32 45" src="https://user-images.githubusercontent.com/5035625/175954154-aa77d4eb-f797-42b6-a3cc-ef65f7da5676.png">
</details>

从你的截图来看，你应该是安装了深色模式之类的插件，你可以把插件关了之后再试试。

**Comment by Pylogmon** [comment]
> 从你的截图来看，你应该是安装了深色模式之类的插件，你可以把插件关了之后再试试。

我确实安装了dark reader,但是我把插件禁用之后还是存在这个问题，而且在测试中我还发现一个现象，希望有用。
我的插件设置是在点击插件图标后网页翻译只显示译文，这样设置的话翻译完成后再点击图标来显示原文就会出现链接消失的情况。
但是如果我设置为点击插件图标后显示原文，然后在右下角菜单中来切换原文和译文，就不会有消失的问题。
