### ISSUE TITLE
网页翻译结果框的宽度

### ISSUE THREAD

**Issue by yantaozhao** [hcfyapp/crx-selection-translate#1426]
网页翻译结果框的宽度，目前是无论字数多少，都是一整行的宽度。

建议：框css样式里添加 `width:fit-content` ，使框的宽度适应内容。

**Comment by lmk123** [comment]
挺好的建议，我试试

**Comment by oiOxOio** [comment]
吐槽下这个logo，能否换个更好看的呢，在没了解插件的功能前差点被这个图标劝退

**Comment by lmk123** [comment]
@oIOxOIo 这个 logo 可能不太好看，但是 9 年来我用的都是这个 logo，如果换掉的话，9 年来积累的“眼熟”的感觉就没了，所以我一直没敢换 :joy:

**Comment by lmk123** [comment]
v9.7.0 开始，划词翻译对网页翻译的译文样式做了优化，现在可以选择别的译文样式如“直线”、”波浪线”这一类，就会只显示跟译文内容一样的长度，所以算是变相的解决了这个问题。
