### ISSUE TITLE
翻译后的页面很奇怪,字竖着的

### ISSUE THREAD

**Issue by balzac233** [hcfyapp/crx-selection-translate#1427]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.
2.
3.

### 实际行为
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/42673039/176370123-0436cec1-4041-4614-9797-e4feb0b0bbc3.png">

**Comment by balzac233** [comment]
就是github的个人设置页面

**Comment by lmk123** [comment]
我试了一下，左侧的菜单确实竖着，不过右侧内容是正常的
<details>
<summary>
  点击查看截图

</summary>

<img width="858" alt="截屏2022-06-30 15 36 06" src="https://user-images.githubusercontent.com/5035625/176620259-07991841-06d1-41e6-b464-b798b6acd98d.png">
</details>

左侧竖着的情况我无能为力，这是由 GitHub 的样式控制的，但你截图右侧是空白，我猜应该是你的 github 没有加载样式。
