### ISSUE TITLE
为什么会员过期后才可以续费??

### ISSUE THREAD

**Issue by Goojoe** [hcfyapp/crx-selection-translate#1428]
**没有这个功能（改进）的时候，你遇到了什么问题？**
为什么会员过期后才可以续费??

**你想要如何解决你的问题？**
修改为在会员期限内可付费

**补充信息**
我不理解,我不理解,我不理解

**Comment by lmk123** [comment]
没有特别的原因，只是想这么设置就这么设置了 :joy:
