### ISSUE TITLE
希望PDF阅读器能自动翻译页面

### ISSUE THREAD

**Issue by Starry202206** [hcfyapp/crx-selection-translate#1429]
- **没有这个功能（改进）的时候，你遇到了什么问题？**  
- 目前PDF阅读器需要鼠标框选内容才能实现翻译，看PDF时间久了这样的操作会很繁琐（很多英文pdf鼠标很不好选定内容）。  
    
  **你想要如何解决你的问题？**  
- 添加像网页翻译一样的功能对PDF进行翻译  
	- 翻到某页后自动会对页面进行翻译  
		- 1、如果PDF不能显示内容在PDF，可翻译在某个弹窗上都很好。  
		- 2、如果不能实现自动翻译，可添加一个全页翻译按钮，按键后翻译单页内容都会大大提升使用便捷度。

**Comment by lmk123** [comment]
这个功能目前对于我来说无能为力，因为在技术上是有难度的。

PDF 文档在转为浏览器的网页后，它的结构非常特殊，跟普通的网页不太一样，就连提取文本都比较困难，所以全文翻译目前没法应用在内置 PDF 阅读器里。
