### ISSUE TITLE
使用网页全文翻译后部分文本没翻译，并且同页的部分中文内容会自动翻译成英文

### ISSUE THREAD

**Issue by Icaruxxx** [hcfyapp/crx-selection-translate#1433]
## 基本信息

划词翻译版本：v8.7.5.1
浏览器版本：edge 103.0.1264.49 
操作系统：windows 10 21H1

## 重现问题的步骤

1.打开网页1https://www.udemy.com/course/absolute-clarity-a-game-plan-for-lasting-self-fulfilment-and-happiness/
2.翻到“要求”一栏
3.设置目标语种首要和次要为中文，开启全文翻译

### 预期行为
网页英文翻译为中文，网页原中文不参与翻译

### 实际行为
1️⃣ =============================
翻译前
![1](https://user-images.githubusercontent.com/8536920/178432678-aefe0888-cf7b-4549-8dd4-4146c385132f.png)

2️⃣ =============================
翻译后
![2](https://user-images.githubusercontent.com/8536920/178432758-310c85d1-54aa-435a-9677-0529f04f8fcb.png)
网页原中文翻译为原文，而部分英文还是原文

### 补充信息
设置目标语种首要和次要为中文和英文，在网页1开启全文翻译极少数情况可以全文翻译，只试过一次,但在网页2https://www.udemy.com/topic/personal-development/ .设置目标语种首要和次要为中文和英文或全中文,部分英文都显示原文

**Comment by lmk123** [comment]
目前对于中英文混合的页面确实会有这个问题。我将这个网页的语种从简体中文改为英语，再用全文翻译的时候，就能正常全都翻译为中文了

而设置中的目标语种只对翻译面板生效，对网页全文翻译是不生效的。不过，我将在之后的版本给网页全文翻译也加上目标语种的选项，应该就能避免这个问题了。后续进展可以关注 #943
