### ISSUE TITLE
翻译pdf时出现问题

### ISSUE THREAD

**Issue by mouju** [hcfyapp/crx-selection-translate#1434]
## 基本信息

划词翻译版本： v8.7.5.1
浏览器版本：Microsoft Edge 版本 104.0.1293.14 (正式版本) beta (64 位)
操作系统：Win10

## 重现问题的步骤

1. 用划词翻译内置的PDF阅读器打开了这篇论文（PDF），这是[这篇论文的链接](https://www.sciencedirect.com/science/article/pii/S0140366421002449)，或许你可以下载下来尝试。就是一篇英文论文，排版是双列和单列混合的，并且会有公式和页尾的批注等等。
2. 点全文翻译（双语模式）

### 预期行为
翻译这篇论文，正如网页上的翻译一样，并且呈现双语
### 实际行为
实际上它似乎把英文翻译成了英文和中文混合的形式，而且译文显示的非常淡，而且只翻译了一小部分的文章，有翻译的部分大多是页眉和页尾，正文几乎没有翻译，并且译文严重错位，我找了半天才把译文和正文对应起来并找到了下面的部分作为示例：
原文：Computer Communications 176 (2021) 282–289
译文：Computer Communications 176 (2021) 282–289

原文：（分为两列）左侧页眉：Z. Huang, H. Ma, S. Wang et al.          右侧页眉：Computer Communications 176 (2021) 282
译文：Z. Huang、H. Ma、S. Wang 等人。计算机通信 176 (2021) 282–289
它甚至把复制pdf网址翻译成了copy pdf url
下面是双语模式和译文模式的截图
![image](https://user-images.githubusercontent.com/48321816/178512082-a0b5447b-fc1b-4142-816f-6b7f2c0a71dc.png)
![image](https://user-images.githubusercontent.com/48321816/178512152-811cae4e-b887-4812-8a02-e591a3155e28.png)
### 补充信息
我尝试在划词翻译的扩展选项->网页划词翻译->文本筛选里开启或关闭忽略中文选项，无效
在划词翻译的扩展选项->网页划词翻译里开关突出显示译文和让译文可编辑，没有任何变化（除了译文变得可以/不可以编辑了之外）
当我切换为译文模式的时候，一部分译文变成了中文，但是仍然有一部分译文像第一个示例那样依然是英文的。

**Comment by lmk123** [comment]
网页全文翻译目前在内置 PDF 阅读器中确实会是这样子，换句话说，网页全文翻译在内置 PDF 内是无效的。PDF 的文件结构较为复杂，我暂时做不到像普通网页那样对 PDF 文件进行全文翻译。

这一点没有在软件里做说明，不过我有写在网页全文翻译的常见问题里：https://hcfy.app/docs/guides/page#faq

**Comment by mouju** [comment]
哇，你回复的好快，谢啦~
