### ISSUE TITLE
在金山文档表格中无法使用划词翻译，右键也不行

### ISSUE THREAD

**Issue by note4** [hcfyapp/crx-selection-translate#1437]
## 基本信息

划词翻译版本：v8.7.5.1
浏览器版本：版本 103.0.5060.114（正式版本） (x86_64)
操作系统：MacOS Monterey

## 重现问题的步骤

1.打开金山文档中的表格文件
2.双击单元格中文字不会出现划词翻译悬浮按钮
3.右键菜单也没有划词翻译选项

### 预期行为
可以像在石墨文档和语雀文档表格一样，划取文字可以出现悬浮按钮，点击按钮对指定的文字进行翻译

**Comment by lmk123** [comment]
我看了一下，确实有这个问题，但这个问题没办法解决 :joy:

这是因为在金山文档里选中文本后，虽然从视觉上看确实是选中了，但实际上那是金山文档模拟的，从代码层面是没有选中的，所以没法读取到选中的文本。

如果你懂技术的话——你可以在选中文本后在控制台运行 `getSelection().toString()`，你会发现读取出来的是空的。
