### ISSUE TITLE
【已修复，通过离线安装包升级到 v8.7.6 即可】deepl 显示：在target语种选择下拉框中找不到语种zh-ZH的选项

### ISSUE THREAD

**Issue by FEDuang** [hcfyapp/crx-selection-translate#1438]
作者的话：我已经在 v8.7.6 中修复了这个问题，请通过离线安装包立刻升级到此版本：

https://hcfy.app/docs/install/#offline

以下是原文
---------------

## 基本信息
划词翻译版本：v8.7.5.1
浏览器版本：Microsoft Edge 103.10.1264.62 
操作系统：Windows 11 家庭中文版：22621.232

## 重现问题的步骤

1.划词翻译

### 预期行为
deepl 显示对应的翻译

### 实际行为
显示：在target语种选择下拉框中找不到语种zh-ZH的选项

### 补充信息
我关闭代理也没有解决，我能正常访问 www.deepl.com

**Comment by AClon314** [comment]
我也出现了相同的情况，也是Edge，能正常访问[deepl.com/translate](https://www.deepl.com/translator)

**Comment by lmk123** [comment]
在 macOS 的 Edge 上没有重现。我找台 Windows 试试

**Comment by lmk123** [comment]
我在 macOS 和 Windows 上的 Edge 都没有重现。Windows 的 Edge 版本号是 103.0.1264.62（正式版本）（64 位）

我的源语种设置的是“自动检测”，目标语种设置的“中文（简体）”，次要目标语种是“英语”，然后在 https://hcfy.app 上划选了一些中文试了一下，DeepL 都能正常显示翻译结果，没有出现这个报错。

另外，我检查了一下代码，理论上不会有 `zh-ZH` 这个语种代号才对。

能否补充一下更多信息？比如你是在哪个网站翻译了什么文本、或者一些相关的设置？

**Comment by libazhahei** [comment]
https://www.reddit.com/r/unsw/comments/rtg8ip/econ2206_vs_econ2209/ 这个网站无法翻译

**Comment by lmk123** [comment]
我重现了 :joy: 正在修复

**Comment by lmk123** [comment]
已修复，正在生成离线安装包

**Comment by lmk123** [comment]
我已经在 v8.7.6 中修复了这个问题，请通过离线安装包立刻升级到此版本：

https://hcfy.app/docs/install/#download
