### ISSUE TITLE
更新离线包后需重新添加秘钥/勾选忽略字符仍会显示翻译结果

### ISSUE THREAD

**Issue by Zyt221** [hcfyapp/crx-selection-translate#1439]
## 基本信息

划词翻译版本：8.7.6
浏览器版本：Chrome 103.0.5060.114
操作系统：Win7

## 重现问题的步骤

1.勾选忽略字符
2.在页面鼠标选中纯标点符号，如句号、分号、引号
3.仍会显示标点符号的翻译结果

**Comment by lmk123** [comment]
这不是由 v8.7.6 引起的 bug，而是一直以来忽略字符的规则中本身就不包含对“句号、分号、引号”的忽略。

“忽略字符”的描述为：如果划选的文本全部都是由**数字、点、括号、空格、横线、加号和圆点**（即 •，多用于密码框）组成的，则不显示翻译按钮或翻译结果。

也就是说，下面这段文本在划选后是不会出现翻译按钮的：

```
23 .-+•(2-)••4
```

但下面这段文本会，因为其中包含句号、分号、引号：

```
23。(2；•“4
```

**Comment by lmk123** [comment]
另外，我在 Chrome 浏览器通过离线安装包升级到 v8.7.6 之后，密钥都还在。只要你没有卸载划词翻译，那么升级过程中应该是不会丢失已经配置好的设置、密钥、收藏夹数据的。

**Comment by Zyt221** [comment]
> 另外，我在 Chrome 浏览器通过离线安装包升级到 v8.7.6 之后，密钥都还在。只要你没有卸载划词翻译，那么升级过程中应该是不会丢失已经配置好的设置、密钥、收藏夹数据的。

是的，先移除了再添加的，了解了
