### ISSUE TITLE
独立翻译窗口在不同显示器上位置不能保持相对

### ISSUE THREAD

**Issue by ringcrl** [hcfyapp/crx-selection-translate#1440]
## 基本信息

划词翻译版本：8.7.5.1
浏览器版本：Chrome 103
操作系统：mac

## 重现问题的步骤

1.在34寸屏幕移动了独立翻译窗口到靠右位置
2.在笔记本上再次打开划词翻译窗口已经超出了像素位置

### 预期行为

划词翻译窗口在不同分辨率屏幕下保持相对位置，而不是绝对像素

**Comment by lmk123** [comment]
在经过一番研究之后，我决定不使用相对位置了，因为太复杂了。

如果只是单个显示器的就很容易，但是如果涉及到两个甚至更多显示器的情况，那么就很复杂了。

举例：一个 13 寸的笔记本电脑外接了一个 27 寸的显示器，现在需要将独立窗口的位置同步到另外一台电脑的 34 寸显示器上。

这里面涉及到多个显示器的排列方式（左右 / 上下）、每块显示器所处的位置（外接显示器在左边还是右边？）等。

这项改进需要投入很多时间不断优化，所以我觉得更好的方案是：

- https://github.com/hcfyapp/crx-selection-translate/issues/1907
