### ISSUE TITLE
DeepL API 错误

### ISSUE THREAD

**Issue by ZhenlingTang** [hcfyapp/crx-selection-translate#1442]
划词翻译版本：v8.7.6
浏览器版本：chrome 103最新正式版
操作系统：win10

问题：
1.页面全文翻译，显示“翻译结果时出错。错误信息：尝试通过密钥、翻译积分、免费试用使用DeepL时均失败了。” 
2.API 密钥之前一直可以用，从7月21日开始到现在，显示错误信息。
3.直接访问DeepL网页版是可以翻译的。

**Comment by lmk123** [comment]
DeepL 最近确实出现了问题，升级到 v8.7.6 即可，见 https://github.com/hcfyapp/crx-selection-translate/issues/1438

如果升级之后还有问题，欢迎继续留言

**Comment by ZhenlingTang** [comment]
已解决，以为自动升级到了v8.7.6，手动升级后可以用了
