### ISSUE TITLE
Google 翻译提示：远程服务器没有相应

### ISSUE THREAD

**Issue by connor-circle** [hcfyapp/crx-selection-translate#1443]
## 基本信息

划词翻译版本：v8.7.6
浏览器版本：Chrome Version 103.0.5060.134 (Official Build) (arm64)
操作系统：macOS12.5

## 重现问题的步骤

1. 在网页中使用划词翻译，Google 翻译无结果

### 预期行为
Google 翻译出现内容
### 实际行为
Google 翻译提示👇
**远程服务器没有相应**
<img width="985" alt="Screen Shot 2022-07-22 at 14 14 44" src="https://user-images.githubusercontent.com/35033310/180375194-8137b4ec-58f5-48f7-8d98-751d92e31017.png">
### 补充信息

我能正常打开translate.google.cn和translate.google.com，并且已将translate.google.com添加到代理中，设置为host-suffix
<img width="1153" alt="Screen Shot 2022-07-22 at 14 30 39" src="https://user-images.githubusercontent.com/35033310/180377462-ec198eb5-1435-475f-be59-6a72e4c1b30a.png">
<img width="1164" alt="Screen Shot 2022-07-22 at 14 28 49" src="https://user-images.githubusercontent.com/35033310/180377514-ed13496d-792b-4e53-b3ea-6d7d58d8d888.png">

此外，我在划词的Google translate设置中选择了`com`和`速度快，但准确率低`两个选项
<img width="462" alt="Screen Shot 2022-07-22 at 14 29 45" src="https://user-images.githubusercontent.com/35033310/180377553-26664f02-ea2c-4a58-8463-a990be9232cf.png">

请问这是划词的问题还是谷歌抽风了呢，谢谢

**Comment by lmk123** [comment]
我用 macOS 12.4 Chrome 版本 103.0.5060.134（正式版本） (arm64) 划词翻译 v8.7.6，并调整成你的设置，是可以正常使用谷歌翻译。我还试着重装了划词翻译，也可以正常使用。虽然 macOS 版本不一样，但我估计跟 macOS 版本没关系。

由于我没法重现、且没有其他用户反馈这个问题，所以我只能给出一些可能性：

- 把 translate.googleapis.com 也加到代理试试
- 有可能是你修改了划词翻译的【有权访问的网站】，如果是的话，需要改回“所有网站”
- 有可能是有什么原因导致虽然你能在网页里正常打开，但划词翻译实际去请求的时候还是不行，但我也猜不到是什么原因

你可以先试一下以上的办法，期待你的反馈

**Comment by connor-circle** [comment]
谷歌抽风吧，我刚刚试了下，没有任何问题了😂，谢谢你的及时回复。
