### ISSUE TITLE
deepl翻译问题

### ISSUE THREAD

**Issue by oppszhengxiwen** [hcfyapp/crx-selection-translate#1444]
## 基本信息

划词翻译版本：
浏览器版本：翻译结果时出错。错误信息：尝试通过密钥、翻译积分、免费试用使用DeepL时均失败了。
操作系统：

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
https://hcfy.app/blog/2022/07/18/deepl
