### ISSUE TITLE
独立窗口打开弹出错误

### ISSUE THREAD

**Issue by caris223** [hcfyapp/crx-selection-translate#1446]
## 基本信息

划词翻译版本：8.7.5.1
浏览器版本：Chrome 
                      版本 103.0.5060.134（正式版本） （64 位）
操作系统：windows 10

## 重现问题的步骤

1. 点击划词翻译扩展按钮
2. 点击下面的"独立翻译窗口"按钮
3

### 预期行为
打开独立翻译窗口
### 实际行为
没有打开,并弹出错误提示:
打开独立窗口时发生了一个错误：Invalid value for bounds. Bounds must be at least 50% within visible screen space.
### 补充信息

![image](https://user-images.githubusercontent.com/103040347/180996715-083000e9-d6cd-4518-96fa-f7daff2ba7be.png)
我用了外接显示器

**Comment by lmk123** [comment]
去划词翻译【设置】-【翻译面板】-【独立翻译窗口】，然后点一下【重置位置与大小】按钮即可。

之后会对外接显示器做优化，进展可以跟进 #1440
