### ISSUE TITLE
开通会员

### ISSUE THREAD

**Issue by channinun** [hcfyapp/crx-selection-translate#1447]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.
2.
3.

### 补充信息
你好我昨天有用paypal購買永久會員 但是到了今天我還不是永久會員
email:chaniiun14@gmail.com

**Comment by lmk123** [comment]
稍等，我确认一下你的订单

**Comment by lmk123** [comment]
已将你的划词翻译账号设置为永久会员，麻烦在划词翻译的个人中心确认一下。
