### ISSUE TITLE
请问能否更换一下绑定的邮箱

### ISSUE THREAD

**Issue by GeniusLv2006** [hcfyapp/crx-selection-translate#1448]
## 我先说明一下，我并不是想要交易我的账号，而是我的QQ邮箱不再使用，想要切换到网易邮箱。如果有必要我可以证明两个邮箱都归我所有。

请问能否更换一下绑定的邮箱？我购买了永久会员，而先前的那个邮箱我不想再使用。我注意到扩展中似乎没有更换邮箱的选项。
谢谢。

**Comment by lmk123** [comment]
我确实可以在后台修改你的邮箱，但我不建议你这么做，因为我在设计之初没有仔细考虑过更换邮箱的场景，而作为账号全局唯一凭证的邮箱，绑定了会员、同步的设置等信息，所以修改之后，我不确定会有什么问题。

我建议如果你的邮箱还能收信的话，做一个邮件转发即可。

**Comment by lmk123** [comment]
由于长时间无回复，所以这个 issue 我先关了，但你仍然可以继续留言，我还是会跟进的。
