### ISSUE TITLE
选择了 美式发音 , 但是不生效, 还是英式发音

### ISSUE THREAD

**Issue by youxdd** [hcfyapp/crx-selection-translate#1449]
![image](https://user-images.githubusercontent.com/17402720/181213568-411f4e9e-1735-46db-8203-b52b5f15734f.png)
选择了 美式发音 , 但是不生效, 还是英式发音

最新版插件

**Comment by lmk123** [comment]
请先选择“始终使用系统语音朗读”，否则会优先用翻译服务自己的语音来朗读，也就用不到你下面的设置了

如果这么设置之后仍然没用，那么麻烦告诉我一下你翻译的是什么单词、用的是哪个翻译服务

**Comment by lmk123** [comment]
对了，这个功能是会员功能，如果你不是会员，那么也是不生效的

**Comment by youxdd** [comment]
@lmk123  解决了 谢谢你!
