### ISSUE TITLE
PDF阅读过程中选中多个区块导致划词翻译悬浮窗未能正确弹出

### ISSUE THREAD

**Issue by ABucket** [hcfyapp/crx-selection-translate#1450]
## 基本信息

划词翻译版本：8.7.6
浏览器版本：Google Chrome 版本 103.0.5060.134（正式版本） （64 位）
操作系统：Windows 10 21H2 操作系统内部版本 19044.1826

## 重现问题的步骤

1. 下载下方链接中的PDF
[Psy.pdf](https://github.com/hcfyapp/crx-selection-translate/files/9216639/Psy.pdf)
2. 在浏览器中打开
3. 选中PDF第二页以“The  nature-nurture issue  recurs  throughout this text ”为开头的整个段落

### 预期行为
弹出划词翻译悬浮窗 正常使用翻译功能
### 实际行为
无划词翻译悬浮窗弹出 无法正常翻译

###额外信息
此PDF中还有多处位置均可复现此问题

**Comment by lmk123** [comment]
我猜你是直接在浏览器里打开了，没有在划词翻译的内置 PDF 阅读器里打开。我在划词翻译的内置 pdf 阅读器里是能正常使用的。

如果不是，欢迎继续留言。
