### ISSUE TITLE
独立翻译窗口 无法弹出

### ISSUE THREAD

**Issue by ningbowang** [hcfyapp/crx-selection-translate#1451]
## 基本信息

划词翻译版本：8.7.6
浏览器版本：103.0.5060.134（正式版本） （64 位）
操作系统：Windows 11 专业版 22H2

## 重现问题的步骤
情况一：
    使用快捷键，CTRL Q   独立翻译窗口无反应

**情况二：
    点击浏览器上划词翻译的拓展图标，再点击弹出窗口最下方的“独立翻译窗口”按钮，弹出错误消息提示框，内容为“打开独立窗口时发生了一个错误：Invalid value for bounds. Bounds must be at least 50% within visible screen space.”**

### 预期行为
使用快捷键后，独立翻译窗口正常弹出。

### 实际行为
使用快捷键后，无任何反应，通过“情况二”的方式时会弹出错误消息提示框，如“情况二”描述，或请看下方截图。
### 补充信息

![Snipaste_2022-07-30_13-43-43](https://user-images.githubusercontent.com/47706456/181876598-220d2a25-42f7-41e9-bf1d-e8ca475b0221.png)

**Comment by ningbowang** [comment]
我回退到 划词翻译8.7.5.1 后能够正常使用，但是又有这个版本“[#1438](https://github.com/hcfyapp/crx-selection-translate/issues/1438) 修复 DeepL 报错"找不到语种 zh-ZH"”的问题，这个起码不那么致命。无法弹出独立窗口让我几乎失去了使用这个插件的初始动力。

**Comment by yufenglyu** [comment]
+1. 无法调用独立翻译窗口

**Comment by lmk123** [comment]
8.7.6 跟 8.7.5.1  之间除了修复了 bug，没有任何其他变动，之所以回退到旧版本能正常使用，是因为卸载划词翻译后，就将独立窗口的位置给重置了。

你应该使用了两个屏幕，那么当你拔掉一个屏幕时，就可能会出现这个问题。

目前可以解决这个问题的办法是：前往【设置】-【翻译面板】-【独立翻译窗口】，点击【重置位置与大小】按钮。之后我会进一步优化双屏幕的情况

**Comment by ningbowang** [comment]
我一直是笔记本屏幕，没有外接过显示器。不过这么说的话可能是我最近在公司电脑登录，公司是27寸，笔记本是15.6，两边的配置同步了造成了这个问题。我又重新升到了8.7.6，然后正常调用。

**Comment by lmk123** [comment]
是的，因为独立窗口位置也是会同步的。看来我不应该同步独立窗口的位置。

**Comment by ningbowang** [comment]
谢谢解答，下次出现这种状况就知道怎么解决了。另外，反馈问题时看到作者正在开发桌面端，好奇问下什么问题考虑的，因为就我目前的使用而言，我的需求是占用小（插件），启动快（开电脑首先开chrome），调用方便（快捷键调用独立窗口），快捷键翻译网页（谷歌右键翻译成中文居然没有快捷键，这也是我付费插件的主要原因），想不到为什么还要有桌面端。

**Comment by lmk123** [comment]
因为扩展程序的能力还是比不上桌面版软件，比如：

- 全局置顶翻译窗口，将独立翻译窗口放在桌面最前面
- 在网页之外的程序里划词翻译。目前扩展程序只能做到在别的程序里复制文本然后按快捷键打开独立翻译窗口

但是，开发桌面版并不意味着我会放弃扩展程序，只是让用户多了一个选项，看个人喜好取舍而已。

**Comment by ningbowang** [comment]
> 是的，因为独立窗口位置也是会同步的。看来我不应该同步独立窗口的位置。

你好，上面说的同步独立窗口位置造成的 无法快捷键调用 的问题今天又稳定复现，以后一直会对我造成影响：白天公司电脑使用之后，同步设置，晚上在家开笔记本快捷键又失效，重置之后就好了。
还请尽快更新修复，谢谢。

**Comment by lmk123** [comment]
好的，后续进展我会更新在 #1440
