### ISSUE TITLE
google划词翻译和全文翻译失效

### ISSUE THREAD

**Issue by Icaruxxx** [hcfyapp/crx-selection-translate#1452]
## 基本信息

划词翻译版本：8.7.6
浏览器版本：edge 103.0.1264.77
操作系统：wn10 21H1

## 重现问题的步骤

1.打开任意一个英文网站
2.使用google划词翻译或全文翻译

### 预期行为
显示中文翻译结果

### 实际行为
google翻译响应超时，没有返回翻译结果
![fy](https://user-images.githubusercontent.com/8536920/182021986-ccdb6573-ef09-4f7c-8bff-d39c0ed366f9.png)

### 补充信息

经常性失效，偶尔正常

**Comment by lmk123** [comment]
在我这里是正常的，且没有收到其他用户的类似反馈。

如果经常失效但偶尔正常，那我猜测这是你所在的网络环境导致的。

谷歌翻译可能会被你所在的网络给禁掉，比如我曾经收到反馈，有的学校会屏蔽域名中带有 google 的网站，这就会导致谷歌翻译没法正常使用。我建议你按照文档的说明 https://hcfy.app/docs/services/free#google 确认你能否正常打开谷歌翻译，排查网络问题。

如果你确认不是你的网络问题，欢迎继续回复。

**Comment by Matt-V50** [comment]
Translate of Google has changed its API address, please make sure the domain `translate.googleapis.com` has been setting done with the proxy request if you have a proxy choice list.
