### ISSUE TITLE
在浏览器开启划词翻译后，控制台会出现警告提示

### ISSUE THREAD

**Issue by lainbo** [hcfyapp/crx-selection-translate#1453]
![image](https://user-images.githubusercontent.com/46062895/182088648-ee04bb39-7b90-4346-b1bb-e968871c46a9.png)
作为一个前端开发人员，在调试自己页面的时候看见这个警告一开始比较困扰，以为是自己的项目出现了什么问题，但是后来发现这个是划词翻译带来的警告

弃用警告说这个api将在109版本中生效，现在Chrome已经来到了103，希望能尽快修复一下，以免届时影响到正常使用

**Comment by lmk123** [comment]
不会影响到正常使用，因为代码用的是 `event.path || event.composedPath()`

我会在下个版本中去掉 .path

**Comment by lmk123** [comment]
已在 #1587 中解决此问题
