### ISSUE TITLE
https://telegra.ph/  的文章不能全文翻译，只能翻译标题

### ISSUE THREAD

**Issue by zhangwei89** [hcfyapp/crx-selection-translate#1454]
## 基本信息

划词翻译版本：v8.7.5.1
浏览器版本： Chrome 版本 103.0.5060.114
操作系统：Windows10

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
能提供一个具体的网址吗？我进去这个官网之后，只有一个编辑器

**Comment by zhangwei89** [comment]
https://telegra.ph/Apple-already-sold-everyone-an-iPhone-Now-what---The-Economist-08-01

**Comment by lmk123** [comment]
我想起来了，之前也有用户反馈过这个网站的问题，我的回复见 https://github.com/hcfyapp/crx-selection-translate/issues/1303#issuecomment-1045983376
