### ISSUE TITLE
ESC键能关闭独立翻译窗口很好，但误关闭就很难受了

### ISSUE THREAD

**Issue by alexcchen** [hcfyapp/crx-selection-translate#1455]
我使用的是 Windows 7 Microsoft Edge版本 103.0.1264.77 (正式版本) (64 位)  和划词翻译 v8.7.6，今天我发现独立翻译窗口ESC键关闭有误判情况。重现问题的步骤如下：

按自己设置的快捷键alt+q，打开独立翻译窗口，使用必应拼音输入法输入汉字，自动翻译为英文，发现拼音输入错误，不使用back键一个个删除拼音，使用ESC键删除整段拼音

预期行为：划词翻译独立窗口应该保持之前已输入模样，维持已经输文字原样

实际行为：在按esc键拼音删除之后，独立翻译窗口误关闭(此处逻辑应该需要再独立点一次ESC键才能退出，而不是和拼音输入共用一次ESC键），之前输入文字一并消失

**Comment by lmk123** [comment]
其实已经有不少用户反馈过这个问题，但是很难解决，究其原因，就是我没法准确判断出按下 ESC 的当下，用户是否正在输入法当中。

1. 一开始，我没有做任何判断，只要按下 ESC 就关闭，然后有用户反馈在输入框中本来只是想按下 ESC 取消输入法的，结果独立窗口关闭了
2. 然后，我尝试检测用户是否正在使用输入法，但是经过几个用户的反馈，技术上无法检测出每种输入法是否正在输入中。比如我自己在 macOS 上测试的话，macOS 自带输入法和搜狗输入法都是能检测出来的，但是看来你在 Windows 上的必应输入法就检测不出来，所以就导致了你的问题

我打算做个改进：

1. 给用户一个选项，允许用户自行决定是否开启“按下 ESC 关闭独立翻译窗口”功能
2. 额外提供一个“关闭独立翻译窗口”的快捷键

**Comment by alexcchen** [comment]
可以区分Esc键的，KeyDowd和KeyUp、keypress事件吗？

我查到 “Javascript中 有3个事件句柄在对应键盘的输入状态：keydown、keypress和keyup。分别对应的意思是：按键被按下（按下按键但还没有抬起）、点击按键（按下并抬起按键）、按键抬起（按键抬起之后）”，

基于此，我有个不成熟的推理：
我在独立翻译窗口的控制面板中，找到了您写的关于Esc键的Keyup事件检测代码

            window.addEventListener("keyup", (e=>{
                if (27 === e.keyCode) {
                    if ("TEXTAREA" == e.target.nodeName && x)
                        return;
                    window.close()
                }
            }

我尝试了下，我的拼音输入法在按下Esc就会直接退出输入法，不用等待弹起，那能否证明输入法是否会消耗Esc键的按下事件呢？如果成立的话，您判断的是keyup事件等于Esc（27），这样由于输入法只需要消耗掉Esc的按下事件进行退出，退出输入法后，立即就聚焦到独立输入窗口，此时Esc键还按着没放手，放手弹起后，触发了留给独立翻译窗口的一个Keyup事件，导致误操作，就说的通了。

如果您将Keyup检测改为Keypress事件（按下并抬起），这样的话我的输入法消耗了半个Kepress，只剩下Keyup，或者其他输入法消耗了一个keypress，便不会触发完整的Keypress事件。

如果改为Keypress后还是会误关闭窗口，（即输入法不会消耗掉窗口的Esc按键事件），行不通，您可以设置为连续两次Keypress事件触发关闭窗口吗？即双击Esc，或则三击空格键（32）检测作为退出检测吗？

希望您别对我这外行的指点动气，如果还是行不通，就当我放屁。。

**Comment by alexcchen** [comment]
我试了下，文件夹的重命名就是检测的Keydown，并且用输入法的Keydown会抵消一次keydown事件，使得文件夹重命名不回由于输入法的退出而退出编辑，只有再次使用keydown才会退出文件夹名称编辑，所以您还可以再试下用Keydown替代keyup。。

**Comment by lmk123** [comment]
怎么会动气，任何能帮助我改善划词翻译的建议我都欢迎 :joy:

我确实监听的 keyup 事件，但改成 keydown 并没有用，因为当你在输入过程中按下 ESC 时，**输入法和我会同时收到 keydown 事件**，而不是**只有输入法会收到 keydwon**。

> 我试了下，文件夹的重命名就是检测的Keydown，并且用输入法的Keydown会抵消一次keydown事件，使得文件夹重命名不回由于输入法的退出而退出编辑，只有再次使用keydown才会退出文件夹名称编辑，所以您还可以再试下用Keydown替代keyup。。

文件夹重命名与输入法都属于操作系统级别的操作，所以操作系统可以判断在收到 ESC 时，如果正处于输入法状态，那就优先取消输入法。

但是，扩展程序里的独立翻译窗口（实际上是个网页）跟操作系统的输入法属于两个世界，而且中间还隔了一个浏览器。当你在独立翻译窗口中按下 ESC 时，输入法收到了 ESC，然后浏览器也收到了 ESC，然后浏览器又把 ESC 发送给了我的代码，而输入法和 Chrome 浏览器之间并没有“联动”，也就是 Chrome 浏览器不会因为输入法正在输入中而不给我发送 ESC 事件。

我能做的就是判断按下 ESC 的时候是否正处于输入法过程中，事实上 `"TEXTAREA" == e.target.nodeName && x` 就是干这个的，其中的 `x` 就代表输入法是否正在启用中：

```js
let x = false
window.addEventListener('compositionstart', () => {
  x = true
})
window.addEventListener('compositionend', () => {
  x = false
})
```

但很显然，这段代码并不能很好的支持所有输入法，也就是说，问题出在浏览器，是浏览器没有支持所有输入法的 `compositionstart` & `compositionend` 事件，对此我也无能为力。

**Comment by lmk123** [comment]
> 如果改为Keypress后还是会误关闭窗口，（即输入法不会消耗掉窗口的Esc按键事件），行不通，您可以设置为连续两次Keypress事件触发关闭窗口吗？即双击Esc，或则三击空格键（32）检测作为退出检测吗？

那我就加个选项吧，默认单击 ESC 关闭独立窗口，但可以改成双击 ESC 关闭独立窗口

**Comment by alexcchen** [comment]
nice谢谢

**Comment by alexcchen** [comment]
或则按照打开独立窗口的组合快捷键方式，再次点击打开独立窗口的组合快捷键方式就会关闭独立窗口，仅作建议

**Comment by lujjjh** [comment]
我也遇到了这个问题，环境是 macOS 12.6 + Chrome + 搜狗输入法。

测试了一下文字上屏过程中按 <kbd>esc</kbd>，事件的触发顺序是：

1. compositionstart
2. keydown (esc)
3. compositionend
4. keyup (esc)

compositionend 事件产生于按下 <kbd>esc</kbd> 和松开 <kbd>esc</kbd> 之间，这也是为什么 <kbd>esc</kbd> 的 keyup 事件无法通过 [`isComposing`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing) 或者 `x` 来判断是否刚结束输入过程。

至于为什么目前的版本

> 我自己在 macOS 上测试的话，macOS 自带输入法和搜狗输入法都是能检测出来的

我怀疑是不是装了诸如 Karabiner-Elements 之类的 app，改变了 <kbd>esc</kbd> 的行为？

一个比较理想的解决方案：

```js
window.addEventListener('keydown', (e) => {
  // 除了 composition，长按 esc 会重复触发 keydown
  if (e.defaultPrevented || e.repeat || e.isComposing) {
    return;
  }

  // TODO: 检查修饰键？
  if (e.key === 'Escape') {
    e.preventDefault();
    window.close();
  }
});
```
