### ISSUE TITLE
调用独立窗口读取粘贴板翻译时，独立窗口会获取到窗口焦点，希望可自定义开关

### ISSUE THREAD

**Issue by zwjjiaozhu** [hcfyapp/crx-selection-translate#1456]
每次使用快捷键调用“独立窗口”（即使窗口已开启）时，该窗口会自动获取到焦点，还得再点击一次划词的内容，才会切换窗口焦点，影响划词体验。
希望增加：当打开"独立窗口"时是否获取窗口焦点的选项
感谢

**Comment by zwjjiaozhu** [comment]
大佬，这个功能在哪个地方呀，找了半天也没看到。试了下，使用快捷键打开独立窗口，还是会自动获取到焦点 @lmk123

**Comment by lmk123** [comment]
即将发布的 v9.4.0 新增了这个选项，在划词翻译设置页找到【翻译面板】->【独立翻译窗口】，勾选“不要获取焦点”即可。

v9.4.0 预计在明天发布。
