### ISSUE TITLE
开启划词翻译插件后 会导致Chrome浏览器的网址栏无法复制网址

### ISSUE THREAD

**Issue by hnboy2005** [hcfyapp/crx-selection-translate#1458]
## 基本信息

划词翻译版本：8.7.6
浏览器版本： 版本 104.0.5112.79（正式版本） (arm64)
操作系统：MacOS 12.4

## 重现问题的步骤

1.开启划词翻译插件
2. 复制浏览器的地址栏
3. 新建一个浏览器页签 粘贴地址栏

**Comment by lmk123** [comment]
我使用 macOS 12.5 Chrome 104.0.5112.79（正式版本） (arm64) 没有重现你的问题。

我打开了 https://github.com/notifications ，在地址栏中复制网址后，在打开的新标签页的地址栏中可以正常粘贴。

请再次确认这一问题是否真的由划词翻译引起，如果确认是划词翻译的问题，请补充更多细节让我也能重现此问题。
