### ISSUE TITLE
无法使用翻译积分

### ISSUE THREAD

**Issue by Thong2537** [hcfyapp/crx-selection-translate#1459]
所有可以用翻译积分的服务都无法使用，提示401错误。但事实上我的账号有6000+积分，尝试充值再充值1000积分也无法正常使用。

**Comment by lmk123** [comment]
我试试看

**Comment by lmk123** [comment]
我试了一下，我这边只有有道翻译会报 401 错误，那是因为我的有道翻译账户没余额了，我刚才已经充值了，应该马上会恢复

**Comment by lmk123** [comment]
有道翻译已经恢复了，我这边测试过，以下所有服务都是能正常通过翻译积分使用的：

<img width="542" alt="截屏2022-08-06 21 45 55" src="https://user-images.githubusercontent.com/5035625/183251607-917c4c21-42d2-45bc-acec-3d37111f3c99.png">

**Comment by Thong2537** [comment]
现在已经OK了
