### ISSUE TITLE
可否添加划词单词显示音标的功能，这个比较实用

### ISSUE THREAD

**Issue by 15920415252** [hcfyapp/crx-selection-translate#1460]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，现有 PDF 不支持标记功能，导致我无法在 pdf 上标记内容。

**你想要如何解决你的问题？**
比如，添加 PDF 标记功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
比如，如果划词翻译无法添加 PDF 标记功能，那么至少允许我在别的 PDF 软件里进行划词翻译。

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。

**Comment by lmk123** [comment]
你是想划词之后只显示音标吗？虽然技术上可以做到，但我觉得没有这么做的必要，毕竟显示翻译结果的同时也会显示音标。

如果你指的不是我说的这种情况，那么可以继续留言与我探讨

**Comment by 15920415252** [comment]
就是翻译PDF时，划某个单词没有音标显示，不知道怎么读，哈哈

**Comment by lmk123** [comment]
是否显示音标是跟翻译服务有关的，目前谷歌和有道是能显示音标得
