### ISSUE TITLE
截图翻译出现问题

### ISSUE THREAD

**Issue by hellolfz** [hcfyapp/crx-selection-translate#1461]
## 基本信息

划词翻译版本：v8.7.6
浏览器版本： Firefox 99.0 (64 位)
操作系统：Win 11

## 重现问题的步骤

1. 按照提示申请了百度密匙
2.进入SwissTargetPrediction
3.使用划词翻译截取该网站中那个统计饼图下的几个英文标注，但提示：尝试通过密匙、翻译积分识别文字时均失败了。

### 补充信息

![图片](https://user-images.githubusercontent.com/52497585/183823344-58e8ce09-aa46-4219-96c0-4fe7040b243f.png)
![图片](https://user-images.githubusercontent.com/52497585/183823448-4009fc0a-ad2e-4ad4-b418-0ff7c462260f.png)

**Comment by lmk123** [comment]
有以下几种可能：

- 你的密钥填错了
- 你没有领取免费资源包

如果不是以上两种情况，那只能联系百度文字识别的客服解决了。

**Comment by hellolfz** [comment]
密匙确定没错，创建了应用，也领取了免费API，如图一“通用文字识别”等API均有领取。但是如图二在应用列表下面的API中中却显示大部分API都是“待开通付费”。似乎是这个原因？或者说我需要操作哪里将领取的API放进我创建的应用里？
![图片](https://user-images.githubusercontent.com/52497585/183912920-448fe41d-38ba-460e-b219-21e0bd3a2ac7.png)
![图片](https://user-images.githubusercontent.com/52497585/183913059-3caf6989-8559-48f9-9a7c-e9a3ffe4d906.png)

**Comment by lmk123** [comment]
我看了一下我自己的，我的 API 列表里的状态也是“待开通付费”，但我是能正常使用百度文字识别的。

这种情况只能找客服反馈了，注意到你截图里的那句话没：`若长时间未生效，可提交工单咨询`，我估计他们就是偶尔会有这样的 bug

**Comment by lmk123** [comment]
请问你有提交工单吗，有解决你的问题吗？

**Comment by lmk123** [comment]
我又试了一下，我这边是正常的。

如果你发现了你报错的原因的话，希望你能反馈给我，我会把这个案例加入文档，帮助其他人排查问题。
