### ISSUE TITLE
独立窗口打不开

### ISSUE THREAD

**Issue by Bianr233** [hcfyapp/crx-selection-translate#1463]
## 基本信息

划词翻译版本：最新

浏览器版本：104.0.5112.81（正式版本） （64 位）chrome
操作系统：win11

## 重现问题的步骤

1.打开独立窗口时发生了一个错误：Invalid value for bounds. Bounds must be at least 50% within visible screen space.

### 补充信息

以前一直可以，几个月之前不可以了。

**Comment by lmk123** [comment]
目前可以解决这个问题的办法是：前往【设置】-【翻译面板】-【独立翻译窗口】，点击【重置位置与大小】按钮。

之后我会进一步优化双屏幕的情况，后续进展我会更新在 https://github.com/hcfyapp/crx-selection-translate/issues/1440
