### ISSUE TITLE
翻译面板位置设置无效，始终固定在某个位置

### ISSUE THREAD

**Issue by History-exe** [hcfyapp/crx-selection-translate#1464]
## 基本信息

划词翻译版本：v8.7.6
浏览器版本：Firefox 103.0 64bit
操作系统：Ubuntu 20.04.4 LTS

## 重现问题的步骤

1. 同时使用划词翻译和Diigo插件(Diigo可实现网页阅读文字标记重点等功能)
2. 由于两个插件的弹出操作按钮冲突，故想更改划词翻译的弹出操作按钮，因为Diigo的操作按钮位置不能更改。
3. 进入划词翻译设置-翻译面板-网页划词面板-弹窗显示方向设置具体弹窗位置
![2022-08-13 11-07-12 的屏幕截图](https://user-images.githubusercontent.com/33642965/184466496-a254cca7-5646-4e45-b524-244ad2655ce6.png)

### 预期行为
通过更改设置，应该可以改变划词翻译弹出按钮位置

### 实际行为
更改设置后，弹出按钮位置并未改变，已经尝试过重启浏览器，无效果。依旧显示在右下方
![2022-08-13 11-06-49 的屏幕截图](https://user-images.githubusercontent.com/33642965/184466505-2b496d1d-2a1c-4052-ac0f-1f401298a303.png)

**Comment by lmk123** [comment]
你更改的是【弹窗】显示方向，不是翻译按钮的；翻译按钮的位置在【网页划词翻译】-【翻译按钮】-【按钮显示位置】更改
