### ISSUE TITLE
能否提供隐藏【译】图标的配置？

### ISSUE THREAD

**Issue by xianghongai** [hcfyapp/crx-selection-translate#1467]
**没有这个功能（改进）的时候，你遇到了什么问题？**
选择文本后，弹出【译】图标，遮罩到内容了。希望能提供隐藏功能，用户可通过快捷按键打开翻译面板。

**你想要如何解决你的问题？**
不立即弹出【译】图标。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
——暂无——

**补充信息**
——暂无——

**Comment by lmk123** [comment]
已有功能，在设置中开启【在所有网址中禁用网页划词】即可。
