### ISSUE TITLE
PDF 中【复制 PDF 网址】这个功能能否用 Icon 替代？或者设定为 12 号字体？

### ISSUE THREAD

**Issue by xianghongai** [hcfyapp/crx-selection-translate#1468]
**没有这个功能（改进）的时候，你遇到了什么问题？**
目前 【复制 PDF 网址】这个按钮文字很大。

**你想要如何解决你的问题？**
用 Icon 替代，或者设定为 12 号字体。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
——暂无——

**补充信息**
——暂无——

**Comment by lmk123** [comment]
大一点是为了突出，虽然可能丑了一点，但我不觉得到了影响到使用的程度。改小一点或者变成图标，会不显眼

**Comment by xianghongai** [comment]
`好看`的体验是第一位的 😂

不需要显眼，还有好多功能都是折叠到菜单中的了，要用，总是能找得到的。

**Comment by lmk123** [comment]
好看确实很重要，这我不否认 :joy:

不过我本人不是一名设计师，从我的角度来看，做这个调整可能会让新用户找不到、且对于整体的“好看”不会提升多少，所以我觉得这么做没太大必要 :joy:

**Comment by xianghongai** [comment]
我们是工程师，尽量追求系统的一致性、协调性。

**Comment by lmk123** [comment]
我比较注重稳定性与性价比，如果一个改动在我看来没有带来足够多的好处、搞不好还会有坏处，我不会动 :joy:

所以我会在提需求的模板里特意让用户解释为什么这个改动是必要的
