### ISSUE TITLE
翻译结果时出错。错误信息：有道翻译需要自行申请后使用（免费），请前往【服务申请】查看申请步骤。

### ISSUE THREAD

**Issue by tongtongSpring** [hcfyapp/crx-selection-translate#1471]
## 基本信息
所有切换源头都出现了 “翻译结果时出错。错误信息：有道翻译需要自行申请后使用（免费），请前往【服务申请】查看申请步骤。”
之前都可以的。

划词翻译版本：v8.7.6
浏览器版本：google
操作系统：mac intel

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
这个错误是符合预期的，因为除了 Google、DeepL 和必应词典，其它翻译源就是需要自行申请之后才能用的，见文档说明：https://hcfy.app/docs/faq/#why-apply

你说的“之前都可以的”是指你没有申请过也能直接用？那说明你购买过翻译积分（或者如果没购买过，我也曾经给所有会员赠送过 10,000 的翻译积分），是通过翻译积分使用的，见翻译积分的介绍 https://hcfy.app/docs/services/tp

如果不是我说的这些情况，麻烦提供更详细的说明
