### ISSUE TITLE
全文翻译时的语言切换设置问题

### ISSUE THREAD

**Issue by dfjfj** [hcfyapp/crx-selection-translate#1473]
全文翻译时, 右下角会出现全文翻译设置选项框. 有时候在需要查看原文时, 会点击原文, 然后切换成原文. 然后再下一个网页进行浏览时, 我又在右键菜单里点击了全文翻译, 发现没有双语出现, 想了一会儿, 才想到可能是右下角选项框默认记录了我上一次的选择, 一看果真是.

这个逻辑不对, 我选择全文翻译时, 肯定是要翻译的. 而且即便不管是否需要双语, 原文还是纯翻译, 都不太适合记录上一次选项, 尤其是我选择了原文, 这让我很迷惑, 为什么我选择了全文翻译却没有效果. 

建议: 取消记录全文翻译右下角选项框中的选择, 或者再加一个状态选择按钮, 让我们自己来选择是否应该记录下来. 这个功能应该允许能保存到云端. 谢谢.

**Comment by lmk123** [comment]
我会新增一个选项，可以让用户选择不记住翻译模式
