### ISSUE TITLE
大多数网站都没有权限

### ISSUE THREAD

**Issue by jackccbzhang** [hcfyapp/crx-selection-translate#1474]
<p style="background-color:red">不知道为什么，大多数网站都显示没有权限操作</p>
建议修复一下

**Comment by lmk123** [comment]
我没有遇到这个问题，我猜测你可能修改过划词翻译的权限，见 https://hcfy.app/docs/guides/options#per

如果不是因为这个，麻烦提供更详细的信息给我，比如：

- 按照问题模板提供浏览器版本、划词翻译版本等
- 哪个或哪些网站没有权限
- 任何其它可能帮助我解决此问题的信息
