### ISSUE TITLE
你好，能否在内置PDF阅读器中添加标注功能？

### ISSUE THREAD

**Issue by WrennCool** [hcfyapp/crx-selection-translate#1476]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，现有 PDF 不支持标记功能，导致我无法在 pdf 上标记内容。

**你想要如何解决你的问题？**
比如，添加 PDF 标记功能。如荧光笔、钢笔、橡皮擦等功能

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
比如，如果划词翻译无法添加 PDF 标记功能，那么至少允许我在别的 PDF 软件里进行划词翻译。

**补充信息**
如EDGE自身的pdf标注功能

**Comment by lmk123** [comment]
有这个计划，但是技术上有点难度所以估计很久之后才会实现，目前推荐使用其它 pdf 阅读器，然后配合划词翻译[在浏览器外使用](https://hcfy.app/docs/guides/extra)
