### ISSUE TITLE
无法打开独立翻译窗口

### ISSUE THREAD

**Issue by eforlina** [hcfyapp/crx-selection-translate#1477]
## 基本信息

划词翻译版本： v8.7.6
浏览器版本：Version 104.0.5112.102 (Official Build) (64-bit)
操作系统：Windows 11 Version 21H2 (OS Build 22000.856)

## 重现问题的步骤
如图，点击就报错：
![image](https://user-images.githubusercontent.com/9491214/187621952-20098853-4704-485b-9793-d32787114cc4.png)

设置的全局快捷键也无法打开

### 补充信息
我是在hyper-v虚拟机环境中；我使用双屏工作。

**Comment by lmk123** [comment]
前往设置 - 翻译面板 - 独立翻译窗口点一下【重置】即可
