### ISSUE TITLE
网页全文翻译时无法选择语言

### ISSUE THREAD

**Issue by forkmax** [hcfyapp/crx-selection-translate#1478]
您好，请问能否设置网页全文翻译的语言。举例，当我打开一个繁体中文的网页，我想要网页全文翻译为简体中文，但是现在的逻辑似乎是把繁体中文翻译成了英语，请问能否自行设置翻译后的语言，谢谢。

**Comment by lmk123** [comment]
将会在之后的版本中添加此功能，进度可以关注 #943
