### ISSUE TITLE
增加双语实时对照功能(网页翻译，指定句子)

### ISSUE THREAD

**Issue by Beyrea** [hcfyapp/crx-selection-translate#1479]
在网页翻译(双语)时，能否增加双语实时对照的功能？
当鼠标移动到指定句子时，将会有高光显示双语的对应内容

如同下图，谷歌翻译：
![屏幕截图 2022-09-03 162406](https://user-images.githubusercontent.com/58060724/188262614-2c217f14-0340-40dd-9066-809d4e5fff47.png)

**Comment by lmk123** [comment]
这个功能目前技术上是做不到的。

<details>
<summary>
技术上的解释
</summary>
如果要实现这个功能，那么就需要各个翻译服务给我提供分句的数据，但目前为止，没有任何翻译服务提供了文本到译文之间的句子映射关系。
</details>
