### ISSUE TITLE
收藏夹中的单词，可以自动在文章中高亮显示出来

### ISSUE THREAD

**Issue by zhitiao** [hcfyapp/crx-selection-translate#1480]
**没有这个功能（改进）的时候，你遇到了什么问题？**
收藏夹的单词是自己不认识的，想要在日常阅读中时常复习或者自动标记出来点击查看翻译。

**你想要如何解决你的问题？**
收藏夹中的单词，自动在网页中高亮出来，鼠标hover后直接显示翻译

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
导出收藏夹，让我能在其他软件中复习

**补充信息**
有个软件做得很好，叫Burning Vocabulary，可以参考

**Comment by lmk123** [comment]
这个功能已经在开发计划当中了，后续可以关注 #1172
