### ISSUE TITLE
翻译面板的【启用翻译源】设置中允许对自定义翻译源进行设置

### ISSUE THREAD

**Issue by cesaryuan** [hcfyapp/crx-selection-translate#1481]
**没有这个功能（改进）的时候，你遇到了什么问题？**
造成自定义翻译源翻译额度的浪费

**你想要如何解决你的问题？**
为翻译面板添加自定义翻译源的启用设置
![image](https://user-images.githubusercontent.com/35998162/188467169-d681ffa4-c614-40aa-8fd4-f66d0f65fd25.png)

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
没有好像哈哈

**Comment by lmk123** [comment]
目前确实没有，不过你可以在自定义翻译源那里删掉你不想启用的翻译服务，等想用的时候重新添加即可。我觉得这样做就可以解决你的问题了，所以可能不会单独做一个自定义翻译元的启用 / 停用了。
