### ISSUE TITLE
划词翻译中谷歌翻译阅读长句子时会读一部分后停止

### ISSUE THREAD

**Issue by ZHHanW** [hcfyapp/crx-selection-translate#1482]
## 基本信息

划词翻译版本：8.7.6
浏览器版本：版本 104.0.5112.102（正式版本） （64 位）
操作系统：Win11

## 重现问题的步骤

1.翻译一段英语
2.用谷歌翻译读这段英语

### 预期行为
读完全部单词
### 实际行为
读一部分
### 补充信息

deepl没有问题

**Comment by lmk123** [comment]
解决方案：在划词翻译设置 - 通用 - 系统语音里选择“始终使用系统语音”

这是因为谷歌翻译的语音地址使用了谷歌翻译本身的语音朗读服务，但是这个服务最近被谷歌限制了（即在朗读一部分后停止），而 DeepL 使用的是操作系统自带的语音，所以不会有这个问题。
