### ISSUE TITLE
hcfy.app 域名无法访问

### ISSUE THREAD

**Issue by ydcool** [hcfyapp/crx-selection-translate#1483]
**没有这个功能（改进）的时候，你遇到了什么问题？**
大陆国企单位，办公网络无法访问 hcfy.app 域名。导致经常丢失登陆信息，无法登陆，无法访问会员信息，无法使用积分等。

翻译功能正常使用，办公网络没有主动屏蔽 hcfy.app, 但是对境外ip有限制。

**你想要如何解决你的问题？**
有没有计划将服务从 aws 迁移到国内云厂商，或者做下双线双活，提升国内用户访问体验？

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**

**补充信息**

**Comment by lmk123** [comment]
hcfy.app 仅仅只是官网的域名，划词翻译的服务器（也就是登录、会员信息、翻译积分等一切划词翻译软件内的功能）就是部署在国内机房的，所以你这个问题感觉不像是我能解决的问题……

**Comment by ydcool** [comment]
> hcfy.app 仅仅只是官网的域名，划词翻译的服务器（也就是登录、会员信息、翻译积分等一切划词翻译软件内的功能）就是部署在国内机房的，所以你这个问题感觉不像是我能解决的问题……

确实。
