### ISSUE TITLE
建议开发客户端应用程序

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1484]
我是那种双系统用户 linux + windows
在windows会使用天若OCR，PANDA OCR，怎么说呢，一开始感觉找到宝藏，但是现在感觉不尽人意。

在browser环境中我一直是划词翻译的铁粉
虽说现在有独立窗口，browser关闭保持后台运行的功能，但是使用起来还是差强人意。
例如无法截图翻译browser环境之外的东西。

强烈建议开发自己的客户端程序，主要加强OCR截图翻译功能。
如果真的会考虑开发的话，请必须一定开发linux版本 （deb，rpm，arch...)
目前国内关于OCR翻译的话可以简略到2家（PANDA OCR，天若OCR）
希望划词翻译开发客户端杀入这片江湖！！

**Comment by lmk123** [comment]
正在开发中 :joy:

https://github.com/hcfyapp/hcfy-desktop

**Comment by lmk123** [comment]
另外，你可以在设置里开启【自动翻译剪切板内的图片】，这样当你用微信等第三方截图工具截图后，再打开独立翻译窗口时就会翻译截图了

**Comment by ghost** [comment]
@lmk123 NICE
坐等了，目前我都是自己要反编译天若OCR，PANDA OCR，翻得一批。
哈哈，开心。期待中。
