### ISSUE TITLE
使用网页全文翻译, 页面中包含有中文时, 源语言及目标语言翻译设置无效 , 

### ISSUE THREAD

**Issue by LoopholesInTheHeart** [hcfyapp/crx-selection-translate#1486]
## 基本信息

划词翻译版本：划词翻译 v8.7.7
浏览器版本：Chrome 版本 105.0.5195.127（正式版本） （64 位）
操作系统：win10

## 重现问题的步骤

1. 打开一个中英文混合的页面
2. 设置目标语种为中文
3. 执行 划词翻译-网页全文翻译 
4. 中文保持不变, 英语也保持不变

### 预期行为
英语翻译成中文, 同时中文保持不变
或者 英语翻译成中文, 同时中文翻译成英语,
或者 在设置里选择源语言后, 按照设置来

### 实际行为
在任何有中文文本的英语页面, 都没变

**Comment by LoopholesInTheHeart** [comment]
标题打错了

**Comment by LoopholesInTheHeart** [comment]
测试了  v8.7.7

**Comment by LoopholesInTheHeart** [comment]
我看了置顶帖子, 然后在Google翻译里面测试了下, 似乎设置源语言为法语的时候, 中英文混合文本 , 能达到预期的效果;
日语不行, 有些翻译品质不高;
俄语感觉有时候有些中文莫名其妙的消失了;

**Comment by lmk123** [comment]
首先，你得提供一个具体的网址让我能重现你的问题 :joy:

**Comment by LoopholesInTheHeart** [comment]
> 首先，你得提供一个具体的网址让我能重现你的问题 首先，你必须提供一个具体的网址，让我能够解决你的问题😂😂

之前试是任何页面都这样, 包括本页
在更新为  v8.7.7 , 并且参考置顶帖, 手动将翻译页面的 划词翻译源语种设置成英语后可以了.
