### ISSUE TITLE
notion的在线文档无法全文翻译

### ISSUE THREAD

**Issue by auflute** [hcfyapp/crx-selection-translate#1488]
## 基本信息

划词翻译版本：v8.7.6
浏览器版本：
Brave
[版本 1.43.89 Chromium: 105.0.5195.102（正式版本） (x86_64)](https://brave.com/latest/)

操作系统：mac os big Sur 11.7

## 重现问题的步骤
notion的在线文档无法全文翻译

### 补充信息

如下图，只有顶部几个选项被翻译了，正文没有被翻译
![image](https://user-images.githubusercontent.com/4373665/190988854-b8169367-0ed5-48de-8a99-6451442e0702.png)
图中网页链接：
https://coinvise.notion.site/How-Creator-DAOs-redefine-the-way-we-work-21c3f7b601b841629ba8de3761451a95

**Comment by lmk123** [comment]
感谢反馈，已重现此问题，将会在未来的版本中修复

**Comment by lmk123** [comment]
我看了一下，其实划词翻译翻译过了，**但是 notion 阻止了划词翻译显示翻译结果**，如下图

<details>
<img width="569" alt="image" src="https://user-images.githubusercontent.com/5035625/207099671-a68fefaf-d77d-4bc5-a811-45157d3da78c.png">
</details>

要突破 notion 的限制的话，不仅麻烦，也不稳定——就算我突破了一次，以后 notion 改一次代码就又不行了。

所以我目前不打算突破它的限制，用划词的方式看吧 :joy:
