### ISSUE TITLE
单词翻译时只有一个释义，希望有更详细的说明

### ISSUE THREAD

**Issue by xulonc** [hcfyapp/crx-selection-translate#1491]
**没有这个功能（改进）的时候，你遇到了什么问题？**
单词翻译时只有一个释义
![image](https://user-images.githubusercontent.com/77042549/192480369-ab35e2d1-445c-4bb0-82e6-e0615f4738fb.png)

**你想要如何解决你的问题？**
单词翻译时只有一个释义，希望有更详细的说明
![image](https://user-images.githubusercontent.com/77042549/192480210-1b764f03-8a11-4fa7-873f-0326fbf8e746.png)

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
无

**补充信息**
无

**Comment by lmk123** [comment]
无法解决。百度翻译本身没有提供单词释义，我也没法变出来 :joy:

建议在翻译单词时使用必应词典
