### ISSUE TITLE
“速度慢、准确率高”的谷歌翻译出错了

### ISSUE THREAD

**Issue by liukk18** [hcfyapp/crx-selection-translate#1492]
![图片](https://user-images.githubusercontent.com/56376032/192664679-9bc4d00c-bdf1-4f15-81fb-dd528069dc9f.png)
1.
2.
3.

**Comment by lmk123** [comment]
已确认有此问题，将尝试在下个版本修复。你可以先把谷歌翻译切换到“速度快、准确率低”使用

**Comment by liukk18** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hcfyapp/crx-selection-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hcfyapp/crx-selection-translate] “速度慢、准确率高”的谷歌翻译出错了 (Issue #1492)





 
已确认有此问题，将尝试在下个版本修复。你可以先把谷歌翻译切换到“速度快、准确率低”使用

**Comment by lmk123** [comment]
v10.4.0 解决了这个问题。
