### ISSUE TITLE
更新版本8.7.7.1后，谷歌翻译结果显示远程服务器返回了错误的 HTTP 响应码：404。

### ISSUE THREAD

**Issue by Yooupi** [hcfyapp/crx-selection-translate#1494]
## 基本信息

划词翻译版本：8.7.7.1
浏览器版本：Edge_105.0.1343.50 (正式版本) (64 位)
操作系统：Windows11_22H2

## 重现问题的步骤

1.
2.
3.

### 实际行为
![image](https://user-images.githubusercontent.com/101870448/192723852-0814334e-61fa-4792-8547-a533715db633.png)

**Comment by lmk123** [comment]
试试先在浏览器打开一下 https://translate.google.cn 看看

**Comment by Yooupi** [comment]
https://translate.google.cn/
![image](https://user-images.githubusercontent.com/101870448/192728512-8948e576-3764-4f0f-b11d-a96ac4a17e9f.png)
可以打开的

**Comment by lmk123** [comment]
那你再在划词翻译里用谷歌翻译试试。

我第一次用的时候也出现了这个问题，但是开一下谷歌翻译的网页版就能正常用了

**Comment by Yooupi** [comment]
确实，再试一次就好了😊

**Comment by lmk123** [comment]
感谢反馈，我会将这个问题写进常见问题当中。
