### ISSUE TITLE
打开独立翻译窗口快捷鍵的問題

### ISSUE THREAD

**Issue by yee221** [hcfyapp/crx-selection-translate#1495]
## 基本信息

划词翻译版本：8.7.7
浏览器版本： Chrome 105.0.5195.127
操作系统：windows11 

## 重现问题的步骤

1.每次把打开独立翻译窗口的快捷鍵關掉隔一段時間又會自動打開，打遊戲都會不小心誤觸
2.
3.

**Comment by lmk123** [comment]
请参考常见问题里的【修改快捷键后没有生效】来删除快捷键 https://hcfy.app/docs/faq/#edit-shortcut-key
