### ISSUE TITLE
安装了8.7.7.3版本后谷歌翻译还是报10秒超时

### ISSUE THREAD

**Issue by pengmin** [hcfyapp/crx-selection-translate#1497]
## 基本信息
选择谷歌翻译，超时10秒
划词翻译版本：
8.7.7.3
浏览器版本：
Microsoft Edge
版本 105.0.1343.53 (正式版本) (64 位)
操作系统：
win10

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
你用的应该是速度慢准确率高，这个问题暂时没有解决，我正在优先解决速度快、准确率低的。

这个问题的后续进展可以关注 #1492
