### ISSUE TITLE
能不能新增一个调用本地翻译的接口啊

### ISSUE THREAD

**Issue by frozenleaves** [hcfyapp/crx-selection-translate#1498]
比如我本地有[Hugging Face Transformer](https://github.com/huggingface/transformers)的服务，可以直接用来做翻译，不用申请API，但是想要用在划词翻译中，能不能开发一个接口导入这种类型啊.

**Comment by lmk123** [comment]
我猜你需要的是[自定义翻译源](https://hcfy.app/docs/services/custom-api)
