### ISSUE TITLE
国内谷歌翻译页面404

### ISSUE THREAD

**Issue by kdxiaoyi** [hcfyapp/crx-selection-translate#1499]
## 基本信息
划词翻译版本：edge商店最新 8.7.6 （国庆）
浏览器版本：edge 105.0.1343.53 (正式版本) (64 位)
操作系统：win11 x64 pro

## 重现问题的步骤
1. 使用**国内**谷歌翻译翻译文本
### 预期行为
正确返回文本
### 实际行为
404 ↓
![划词翻译报404](https://user-images.githubusercontent.com/96934144/193404142-904d8dec-5309-40e2-b926-879b17a3fc7a.png)

### 补充信息
国内谷歌翻译页面变成了这个↓
[![https://translate.google.cn/](https://user-images.githubusercontent.com/96934144/193404016-43388a60-2040-474a-b581-cbd47de5d92e.png)](https://translate.google.cn/)

用之前翻译成功的URL访问404↓
[![https://translate.google.cn/?sourceid=cnhp&sl=zh-CN&tl=en&op=translate](https://user-images.githubusercontent.com/96934144/193404050-e215a49c-41be-40e1-82f5-a69186a7c817.png)](https://translate.google.cn/?sourceid=cnhp&sl=zh-CN&tl=en&op=translate)

**请测试您的上述URL是否访问正常，我怀疑我这边出了问题**

图片可以点击

**Comment by lmk123** [comment]
这是谷歌的问题，最近国内连接谷歌翻译就是如此不稳定，所以导致了谷歌翻译不可用。现在不仅仅是你，谷歌翻译在全国都会出现这个问题，相关链接：

- [突然发现,谷歌翻译cn站没了 - 小众论坛](https://meta.appinn.net/t/topic/36698/17)
- [谷歌翻译用不了了 - V2EX](https://www.v2ex.com/t/883853)

**Comment by lmk123** [comment]
另外，解决方案见公告 https://hcfy.app/blog/2022/09/28/ggg
