### ISSUE TITLE
翻译内容有明显错误，被篡改为广告信息

### ISSUE THREAD

**Issue by imjoeyli** [hcfyapp/crx-selection-translate#1500]
## 基本信息

划词翻译版本：8.7.7
浏览器版本：Chrome 105.0.5195.125
操作系统：macOS 12.5.1

## 重现问题的步骤

1. 翻译源选择 DeepL
2. 打开某个英文网页，比如 https://news.ycombinator.com/item?id=33020078
3. 开启全文翻译

### 预期行为

显示正确的中英对照翻译

### 实际行为

部分翻译明显错误，被篡改为广告信息（主要是淘宝网），如图：

![20221002121456](https://user-images.githubusercontent.com/48614287/193437607-2bed65e9-3232-4adc-9ce3-0dbbc609a4b0.png)
![20221002011905](https://user-images.githubusercontent.com/48614287/193437609-c473aace-f181-44e3-98a8-9dcd566ce422.png)

### 补充信息

在 DeepL 官网翻译相同内容，结果是正确的，没有广告，如图所示：

![20221002121807](https://user-images.githubusercontent.com/48614287/193437637-879281bc-5460-43e1-9d3c-7e2a8afbb8e5.png)
![20221002121824](https://user-images.githubusercontent.com/48614287/193437635-1f979353-2db5-44e8-b328-bd291b4bb06a.png)

**Comment by lmk123** [comment]
网页全文翻译会将网页里的所有文本合并成同一段话发给 DeepL 进行翻译，对一句话的翻译会被上下文所影响。你单独把这句话放在 DeepL 里翻译是没有上下文的，所以出现跟网页全文翻译不一样的情况是正常的。

不过，你的问题在我这里没有重现，如下图：

<img width="1087" alt="截屏2022-10-02 16 46 09" src="https://user-images.githubusercontent.com/5035625/193445921-ea386d6d-35af-4448-8594-67b16922dac6.png">

<img width="674" alt="截屏2022-10-02 16 47 31" src="https://user-images.githubusercontent.com/5035625/193445955-9bc39ba9-c94c-4166-b558-3bf4d3603be5.png">

老实说我也不知道这是什么原因造成的 :joy:

**Comment by lmk123** [comment]
由于我无法重现这个问题，所以也无从解决，这个 issue 我先关闭了。

不过，你仍然可以提供新的重现信息，届时我会继续跟进。
