### ISSUE TITLE
可否增加导出用户设置到本地的功能

### ISSUE THREAD

**Issue by KamenRevice** [hcfyapp/crx-selection-translate#1501]
希望增加把个人设置数据导出到本地和导入设置，这样一些翻译api可以之间配置，比方说百度和腾讯的翻译api

**Comment by lmk123** [comment]
翻译 API 本身就是可以导出 / 导入的，在设置 - 服务申请就能看到导出和导入的按钮。

其它设置确实无法导出 / 导入，将在未来的版本中添加此功能。
