### ISSUE TITLE
无法全文网页翻译，提示404

### ISSUE THREAD

**Issue by xxxxxhan** [hcfyapp/crx-selection-translate#1504]
## 基本信息## 基本信息

划词翻译版本：8.7.6 8.7.8
浏览器版本：edge
操作系统：Windows

## 重现问题的步骤

1.全文翻译

检查了划词权限：所有站点，没问题

人在国内，没有设置过其他域名

自行下载8.7.8 没用

尝试了hosts，也没用

最后，我没有梯子/哭

我很苦恼，我不知道怎么解决

**Comment by lmk123** [comment]
如果实在不能再用谷歌翻译的话，可以切换别的翻译服务使用，比如 DeepL。

在开启网页全文翻译之后，在网页右下角会出现一个划词翻译图标，将里面的【谷歌翻译】切换为其它翻译服务即可。

**Comment by xxxxxhan** [comment]
我已收到您的邮件。
