### ISSUE TITLE
内置PDF阅读器字体匹配问题

### ISSUE THREAD

**Issue by WYNwin511** [hcfyapp/crx-selection-translate#1505]
内置PDF阅读器打开文档后字体会发生变化，有些字体并不适配，导致文档显示有问题，希望可以进行改进，谢谢

**Comment by lmk123** [comment]
这个问题我改不了，得由上游（也就是 [PDF.js](https://mozilla.github.io/pdf.js/)）来改 :joy:

我能做的就是时不时的更新一下内置的 PDF.js 的版本。
