### ISSUE TITLE
能不能推出一个Deelp的PDF翻译功能

### ISSUE THREAD

**Issue by msjsc001** [hcfyapp/crx-selection-translate#1507]
目前在某宝上这个翻译业务非常火热（约100页1元），但都不是很方便，划词翻译能不能推出一个自动计费翻译PDF文档的功能。

**Comment by lmk123** [comment]
我不太理解这个功能是否有必要，因为我看到在 https://www.deepl.com/translator 里就是可以直接翻译 pdf、doc 等文件的

再做一个跟 deepL 官网同样的功能会有更多好处吗？

**Comment by msjsc001** [comment]
Deelp 的官方免费网页PDF翻译只能翻译5000字符的文档（非常小），最大5个文档（每月）。
个人购买它的Pro需要信用卡非常麻烦费用也非常高，也有各种限制比如文件大小篇数，传到淘宝代翻也是操作繁琐。
现在也还没有网站能直接上传PDF后计算后翻译量付费自动翻译的服务，如果有这种服务应该能很大程度的便利到PDF翻译的人群，不过实际也看这种功能是否有利于你们（开发者）了。

或者可以开发一个PDF一键持续翻译当前页面的功能？
也就是翻到某页后自动就翻译出来到提示框，不用自己再划选，这样我想应该也会很实用，供你们参考

**Comment by lmk123** [comment]
明白了，我会考虑一下

备注：DeepL 的文档翻译接口 https://www.deepl.com/zh/docs-api/documents/

**Comment by caiisen** [comment]
https://translate.google.com/
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/57999483/195355233-892efffe-03ce-455e-a765-3468eaabfdfd.png">

谷歌翻译是能直接上传PDF文档的，如果只是为了翻译PDF，而不强调DeepL和Google Translate孰优孰劣的话，还是可以尝试的。
BTW 需要特殊网络环境

**Comment by cotagxrdhy** [comment]
他是想破解官网的限制，这个功能免费就别想了

**Comment by msjsc001** [comment]
这个功能DEEPL可以直接上传翻译，不太有必要，关闭这个需求。
