### ISSUE TITLE
腾讯云实时语音识别,直接购买腾讯云的服务,这里应该怎么配置

### ISSUE THREAD

**Issue by ZongrongLi** [hcfyapp/crx-selection-translate#1508]
**没有这个功能（改进）的时候，你遇到了什么问题？**
腾讯云实时语音识别, 直接在腾讯云那里购买的语音识别资源包, 这边无法使用, 依然提示"腾讯云实时语音识别只能付费使用，请前往【服务申请】购买翻译积分。",需要什么额外配置么, 我以前的划词翻译用的好好的, 是同一个key

**你想要如何解决你的问题？**
比如，添加 PDF 标记功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
比如，如果划词翻译无法添加 PDF 标记功能，那么至少允许我在别的 PDF 软件里进行划词翻译。

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。

**Comment by lmk123** [comment]
实时语音识别目前只支持购买划词翻译的【翻译积分】来使用，不支持自行填写密钥，这里有说明 https://hcfy.app/docs/guides/video
