### ISSUE TITLE
Brave（Chrome内核）提示无法解压缩扩展程序

### ISSUE THREAD

**Issue by GHDeepUser** [hcfyapp/crx-selection-translate#1510]
## 基本信息

划词翻译版本：8.7.8
浏览器版本：Brave 1.44.112
操作系统：Win10

## 重现问题的步骤

1.进入chrome web store 安装提示“无法解压缩扩展程序”
2.下载离线安装包安装也提示“无法解压缩扩展程序”，8.7.8和8.7.7两个离线都不行

试了其他扩展程序安装没有此问题

![Snipaste_2022-10-13_16-52-00](https://user-images.githubusercontent.com/15059695/195551236-a2dba17d-8c14-4214-9bd8-0899c1c8b118.png)

**Comment by lmk123** [comment]
没用过 Brave，我也不知道怎么办，看有没有其他人能帮你解决这个问题吧 :joy:

**Comment by GHDeepUser** [comment]
原来装的是8.7.1，扩展一直没有自动更新，手动卸载后再装就装不上了，悲剧

**Comment by GHDeepUser** [comment]
找到问题了！是被杀软拦截了 😂包里有sougou.ico文件，杀软以为有搜狗全家桶安装给拦截了，导致浏览器提示解压缩包失败！

**Comment by lmk123** [comment]
😂 很好的案例，以后要是有用户说安装不上我就让他们关杀软
