### ISSUE TITLE
关闭VPN或将bing的那几个域名加入代理（设置直连），还是无法使用bing翻译

### ISSUE THREAD

**Issue by DogeFlow** [hcfyapp/crx-selection-translate#1511]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
我这边是正常的，如图：

<img width="403" alt="image" src="https://user-images.githubusercontent.com/5035625/195758924-66e5dc17-ee2d-4a6b-8bd6-4a67d4a8d814.png">

你不能用的报错消息是什么？

**Comment by DogeFlow** [comment]
> 我这边是正常的，如图：
> 
> <img alt="image" width="403" src="https://user-images.githubusercontent.com/5035625/195758924-66e5dc17-ee2d-4a6b-8bd6-4a67d4a8d814.png">
> 
> 你不能用的报错消息是什么？

单个单词可以翻译，但是短句就不行了，以前是可以的
![image](https://user-images.githubusercontent.com/34650487/195760155-bffd0ca0-8a59-4ea4-8990-88187290db93.png)

**Comment by lmk123** [comment]
具体是什么短句？

**Comment by DogeFlow** [comment]
> 

随便一个句子都不行，但单词可以，比如这个
![image](https://user-images.githubusercontent.com/34650487/195769572-a2625342-1ffc-4cb9-aeac-182b14f311f3.png)

**Comment by lmk123** [comment]
必应词典确实没有提供结果：

<img width="359" alt="image" src="https://user-images.githubusercontent.com/5035625/195770169-d136d320-34ba-4d62-b39e-ae957dbe496a.png">

**Comment by lmk123** [comment]
划词翻译里的是“必应词典”，不是“必应翻译”。词典是只会对单词有翻译结果的，你在 https://cn.bing.com/dict 试一下就知道了，划词翻译的结果就来自这里，它不提供的话我也没法捏造一个结果出来。

**Comment by DogeFlow** [comment]
> 划词翻译里的是“必应词典”，不是“必应翻译”。词典是只会对单词有翻译结果的，你在 https://cn.bing.com/dict 试一下就知道了，划词翻译的结果就来自这里，它不提供的话我也没法捏造一个结果出来。

好的，明白了，谢谢
