### ISSUE TITLE
后期是否会推出独立的个人术语库?

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1512]
请问划词翻译后期是否会推出术语库支持?
虽然现在一些翻译API支持了个人术语库, 但是仅限于网页版, 并不和API互通. (简单地说就是难用的一批)
感觉划词翻译可以支持独立的术语库, 用户在划词翻译配置好 (以界面UI的方式导入, 对新手较为友好. 对于老油条可以支持导入csv、xls、xlsx等等 ) 翻译的时候自动识别术语库.

可能这样会导致翻译的速度变慢, 可以支持开关功能, 例如google\deepl开启术语库功能, 其他翻译关闭.

感觉这个功能不错, 希望可以考虑.

**Comment by lmk123** [comment]
术语库这个功能没法加在划词翻译里。

划词翻译没有能力处理翻译结果的，我所做的只是把文字发给翻译服务，然后显示翻译服务返回的结果，而术语库是用来调整翻译结果的，所以只能在翻译服务那一侧加。

目前有一些 API 其实是支持术语库的，比如百度翻译可以在 https://fanyi-api.baidu.com/manage/term 添加术语库，我可以在文档里加上各个翻译服务的术语库介绍。

**Comment by lmk123** [comment]
我在官网各个服务的申请步骤中更新了术语表的说明。

目前来看，百度翻译（不含专业版）、阿里翻译（含专业版）是支持术语表的；有道和 DeepL 虽然支持，但需要划词翻译写代码做接入；其它服务不支持。
