### ISSUE TITLE
deepl重复翻译

### ISSUE THREAD

**Issue by yuanhepeng** [hcfyapp/crx-selection-translate#1514]
![图片](https://user-images.githubusercontent.com/39111057/195866647-fb43da02-3b95-4627-be22-e8d99421dffe.png)

**Comment by lmk123** [comment]
因为 deepl 提供了多种结果所以我都显示出来了

<img width="518" alt="image" src="https://user-images.githubusercontent.com/5035625/195871713-c1735ee1-f59e-4972-95ba-26b127fb7fb5.png">
