### ISSUE TITLE
使用 google.com 翻译报错：远程服务器返回了错误的 HTTP 响应码：400

### ISSUE THREAD

**Issue by oodzchen** [hcfyapp/crx-selection-translate#1515]
## 基本信息

划词翻译版本：8.7.9
浏览器版本：Firefox Developer Edition 106.0b8 (64-bit)
操作系统：Linux (Manjaro)

## 重现问题的步骤

1. 设置里面的谷歌翻译选择「国外.com」-「速度快、准确率低」
2. 随便打开一个英文网页，选中一段英文并点击翻译按钮

### 预期行为
正常翻译成中文

### 实际行为
谷歌翻译结果显示：
> 远程服务器返回了错误的 HTTP 响应码：400

### 补充信息

我的电脑一直有系统级代理，直接打开 translate.google.com 一直是正常的，中国版谷歌翻译关闭之后我立刻设置成了 .com 版本，用了两天，好像不太稳定，今天网页划词翻译直接不能用，在新窗口打开进行翻译却是正常的。

必应翻译也不稳定，时而可以翻译，时而不行，cn.bing.com 我一直都没走代理的，现在直接新窗口打开翻译也不行。

现在的结果是划词翻译几乎没法用。

**Comment by lmk123** [comment]
先说必应的问题。划词翻译里的不是必应翻译，是必应词典，必应词典只会对单词有翻译结果。

然后是谷歌的问题，我我 Firefox 105.0.3 正式版没法重现，目前也没有收到其它谷歌翻译 400 问题的报告。你可以试一下卸载划词翻译后重新安装看看

**Comment by lmk123** [comment]
对了，还有一点，就算你选择了国外（.com），也还是要按照公告里的说明 [https://hcfy.app/blog/2022/09/28/ggg](https://hcfy.app/blog/2022/09/28/ggg) 把 `translate.googleapis.com` 设为走代理或者加 hosts 的

**Comment by oodzchen** [comment]
@lmk123 确实是 `translate.googleapis.com` 的问题，加入到代理就好了
