### ISSUE TITLE
百度翻译公共配额用尽

### ISSUE THREAD

**Issue by LenKiMo** [hcfyapp/crx-selection-translate#1517]
划词翻译版本：8.7.8
浏览器版本：Microsoft Edge 版本 106.0.1370.47 (正式版本) (64 位)
操作系统：Windows 10

## 重现问题的步骤

1.发起任意百度翻译
2.
3.

### 预期行为
正常翻译

### 实际行为
百度翻译报错 54004 `账户余额不足`

**Comment by lmk123** [comment]
我的百度翻译账号欠费了 😂 已充值，现在恢复了
