### ISSUE TITLE
网页翻译显示“远程服务器返回了错误的http”

### ISSUE THREAD

**Issue by Leanne2002** [hcfyapp/crx-selection-translate#1520]
## 基本信息

划词翻译版本：不清楚
浏览器版本：edge
操作系统：windows11

## 重现问题的步骤

1. 打开https://www.laculturegenerale.com/pepin-le-bref-biographie-histoire/#Bibliographie
2. 选择全文翻译
3.显示错误

### 补充信息

#

**Comment by lmk123** [comment]
https://hcfy.app/blog/2022/09/28/ggg

很早就发公告了

**Comment by Leanne2002** [comment]
> https://hcfy.app/blog/2022/09/28/ggg
> 
> 很早就发公告了

已经修改过HOST并且测试过谷歌翻译可使用仍出现此问题

**Comment by lmk123** [comment]
目前为止还没有使用公告的方案后仍不能用谷歌翻译的用户。

有很多可能性，公告里其实都有写过：

1. IP 失效了，换个 IP 试试（即使用手动修改的方式，自选一个 IP
2. 修改 hosts 之后是需要完全重启浏览器的
