### ISSUE TITLE
增加 单词和句子分开翻译 的功能

### ISSUE THREAD

**Issue by liwind** [hcfyapp/crx-selection-translate#1521]
**问题**
希望划词翻译时，如果是单词可以显示更详细释义，而句子则直接翻译。

**建议**
这就需要设计时分开单词和句子（一个词汇判定为单词多个则是句子），可以分别使用不同的翻译API（如单词用有道，翻译用百度）。
这样单词翻译就能显示更多释义，后续也能添加自定义词典，单词本及导出 等功能。

**补充信息**
谷歌翻译和有道翻译单词和句子都是分开的，单词能显示更多释义。

**Comment by lmk123** [comment]
此 issue 已合并至 #1693
