### ISSUE TITLE
最新版chrome配合最新版插件不能翻译本地网页

### ISSUE THREAD

**Issue by jdnx** [hcfyapp/crx-selection-translate#1522]
## 基本信息

划词翻译版本：商店2022.10.20最新版
浏览器版本：chrome 106
操作系统：win10 x64

## 重现问题的步骤

1. chrome打开一个本地保存的html,显示该网页禁止划词翻译, 选中文本后右键选翻译也不能翻译,只是打开插件的界面,只能手工复制文本到框中点翻译

 之前在chrome 103版本中 使用v7.5.15的离线版本上述功能正常, 与在线的网页一样可正常翻译, 找了最新版的设置也没看到关于禁止本地网页翻译的选项, 不知道是什么问题, 请指教,谢谢!

**Comment by lmk123** [comment]
确认一下是否允许划词翻译访问本地网址 https://hcfy.app/docs/faq/#file-url
