### ISSUE TITLE
希望增加Yandex网页翻译的选项

### ISSUE THREAD

**Issue by GeniusLv2006** [hcfyapp/crx-selection-translate#1523]
Google翻译国内无法直接访问，需要添加hosts文件或者科学上网才能解决。Yandex翻译国内可以直接访问且速度尚可。
而且Yandex的网页翻译似乎是可以像以前Google翻译那样直接调用不是一定要使用api的（如果我的说法有错误敬请谅解），Firefox中的翻译扩展Translate Web Pages（https://github.com/FilipePS/Traduzir-paginas-web ）就可以使用Yandex翻译。
虽然说Yandex本身的翻译质量可能不是那么理想，但是至少是多了一个选择，而且使用更方便。
希望能添加Yandex翻译的选项，谢谢。

**Comment by lmk123** [comment]
好的，感谢提供建议

**Comment by lmk123** [comment]
我本来代码都写好了，结果试了一下发现 Yandex 的翻译结果非常不准确，基本到了不能用的程度。我本来以为是我的代码有问题，但用 https://github.com/FilipePS/Traduzir-paginas-web 里的 Yandex 试了一下发现也是一样的，如下图。

但是 Yandex Translate 的官网里的翻译结果就是正常的，所以很显然是 Yandex 对它们的免费试用接口做了手脚，故意提供质量极低的翻译。

我现在要纠结一下要不要加进来了…

<img width="665" alt="截屏2023-03-07 12 18 55" src="https://user-images.githubusercontent.com/5035625/223319856-fa9ed89b-e0f6-44a7-8395-518b3f17a76c.png">
