### ISSUE TITLE
密码无法更改

### ISSUE THREAD

**Issue by 0netouch** [hcfyapp/crx-selection-translate#1524]
## 基本信息

划词翻译版本：8.7.7
浏览器版本：106.0.5249.119
操作系统：win11

## 重现问题的步骤

1.忘记密码
2.重置密码
3.用新密码登陆 显示用户名与密码不正确

### 预期行为
![QQ截图20221022155905](https://user-images.githubusercontent.com/82279457/197327913-5747806d-30d5-41ef-b047-6045ddfe2e22.png)

**Comment by lmk123** [comment]
稍等，我试一下

**Comment by lmk123** [comment]
我试了一下，是可以正常修改成功的。可能情况：

1. 邮箱账号是区分大小写的，确认一下你注册账号时有没有写过大写字母
2. 修改密码时需要等网页有“修改成功”的提示才能关闭网页

**Comment by 0netouch** [comment]
![QQ截图20221023212117](https://user-images.githubusercontent.com/82279457/197394674-8f38e744-f7df-4c1e-8815-2cc8b145e2da.png)
![QQ截图20221023212130](https://user-images.githubusercontent.com/82279457/197394677-0d76c9f6-e852-4c41-a46a-af587e57b210.png)

**Comment by 0netouch** [comment]
· 乌龙了 发现自动记录的登陆邮箱前面多个i
