### ISSUE TITLE
Chrome上Deepl不能翻译报错

### ISSUE THREAD

**Issue by yushuwai** [hcfyapp/crx-selection-translate#1527]
## 基本信息

划词翻译版本： v8.7.10
浏览器版本：Chrome 106.0.5249.119（正式版本） （64 位）
操作系统：Windows 10 21H2

## 重现问题的步骤

1.打开任意英文网页，如 https://www.nature.com。
选择划词翻译里的 Deepl 双语 或 译文。英文网页均不能翻译，反馈 “翻译结果时出错。错误信息：响应超时”。

### 补充信息
切换为Google 翻译网页无任何问题。

**Comment by lmk123** [comment]
请先根据文档排查问题，如果不是文档中描述的问题，欢迎继续留言。https://hcfy.app/docs/faq/#deepl-only
