### ISSUE TITLE
Deepl仍是黄点→红点

### ISSUE THREAD

**Issue by KURAPIKAAAA** [hcfyapp/crx-selection-translate#1530]
## 基本信息

划词翻译版本：10.2.2
浏览器版本：Chrome 107.0.5304.62
操作系统：win1020h2

## 重现问题的步骤

1.挂梯子谷歌翻译可用，但换成Deepl，复制文字时图标上显示黄点，几秒后变红
2.
3.

**Comment by KURAPIKAAAA** [comment]
↑使用的不是网页翻译，是在AdobeDC内查看PDF使用的划词翻译

**Comment by lmk123** [comment]
你使用的是 copytranslator，不是划词翻译。
