### ISSUE TITLE
充值会员后的提示界面有误

### ISSUE THREAD

**Issue by ciceroxiao** [hcfyapp/crx-selection-translate#1531]
## 基本信息

划词翻译版本：划词翻译 v8.7.10
浏览器版本：Chromium Version 106.0.5249.119 (Official Build) snap (64-bit)
操作系统：Ubuntu 22.04.1 LTS

## 重现问题的步骤

1.注册账号；
2.微信充值 - 一个月；
3.充值成功后，界面显示信息有误。

### 预期行为
预期会告知用户会员到期日期。

### 实际行为
未正常显示会员到期日期，而是显示 undefined.

`<div class="bp3-dialog-body">您的会员到期时间为 undefined。</div>`
![Screenshot from 2022-10-28 15-05-48](https://user-images.githubusercontent.com/115197878/198550312-b5329ad1-03ed-43a4-8cea-83ac5df76aa2.png)

### 补充信息

疑似是网页源码的变量未能设置正确或者是变量传递错误。

**Comment by lmk123** [comment]
我用划词翻译 8.7.10、macOS Chrome 106.0.5249.119（正式版本） (arm64) 试了一下，充值一个月后能正常显示时间，如下图。那请问你的会员有正常到账吗？可以在个人中心确认一下你的会员到期时间。

<img width="509" alt="截屏2022-10-28 18 09 51" src="https://user-images.githubusercontent.com/5035625/198563100-c7da8ed8-852c-4a05-ba14-8734ca33e76c.png">

**Comment by lmk123** [comment]
而且我还注意到一个问题，就是你的界面里没有”支付成功！”这几个字，这很奇怪，除非代码被修改过，否则支付成功界面不可能会没有“支付成功！”这几个字才对。

**Comment by ciceroxiao** [comment]
我确实没有看到“支付成功！”这个提示。
我没有修改代码的动机：提交 Bug 需要时间，而提交 Bug 之后，我也得不到任何奖励。
我在个人中心能够看到自己的会员到期时间。

**Comment by lmk123** [comment]
我说的不是你，我只是想到一种可能性，那就是你使用的可能是被别人修改过代码后重新打包的划词翻译 😂 以前曾经有用户在其它地方下载了划词翻译，而里面含有恶意代码的情况

请问你是在哪里下载的划词翻译？

另外，你可以提供一下你付款时的交易单号，我可以在后台查一下你的付款记录，确认一下你的会员状态是否正常

**Comment by ciceroxiao** [comment]
因为我使用的是 Chromium，所以是在 Chrome Web Store 下载的。
交易单号的话，要翻很久才能找到。不过，我的划词翻译账号是：《为保护隐私，已隐藏》。
就目前来看，我账号的会员状态是合理正常的。

**Comment by lmk123** [comment]
我在后台看到你的账号了，会员到期时间确实是正确的。

如果是从 Chrome Web Store 下载的那就没问题，不过我对于为什么你会出现这个 bug 以及没有“支付成功！”这几个字没啥头绪 :joy:

有可能得用 Chromium 而不是 Chrome 才能重现成功，我换个 Chromium 试试
