### ISSUE TITLE
美音朗读很诡异

### ISSUE THREAD

**Issue by VKWF** [hcfyapp/crx-selection-translate#1532]
## 基本信息

划词翻译版本：8.7.10
浏览器版本：chrome 107.0.5304.87
操作系统：macOS Ventura 13.0

## 重现问题的步骤

macOS升级到13后，划词翻译用美音朗读时，声音变得非常奇怪，音量很低、声音很哑很尖，像曾志伟捏着嗓子说话。。。英音是正常的。
我用的api是腾讯翻译君和有道，上述问题在这两个上面都存在。

**Comment by lmk123** [comment]
我还没升级到 13，但我估计大概率无解，因为划词翻译的语音就是由操作系统朗读的，操作系统的语音就是如此那我也改不了 :joy:

我在网上看到 13 问题一大堆，所以还没升级，等我升到 13 了看看吧

**Comment by lmk123** [comment]
重现了。

使用有道翻译 `and` 这个单词，然后点击美音的播放按钮，声音非常奇怪。英音正常。

正在确认能否从划词翻译这边修复
