### ISSUE TITLE
音视频翻译只识别语音不翻译

### ISSUE THREAD

**Issue by bterhnebe** [hcfyapp/crx-selection-translate#1534]
## 基本信息

划词翻译版本： v8.7.10
浏览器版本：edge 107.0.1418.24
操作系统：WIN10

## 重现问题的步骤

1.音视频翻译只识别语音不翻译。youtube和twitch都试过了都是这样。
2.截图：https://i.imgur.com/37wD6GB.png
3.

### 补充信息

[https://i.imgur.com/37wD6GB.png](url)

**Comment by lmk123** [comment]
这一点在文档里有提到过：

<img width="369" alt="image" src="https://user-images.githubusercontent.com/5035625/199065187-7737ad24-a82a-4e87-a532-3f967598f6e4.png">

这个问题只能等我以后接别的短句好一点的服务来解决了。
