### ISSUE TITLE
网页翻译：允许不翻译 #tag 标签

### ISSUE THREAD

**Issue by XHXIAIEIN** [hcfyapp/crx-selection-translate#1535]
**没有这个功能（改进）的时候，你遇到了什么问题？**

[例如这个instagram帖子](https://www.instagram.com/p/CkY8NCZrqfe/) 会自动将#标签翻译，

**你想要如何解决你的问题？**

希望能添加一个设置，在twitter或者instagram这类网站，不翻译标签的部分

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
我看到设置里面有一个“源文本处理”，不知道能不能用这个？但是不知道怎么使用，可否提供一些案例？

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。

**Comment by lmk123** [comment]
我将在之后的版本中给全文翻译加一些选项，允许用户设置跳过某些文本，比如 # 开头或者中文等。
