### ISSUE TITLE
网页翻译，在翻译结果生成前，不将原文替换为 "正在翻译..."，

### ISSUE THREAD

**Issue by XHXIAIEIN** [hcfyapp/crx-selection-translate#1536]
**没有这个功能（改进）的时候，你遇到了什么问题？**

目前，在开启网页翻译时，会自动将所有内容替换成"正在翻译"，大多数网站中会导致页面排版发生很大的变化，在美观上，体验非常糟糕。

**你想要如何解决你的问题？**

添加一个选项，在翻译结果生成前，不将原文替换为 "正在翻译..."，

**Comment by lmk123** [comment]
下个版本将不再全局显示“正在翻译，请稍候……”，而是改为在页面顶部或底部显示唯一一个 loading 状态标识
