### ISSUE TITLE
网页翻译，火山翻译源，前面有多余的空格

### ISSUE THREAD

**Issue by XHXIAIEIN** [hcfyapp/crx-selection-translate#1538]
## 基本信息

划词翻译版本：v8.7.11
浏览器版本：107.0.5304.88
操作系统：Windows11 22H2

## 重现问题的步骤
1. 打开[Twitter](https://twitter.com/home)
2. 激活插件(Ctrl + Q)
4. 火山翻译，双语

### 预期行为

```
HelloWorld!
你好世界！
```

### 实际行为

```
HelloWorld!
 你好世界！
```

**Comment by lmk123** [comment]
为何关了？是因为现在火山翻译没有这个问题了吗

**Comment by XHXIAIEIN** [comment]
似乎只会在双语模式下重现
