### ISSUE TITLE
必应词典的“网络释义”不见了

### ISSUE THREAD

**Issue by yf836760** [hcfyapp/crx-selection-translate#1540]
## 基本信息
今天我发现必应词典的“网络释义”不见了，我收藏了不少的生词，但是有些生词本来有对应的网络释义，却显示无结果。
划词翻译版本：8.7.11
浏览器版本：Microsoft Edge版本 107.0.1418.26 (正式版本) (64 位)
操作系统：Win11 22621.675

## 重现问题的步骤
1. 翻译收藏夹里面的“composite formatting”和“hex dump"

### 预期行为
应当出现翻译结果，因为这是我当初添加到收藏夹的生词。

### 实际行为
显示”无翻译结果。“

### 补充信息
感觉必应词典的”网络释义“全都不见了，可能“composite formatting”和“hex dump"当初都只有一个”网络释义“

**Comment by lmk123** [comment]
我不清楚以前有没有，不过我刚才试了下“composite formatting”确实是没有翻译结果的，如图：

<img width="358" alt="截屏2022-11-03 12 21 55" src="https://user-images.githubusercontent.com/5035625/199647174-4b15f6c1-4dbd-49fb-a539-c0f31a623a54.png">

如果必应词典不提供翻译结果，那我也没法捏造一个出来 :joy:
