### ISSUE TITLE
独立翻译窗口。谷歌翻译会出现拼音音标

### ISSUE THREAD

**Issue by XHXIAIEIN** [hcfyapp/crx-selection-translate#1541]
**没有这个功能（改进）的时候，你遇到了什么问题？**

目前，只有谷歌翻译会在上面出现一个拼音音标的信息，在大多数情况似乎是没有用的，因为它显示的音标也是原文的音标，大可不必。。

![Snipaste_2022-11-07_13-57-23](https://user-images.githubusercontent.com/45864744/200236609-843e1abf-4986-46ae-b71d-a658d693a92b.png)

**你想要如何解决你的问题？**

希望能加在设置里面加个开关去掉。或者直接去掉？

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**

**补充信息**

**Comment by lmk123** [comment]
下个版本将会添加一个选项，可以关闭音标

**Comment by Langeeker** [comment]
> 下个版本将会添加一个选项，可以关闭音标

从头翻了三遍选项都没找到这个关闭音标的地方，请问在哪里设置？

**Comment by lmk123** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/5035625/230127461-1c83f7e0-6807-495d-859f-b759450cd2b4.png">

**Comment by Langeeker** [comment]
> <img alt="image" width="638" src="https://user-images.githubusercontent.com/5035625/230127461-1c83f7e0-6807-495d-859f-b759450cd2b4.png">

找到了，谢谢开发者！这次就不开 issue 了，想提一个改进 feature ，划词翻译 translate-panel 的 max-height 能不能可以给用户设置具体高度数值。估计很多使用者都不会只开一个翻译服务，比如我经常开三个翻译源相互对比，在默认宽度下，只有500多px的最大高度，翻译一段话的时候，有时候一个翻译都显示不全，拖下去上面的翻译又看不到了，烦心。

现在的解决方案有两个：
1 手动拉长宽度，造成一句话很长，读起来费力且效果不好。
2 使用pin钉住，这样自动就会容纳现有内容展开，能满足需求，但是我初衷并不是想要翻译框常驻，所以每次还要取消 pin，很繁琐。下次使用，还得重复 pin/unpin ，非常影响效率（知道有拖动自动 pin 的功能，但是取消的时候一样还得再去点 pin 按钮）。

所以希望划词翻译增加 translate-panel 的 max-height 设置具体高度数值。或者支持整个面部的竖向拖动，这个还是得允许 max-height 突破现有数值才行。
