### ISSUE TITLE
Chrome中划词翻译插件崩溃

### ISSUE THREAD

**Issue by 2222A** [hcfyapp/crx-selection-translate#1542]
## 基本信息

划词翻译版本：8.7.11
浏览器版本： Chrome 104.0.5112.81（正式版本） （64 位）
操作系统：win10专业版，2021/‎12/‎19，19044.2130

## 重现问题的步骤

1.电脑关机（甚至有时候是关闭浏览器）
2.电脑打开，打开浏览器
3.发现划词翻译崩溃，需要在插件管理中进行修复，即会重新安装

### 预期行为
正常打开浏览器就使用

### 实际行为

每次开机打开浏览器，或者就是打开关闭浏览器就会导致插件崩溃

**Comment by lmk123** [comment]
神奇了，我第一次收到划词翻译崩溃的反馈 :joy:

我也毫无头绪，也许你可以试试关掉电脑的杀毒软件（360 之类的）然后重启试试

**Comment by sdir** [comment]
我的也一直奔溃，卸载重装插件也不行。每次都是强制退出浏览器，现在插件处于不可用状态

划词翻译版本：8.7.11
浏览器版本： Chrome 106.0.5249.119（正式版本） （64 位）
操作系统：MacOS 12.6

**Comment by lmk123** [comment]
我的 macOS 12.6、Chrome 107.0.5304.110（正式版本） (arm64)没有出现过这个问题 :joy:

**Comment by lmk123** [comment]
最近确实收到了大概 6 个出现了划词翻译崩溃的反馈，但是也有人反馈在点击“修复”之后就能恢复了。

这个问题我没法重现，感觉像是 Chrome 浏览器自己的 bug。

**Comment by lmk123** [comment]
由于长时间没有相关反馈，所以这个工单我先关闭了。如果以后再出现类似情况，欢迎反馈。

**Comment by 2222A** [comment]
我也莫名奇妙的复现不了了 ，它又正常了苦笑🤣
