### ISSUE TITLE
独立窗口使用DeepL翻译特别慢（自己申请的密钥）

### ISSUE THREAD

**Issue by ZhouSong0** [hcfyapp/crx-selection-translate#1543]
## 基本信息

划词翻译版本：
浏览器版本：版本 107.0.5304.89
操作系统：Win11家庭版

## 重现问题的步骤

1.划词翻译在使用独立翻译窗口的时候，使用DeepL翻译时特别慢（大概十几秒左右），我并没有使用免费试用而是用的自己申请的Free接口类型密钥，按照帮助文档中的说明，应该几秒钟就出来了。使用彩云和腾讯基本上都是秒翻译。

**Comment by lmk123** [comment]
我写 2 秒左右是我自己所在地的测试，但实际上影响网速的因素很多，比如我测了一下，在辽宁大连需要 10 秒才有结果，不过其它大部分地区都确实是 2 秒左右

https://tool.chinaz.com/speedtest/api-free.deepl.com

这个问题我没法解决，要解决的话就得让 DeepL 在国内部署服务器 :joy:
