### ISSUE TITLE
独立翻译窗口在win10下面的任务栏是黑色的，和默认黑色的任务栏颜色一样，不容易分辨

### ISSUE THREAD

**Issue by meihus** [hcfyapp/crx-selection-translate#1544]
![image](https://user-images.githubusercontent.com/63285959/200796738-b8db33e1-b164-411a-a63e-0f9cc9072dff.png)

**Comment by lmk123** [comment]
这个问题其实好久以前就有人吐槽了 :joy:

我会在之后的版本改善一下这个图标，后续进展可以跟进 #1002
