### ISSUE TITLE
内置PDF文本选中位置与文本显示位置不一致

### ISSUE THREAD

**Issue by WVXTXVW** [hcfyapp/crx-selection-translate#1546]
## 基本信息

划词翻译版本：8.7.11
浏览器版本：chrome版本 86.0.4240.198（正式版本） （64 位）
操作系统：win10

## 重现问题的步骤

1.打开英文论文
2.选中想要翻译的片段
3.大概率会出现问题

### 预期行为
![image](https://user-images.githubusercontent.com/58168893/201601717-2ba8870f-7322-46ff-868b-99b0b967a505.png)
这张图为其它PDF阅读器里选中illustrated这段文本的效果

### 实际行为
![微信截图_20221114154032](https://user-images.githubusercontent.com/58168893/201602567-00a35345-6b16-49de-b72a-cb5685d334c7.png)
这张图为划词翻译内置PDF阅读器里选中illustrated这段文本的效果

### 补充信息
这个问题出现了很久了，划词翻译这个插件很好用，对于我来说就只有这一点实在是有点难受，希望作者能够注意到这个问题，并进行优化

问题示例中采用的PDF文件：
[A fast MPPT-based anomaly detection and accurate fault diagnosis technique for PV arrays.pdf](https://github.com/hcfyapp/crx-selection-translate/files/10000759/A.fast.MPPT-based.anomaly.detection.and.accurate.fault.diagnosis.technique.for.PV.arrays.pdf)

**Comment by lmk123** [comment]
感谢反馈。内置的 PDF 基于开源项目 PDF.js 开发，你所反馈的问题只能等它们修复后由我更新在划词翻译内。

我会在近期将内置的 PDF.js 版本更新到最新版，届时你可以试试看能否解决你的问题。

**Comment by lmk123** [comment]
即将发布的 v9.1.0 已将内置 PDF 阅读器升级到了最新版本，届时你可以试一下这个问题有没有解决，没有解决的话只能等 PDF.js 以后修复了。
