### ISSUE TITLE
Newline Feature Suggestions

### ISSUE THREAD

**Issue by mswbol** [hcfyapp/crx-selection-translate#1547]
![image](https://user-images.githubusercontent.com/46061868/201930505-88ae3f93-61df-4692-b0cb-c3a40f3e2ad7.png)

当用户选择使用 【回车键】进行翻译时，应该默认允许用户使用【ctrl + 回车键】或 使用【shift + 回车键】进行换行。
当用户选择使用【ctrl + 回车键进】行翻译时，应该默认允许用户使用【ctrl + 回车键】 或 使用【shift + 回车键】进行换行。

**Comment by lmk123** [comment]
这其实是个 bug :joy: 见 #1489

将在未来的版本中修复

**Comment by mswbol** [comment]
@lmk123 当用户选择使用 【回车键】进行翻译时，应该默认允许用户使用【ctrl + 回车键】或 使用【shift + 回车键】进行换行。
当用户选择使用【ctrl + 回车键进】行翻译时，应该默认允许用户使用【ctrl + 回车键】 或 使用【shift + 回车键】进行换行。

期待你的回复，让我明白你已经看到了此条消息
