### ISSUE TITLE
火山翻译的配置无法正常导入

### ISSUE THREAD

**Issue by Samge0** [hcfyapp/crx-selection-translate#1549]
## 基本信息

划词翻译版本：v8.7.11
浏览器版本：Chrome 版本 107.0.5304.110（正式版本） （64 位）
操作系统：ubuntu20.04、mac、windows server2019

## 重现问题的步骤

1.在ubuntu20.04中导出密钥配置，分别导入到mac、windows2019的chrome中，插件版本都是v8.7.11；
2.百度、腾讯、彩云、有道这几个密钥的配置都能正常导出导入，只有火山翻译的密钥无法正常导出导入；
3.尝试排除系统问题跟浏览器版本问题，结果都是一样的，怀疑导出/导入操作是否没有记录火山翻译的信息。

### 预期行为
期望所有密钥都能正常导出导入；

### 实际行为
目前仅发现 火山翻译 的密钥无法正常导出导入；

**Comment by lmk123** [comment]
感谢反馈，这确实是一个 bug，我将尽快修复

**Comment by lmk123** [comment]
即将发布的 v9.1.0 已修复此问题。
