### ISSUE TITLE
DeepL 报响应超时错误（2022-11-21）

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1553]
## 基本信息

划词翻译版本：9.1.0
浏览器版本：Firefox 107
操作系统：macOS

## 重现问题的步骤

1. 在网页上划词
2.
3.

### 预期行为
DeepL 显示翻译结果
### 实际行为
DeepL 报响应超时
### 补充信息

已根据文档排查问题，确认能正常打开 deepl.com 且能正常翻译

2022 年 11 月 30 日已确认**有且仅有 macOS 上的 Firefox 有问题**，macOS 上的其它浏览器、Windows 上的 Firefox 都是正常的。

**Comment by ZhenlingTang** [comment]
win10 chrome 107.0.5304.89 在全文翻译时，也出现了上面的问题

**Comment by lmk123** [comment]
Chrome 上已经确认过是正常的，Chrome 上的响应超时看一下 https://hcfy.app/docs/services/free#deepl

**Comment by lmk123** [comment]
虽然没有针对这个问题做过修复，但 v9.2.0 中重构 DeepL 后，意外的发现此问题也被解决了。

**Comment by lmk123** [comment]
又试了下，发现 v9.1.1 中也无法重现此问题了，看来是 DeepL 自己调整了代码之后，不再有这个问题了。
