### ISSUE TITLE
安卓Firefox Nightly中添加了这个扩展，但是无法弹出“设置”面板，可以修复吗？

### ISSUE THREAD

**Issue by chzzfly** [hcfyapp/crx-selection-translate#1554]
## 基本信息

划词翻译版本：9.1.0
浏览器版本：谷歌应用商店下载的Firefox Nightly 1122
操作系统：Android

## 重现问题的步骤

1. 手机浏览器中添加此扩展
2. 打开此扩展的设置，不能弹出“设置”面板，也无法进行账号登陆等操作

### 补充信息

https://sspai.com/post/63040 可以根据这篇文章设置，让Firefox nightly 安装任意扩展。

**Comment by lmk123** [comment]
划词翻译暂未对手机浏览器做过适配

**Comment by chzzfly** [comment]
> 



> 划词翻译暂未对手机浏览器做过适配

事实上，kiwi，Firefox等浏览器可以安装PC上大部分的扩展，如果在手机上能做些简单的支持，让其处于基本可用的状态，将会更好。

**Comment by lmk123** [comment]
你可能认为这只是“简单的支持”，但是：

- 首先，Firefox 的用户是 Chrome、Edge、Firefox 这三家当中最少的
- 其次，Firefox 兼容起来是最麻烦的，在给 PC 端的 Firefox 做兼容的时候就花费了不少时间，且还有一堆[无法解决的问题](https://hcfy.app/docs/guides/firefox)，所以移动端的 Firefox 我更是不敢碰 :joy:
- 最后，一旦我做了兼容，也就意味着以后出了问题要维护，兼容成本高、维护成本高，用户量也少，性价比太低了

**Comment by zhahuya** [comment]
> 你可能认为这只是“简单的支持”，但是：
> 
>     * 首先，Firefox 的用户是 Chrome、Edge、Firefox 这三家当中最少的
> 
>     * 其次，Firefox 兼容起来是最麻烦的，在给 PC 端的 Firefox 做兼容的时候就花费了不少时间，且还有一堆[无法解决的问题](https://hcfy.app/docs/guides/firefox)，所以移动端的 Firefox 我更是不敢碰 😂
> 
>     * 最后，一旦我做了兼容，也就意味着以后出了问题要维护，兼容成本高、维护成本高，用户量也少，性价比太低了

好的
