### ISSUE TITLE
谷歌翻译报错 `Unexpected token < in JSON at position 0`

### ISSUE THREAD

**Issue by guiguisdbd** [hcfyapp/crx-selection-translate#1556]
## 基本信息

划词翻译版本： v9.1.0
浏览器版本：Chrome 100.0.4896.127（正式版本） 
操作系统：Mac OS 12.4

## 重现问题的步骤
0. 首先，这个问题出现在“在线编写英文文档”的场景中，网页长时间打开，不会刷新。

1. 使用梯子，确保可以正常访问国外的谷歌翻译
2. 选择 速度慢准确率高模式
3. 多次进行划词翻译 翻译多个句子， （连续不断的翻译似乎不会触发这个问题。间隔一段时间，比如数分钟后，再次在同一个页面进行翻译时会触发报错）

### 预期行为
正常返回结果
### 实际行为
<img width="450" alt="截屏2022-11-24 15 52 45" src="https://user-images.githubusercontent.com/57624817/203724613-3c98292e-578e-4dca-9df3-02a1113fa383.png">

### 补充信息
线索1: 问题出现时，我调整设置为 速度快准确率低，会短暂的修复这个问题。插件似乎又可以使用了。
但之后（重复步骤3），还会出现翻译报错。再次切换回 速度慢准确率高，又可以解决问题（短暂地）。
线索2: 出现问题时，我新建了一个百度翻译的网页，fanyi.baidu.com，在其文本框中使用划词翻译插件。
此时谷歌翻译恢复了，返回文档编辑页面，功能也恢复了（点击了“重试”按钮，没有刷新页面）。
线索3: 问题出现时，刷新页面时没用的。
线索4: 当从“速度快 准确率低”模式，发现出现问题，进一步，切换至“速度慢准确率高”模式之后，再次发生报错的提示会略有变化，一般为：Unexpected token < in JSON at position 0
<img width="451" alt="截屏2022-11-24 16 09 25" src="https://user-images.githubusercontent.com/57624817/203727842-c36c6a0d-8597-4ff6-8532-83c6d0c556d6.png">

**Comment by lmk123** [comment]
你是不是安装了两个划词翻译？

**Comment by lmk123** [comment]
在 v9.1.0 中，只要使用了“速度慢、准确率高”的谷歌翻译，就一定会在一段时间之后出现图中的报错，这是我特意在 v9.1.0 中加上的；而在 v9.1.0 之前，这个错误就会是“解析谷歌翻译结果时出现错误：n[0] is undefined”

**Comment by lmk123** [comment]
而你现在会交替出现这两种错误信息，我感觉像是你既安装了 v9.1.0，也安装了以前旧版本的划词翻译

**Comment by lmk123** [comment]
总结一下，使用了“速度慢、准确率高”会出现图中的报错是正常现象，但是你说你切换到”速度快、准确率低”之后会出现报错就很奇怪了，理论上不会出现才对，你需要告诉我具体报错是什么，我才能分析问题原因

**Comment by guiguisdbd** [comment]
> 总结一下，使用了“速度慢、准确率高”会出现图中的报错是正常现象，但是你说你切换到”速度快、准确率低”之后会出现报错就很奇怪了，理论上不会出现才对，你需要告诉我具体报错是什么，我才能分析问题原因

感谢您的及时回复，我附上了 切换到”速度快、准确率低”之后会出现报错 截图，供您参考。另外，已在chrome://extensions/中确认，应该没有重复同时安装两个版本的插件。目前的版本是9.1.0 。
<img width="451" alt="截屏2022-11-24 16 09 25" src="https://user-images.githubusercontent.com/57624817/203731272-bebd0577-de77-4db4-aace-de0e571eb629.png">

**Comment by lmk123** [comment]
我大概知道是怎么回事了。谷歌翻译应该报了 400 / 403 / 429 之类的错误，但是我在 v9.1.0 中有个 bug，没有把这个错误抛出来，而是把错误当成正常的翻译结果来解析，于是就变成了 `Unexpected token < in JSON at position 0` 这个错误。

我会在下个版本中先解决这个错误没有抛出来的问题，然后我们再看看你的谷歌翻译具体抛出来的是什么错。

**Comment by lmk123** [comment]
我也可以现在就告诉你怎么查看具体的报错，不过需要你进行一些步骤

**Comment by guiguisdbd** [comment]
好的，您可以告诉我相应的操作步骤，和您需要的关键反馈。 收集到素材后我会第一时间回复您，最迟不超过一天。
再次向您表达感谢和敬意。

**Comment by guiguisdbd** [comment]
刚刚看了你的主页才发现微信小助手和划词翻译的作者都是你  同样作为某些项目的独立开发者，非常能体会独立意味着什么，要面对什么。  致以问候吧

**Comment by lmk123** [comment]
:joy: 看来是同道中人，搞独立开发真的太难了

**Comment by lmk123** [comment]
查看谷歌翻译报错的步骤：

1. 在浏览器地址栏粘贴 `chrome://extensions/?id=ikhdkkncnoglghljlkmcimlnlhkeamad` 并按回车打开（也就是划词翻译的扩展详情页）
2. 点击【查看视图】里的“背景页”链接，会弹出来一个标题为 DevTools 开头的窗口
3. 在 DevTools 里切换到“网络”标签卡，然后点一下“Fetch/XHR”
4. 回到划词翻译里随便翻译一个单词

按照预期，此时 DevTools 里会看到一些 HTTP 请求，比如我这里是 

<img width="447" alt="image" src="https://user-images.githubusercontent.com/5035625/203734358-893979dc-6440-4a25-be2e-9d8a21f916ca.png">

如果你的谷歌翻译会报错，那么图中有问题的 HTTP 请求会被标为红色，麻烦点一下被标红的 HTTP 请求，然后截图发我一下【标头】、【载荷】、【预览】里的内容

**Comment by lmk123** [comment]
不用按照上面的步骤给我信息了，我检查了下我的代码，知道是什么问题了 :joy:

我这就发个新版本解决

**Comment by lmk123** [comment]
我刚才发布了 v9.1.1，能否麻烦你按照下面的步骤安装一下 v9.1.1 的离线安装包，试一下有没有解决你的问题？

https://hcfy.app/docs/install/#offline

**Comment by guiguisdbd** [comment]
收到 已经更新到9.1.1.如果不出意外的话，应该不会出现任何问题，那便是最好的结果和反馈了吧。

**Comment by lmk123** [comment]
嗯嗯，按照我的预期，你更新到 v9.1.1 之后，谷歌翻译应该会报一次 HTTP Error: 429 这个错误，点重试之后就会恢复正常使用，你可以试试

**Comment by guiguisdbd** [comment]
嗯…… 刚安装的时候刷新了一次页面，之后一直到目前，都一直在正常工作。 
辛苦了！

**Comment by lmk123** [comment]
没事没事，也非常感谢你的反馈，如果还有问题欢迎继续反馈

**Comment by guiguisdbd** [comment]
一个项目就是这样一点一点成长起来的，像个孩子，能参与也很荣幸。有机会可以多交流合作 不知道github有私信功能么😂

**Comment by lmk123** [comment]
GitHub 没有私信功能 :joy: 你可以在公众号联系到我
