### ISSUE TITLE
edge浏览器内置pdf翻译错位

### ISSUE THREAD

**Issue by zzXuAn997** [hcfyapp/crx-selection-translate#1557]
## 基本信息
使用edge浏览器的划词翻译时，部分英文文献会出现选中的翻译文本错位或无法选中等问题，当我用chrome版的时候，无此问题
划词翻译版本：
浏览器版本：edge 107.0.1418.56
操作系统：win11，我之前在win10系统也出现过

## 重现问题的步骤

1.用edge打开英文文献（部分英文文献会出现，出现频率较高且出现的文献会一直出现）
2.第一次打开是edge阅读器，第二次打开才是内置pdf阅读器（这个我挺喜欢的）
3.选取词句翻译时，出现错位或无法选中等问题

**Comment by lmk123** [comment]
我没法修复 :joy: 内置 pdf 阅读器是基于第三方开源的 pdf 阅读器二次开发的，我能做的就是尽可能快的将 pdf 阅读器升级到最新版本。

划词翻译 v9.1.1 已经使用了最新版本的 pdf 阅读器，你可以试试看这个问题有没有得到改善。
