### ISSUE TITLE
收藏和历史记录可以放进独立翻译窗口里

### ISSUE THREAD

**Issue by RichardLuo0** [hcfyapp/crx-selection-translate#1558]
**没有这个功能（改进）的时候，你遇到了什么问题？**
每次都要进设置复习收藏的单词

**你想要如何解决你的问题？**
收藏可以直接放进独立翻译窗口里

**Comment by lmk123** [comment]
我对独立翻译窗口的定位是一个仅用来显示翻译结果的地方，它应该跟网页上弹出的翻译结果一样小巧精简，不适合添加收藏夹这类需要大窗口的功能。
