### ISSUE TITLE
百度翻译莫名其妙用掉了258w字符？？

### ISSUE THREAD

**Issue by maige12138** [hcfyapp/crx-selection-translate#1559]
## 基本信息

划词翻译版本：最新
浏览器版本：火狐最新

今天早上就看了一个网站，没多少字的那种，突然花掉我258w的字符量？
100多的费用啊

**Comment by maige12138** [comment]
![图片](https://user-images.githubusercontent.com/62500256/203967014-9de276b8-78aa-4b56-a980-b12a46286686.png)

**Comment by lmk123** [comment]
之前也有人有类似情况出现，可能原因如下：

- 你的密钥被用在了其它软件里，其它软件内跟划词翻译加起来一共用了这么多
- 你的密钥泄漏了，例如我曾在某个翻译群里看到有人把密钥截图发出来
- 你频繁的使用了网页全文翻译功能

我的建议：

联系百度翻译客服问一下你这两百多万字符的具体使用内容，如果能确定是划词翻译的 bug 导致消耗了这么多字符，我会赔付给你。

**Comment by lmk123** [comment]
另外，保险起见：

- 立刻去 https://fanyi-api.baidu.com/api/trans/product/desktop 重置密钥
- 在接下来的一段时间内，只在划词翻译里一直用看看有没有问题，最好时不时的去确认一下字符数有没有异常，毕竟百度翻译不会实时提醒字符数使用情况

如果确认是划词翻译的问题，我来赔付给你。

**Comment by lmk123** [comment]
由于长时间无反馈，所以这个工单我先关闭了。如果你有了新的发现，欢迎继续留言，我会重新跟进。

**Comment by maige12138** [comment]
啊这？我不是回复你了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月12日(周一) 晚上9:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hcfyapp/crx-selection-translate] 百度翻译莫名其妙用掉了258w字符？？ (Issue #1559)




 
由于长时间无反馈，所以这个工单我先关闭了。如果你有了新的发现，欢迎继续留言，我会重新跟进。

**Comment by lmk123** [comment]
我在 18 天前就回复你了，但是你一直没有回复。

你可以在 https://github.com/hcfyapp/crx-selection-translate/issues/1559 看到我的回复

**Comment by maige12138** [comment]
我之前直接转发的他的邮件，不知道你那边为什么没有收到，现在我直接发给你看看

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月13日(周二) 晚上11:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hcfyapp/crx-selection-translate] 百度翻译莫名其妙用掉了258w字符？？ (Issue #1559)




 
我在 18 天前就回复你了，但是你一直没有回复。
 
你可以在 #1559 看到我的回复

**Comment by lmk123** [comment]
> 我之前直接转发的他的邮件，不知道你那边为什么没有收到，现在我直接发给你看看

你说的“他”是指百度翻译客服吗？

我还是没有收到你的回复，你不要用邮箱发了，直接在网页版的 GitHub 里贴百度翻译客服的邮件截图吧

**Comment by maige12138** [comment]
嗯？“他”是指客服，上一个邮件的附件就是客服发的东西，如果还是没有我就去github试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月14日(周三) 下午2:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hcfyapp/crx-selection-translate] 百度翻译莫名其妙用掉了258w字符？？ (Issue #1559)




  
我之前直接转发的他的邮件，不知道你那边为什么没有收到，现在我直接发给你看看
  
你说的“他”是指百度翻译客服吗？
 
我还是没有收到你的回复，你不要用邮箱发了，直接在网页版的 GitHub 里贴百度翻译客服的邮件截图吧

**Comment by lmk123** [comment]
还是没有

**Comment by scruel** [comment]
> 还是没有

这个在线同步会同步密钥么？本地设置的导入导出究竟什么时候能有？感觉插件很不安全。
