### ISSUE TITLE
打开独立窗口时发生了一个错误：Invalid value for bounds. Bounds must be at least 50% within visible screen space.

### ISSUE THREAD

**Issue by xming521** [hcfyapp/crx-selection-translate#1561]
## 基本信息
打开独立窗口时发生了一个错误：Invalid value for bounds. Bounds must be at least 50% within visible screen space.
我正在使用win自带远程 分辨率和缩放可能发生了变化
划词翻译版本：v8.7.11
浏览器版本：Cent Browser 版本 5.0.1002.276（正式版本） （64 位） (Chromium 102.0.5005.167)
操作系统：win11 22H2 22621.755

## 重现问题的步骤

1.打开独立窗口
2.
3.

**Comment by lmk123** [comment]
在【设置】-【翻译面板】-【独立翻译窗口】点一下“重置位置与大小”即可
