### ISSUE TITLE
新功能建议：能导出收藏的单词

### ISSUE THREAD

**Issue by xiaotianhu** [hcfyapp/crx-selection-translate#1562]
**没有这个功能（改进）的时候，你遇到了什么问题？**
单词收藏后，只能在插件的收藏里看，不能方便的导出，转换格式后导入到其他背单词的应用里。

**你想要如何解决你的问题？**
支持直接导入到其他背单词的App中
或 能在单词收藏页面导出单词 （比如markdown/txt/anki格式)
或 收藏时可以设置回调API，调用其他接口

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**

**补充信息**

**Comment by lmk123** [comment]
导出功能将在最近开始开发。现在的问题是我不知道要导出的具体格式，目前有用户提供了 excel 格式的具体内容，我会先开发一个导出成 excel 的形式。

如果可以的话，希望你能提供一下你所说的 markdown / txt / anki 等的具体格式到 #1765，我添加进导出格式当中。
