### ISSUE TITLE
划词窗口翻译含有特殊格式的文本时出现多余回车

### ISSUE THREAD

**Issue by Orienser** [hcfyapp/crx-selection-translate#1563]
## 基本信息

划词翻译版本：v9.1.1
浏览器版本：107.0.5304.107
操作系统：Windows 10 家庭中文版 22H2

## 重现问题的步骤

1. 问题可在该网页复现：[https://www.mongodb.com/docs/manual/reference/operator/aggregation/fill/#mongodb-pipeline-pipe.-fill](https://www.mongodb.com/docs/manual/reference/operator/aggregation/fill/#mongodb-pipeline-pipe.-fill)
2. 对带有蓝色单词格式的文本执行划词翻译，如下图：
![image](https://user-images.githubusercontent.com/13484542/204522421-7b0108d1-64bb-4d65-9007-2bc6ed34b071.png)
3. 可以看到，在面板的翻译结果中，`$fill`的前后各加了一个回车，但原文是没有回车的。
4. 全文翻译模式则没有该问题，如下图：
![image](https://user-images.githubusercontent.com/13484542/204522635-da723623-acb1-4995-a228-f163668354b6.png)

### 预期行为
划词翻译的结果不应在有特殊格式的单词前后加空格。

### 实际行为
划词翻译的结果在有特殊格式的单词前后加了空格。

### 补充信息
在同网站的另一个页面中，对同样格式的文本执行划词翻译不会出现多余回车的问题。
页面链接：[https://www.mongodb.com/docs/manual/meta/aggregation-quick-reference](https://www.mongodb.com/docs/manual/meta/aggregation-quick-reference/)
翻译结果：
![image](https://user-images.githubusercontent.com/13484542/204523696-87922123-f947-43f0-a8a6-ab83c01d9b91.png)

**Comment by lmk123** [comment]
首先给你的反馈内容点赞，已经很久没看到如此详实的反馈信息了。

这个问题我重现了，但是我没法解决。获取划选的文本内容使用的是浏览器提供的方法，换句话说，浏览器提供给了我什么，我就只能用什么。

不过，我详细比较了你提供的两处地方，虽然从表面上看它们是一样的，但底层的 HTML 结构是不一样的。

出现问题的 HTML 结构是这样的：

```html
<p>You can use <a><span><code>$fill</code></span></a> to populate missing data points:</p>
```

而没有出现问题的 HTML 结构是这样的：

```html
<p>In the <a><code>db.collection.aggregate()</code></a> method</p>
```

注意：出现问题的 $fill 多了一层 `<span>`，我猜这就是让浏览器在 $fill 两侧加上换行符的原因。但是我也不能去掉这些换行符，因为大部分情况下，浏览器添加的换行符是准确的（比如用户跨段落划选了文本的时候）。

如果你确认你不会跨段落划选文本，你可以在设置的“源文本处理”里勾选【去掉换行符】来避免出现这个问题。

**Comment by Orienser** [comment]
感谢回复，从 HTML 结构来看，出现换行的确是正常结果。必要时我会尝试用“源文本处理”解决。
