### ISSUE TITLE
阿里翻译服务无法使用，显示调用失败

### ISSUE THREAD

**Issue by hyb-oyqq** [hcfyapp/crx-selection-translate#1564]
## 基本信息

划词翻译版本：9.1.0
浏览器版本：Google Chrome 64位 107.0.5304.107
操作系统：windows 11家庭中文版 22H2 22621.819

## 重现问题的步骤

1.使用阿里翻译源翻译任意网站均可复现

### 预期行为
正常输出翻译结果

### 实际行为
显示尝试使用密钥时失败

### 补充信息
检查过阿里云AccessKey 审计，发现插件已经正常调用（此处说明AccessKey 无误），但返回了一个errorMessage，大概内容是Specified signature is not matched with our calculation.

如果是插件bug，希望尽快修复。
如果是我的插件配置问题的话，希望可以帮助指导我如何正确配置，谢谢

"errorMessage": "Specified signature is not matched with our calculation. server string to sign is:POST\napplication/json\nVPVTnflsUyYa1x200YoWgQ==\napplication/json;charset=UTF-8\nThu, 01 Dec 2022 10:54:44 GMT\nx-acs-signature-method:HMAC-SHA1\nx-acs-signature-nonce:41da2a64-e191-4291-a415-334bd28e7174\nx-acs-version:2019-01-02\n/api/translate/web/general",

**Comment by lmk123** [comment]
我用自己的密钥试过了，是没有问题的。

从报错内容来看是签名计算错误，我猜你的操作系统时区可能不是北京时间。如果调整成北京时间后还是有问题，你可以继续留言。

**Comment by hyb-oyqq** [comment]
> 我用自己的密钥试过了，是没有问题的。
> 
> 从报错内容来看是签名计算错误，我猜你的操作系统时区可能不是北京时间。如果调整成北京时间后还是有问题，你可以继续留言。

![image](https://user-images.githubusercontent.com/35864297/205068768-383e766c-2c61-4ae5-95cc-12eaec11505b.png)
我的时区没有错误，但问题依旧存在

**Comment by lmk123** [comment]
我也没啥头绪，毕竟我这里没法重现，且没有其他人反馈有这个问题。

你可以试一下：

1. 首先创建一对新的密钥
2. 然后卸载划词翻译后重新安装，并关闭所有其它扩展程序
3. 重启电脑后，在划词翻译内填入新的密钥再试试看

如果这样还是不行，那我也没办法了 :joy:

**Comment by hyb-oyqq** [comment]
> 我也没啥头绪，毕竟我这里没法重现，且没有其他人反馈有这个问题。
> 
> 你可以试一下：
> 
> 1. 首先创建一对新的密钥
> 2. 然后卸载划词翻译后重新安装，并关闭所有其它扩展程序
> 3. 重启电脑后，在划词翻译内填入新的密钥再试试看
> 
> 如果这样还是不行，那我也没办法了 😂

我一开始设置的地区是美国，但是我觉得这应该和区域设置和时区没关系，因为我配置的百度和彩云都可以正常调用，如果百度调用时也用了签名那应该也是不可用，但是实际上除了阿里和阿里高级版其他都可以正常调用。为了防止是因为校园网的屏蔽导致无法使用我还尝试了使用梯子开启全局来试图调用但依旧没有办法正常调用。
我查询到我使用的插件落后了一个版本，我会尝试更换浏览器，更新插件等方法继续尝试，如果有进度我会在下方继续留言

**Comment by hyb-oyqq** [comment]
我在我的电脑上使用虚拟机环境复现成功复现了
划词翻译版本：9.1.1
浏览器版本：Microsoft Edge 64位  107.0.1418.56
操作系统：windows 10专业版（未激活） 22H2 19045.2251
目前来看暂时是没有办法使用阿里翻译了，只能先将就用百度和彩云了
![image](https://user-images.githubusercontent.com/35864297/205084322-6147367d-fbc1-4715-8385-e7e09f0bc75e.png)

**Comment by lmk123** [comment]
> 我一开始设置的地区是美国，但是我觉得这应该和区域设置和时区没关系，因为我配置的百度和彩云都可以正常调用

百度翻译和彩云小译的签名算法不需要时间作为变量，而阿里翻译需要。

> 我在我的电脑上使用虚拟机环境复现成功复现了

我也换 Edge 试了下，还是无法重现，我还试了下，通过翻译积分使用阿里翻译也是正常的。

**Comment by lmk123** [comment]
对了，你可以明天或者后天再试一下，之前也有用户反馈刚申请阿里翻译的时候一直报 400 错误，但第二天就正常了。

**Comment by hyb-oyqq** [comment]
> 对了，你可以明天或者后天再试一下，之前也有用户反馈刚申请阿里翻译的时候一直报 400 错误，但第二天就正常了。

这个问题已经有一两周了，只不过这周百度配额用了一半了想匀一点配额才想起还有个阿里没法用来提交issue的😂
还是先谢谢了，我等下个版本或者放假换个网络环境再试试（我总感觉是校园网惹的祸）
