### ISSUE TITLE
受到未知bug问题的启发想提一个功能建议

### ISSUE THREAD

**Issue by hyb-oyqq** [hcfyapp/crx-selection-translate#1565]
**没有这个功能（改进）的时候，你遇到了什么问题？**
#1564 

**你想要如何解决你的问题？**
新增翻译服务调用日志功能，方便检查问题错误

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
在问题反馈页面提供抓取错误日志的教程或指导方便更好的反馈错误避免无效提问

**Comment by lmk123** [comment]
我认为目前的划词翻译用不到。

翻译服务的签名算法是不会变的，只要密钥填对了那基本不会有问题，出现问题的基本是用户自己填错了密钥或者时区不对，少部分是因为账号或 IP 被翻译服务风控了给封了，你提的阿里翻译的问题其它人也提过，但他们也反馈重装划词翻译或者过一段时间就恢复了，所以这几本可以说是阿里翻译自己的问题。

总的来说，没有添加日志功能的现在已经能满足问题反馈的要求了，就算加了日志，要教导用户从里面找出有用的信息进行反馈难度过大（现在连按照格式反馈问题都有很多用户做不到），所以我暂时不会加。
