### ISSUE TITLE
网页翻译突出显示译文改进建议，内附效果图

### ISSUE THREAD

**Issue by Unintendedz** [hcfyapp/crx-selection-translate#1566]
## 这是当前插件网页翻译双语的样子
![image](https://user-images.githubusercontent.com/64687143/205210000-18722330-2e54-40b8-911a-5a69aa084067.png)

## 即使打开突出显示译文效果也不够理想
![image](https://user-images.githubusercontent.com/64687143/205209015-e34324fd-758b-4517-b6c2-7ce335d3d7ed.png)

## 这是我想建议的方式（PS：译文字体有稍微放大到 1.1em）
![image](https://user-images.githubusercontent.com/64687143/205209936-0af1e0f8-ac9d-4d1f-8857-73a823540516.png)

我相信这样能够极大地提升突出显示译文这个功能的效果，是非常具有性价比的改动。

**Comment by lmk123** [comment]
感谢提出建议。

确实有更加突出，但如果要将原文置灰的话，会破坏网页的原有结构（如果你知道 HTML 的话，即需要在原文外包裹一层 `div`），这可能会导致原网页的样式无法正确应用到原文上从而导致页面显示错乱。

另外，我不确定这种样式适用于**所有网页**，你图中的网页是黑底白字，但也有很多网页是白底黑字，还有很多网页是各种奇奇怪怪的颜色，所以我不敢使用颜色来突出译文。
