### ISSUE TITLE
网页翻译识别语言失败

### ISSUE THREAD

**Issue by chaniqure** [hcfyapp/crx-selection-translate#1567]
![screenshot-20221202-145014](https://user-images.githubusercontent.com/25723223/205233192-1673135f-ec3c-4630-a8aa-50486209df87.png)

## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.查看谷歌邮箱，点击网页翻译

**Comment by lmk123** [comment]
请查看 https://hcfy.app/docs/guides/page#yyy
