### ISSUE TITLE
添加了翻译的key及id，刷新视频后仍提示腾讯云实时语音识别只能付费使用，请前往【服务申请】购买翻译积分。

### ISSUE THREAD

**Issue by digger-yu** [hcfyapp/crx-selection-translate#1568]
## 基本信息

划词翻译版本：
划词翻译 v9.1.1

浏览器版本：

firefox 107.0.1 (64 位)  已是最新
操作系统：

windows 10 

## 重现问题的步骤

1. 想用划词翻译的视频翻译，目前是划词翻译未登录用户，已经在插件选项，服务申请中，添加了腾讯的secid及key
2. 但刷新bilibili视频之后，选择右键，划词翻译，音视频翻译，选择播放视频开始识别
3. 但还是提示腾讯云实时语音识别只能付费使用，请前往【服务申请】购买翻译积分。
4. 试过两个pc的火狐，都是最新版，有同样的现象

**Comment by lmk123** [comment]
先看一下说明 https://hcfy.app/docs/guides/video

这是因为腾讯云的音视频翻译功能需要提供额外信息（account id），但现在划词翻译不支持填写这个额外的信息，所以没法跟腾讯翻译的 key 和 id 通用

**Comment by lmk123** [comment]
我会在未来将腾讯云实时语音识别改为可以跟腾讯翻译密钥通用的，后续进展可以跟进 #1569
