### ISSUE TITLE
希望后续能接入微软翻译

### ISSUE THREAD

**Issue by rrtt2323** [hcfyapp/crx-selection-translate#1571]
希望后续能够在所有翻译功能选项中，接入微软翻译的api，因为从个人平时的使用体验上讲，微软翻译的准确性和词句通顺度都比较优秀

**Comment by cotagxrdhy** [comment]
edge浏览器可以免费使用

**Comment by lmk123** [comment]
微软翻译就是必应吧，后面会接入的，见 #1271
