### ISSUE TITLE
接入「能不能好好说话？」“翻译”接口

### ISSUE THREAD

**Issue by ZeaKyX** [hcfyapp/crx-selection-translate#1572]
[拼音首字母缩写翻译工具](https://lab.magiconch.com/nbnhhsh/)
```
社交平台上通过拼音首字母缩写指代特定词句的情况越来越多，为了让更多人能勉强理解这一门另类沟通方式、做了这一个划词转义工具。
```
虽然该项目初期可能带有一些纯趣味作品的意思，但现在用户字典丰富了，已经非常实用。手动滑稽

**补充信息**
github脚本：https://github.com/itorr/nbnhhsh

**Comment by lmk123** [comment]
这个跟翻译不相关啊 :joy: 我想保持划词翻译的核心功能是单一的。
