### ISSUE TITLE
重复翻译

### ISSUE THREAD

**Issue by ronnywr** [hcfyapp/crx-selection-translate#1574]
## 基本信息
<img width="722" alt="image" src="https://user-images.githubusercontent.com/38126770/207013554-0d74108b-d9aa-4475-b3db-1c3f61f57640.png">

划词翻译版本：9.1.1
浏览器版本：chrome 107.0.5304.110
操作系统：mac 12.5.1

## 重现问题的步骤

1.https://www.coursera.org/learn/conduct-ux-research/lecture/BYz8S/case-study-improving-design-at-google
2.全文翻译
3.

**Comment by lmk123** [comment]
我使用 macOS 13.0.1、划词翻译 9.1.1，Chrome 版本 108.0.5359.98（正式版本） (arm64) 试了一下，没有重现，如下图

<details>
<img width="813" alt="image" src="https://user-images.githubusercontent.com/5035625/207101582-425ac2f7-966a-44bc-9730-a3b7618e6c3b.png">
</details>

你可以试试把 Chrome 升级到 108 看看

p.s. 补充一下重现步骤：需要点击【视频脚本】才能看到截图中的那段话

**Comment by lmk123** [comment]
由于长期无反馈，所以这个工单我就先关闭了。如果你仍有疑问，欢迎继续留言，我会继续跟进。
