### ISSUE TITLE
建議可以自動將翻譯文字的換行符號去除

### ISSUE THREAD

**Issue by ggg5269** [hcfyapp/crx-selection-translate#1576]
**没有这个功能（改进）的时候，你遇到了什么问题？**
例如[這個網頁](https://www.cpc.ncep.noaa.gov/products/predictions/610day/fxus06.html)，框選翻譯後，因為每一段文字都被不正確的斷行切開，導致翻譯結果不精準。

**你想要如何解决你的问题？**
傳入翻譯 API 前，先行替換所有的 line break 為 空字串

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
沒有想法

**补充信息**
或許可應應不同需求，將此功能設為可選模式

**Comment by lmk123** [comment]
> 先行替換所有的 line break 為 空字串

这个是不能一刀切的替换掉的，因为当我特意划选了多个段落的文本后，翻译结果按照预期也应该是多个段落才对。

当你确实需要替换掉换行符的时候，你可以在设置的【源文本处理】中勾选“替换换行符”，这样就能解决你的问题了。

**Comment by ggg5269** [comment]
感謝回覆，已使用這個設定，確實可以解決問題

另外開一個話題
在這個網頁中，我使用網頁翻譯，結果中間內文部分都沒有被翻譯，僅上方及側邊有影響，不知道是不是哪裡沒有設定對？
![image](https://user-images.githubusercontent.com/37011770/207512030-d07189c2-8adb-49c4-a50a-58212d4774de.png)

**Comment by lmk123** [comment]
因为这个网页的正文内容被包裹在了 [\<pre\>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) 标签当中。

\<pre\> 一般是被用来包裹代码的，所以划词翻译统一跳过了对这个标签内文本的翻译。这个行为目前没有设置项可以关闭。

 p.s. 不同的问题请开一个新的 issue
