### ISSUE TITLE
页面卡停，不能使用

### ISSUE THREAD

**Issue by jh-1677** [hcfyapp/crx-selection-translate#1577]
## 基本信息

划词翻译版本： v9.1.1
浏览器版本：chrome 版本 108.0.5359.98（正式版本） （64 位）
操作系统：ubuntu 22.04

## 重现问题的步骤

1. 使用插件打开pdf
2. 页面卡停，鼠标等均不能点击使用
3. 重启，重装等都没有作用

**Comment by lmk123** [comment]
我没有 ubuntu 环境，所以我没法重现……另外我测试了，在 macOS / Windows 的 Chrome 108 是没有的这个问题的。

不过我大致猜到是什么原因引起的。v9.1.1 里的 PDF 阅读器代码使用了很多浏览器的新特性，可能是 ubuntu 里的 Chrome 支持的还不够好。

在 v9.2.0 中，我把 PDF 阅读器里的新特性替换成了旧代码，应该可以解决你的问题，等我发布 v9.2.0 了之后你可以再试试看，在这之前，你可以临时通过安装 v9.0.1 的离线安装包使用。

**Comment by jh-1677** [comment]
谢谢您的回复和耐心解答。
目前我在Firefox浏览器中使用插件，一切正常，另外感谢开发这样一款很实用的插件。谢谢
祝好！

lmk123 ***@***.***> 于2022年12月14日周三 12:59写道：
