### ISSUE TITLE
请问阿里翻译（专业版）的“选择专业领域”如何选择？

### ISSUE THREAD

**Issue by lijun2006** [hcfyapp/crx-selection-translate#1578]
## 基本信息
请问阿里翻译（专业版）的“选择专业领域”如何选择？

划词翻译版本：v8.7.8
浏览器版本：chrome 版本 107.0.5304.88（正式版本） （64 位）
操作系统：Windows 10 家庭中文版

### 实际行为
![image](https://user-images.githubusercontent.com/63136318/208064278-5f8945fe-b31f-48f5-83f4-d9209fc53fa0.png)

**Comment by lijun2006** [comment]
已解决！谢谢！
![image](https://user-images.githubusercontent.com/63136318/208067565-ef0720a2-ecc7-4e72-9d5b-a69fde9eb658.png)

**Comment by lmk123** [comment]
看来你已经找到了 :joy:
