### ISSUE TITLE
独立翻译窗口不能使用

### ISSUE THREAD

**Issue by haroldxing** [hcfyapp/crx-selection-translate#1580]
## 基本信息

划词翻译版本：9.1.1
浏览器版本：Chrome 版本 108.0.5359.124（正式版本） (x86_64)
操作系统：macOS 12.2.1 (21D62)

## 重现问题的步骤

https://user-images.githubusercontent.com/75294740/208380804-2245d033-ad86-48a0-8860-aa9e7ee185e9.mov

### 预期行为
打开独立翻译窗口
### 实际行为
报错
### 补充信息
最初是无法使用快捷键唤起，通过排除法发现不是快捷键的问题

**Comment by lmk123** [comment]
在【设置】-【翻译面板】-【独立翻译窗口】中点击一下【重置位置与大小】即可。

下个版本会将这个信息抛出来。
