### ISSUE TITLE
是否可以在“网页全文翻译”时弹出的右下角面板中添加“目标语种”选择菜单？

### ISSUE THREAD

**Issue by anaizy31** [hcfyapp/crx-selection-translate#1583]
在当前版本下，切换网页全文翻译目标语种需要打开设置，进入网页全文翻译菜单处通过下拉菜单更改。

我希望在右下角面板中加入这个下拉菜单，让我们可以实时更改网页全文翻译的目标语种。

如果无法做到的话，是否可以在插件菜单页中加入首要与次要目标语种的选项？（与 翻译面板 -> 语种 中一样）

由于我在使用网页全文翻译功能时有时需要在 中译英 与 英译中 之间切换，如果能够不需要进入设置页面就能做到这一点，会节省很多时间！

我一直是本插件的忠实用户！感谢作者对这个插件的维护，这个插件便利的功能为我节省了许多时间！

**Comment by lmk123** [comment]
谢谢你的喜欢 ❤️ 

我会在下个版本中加入“目标语种”选项

**Comment by lmk123** [comment]
v9.9.0 当中已加入了目标语种的选项

#1612
