### ISSUE TITLE
关于谷歌翻译在9.2.0版本失效的问题

### ISSUE THREAD

**Issue by WVXTXVW** [hcfyapp/crx-selection-translate#1584]
## 基本信息
由于谷歌翻译退出中国，目前个人采用的是改host来使用谷歌翻译，该方法在9.1.1版本能正常使用，在升级到9.2.0后划词翻译出现了谷歌翻译用不了的情况。同样的设置在9.1.1版本能正常使用。尝试过卸载重装插件，重启浏览器，更换浏览器都无法解决。下图为9.2.0版本的表现情况
![image](https://user-images.githubusercontent.com/58168893/208625423-5d7d0e43-084a-44d5-b245-72a1cbeed2d6.png)

划词翻译版本：9.2.0
浏览器版本：Chrome 92.0.4515.131（该版本为联想浏览器8.0.0.12022）和98.0.4758.102（该版本为Chorme浏览器）
操作系统：win10

**Comment by lmk123** [comment]
感谢反馈，将尽快在 9.2.1 中修复

**Comment by lmk123** [comment]
另外，你也可以将 Chrome 升级到最新版本（至少 v103）即可正常使用谷歌翻译。

**Comment by WVXTXVW** [comment]
感谢作者，我先试试。之前也反馈过内置PDF的问题，9.1版本的更新让我舒服了很多，真的好评

**Comment by WVXTXVW** [comment]
更新chorme后确实能够使用了
