### ISSUE TITLE
在 discord 划词翻译，选中连续对话翻译会包含额外的时间信息

### ISSUE THREAD

**Issue by XHXIAIEIN** [hcfyapp/crx-selection-translate#1585]
## 基本信息

划词翻译版本： v9.1.1
浏览器版本：108.0.5359.125
操作系统：Win11

## 重现问题的步骤
1. 打开网页版 [discord](https://discord.com/)
2. 选中连续的对话，开启划词翻译

![01](https://user-images.githubusercontent.com/45864744/208876091-89b6300d-99d9-4aae-a06d-71935dd3d1b6.png)

![02](https://user-images.githubusercontent.com/45864744/208876353-268eac9e-edca-4629-9c6d-44a0d1bcd5f7.png)

### 预期行为

> what are you guys doing this christmas holidays?
construct wise i meant
and gaming wise

### 实际行为

> what are you guys doing this christmas holidays?
Today at 1:22 AM 
construct wise i meant
Today at 1:22 AM 
and gaming wise

![Snipaste_2022-12-21_17-57-55](https://user-images.githubusercontent.com/45864744/208877109-c64fcb95-f320-4d51-ba72-f36b5248856d.png)

### 补充信息

应该过滤掉这个信息

提议：划词翻译的面板，如果也能显示原文就更好排查错误了。

**Comment by lmk123** [comment]
<img width="249" alt="image" src="https://user-images.githubusercontent.com/5035625/209090074-84d74487-dd99-4752-a9d1-2af97a8a14cb.png">

Discord 在多条连续对话当中会插入时间，虽然默认是隐藏的。

但是，我无法因为 Discord 这一个网站就对用户划选的原文做删改，毕竟用户划了什么就应该显示什么。

不过，你可以使用“源文本处理”功能，通过正则表达式来过滤掉时间信息。

> 划词翻译的面板，如果也能显示原文就更好排查错误了。

点一下右上角的小齿轮，勾选“显示文本框”就能看到原文了
