### ISSUE TITLE
全文翻译的时候，将右下角的图标设置为可隐藏或显示，不影响浏览

### ISSUE THREAD

**Issue by LLC2022** [hcfyapp/crx-selection-translate#1586]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，现有 PDF 不支持标记功能，导致我无法在 pdf 上标记内容。

**你想要如何解决你的问题？**
比如，添加 PDF 标记功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
比如，如果划词翻译无法添加 PDF 标记功能，那么至少允许我在别的 PDF 软件里进行划词翻译。

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。

**Comment by lmk123** [comment]
现在的图标占的面积非常小了，而且如果彻底隐藏的话，里面的选项该放在哪里也是个问题。

如果你有更多想法，欢迎按照提问模版将你的想法补全然后在这里继续留言，我会继续跟进。

**Comment by LLC2022** [comment]
可以把设置迁移到扩展面板里面，而且平时也不需要怎么设置
