### ISSUE TITLE
Chrome的api弃用警告

### ISSUE THREAD

**Issue by lainbo** [hcfyapp/crx-selection-translate#1587]
## 基本信息

划词翻译版本：9.1.1
浏览器版本：Chrome 108.0.5359.125
操作系统：Windows 11 22H2

## 重现问题的步骤

1. 打开控制台即可发现警告
![image](https://user-images.githubusercontent.com/46062895/209275778-9044320f-e752-4bf1-91f7-82834026bd68.png)
![image](https://user-images.githubusercontent.com/46062895/209275814-d03febe3-c2ba-4c4c-9bdb-b7958e378409.png)

### 预期行为
预期不要出现警告

### 补充信息

1. Chrome 109 预计在 2023-01-10 正式发布，届时会全面禁用 Event.path
2. Event.path只有在被运行到时，才会在控制台报警告

为了避免届时出现bug，建议换用新的写法

**Comment by lmk123** [comment]
不会出现 bug，因为我做了检测，当没有 event.path 时会改为使用 event.composedPath()

不过你的提议很好，我应该优先用 event.composedPath()

**Comment by lmk123** [comment]
v9.2.2 中我已经改为了优先使用 composedPath，但控制台还是会有这个警告信息，这是由 interactjs 引起的，见 https://github.com/taye/interact.js/issues/976
