### ISSUE TITLE
是否可以支持：关闭独立窗口后，清楚浏览器历史记录

### ISSUE THREAD

**Issue by BeyondXinXin** [hcfyapp/crx-selection-translate#1589]
**没有这个功能（改进）的时候，你遇到了什么问题？**
平时比较喜欢用 ctrl shift t 来恢复关闭的网页。当打开独立窗口翻译并关闭后，恢复的网页变成了翻译独立窗口

**你想要如何解决你的问题？**
是否可以增加选项，关闭独立窗口后清除该条浏览器记录

**Comment by lmk123** [comment]
可以，不过这会让划词翻译多要求一个管理历史记录的权限，我得想一想要怎么做才不会让其他用户感到困扰
