### ISSUE TITLE
腾讯翻译君API无法调用

### ISSUE THREAD

**Issue by fsy8341** [hcfyapp/crx-selection-translate#1590]
如题。
![7777777777](https://user-images.githubusercontent.com/120952847/209792022-37f64ccc-3c2e-4816-bfb1-4a4682aef64c.jpg)

**Comment by lmk123** [comment]
我用了自己的密钥试了一下，是正常的；登陆账号后用翻译积分试了一下，也是正常的。

我猜测是你的密钥免费额度用完了

**Comment by lmk123** [comment]
由于长时间无反馈，所以这个 issue 我就先关闭了。

如果有你仍有疑问，欢迎继续留言，我会重新跟进。
