### ISSUE TITLE
如果选择的文本包含空格（文本为句子），则自动隐藏必应词典

### ISSUE THREAD

**Issue by Raychanan** [hcfyapp/crx-selection-translate#1592]
**没有这个功能（改进）的时候，你遇到了什么问题？**
必应词典。翻译句子的时候面板结果：没有提供词典翻译结果。

**你想要如何解决你的问题？**
翻译句子的时候自动隐藏（不显示）必应词典的错误结果。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
无

**补充信息**
英文，**以空格存在与否为翻译规则。如果有空格，就是句子，则不显示必应词典结果**。比如，沙拉查词把上下文（句子）翻译和词典翻译分开了。

**Comment by lmk123** [comment]
此 issue 已合并至 #1693
