### ISSUE TITLE
Chrome 双击选中的单词没法弹出翻译结果，而 Edge 浏览器就可以

### ISSUE THREAD

**Issue by Xutsuku** [hcfyapp/crx-selection-translate#1593]
## 基本信息

划词翻译版本：v9.2.1
浏览器版本：Chrome
操作系统：win11

## 重现问题的步骤

1.
2.
3.

### 预期行为
双击即可弹出翻译结果，
### 实际行为
双击无任何反应，我希望双击即可弹出翻译结果，
### 补充信息

Edge 浏览器使用的是V9.1.1 ，在copy了和Edge 相同的设置后，Chrome 浏览器不能实现同样的功能， 是不是该功能不再支持了？

**Comment by lmk123** [comment]
已有功能是不会随意删减的。

我在 Chrome 使用 v9.2.1 是能正常使用的。

你在 chrome 卸载划词翻译后重新安装试试，如果可以，那说明是设置里做了一些改动导致不会出现翻译按钮了；如果不行，那说明是划词翻译出现了 bug，需要你提供一下你的 chrome 浏览器版本等信息

**Comment by lmk123** [comment]
另外，v9.2.1 及以下版本的划词翻译有个 bug，导致划词翻译实际上至少在 chrome v80 才能正常运行，你可以确认下你的 chrome 版本是否低于 v80

**Comment by lmk123** [comment]
v9.2.2 修复了划词翻译无法在 Chrome 66 ~ 79 使用的 bug，且已经发布到了 Chrome 扩展商店，你可以更新一下，看看还有没有这个问题。

如果仍有问题，欢迎继续留言，我会跟进。
