### ISSUE TITLE
typing官网音视频翻译无法使用

### ISSUE THREAD

**Issue by narouss** [hcfyapp/crx-selection-translate#1594]
无法翻译网址：https://www.edclub.com/sportal/program-140/45702.play
描述：typingclub网站视频为英语无字幕，使用插件音视频翻译时，无法正常翻译视频，插件显示“当前页面没有视频或音频”。
![image](https://user-images.githubusercontent.com/95953125/210137344-ade6196e-18b8-4141-bc4a-5ad658541ef2.png)

**Comment by lmk123** [comment]
我看了一下，跟 #1219 是同一个问题，你可以关注 #1219 来获取修复进展。
