### ISSUE TITLE
希望能够支持导出收藏夹中的单词（API 或者同步到三方软件 e.g. webdave, anki），这样可以把翻译过的生词都整理起来，集中到一个地方复习

### ISSUE THREAD

**Issue by uohziyoam** [hcfyapp/crx-selection-translate#1596]
**没有这个功能（改进）的时候，你遇到了什么问题？**
没有同步功能，我不能把我在浏览器中翻译过的生词，和其他地方收集的单词整理在一个地方

**你想要如何解决你的问题？**
添加导出收藏夹中的单词功能

**Comment by lmk123** [comment]
导出功能将在最近开始开发。现在的问题是我不知道要导出的具体格式，目前有用户提供了 excel 格式的具体内容，我会先开发一个导出成 excel 的形式。

如果可以的话，希望你能提供一下你想要的具体格式到 #1765，我添加进导出格式当中。
