### ISSUE TITLE
希望能够增强非html自动换行文本合并的功能

### ISSUE THREAD

**Issue by Philogag** [hcfyapp/crx-selection-translate#1598]
**没有这个功能（改进）的时候，你遇到了什么问题？**
在划词一些txt格式的文档的时候，文档编写者通常会手动换行限制其单行宽度以获得更好的阅读体验。
这时候使用划词只能单独翻译每一行而无法翻译成一个完整的段落
> 例子：https://www.kernel.org/doc/Documentation/networking/timestamping.txt

**你想要如何解决你的问题？**
+ 添加一个按钮或快捷键使我可以强制strip每行并全部拼接在一起
    + 虽然这可能会导致多个段落被合并成一个大段落，但我认为这是可接受的
+ 允许编辑划取后的文本内容

**Comment by lmk123** [comment]
目前提供了两种方式来解决这个问题：

- 你可以显示文本框，然后你就可以编辑文本框里的文本来手动合并了。这种方式可能比较繁琐
- 你还可以在【设置】-【翻译面板】-【源文本处理】里勾选【将换行符替换成空格】。
  - 要注意的是，源文本处理会应用到所有文本当中，所以有时候可能你想要保留换行的情况也会被替换。
