### ISSUE TITLE
网页全文翻译后将页面中的链接弄丢了

### ISSUE THREAD

**Issue by xujz520** [hcfyapp/crx-selection-translate#1601]
![image](https://user-images.githubusercontent.com/22070188/210957038-287ff5ff-d7f1-4809-8dd5-4f4cae5e5b05.png)
![image](https://user-images.githubusercontent.com/22070188/210957450-e5172da2-3caf-4e9a-b1a2-ee38a4aee0ed.png)

测试页面地址: https://developer.chrome.com/docs/workbox/modules/workbox-window/
![image](https://user-images.githubusercontent.com/22070188/210956974-b6e2c734-8be2-4f51-aae2-1a60d96ba62f.png)

**Comment by lmk123** [comment]
确实有这个问题，但无法解决。

浏览器的全文翻译功能使用的接口是针对全文翻译做了特别优化了，可以保留原文格式，但这个接口无法用于普通的文本翻译。

划词翻译使用的翻译服务是通用的文本翻译接口，没有针对保留原文格式做优化，所以为了保证翻译结果的准确性，只能丢弃格式来保证原文的完整性，见 https://hcfy.app/docs/guides/page#%E8%AF%91%E6%96%87%E6%B2%A1%E6%9C%89%E4%BF%9D%E7%95%99%E5%8E%9F%E6%96%87%E9%87%8C%E7%9A%84%E9%93%BE%E6%8E%A5

**Comment by GF-Huang** [comment]
@lmk123  为了避免开个新 issue，在这里问个相关的问题，如有打扰，抱歉。

鉴于此问题讨论到全文翻译会丢链接的问题，我这个问题跟原问题相关。如果启用全文翻译时，选择了 `译文` （见下图），那么我在新开的另一个网页中再次启用全文翻译时，默认就会切换到 `译文`，这就会导致一些链接丢失，即使关掉全文翻译或者切换到 `双语` 也不会使链接恢复，需要 F5 刷新页面才可以。这就比较麻烦了，如果能修复这个问题当然最好，如果不能，能否在设置加个开关，新页面不保留 `双语`、`原文` 和 `译文` 的选择状态？

![image](https://user-images.githubusercontent.com/4510984/211905544-0e95aa07-ae32-430a-ac6d-f666b7f3c8f1.png)

**Comment by GF-Huang** [comment]
补充一个跟此问题相关的 BUG，不只是链接丢失，而且代码块的内容 (`xxx`) 也丢失。

### 效果：
![image](https://user-images.githubusercontent.com/4510984/212400243-55b820a4-1dbc-46a3-aeda-9cd6323f8025.png)

### 网页原样：
![image](https://user-images.githubusercontent.com/4510984/212400338-b9a19bcb-6d33-4343-a2fd-6ae56626184f.png)

### 重现步骤：
1. 打开要翻译的目标网站观看网页的原样：https://learn.microsoft.com/en-us/cpp/code-quality/understanding-sal?view=msvc-170
2. 启动划词翻译的全文翻译，切换到 `译文` 标签（不要勾选 `在当前窗口自动开启`），等待翻译完成。
3. F5 刷新页面，再次启动全文翻译，此时，划词翻译的标签状态应该保留在 `译文`，等待翻译完成，把标签切换到 `原文`，可以看到代码块的内容丢失。

### 版本信息：
浏览器：`Edge 版本 108.0.1462.76 (正式版本) (64 位)`
划词翻译：`v9.2.2`
系统：`Windows 11 专业版 22H2 22621.1105`
