### ISSUE TITLE
辅助键设置无效

### ISSUE THREAD

**Issue by yuxiaoy1** [hcfyapp/crx-selection-translate#1604]
## 基本信息

划词翻译版本：9.1.1
浏览器版本：Edge 108.0.1462.76
操作系统：Macos

## 重现问题的步骤

辅助键设置无效，不管怎么设置，不按辅助键的情况下，选中文本后都会直接自动翻译。

**Comment by lmk123** [comment]
你看看你是不是没有勾选“划词后先显示翻译按钮”

**Comment by yuxiaoy1** [comment]
没有勾选，但这两个设置有关联吗？我理解辅助键的目的是我选中文本后，按下辅助键才显示翻译结果，不按则没有，我希望能达到这种效果。另外我是不需要有翻译按钮的。

**Comment by lmk123** [comment]
我猜你是希望平时划词不显示按钮也不显示结果，只想要在通过辅助键时才直接显示结果，那么，你应该勾选“在所有网站中禁用网页划词”。

”划词后先显示翻译按钮”下方已有说明：“勾选后，划词之后会先显示翻译按钮，点击按钮后才会弹出翻译结果；如果不勾选，那么划词后会直接弹出翻译结果。”，
