### ISSUE TITLE
不应该翻译code标签的内容

### ISSUE THREAD

**Issue by xujz520** [hcfyapp/crx-selection-translate#1605]
* windows 10
* 划词翻译 v9.2.2

### 谷歌浏览器自带的网页翻译
![image](https://user-images.githubusercontent.com/22070188/211233969-6a4b41be-e90b-46b5-9295-580ded14c291.png)

### 划词翻译
![image](https://user-images.githubusercontent.com/22070188/211234100-0ff2bfa8-1293-4b39-b809-ded6fa956786.png)

用例:  [https://developer.chrome.com/docs/workbox/modules/workbox-window/#the-very-first-time-a-service-worker-is-installed](https://developer.chrome.com/docs/workbox/modules/workbox-window/#the-very-first-time-a-service-worker-is-installed)

**Comment by lmk123** [comment]
重复 #1603
