### ISSUE TITLE
【功能请求】网页全文翻译 针对页面元素设置黑名单和白名单

### ISSUE THREAD

**Issue by XHXIAIEIN** [hcfyapp/crx-selection-translate#1606]
**没有这个功能（改进）的时候，你遇到了什么问题？**

如果你经常逛某个网站、论坛、平台，在实际浏览时，通常只需要看特定的部分，其他的辅助信息即使不翻译也不影响阅读，例如网页上的次要信息、按钮、菜单、导航等。翻译之后，可能会造成排版上的混乱。

那么，能不能让用户可以自己决定各个网站需要翻译的区域呢？

**你想要如何解决你的问题？**

在网页全文翻译的设置中添加一个高级功能，允许设置网页翻译元素的白名单和黑名单，通过CSS选择器元素ID、Class、XPath 等匹配网站中需要翻译的元素。 

例如可以指定
- ID: `#main`
- Class: `.main`
- CSS选择器: `#root > div > div`
- XPath: `//*[@id="root"]/div/`

![Snipaste_2023-01-11_11-29-29](https://user-images.githubusercontent.com/45864744/211711281-311f4d92-e1b6-4a1f-8b3f-9aa468e35379.png)

**其他信息**

大概模拟了一个设置页面的预览
![Snipaste_2023-01-11_11-25-12](https://user-images.githubusercontent.com/45864744/211710830-e740e61f-1afb-4022-af66-a459291a792f.png)

由于网站里需要翻译的内容有许多，因此点击编辑时，可以在弹窗里面编辑：
![Snipaste_2023-01-11_11-38-43](https://user-images.githubusercontent.com/45864744/211712248-2273451c-8ef8-4858-986b-8a08a5feb4d9.png)

**Comment by XHXIAIEIN** [comment]
https://github.com/hcfyapp/crx-selection-translate/issues/1406

**Comment by lmk123** [comment]
感谢提供详细的方案，后续我会参考。

由于确实跟 #1406 是同一个功能请求，所以你提的这个我就先关闭了。
