### ISSUE TITLE
启用此扩展程序导致radar.cloudflare.com显示内容不完全

### ISSUE THREAD

**Issue by Hanselosz** [hcfyapp/crx-selection-translate#1609]
## 基本信息

划词翻译版本：9.2.2
浏览器版本：Chrome 109.0.5414.75
操作系统：Windows 11 22H2 22621.1105

## 重现问题的步骤

1.打开radar.cloudflare.com
2.该网站内容显示不完全

### 预期行为
该网站内容完全显示
### 实际行为
该网站内容显示不完全
### 补充信息

启用此扩展出现问题，禁用此扩展问题解决

**Comment by lmk123** [comment]
重现了。这个问题还真奇怪，我得研究一下是咋回事

**Comment by lmk123** [comment]
我今天又试了下，发现 radar.cloudflare.com 已经能在开启划词翻译的情况下正常使用了。

我没有进行过修复，所以看样子是 radar.cloudflare.com 本身做了一些改进 :joy:

**Comment by lmk123** [comment]
奇怪了，重启了一下浏览器之后就又重现了

**Comment by lmk123** [comment]
已确认跟 #1689 是同一个问题，即由于划词翻译在 html 下插入了一个 div 导致使用了 Server-side rendering 的网站发现客户端和服务端 html 结构不一样导致的。

所以这个就先关闭了
