### ISSUE TITLE
划词翻译能不能设置划词的时候才显示翻译对话框

### ISSUE THREAD

**Issue by lin64850** [hcfyapp/crx-selection-translate#1610]
翻译的时候，目前是鼠标移动到中文还是英文都会自动弹出翻译对话框，能不能设置，只有在划词的时候才显示翻译对话框，不然很影响体验
如图所示，是鼠标移动到某个字符就自动翻译，能不能需要的翻译的时候在划词显示结果
图片：https://eureka-1302416167.cos.ap-nanjing.myqcloud.com/img/Snipaste_2023-01-15_19-45-32.jpg

**Comment by lmk123** [comment]
你在设置里开启了“鼠标悬浮取词”吧？

**Comment by lin64850** [comment]
主要在设置里面没有看到有 【鼠标悬浮取词】选项~

**Comment by lin64850** [comment]
感谢，大意了
