### ISSUE TITLE
会加入微软翻译么

### ISSUE THREAD

**Issue by java-orange** [hcfyapp/crx-selection-translate#1611]
**没有这个功能（改进）的时候，你遇到了什么问题？**
google翻译太慢了，会加入微软翻译么，在别的平台测试觉得挺好用

**你想要如何解决你的问题？**
添加翻译源：微软翻译

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
增加配置一件设置hosts文件增快google翻译速度

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。
在idea中的translate翻译插件中，使用微软翻译，跟google翻译体验基本类似

**Comment by lmk123** [comment]
会的，不过我得先研究一下怎么接，后续进展可以关注 #1271 

一键设置快速 hosts 的工具是有的，见 https://hcfy.app/blog/2022/09/28/ggg

**Comment by HongJian-Yang** [comment]
> 会的，不过我得先研究一下怎么接，后续进展可以关注 #1271
> 
> 一键设置快速 hosts 的工具是有的，见 https://hcfy.app/blog/2022/09/28/ggg

老哥 研究出来没,  谷歌有时候改了host也抽风
