### ISSUE TITLE
如何去掉这玩意？

### ISSUE THREAD

**Issue by Trudeau566** [hcfyapp/crx-selection-translate#1614]
红框里的玩意儿在翻译非英文的时候就会出现，杵在那看着特别别扭，如何去掉这玩意儿？
![Snipaste_2023-01-22_12-12-57](https://user-images.githubusercontent.com/118544592/213900314-0f008712-766c-48e7-8744-b0f9928e8dcf.png)

**Comment by lmk123** [comment]
目前去不掉，之后会添加一个选项去掉，后续进展可以关注 #1541
