### ISSUE TITLE
希望PDF内置阅读器添加高亮，下划线等功能

### ISSUE THREAD

**Issue by Wjq1024** [hcfyapp/crx-selection-translate#1616]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，现有 的PDF内置阅读器 不支持高亮功能

**你想要如何解决你的问题？**
比如，添加 内置PDF高亮功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
脱离拓展做一个PC端软件（？

**补充信息**
有道词典可以在其他PDF阅读器例如WPS中，在鼠标光标划词后进行翻译，不过速度很慢，排版打乱，只能选用自家翻译源

**Comment by lmk123** [comment]
v9.1.0 起划词翻译的内置pdf 阅读器本身就是支持的

<img width="197" alt="截屏2023-01-24 15 32 18" src="https://user-images.githubusercontent.com/5035625/214235361-a74a3717-1bb3-4642-a0d7-76b067ee5ad2.png">

**Comment by Wjq1024** [comment]
但是这个只能画笔绘图，不能鼠标直接勾选文本后高亮 @lmk123

**Comment by lmk123** [comment]
我会把标注功能（即”鼠标划选文本后高亮”）的功能加入开发计划，但是优先级会很靠后。

这是因为内置 PDF 是一个第三方的独立软件，在它的基础上二次开发难度大、更新困难，且它自己可能也会在未来添加标注功能——现有的画笔绘图就是它自带的功能。
