### ISSUE TITLE
do we hava any plans to support tanslation on all screen

### ISSUE THREAD

**Issue by glkappe** [hcfyapp/crx-selection-translate#1618]
support translate on all applications, like eudic

**Comment by lmk123** [comment]
Yes, the desktop version https://github.com/hcfyapp/hcfy-desktop  I'm working on will do that for scratching words in any program.

Alternatively, you can refer to this article to find out how to use "划词翻译" extension to scratch words in other applications: https://hcfy.app/docs/guides/extra
