### ISSUE TITLE
【网页全文翻译】添加设置，可以选择默认的源语种

### ISSUE THREAD

**Issue by SeWZC** [hcfyapp/crx-selection-translate#1619]
**没有这个功能（改进）的时候，你遇到了什么问题？**
很多时候网页全文翻译我只需要使用英译中的功能，但是一旦遇到网页中有中文的情况，我就需要手动设置源语种为英文，当我需要频繁切换网页时体验会非常不流畅。

**你想要如何解决你的问题？**
在网页全文翻译设置中添加类似于*翻译面板-语种*的设置。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
像*网页全文翻译-目标语种*一样添加一个源语种的选项。

**Comment by lmk123** [comment]
下个版本将会记住你每次选择的源语种的选项，在下次开启全文翻译时会默认使用上次选择的源语种，就像目标语种那样。

后续进展可以关注 #1733
