### ISSUE TITLE
是否有兴趣移植到VSCODE

### ISSUE THREAD

**Issue by TheCGDF** [hcfyapp/crx-selection-translate#1620]
**没有这个功能（改进）的时候，你遇到了什么问题？**
VSCODE上的翻译插件大多过于简陋不太好用

**你想要如何解决你的问题？**
VSCODE版插件

**补充信息**
目前每次为了翻译VSCODE上的东西都要打开浏览器，有点麻烦。。。

**Comment by lmk123** [comment]
最通用的解决方案应该是开发一个桌面端，不然在 vscode 以外的程序中还是得开浏览器。

桌面端我正在开发，不过进度很缓慢 :joy:

**Comment by lmk123** [comment]
桌面端开发完成后会在这里通知 https://github.com/hcfyapp/hcfy-desktop
