### ISSUE TITLE
【v9.5.0 已支持 ChatGPT 翻译】希望能加入ChatGPT的模块

### ISSUE THREAD

**Issue by qqfish128** [hcfyapp/crx-selection-translate#1623]
作者的话：v9.5.0 已接入 ChatGPT，目前已提交审核，等不及的朋友可以[下载离线安装包](https://hcfy.app/docs/install/#offline)体验。

<img width="524" alt="111" src="https://user-images.githubusercontent.com/5035625/222379774-9b4a9c28-e13f-4025-9466-19a78df48169.png">

以下是原文。

-----------

**没有这个功能（改进）的时候，你遇到了什么问题？**
一直以来翻译软件很多，但能实现AI接入的很少。现在ChatGPT又不开放注册了，用户难受。发现你们的软件接入很方便，正是转型升级的好机会！祝做最大，最好，最智能的翻译软件。

**你想要如何解决你的问题？**
接入ChatGPT
会员制，可以接受付费。

**Comment by lmk123** [comment]
这个功能有待讨论。

我个人希望划词翻译的所有功能都是围绕“翻译”来建设的。不相关的功能会把一个软件变得臃肿。

虽然划词翻译很适合这类“输入文字然后输出文字”的场景，但我认为 ChatGPT 实在很难跟翻译沾边。即使我会接入，那么也只会把 ChatGPT 当成一个翻译服务使用。

不过，我确实考虑过开发一个划词后显示 ChatGPT 答复的扩展程序，但这就是一个新软件的。

**Comment by DzlqBL** [comment]
我个人对比过ChatGPT和其他翻译API的结果，发现ChatGPT的翻译结果**基本上**能吊打其他API。所以我个人还是希望作者能够把ChatGPT接口接入（当然现在只有GPT-3/4的API）
**_但是仅用于翻译_**，毕竟我用划词翻译图的也就是翻译，不需要chat。需要chat直接去ChatGPT官网chat就行。
主要是每次要用ChatGPT翻译的时候，总得手动把文字复制过去，还得手动补个"translate into Chinese"，就很麻烦。

网上目前也找不到其他将ChatGPT作为翻译助手的谷歌拓展程序，希望作者可以再次考虑一下。

**Comment by qqfish128** [comment]
翻译界的革命性技术，能跟上的会活下来，跟不上的就完蛋了。



在 2023-02-18 22:39:04，"DzlqBL" ***@***.***> 写道：

我个人对比过ChatGPT和其他翻译API的结果，发现ChatGPT的翻译结果基本上能吊打其他API。所以我个人还是希望作者能够把ChatGPT接口接入（当然现在只有GPT-3/4的API）
但是仅用于翻译，毕竟我用划词翻译图的也就是翻译，不需要chat。需要chat直接去ChatGPT官网chat就行。
主要是每次要用ChatGPT翻译的时候，总得手动把文字复制过去，还得手动补个"translate into Chinese"，就很麻烦。

网上目前也找不到其他将ChatGPT作为翻译助手的谷歌拓展程序，希望作者可以再次考虑一下。

**Comment by lmk123** [comment]
v9.5.0 已支持最新的 ChatGPT API

**Comment by lmk123** [comment]
大概会在今天（2023.03.02）发布

**Comment by dsy86** [comment]
请问9.5接入的ChatGPT语料模型是哪个版本？是昨天最新的那个gpt-3.5-turbo-0301吗？

**Comment by lmk123** [comment]
@dsy86 是

**Comment by dsy86** [comment]
> @dsy86 是

谢谢，辛苦了

**Comment by asasas234** [comment]
不支持全文翻译吗?

**Comment by dsy86** [comment]
> 不支持全文翻译吗?

我试过，支持的。

**Comment by aqlkzf** [comment]
请问可否支持chatGPT网页版的登陆，然后使用chatGPT网页版本进行翻译  1.浏览器插件的一大优势就是网页登陆方便 2.考虑到很多plus用户更希望使用网页版chatGPT 3. 等到chatGPT api免费额度清零时间一到，很多用户还是希望使用免费的chatGPT，利于插件长远发展

**Comment by lmk123** [comment]
@aqlkzf 已新开了 issue #1672 并加入了开发计划当中

**Comment by phantomk** [comment]
GPT4 模型什么时候接入

**Comment by lmk123** [comment]
@phantomk 

> GPT4 模型什么时候接入

下个版本

**Comment by lmk123** [comment]
v9.8.0 版本的划词翻译已支持在无需填写密钥的情况下就直接使用 ChatGPT

**Comment by qqfish128** [comment]
用不了chat gpt 是否会员付费可以用？
















在 2023-04-09 11:00:18，"lmk123" ***@***.***> 写道：

v9.8.0 版本的划词翻译已支持在无需填写密钥的情况下就直接使用 ChatGPT
