### ISSUE TITLE
Deepl无法翻译

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1625]
## 基本信息

划词翻译版本：9.2.2
浏览器版本：firefox 109.0.1
操作系统：Windows11

## 重现问题的步骤

deepl无法翻译，关闭广告过滤也不行。但是我打开网站里面可以翻译。

**Comment by lmk123** [comment]
v9.3.0 已修复此问题，只是还没发布。我应该会在明天发布 v9.3.0
