### ISSUE TITLE
百度翻译无效

### ISSUE THREAD

**Issue by iockx** [hcfyapp/crx-selection-translate#1629]
设置了秘钥，但依旧提示无法翻译：
可以确定秘钥准确无误，因为其他软件也进行了设置，并且可以进行翻译
```
尝试通过密钥、翻译积分使用百度翻译时均失败了。

密钥报错信息：“远程服务器没有响应。请前往百度翻译的官方平台确认密钥是否填写正确以及免费额度是否已用完。”[查看解决方案](https://hcfy.app/docs/faq/#why-services-always-loading)

翻译积分报错信息：“请先登录划词翻译账号。”[为什么此服务需要自行申请之后才能使用？](https://hcfy.app/docs/faq/#why-apply)
```

**Comment by lmk123** [comment]
密钥报错原因是“远程服务器没有响应”，出现这个报错一般是因为你的电脑没法连接到请求的服务器，比如在这个情况中是指百度翻译接口 `https://fanyi-api.baidu.com/api/trans/vip/translate`

你可以检查一下你是不是用了代理之类的，要确保能正常访问百度翻译接口

**Comment by iockx** [comment]
确实是代理原因，关闭之后就可以了，感谢~
