### ISSUE TITLE
在谷歌搜索页面全文翻译没有效果

### ISSUE THREAD

**Issue by noriole** [hcfyapp/crx-selection-translate#1630]
## 基本信息

划词翻译版本：v9.2.2
浏览器版本：
Vivaldi  5.6.2867.62 (Stable channel) （64 位）
内核 Chrome/108.0.0.0
操作系统：win10
## 重现问题的步骤

1.在谷歌搜索页面尝试全文翻译（双语模式），例如：https://www.google.com/search?q=food&ie=UTF-8
2.在谷歌搜索页面尝试全文（译文模式）

### 预期行为
1.正常显示中英对照
2.正常显示译文

### 实际行为
如截图
1.
![image](https://user-images.githubusercontent.com/62467022/218055556-9e50b93d-5fe8-4e30-a9c6-09a7d19c28a9.png)
2.没有任何变化
![image](https://user-images.githubusercontent.com/62467022/218056704-319d0ded-acfb-4dfe-b92e-776754ae6443.png)

### 补充信息

已排除其他扩展的影响
在谷歌浏览器110.0.5481.78（正式版本） （64 位） 也能重现该问题
![image](https://user-images.githubusercontent.com/62467022/218057742-0a554cf8-6f99-4537-ad2d-19ff1acfa876.png)

**Comment by lmk123** [comment]
这是因为你的网页中出现了多个语种（英语和中文），见 https://hcfy.app/docs/guides/page#yyy
