### ISSUE TITLE
能否除去谷歌翻译之后的拼音内容

### ISSUE THREAD

**Issue by tumibloom** [hcfyapp/crx-selection-translate#1634]
能否除去谷歌翻译之后的拼音内容，这样可以使得排版整齐而不显得突兀。

或者都加入拼音（当然，这会让排版看起来很乱，让人一时抓不住翻译之后的内容）

其实可以参考一下沙拉查词，相对来说可能会好一点

**Comment by lmk123** [comment]
下个版本会给个设置项，允许去掉谷歌翻译的音标 #1541
