### ISSUE TITLE
扩展图标右键菜单优化（firefox ）

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1639]
**没有这个功能（改进）的时候，你遇到了什么问题？**
一旦修改了点击扩展按钮开启网页全文翻译，想要再进设置页面就会很麻烦，右键的话也没有自定义的菜单。
![image](https://user-images.githubusercontent.com/16933298/220518382-4dbb605d-b69f-41b5-b9cf-6a73ff811c0f.png)

**你想要如何解决你的问题？**
增加右键菜单如下：
![image](https://user-images.githubusercontent.com/16933298/220518375-7723244a-a6ad-4f81-a4c7-bdf4e9808ec6.png)

**Comment by lmk123** [comment]
好提议，我会把“截图翻译”、”全文翻译”等按钮也一起集成进这个右键菜单中
