### ISSUE TITLE
设置项支持搜索

### ISSUE THREAD

**Issue by kelukeka** [hcfyapp/crx-selection-translate#1642]
**没有这个功能（改进）的时候，你遇到了什么问题？**
现有设置项繁杂且不清晰，经常找不到设置项，建议重新排布设置项，或增加搜索功能
**你想要如何解决你的问题？**
比如，添加 PDF 标记功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
增加搜索设置项功能。

**补充信息**

**Comment by lmk123** [comment]
现有设置页确实有点繁杂。我已经考虑重新组织设置页，也许会一并将搜索功能也加上。

**Comment by lmk123** [comment]
下个版本 v9.6.0 已将设置页整理了一下，主要是将原本的【通用】拆分成了五个子项：【快捷键】【外观】【语音朗读】【通知】【其它】。如果你对新的设置页有任何建议，欢迎继续留言让我知道。

其它部分的暂时没有动，目前我也还没想好要怎么整理一下，以后想到了会继续改进。
