### ISSUE TITLE
PDF阅读器渲染字体发虚

### ISSUE THREAD

**Issue by kelukeka** [hcfyapp/crx-selection-translate#1643]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，现有 PDF 不支持标记功能，导致我无法在 pdf 上标记内容。

**你想要如何解决你的问题？**
PDF阅读器渲染效果有待改进，字体发虚，看着让人眩晕

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
改进渲染方案

**补充信息**
同等缩放比下，edge浏览器渲染效果
![image](https://user-images.githubusercontent.com/77624197/220804798-2d72962d-e85e-4343-9c18-3bfe4b73904b.png)
改插件渲染效果
![image](https://user-images.githubusercontent.com/77624197/220804853-9868e671-cc9a-49db-a22a-21866ffb4695.png)

**Comment by lmk123** [comment]
内置 PDF 阅读器确实有这个问题，但我没法修复，因为它是一个第三方独立软件，只能等它自己修复这个问题后，我再更新进划词翻译当中。
