### ISSUE TITLE
翻译面板自动读取剪贴板文本

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1644]
**没有这个功能（改进）的时候，你遇到了什么问题？**
现在在自动化里只有选择翻译选项，剪贴板文本的内容才会被置入文本框，导致三个选项只有一个真正做了”读取“，实际的功能不符合选项的标题。

**你想要如何解决你的问题？**
增加“仅读取”选项，能自动读取剪贴板中的文本并置入文本框。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
调整“不翻译”选项的逻辑，这个选项我觉得应该要读取剪贴板并将文本置入文本框才对，而不是什么也不做。

**Comment by lmk123** [comment]
你是希望即使是选择“不翻译”的情况下，也将剪切板内的文本置入文本框，但不触发翻译吗？

但是这样做私似乎没什么必要，如果不希望翻译，那为什么要置入文本框？

**Comment by scruel** [comment]
不希望翻译就不会调出面板啊，置入后可以做二次编辑处理

**Comment by lmk123** [comment]
那我加个新选项吧，“不翻译但写入文本框”

**Comment by scruel** [comment]
> 那我加个新选项吧，“不翻译但写入文本框”

我觉得“不翻译”那个选项改成“不翻译但写入文本框”就行，因为毕竟这个功能叫做“自动读取剪切板里的文本”。
如果真的不需要读取剪贴板，关了这个功能就行了，这下面的三个选项问题不大，分别对应询问、读取并置入、读取并置入后翻译三个功能。

**Comment by lmk123** [comment]
“自动读取剪切板里的文本”这个功能就是通过”不翻译”这个选项来关闭的 :joy: 所以我才需要用一个新选项来承载你的需求

**Comment by scruel** [comment]
> “自动读取剪切板里的文本”这个功能就是通过”不翻译”这个选项来关闭的 😂 所以我才需要用一个新选项来承载你的需求

阿哲，那我觉得应该叫做“不读取”才好

**Comment by lmk123** [comment]
我把这个功能改个名字吧，把“自动读取剪切板”改为”自动翻译剪切板”，这样其实更准确一些

**Comment by scruel** [comment]
觉得可就可，无意见
