### ISSUE TITLE
可以兼容下DEEPL自建源吗

### ISSUE THREAD

**Issue by riverai** [hcfyapp/crx-selection-translate#1645]
这里说的自建源是说的deepl docker ,deepl X ,或者类似物他们提供的api。
具体可以看这个https://github.com/windingwind/zotero-pdf-translate/pull/342

我建立了之后试图使用会提示http错误，422，估计是划词翻译自定义源的格式和这个有区别：

里面还保留有信息，为了让你快速测试下。
我想既然能兼容官方的，那么兼容这种应该不会存在障碍吧。

以下是详细
POST http:// /translate HTTP/1.1
Host: 
Connection: keep-alive
Content-Length: 110
Accept: application/json, text/plain, */*
DNT: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50
Content-Type: application/json
Origin: chrome-extension://oikmahiipjniocckomdccmplodldodja
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6

{"text":"划词翻译自定义翻译源测试","destination":["中文(简体)","英语"],"name":"deepldocker"}

回复：
HTTP/1.1 422 Unprocessable Entity
content-type: application/json
server: Rocket
x-frame-options: SAMEORIGIN
permissions-policy: interest-cohort=()
x-content-type-options: nosniff
content-length: 178
date: Thu, 23 Feb 2023 04:58:11 GMT

{
  "error": {
    "code": 422,
    "reason": "Unprocessable Entity",
    "description": "The request was well-formed but was unable to be followed due to semantic errors."
  }
}

**Comment by lmk123** [comment]
技术上应该是能做到兼容的，但我觉得目前没有兼容的必要，因为划词翻译内置了 DeepL，本身就不需要依赖第三方软件来使用。

**Comment by riverai** [comment]
内置的也是逆向的win客户端里面的方法吗？主要是我问了下bob用这个方法的，他们反应响应速度很快。

**Comment by lmk123** [comment]
从我的使用体验来看，划词翻译内置的 DeepL 只在第一次会慢一点（大概 10 秒），之后每次大概 3 秒有结果，总的来说不算慢了。

如果以后划词翻译内置的 DeepL 彻底不能用了，我会考虑兼容第三方的 DeepL 源。

**Comment by lmk123** [comment]
你好 @riverai  ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
