### ISSUE TITLE
申请服务时，报国外手机号无效

### ISSUE THREAD

**Issue by binpeng77** [hcfyapp/crx-selection-translate#1646]
## 基本信息

划词翻译版本：9.4.0
浏览器版本：chrome 110.0.5481.105
操作系统：Windows 10 pro

## 重现问题的步骤

1.
2.
3.

### 补充信息

验证手机号时，接受国外手机号即可。

**Comment by lmk123** [comment]
你说的应该是指你去申请百度翻译 / 腾讯翻译的时候，它们平台提示无法使用国外手机号注册账号吧

这是它们平台的限制，我也没法解决 :joy:

**Comment by lmk123** [comment]
为了避免你没有弄明白，我再进一步解释一下 :joy:

划词翻译的开发者（也就是我）、划词翻译软件、第三方翻译平台（即百度翻译、腾讯翻译等）这三者之间的关系类似于 4s 店、汽车、加油站。

4s 店把汽车卖给了你，但你需要自己去加油，车才能跑，而加油站告诉你由于你手机号是国外的所以不让你加油，那么 4s 店也没办法 :joy:
