### ISSUE TITLE
让译文可编辑功能bug：在双语模式下编辑完译文之后，切换译文单独显示，所有的编辑都被撤销，恢复原样。

### ISSUE THREAD

**Issue by Langeeker** [hcfyapp/crx-selection-translate#1647]
划词翻译版本：v9.4.0 （以前的版本一样有这样的问题）

重现问题的步骤：
1. 开启划词翻译：打开**让译文可编辑**选项，打开一个英文网页，开启网页全文翻译。
2. 双语模式下，对照原文修改译文。
3. **切换译文模式下，通读译文，发现修改后的译文都被撤销，恢复原样。**

预期行为：既然有让译文可编辑功能，那么修改后的译文，至少在不刷新网页的情况下，切换译文单独显示的时候，应该保留已经做出的修改，否则，每次 **双语模式** 下对照原文修改译文后，一旦**切换单独显示译文**想通读译文，就会被完全撤销，很无语。**我理解如果刷新网页了，做出的修改会被撤销，因为会重新生成翻译，但是在不刷新只是切换显示方式的时候，希望能保留已经对译文做出的编辑，相当于对显示译文的部分不要只抓取原始译文，当前页面修改后的译文应该更优先被抓取展示，否则这个让译文可编辑的功能就非常鸡肋了。**

**Comment by lmk123** [comment]
很好的建议，我会尽快上线此功能

**Comment by lmk123** [comment]
很抱歉让你有了不好的体验，为此我已将此功能加急开发进了下个版本当中，预计在 3 月中旬发布。
