### ISSUE TITLE
PDF阅读器在单页打印时会多出一个空白页

### ISSUE THREAD

**Issue by wurenny** [hcfyapp/crx-selection-translate#1648]
## 环境
划词翻译版本：9.4.0
浏览器版本：chrome 110.0.5481.100
操作系统：linux mint 20.3

## 重现问题
1. 首先在划词翻译中设置，浏览器PDF使用划词翻译的阅读器打开
2. 打开在线PDF生成器：https://www.aconvert.com/cn/pdf/
3. 使用百度首页生成一个pdf
![image](https://user-images.githubusercontent.com/6622574/221140391-8db57f21-f5bd-4bb6-9709-70a0e3466873.png)
4. 点击输出文件，跳转到pdf阅读器标签页，按下ctrl + p打印快捷键
5. 显示打印2张纸，在预览中显示也是2张纸，第2页是完全空白的，但pdf文件实际只有一页
6. 点击打印，打印机真的会出2张纸，后面一页是空白的，什么都没有

## 预期行为
打印的页数与pdf实际页数一致

## 实际行为
单页pdf会多打印一张空白页

## 补充信息
1. 只有单页pdf有这个问题，如果pdf本身是大于1页的，目前测试没有这个问题
2. 最新升级chrome后才发现了这个问题，之前没有，之前的的chrome版本大22年3月的
3. 使用chrome内置pdf阅读器打印没这个问题

**Comment by lmk123** [comment]
感谢你的详细反馈，我已成功重现此问题。

由于内置 PDF 阅读器是一个独立的第三方软件，所以这个问题我没法解决，我能做的只有等它修复这个问题之后，将新版本更新进划词翻译当中。

另外，我发现一个可以绕过此问题的办法：在 Chrome 点击打印后，可以在弹出来的页面限制只打印第一页，如下图，希望这能帮到你。

<img width="1313" alt="aaa" src="https://user-images.githubusercontent.com/5035625/221155860-14779c33-437e-476a-ab71-ed240042a688.png">

**Comment by wurenny** [comment]
是的，可以自定义打印页面，当时我也是这么操作绕过的
