### ISSUE TITLE
全文翻译能不能添加"在当前标签页自动开启"功能

### ISSUE THREAD

**Issue by seafood2017** [hcfyapp/crx-selection-translate#1649]
浏览论坛时，点下一页，全文翻译就没了。如果想一直打开就必须打开“在当前窗口一直开启”功能。但是这样别的不想翻译的页面也会被翻译。

两个方案：
要么提供“当前标签页自动开启”功能
要么提供“全文翻译自动跳过中文”功能

望采纳，谢谢。

**Comment by lmk123** [comment]
好的，我会添加“当前标签页自动开启”的功能
