### ISSUE TITLE
请求增加按单词数判断是否使用某个引擎的功能

### ISSUE THREAD

**Issue by Giter-t** [hcfyapp/crx-selection-translate#1650]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，必应词典只能翻译一个单词，那么当我想翻译一个句子的时候就不想显示必应词典。同理，有道和必应词典对单词的翻译比较全面，那么我想翻译单词的时候只显示这两个引擎。

**补充信息**
可参考沙拉查词的此功能。

**Comment by lmk123** [comment]
此 issue 已合并至 #1693
