### ISSUE TITLE
建议网页全文翻译失败后增加重试按钮

### ISSUE THREAD

**Issue by Vixb1122** [hcfyapp/crx-selection-translate#1651]
**没有这个功能（改进）的时候，你遇到了什么问题？**
前面几个段落翻译成功，后面文本翻译失败，得要刷新网页整个网页重新翻译

**你想要如何解决你的问题？**
在翻译失败的查看解决方案后面，增加一个重试的按钮，点击之后重新翻译失败的段落。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
相信作者这么牛逼，肯定能实现。

**补充信息**
功能特别实用，如果可以在重试时选择其他翻译源就更好了

![image](https://user-images.githubusercontent.com/17810492/221352873-635e4b07-f3d3-487b-8342-9099b0e388f9.png)

**Comment by lmk123** [comment]
好的，我会添加此功能

**Comment by Vixb1122** [comment]
大佬，新版推送下edge商店呗

**Comment by Vixb1122** [comment]
@lmk123 重试功能有个BUG，如果是重试带有超链接的标题之类的，会跳转超链接，而不会重试。

**Comment by lmk123** [comment]
> 如果是重试带有超链接的标题之类的，会跳转超链接，而不会重试

跟 #1654 属于同一个问题

> 新版推送下edge商店呗

我早就推送了，但是 edge 审核太慢了，一直没过
