### ISSUE TITLE
把网页翻译直接放在右键的一级菜单中

### ISSUE THREAD

**Issue by PP-19** [hcfyapp/crx-selection-translate#1652]
网页翻译在右键的二级菜单里，不太方便

能不能提供一个选项，允许用户直接把网页翻译按钮放在右键的一级菜单中

**Comment by lmk123** [comment]
你可以在划词翻译设置 - 右键菜单里仅保留全文翻译这一个菜单，那么它就会直接在一级菜单里。

这是扩展程序本身的限制，只要右键菜单数量在2个及以上就会被放进二级菜单。
