### ISSUE TITLE
插件卸载重装后网页翻译剩余次数会被重置!

### ISSUE THREAD

**Issue by KairuiLiu** [hcfyapp/crx-selection-translate#1653]
## 基本信息

划词翻译版本：9.4.0
浏览器版本：版本 110.0.5481.177（正式版本） (arm64)
操作系统：Mac OS 13.1 (22C65)

## 重现问题的步骤

1. 待免费网页翻译次数用完, 移除插件, 重新安装插件, 免费使用次数会恢复为 3 次

### 预期行为

重装后, 用户使用数据被持久化

### 实际行为

失败

**Comment by lmk123** [comment]
确实会如此，但是我也没有办法，浏览器不允许扩展程序在卸载后还保留有数据 :joy:

**Comment by lmk123** [comment]
为了避免这个“漏洞”被更多人知道，所以我准备删除这个 issue 了。你应该可以在你的邮箱里收到我的回复 :joy:
