### ISSUE TITLE
GPT-3.5 API开放了，希望尽快加入接口！

### ISSUE THREAD

**Issue by leegx1998** [hcfyapp/crx-selection-translate#1655]
GPT-3.5 API开放了，希望尽快加入接口！

**Comment by lmk123** [comment]
正在考虑中 :joy:

重复 #1623

**Comment by lmk123** [comment]
v9.5.0 已接入 ChatGPT，目前已提交审核，等不及的话可以[下载离线安装包](https://hcfy.app/docs/install/#offline)体验。
