### ISSUE TITLE
请求加入 GPT3.5 翻译引擎

### ISSUE THREAD

**Issue by Equity0** [hcfyapp/crx-selection-translate#1656]
**没有这个功能（改进）的时候，你遇到了什么问题？**
翻译质量不佳

**你想要如何解决你的问题？**
让用户可以使用自己 openai api 进行划词翻译和全文翻译，或者直接收费

**Comment by lmk123** [comment]
正在考虑中 :joy:

重复 #1623

**Comment by lmk123** [comment]
v9.5.0 已接入 ChatGPT，目前已提交审核，等不及的话可以[下载离线安装包](https://hcfy.app/docs/install/#offline)体验。
