### ISSUE TITLE
请帮忙添加ChatGPT翻译

### ISSUE THREAD

**Issue by dsy86** [hcfyapp/crx-selection-translate#1657]
昨天ChatGPT发布了最新版语料模型API（gpt-3.5-turbo-0301），翻译速度大大提升，价格也有下降，急需将此功能添加进来。目前，也有其他翻译软件添加了ChatGPT，供参考：https://github.com/yetone/bob-plugin-openai-translator#readme

**Comment by lmk123** [comment]
v9.5.0 已接入 ChatGPT，目前已提交审核，等不及的话可以[下载离线安装包](https://hcfy.app/docs/install/#offline)体验。
