### ISSUE TITLE
我買了一年會員 我的信箱是a336441224@gmail.com

### ISSUE THREAD

**Issue by a3364412** [hcfyapp/crx-selection-translate#1658]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
我看了下 PayPal，有两笔 8.3 美元的收款，都是你付的吗？

另外，这两笔订单都显示的“冻结中”，没有真的进入我的账户，你是不是发起投诉了？

**Comment by lmk123** [comment]
交易号 00N68980S30711519 的订单已经退款给你了，另一个订单（交易号 0KW50355B5917882P）我已经对你的投诉提起了回复，你可以确认一下划词翻译的个人中心，现在你的会员到期时间应该已经是 2024 年了。

**Comment by a3364412** [comment]
你好 我有重複訂單 所以其中一個我自己按申請退款了


lmk123 ***@***.***> 於 2023年3月3日 週五 下午1:11寫道：

**Comment by a3364412** [comment]
現在怎麼好像兩筆訂單都退款了



斬幽 ***@***.***> 於 2023年3月3日 週五 下午2:39寫道：

**Comment by lmk123** [comment]
我这边主动给你的其中一个订单（交易号 00N68980S30711519）退款了，另一个订单 （交易号 0KW50355B5917882P）我这边看到的是你提交了投诉，然后 paypal 正在审核

**Comment by a3364412** [comment]
[image: image.png]
下面的訂單我昨天就自己按退款了 所以你是連上面的也一起給我退款了嗎?


lmk123 ***@***.***> 於 2023年3月3日 週五 下午2:43寫道：

**Comment by lmk123** [comment]
我在 GitHub 里看不到你发的图片 :joy: 要不我们用邮箱沟通吧，你发邮件到 support@hcfy.app
