### ISSUE TITLE
希望支持自定义DeepL接口

### ISSUE THREAD

**Issue by github-h** [hcfyapp/crx-selection-translate#1659]
现在有很多现成的deepl的项目可以自己搭建，通过白嫖的API接口可以实现翻译

希望能添加一个自定义的DeepL接口

通过填写自己的API URL实现翻译功能

**Comment by lmk123** [comment]
划词翻译本身就支持 DeepL，且不需要第三方软件，所以我个人认为再加上自定义 URL 的 DeepL 接口似乎有点多余

**Comment by github-h** [comment]
> 划词翻译本身就支持 DeepL，且不需要第三方软件，所以我个人认为再加上自定义 URL 的 DeepL 接口似乎有点多余

但是DeepL的接口注册起来不是比较困难么，毕竟需要美区信用卡

而且不是会出现免费试用出现时效的情况

自己搭建的API接口 可靠性会高一些吧？

**Comment by lmk123** [comment]
> 自己搭建的API接口 可靠性会高一些吧？

只要不是 DeepL API 接口，都有随时失效的可能。

划词翻译的 DeepL 免费试用虽然出现过突然失效的情况，但 2022 全年也只出现了 3 次，这个稳定性很高了

**Comment by github-h** [comment]
> > 自己搭建的API接口 可靠性会高一些吧？
> 
> 只要不是 DeepL API 接口，都有随时失效的可能。
> 
> 划词翻译的 DeepL 免费试用虽然出现过突然失效的情况，但 2022 全年也只出现了 3 次，这个稳定性很高了

也是也是 那就再看看吧
