### ISSUE TITLE
希望可以自定义ChatGPT的prompt格式

### ISSUE THREAD

**Issue by cesaryuan** [hcfyapp/crx-selection-translate#1660]
**没有这个功能（改进）的时候，你遇到了什么问题？**
现在的Prompt格式是`将下面的文本翻译为中文(简体)：{{text}}`，不够灵活

**你想要如何解决你的问题？**
支持自定义prompt的格式

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
无

**补充信息**
有以下几个优点：
1. 可以允许用户自定义翻译风格；比如，我可以在prompt里面加上`请以较为*专业的语气*将下面的文本翻译为中文(简体)：{{text}}`
2. 可以实现选中一个词返回对该词的更为详细的释义（替代必应词典）：比如`将下面的文本翻译为中文，如果只有一个词，请给出该词的详细意思：{{text}}`
3. 可以突破翻译这个场景，实现一些更好玩的东西，比如我这样写prompt：`请总结这段话的意思：{{text}}`

**Comment by lmk123** [comment]
我考虑过这样的场景，但是太过于自定义的话会超出“翻译服务”的范畴。目前我只想让 ChatGPT 成为一个纯粹的翻译服务。

我可能会提供一些预定义的 prompt，比如你提供的“专业语气”或”词典”，但是跟翻译无关的话我大概不会加进去，比如“总结意思”

**Comment by cesaryuan** [comment]
谢谢大佬的回复！

> 但是太过于自定义的话会超出“翻译服务”的范畴

可不可能放在**高级设置**里面，放在普通用户难以接触到的地方

**Comment by lmk123** [comment]
倒不是要不要让普通用户接触到的问题，而是把 ChatGPT 自定义加进划词翻译里的话违背了“单一功能原则”，毕竟大部分用户都是冲着翻译来的。

不过我其实很想专门为 ChatGPT 做一个扩展程序，就是没想好要做成什么样子的 :joy:

**Comment by Editst** [comment]
或许可以参考一下这个基于Bob的插件 [OpenAI Translator Bob Plugin](https://github.com/yetone/bob-plugin-openai-translator)

**Comment by cesaryuan** [comment]
> 而是把 ChatGPT 自定义加进划词翻译里的话违背了“单一功能原则”，毕竟大部分用户都是冲着翻译来的

嗯呢，我想自定义prompt也是想更好的多样化翻译，毕竟仅仅预设几个prompt可能不能覆盖一些边缘的场景（比如各种专业领域的文献翻译可以有不同的prompt），哈哈哈

**Comment by lmk123** [comment]
我准备在下个版本中加入一个自定义 ChatGPT promopt 的选项，可以把默认的 `将下面的文本翻译为中文(简体)：{{text}}` 改成别的

**Comment by lmk123** [comment]
我想给这个选项加一个限制，即必须存在且以 `{{text}}` 结尾，例如 `请总结这段话的意思：{{text}}` 是可以的，但是 `{{text}}没在结尾` 就是不行的。

**Comment by cesaryuan** [comment]
> 我想给这个选项加一个限制，即必须存在且以 `{{text}}` 结尾，例如 `请总结这段话的意思：{{text}}` 是可以的，但是 `{{text}}没在结尾` 就是不行的。

嗯呢，感觉可以，或者这样：Please translate the following text from {{sourceLang}} to {{toLang}}：\`\`\`{{text}}\`\`\`
PS：用英文是因为ChatGPT对英文反应更快；三个反引号可以更好的区分边界

**Comment by lmk123** [comment]
sourceLang 我没加进去，因为大部分情况下 sourceLang 都是自动判断
