### ISSUE TITLE
Deepl 翻译框偶尔给出重复的结果

### ISSUE THREAD

**Issue by shangdev** [hcfyapp/crx-selection-translate#1662]
## 基本信息

划词翻译版本：v9.5.0
浏览器版本：Chrome 版本 110.0.5481.178（正式版本） （64 位）
操作系统：windows10

![image](https://user-images.githubusercontent.com/15621520/222997897-25dbdadb-308e-4104-a68b-7b63f5332585.png)

**Comment by lmk123** [comment]
因为 DeepL 确实给出了重复的结果

<img width="639" alt="image" src="https://user-images.githubusercontent.com/5035625/222998106-2b60ca2e-0ae9-4a2a-9a6f-4953f105a2b4.png">
