### ISSUE TITLE
chargpt出现429错误

### ISSUE THREAD

**Issue by elongwz** [hcfyapp/crx-selection-translate#1663]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.多次使用chatgpt进行网页划词翻译
2.翻译结果显示429错误
3.等待一会在翻译,没事了

### 预期行为
一直可以翻译
### 实际行为
翻译次数过多会出现429错误

**Comment by lmk123** [comment]
429 错误是 ChatGPT 那边的限制，见它们的文档：https://platform.openai.com/docs/guides/rate-limits/overview
