### ISSUE TITLE
点了“窗口常驻/总在最前”后，无论划什么都自动翻译，还自动翻译剪贴板内容。设置里面设置显示按钮才翻译，不翻译剪贴板，但是根本没有用

### ISSUE THREAD

**Issue by mrcat211** [hcfyapp/crx-selection-translate#1664]
## 基本信息

划词翻译版本：v9.5
浏览器版本：edge
操作系统：windows10

## 重现问题的步骤

1.正常翻译
[2.点击了]总在最前按钮后，开始划词自动翻译，无视设置的按钮翻译，不自动翻译剪切板。

3.由于我需要对文本进行编辑，会经常选择词汇，空格，标点，在这种情况下，它全都会自动翻译，非常不方便。

**Comment by lmk123** [comment]
当你点击了左上角的“图钉”图标后，窗口就会处于固定模式，也就是除非明确点击关闭按钮，否则不会消失。

目前，在固定模式下会无视其它设置，只要划词了就会触发翻译。

我在下个版本加个选项吧，可以关闭此行为

**Comment by lmk123** [comment]
但是，固定模式并不会自动翻译剪切板，你可以去设置页确认一下是不是把辅助键设为了 `Ctrl`，导致按下 `Ctrl + C` 的时候触发了翻译

**Comment by lmk123** [comment]
v10.3.0 在【划词翻译设置】-【网页划词翻译】-【网页划词面板】里加了一个选项“为固定模式添加默认行为”，取消勾选后就不会出现一划词就立刻翻译的情况了。
