### ISSUE TITLE
增加网页黑名单 不翻译

### ISSUE THREAD

**Issue by ecjtu-liubin** [hcfyapp/crx-selection-translate#1665]
我平常使用时都是选择划词后直接弹出翻译结果，效果很好。
但是也有一些地方会稍微有点影响，因为并不是所有网站我都需要这个翻译功能，但是目前是不论在哪个网站，双击复制时都会弹出翻译框，在日常使用的很多网站中，都是没有必要的。
所以希望能不能有一个功能，增加一处设置，用于屏蔽某些域名下的翻译功能，或者是指定某些网站下不出现翻译弹窗
感谢

**Comment by lmk123** [comment]
已有此功能，见划词翻译设置 - 网页划词翻译 - 网址筛选

复制时弹出翻译框可能是因为你将 Ctrl 设置为了辅助键。
