### ISSUE TITLE
deepl不能翻译成中文

### ISSUE THREAD

**Issue by 1074305015** [hcfyapp/crx-selection-translate#1668]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.将英语原文进行翻译
2.deepl 显示   在target语种选择下拉框中找不到语种zh-ZH的选项。[查看解决方案](https://hcfy.app/docs/faq/#deepl-only)
3.

**Comment by lmk123** [comment]
我试了一下，是正常的。我猜测是因为你没有把划词翻译升级到最新版本，如果你升级到最新版本了仍然有这问题，麻烦按照格式提供浏览器版本、操作系统等信息，我会用你的浏览器和操作系统再试试

<img width="264" alt="image" src="https://user-images.githubusercontent.com/5035625/224526446-204ed142-fb2a-43c3-a05c-bc1b0d0d56ff.png">

**Comment by 1074305015** [comment]
谢谢，我升级到最新版，已解决问题。




GCT
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hcfyapp/crx-selection-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 中午1:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hcfyapp/crx-selection-translate] deepl不能翻译成中文 (Issue #1668)





 
我试了一下，是正常的。我猜测是因为你没有把划词翻译升级到最新版本，如果你升级到最新版本了仍然有这问题，麻烦按照格式提供浏览器版本、操作系统等信息，我会用你的浏览器和操作系统再试试
