### ISSUE TITLE
請開通會員

### ISSUE THREAD

**Issue by M77cc** [hcfyapp/crx-selection-translate#1670]
請開通會員, 已繳費

交易ID：11M68716JN639922D
交易日期：2023/03/13 09:38:13

**Comment by lmk123** [comment]
你好，已将你的划词翻译账号 bu******25@gmail.com 设为了永久会员，麻烦在划词翻译的设置 - 个人中心确认一下会员到期时间。

如有任何疑问，欢迎继续留言。
