### ISSUE TITLE
使用chatGPT翻译的web排版问题

### ISSUE THREAD

**Issue by JingchengLi** [hcfyapp/crx-selection-translate#1671]
## 基本信息

划词翻译版本：v9.6.0
浏览器版本：chrome版本 110.0.5481.177（正式版本） (arm64)
操作系统：MacOS Monterey 12.3

## 重现问题的步骤
![image](https://user-images.githubusercontent.com/5918144/224710577-dd15cd98-e776-4051-9c82-c5f71003543f.png)
访问 https://www.learncpp.com/cpp-tutorial/circular-dependency-issues-with-stdshared_ptr-and-stdweak_ptr/  这个链接出现web排版问题，在其他网站上同样有类似问题。

**Comment by lmk123** [comment]
感谢反馈，已重现此问题。

备注：有且仅有 ChatGPT 有这个问题，其它翻译服务是正常的。

**Comment by lmk123** [comment]
问题的原因找到了。

ChatGPT 本质上不是一个翻译服务而是对话系统，所以有些文本它没有严格按照原文的换行符来返回翻译结果，比如下面这段话：

```
Hello, how are you?
I'm fine.
```

其它翻译服务都会严格按照原文的换行符来返回结果：

```
你好，最近怎么样？
我很好。
```

但 ChatGPT 的翻译结果可能不会有换行符：

```
你好，最近怎么样？我很好。
```

这就导致原文跟译文对不上了。

要解决这个问题，就需要确保全文翻译的时候进行逐句翻译，详细解释可以看 #1712。

后续进展也会更新到 #1712，所以这个我就先关闭了。

**Comment by JingchengLi** [comment]
> 

不好意思，前面的版本信息没有更新，这个是最新的v9.8上遇到的问题。 @lmk123
