### ISSUE TITLE
支持网页版的 ChatGPT

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1672]
以下内容来自 https://github.com/hcfyapp/crx-selection-translate/issues/1623#issuecomment-1466093415

> 请问可否支持chatGPT网页版的登陆，然后使用chatGPT网页版本进行翻译 1.浏览器插件的一大优势就是网页登陆方便 2.考虑到很多plus用户更希望使用网页版chatGPT 3. 等到chatGPT api免费额度清零时间一到，很多用户还是希望使用免费的chatGPT，利于插件长远发展

**Comment by ghost** [comment]
对的，这个插件就可以不用API进行调用，免费额度有限，用完了就完了。大家根本没法充值也不会那么贵就为了翻译充值。
https://chatgpt4google.com/

**Comment by lmk123** [comment]
@spphinslove 我看了一下这个插件的评论区，发现从扩展程序里调用 ChatGPT 网页接口会导致用户的账号被封啊，而且不止一两个人这么反馈

https://chrome.google.com/webstore/detail/chatgpt-for-google/jgjaeacdkonaoafenlfkkkmbaopkbilf

**Comment by ghost** [comment]
> @spphinslove 我看了一下这个插件的评论区，发现从扩展程序里调用 ChatGPT 网页接口会导致用户的账号被封啊，而且不止一两个人这么反馈
> 
> https://chrome.google.com/webstore/detail/chatgpt-for-google/jgjaeacdkonaoafenlfkkkmbaopkbilf

我火狐浏览器目前没事，API和网页调用我都用了。
https://github.com/wong2/chatgpt-google-extension/issues 
这里没看到有人反馈被封号

**Comment by lmk123** [comment]
我还是决定加进来，不过会提示用户有被封号的可能性
