### ISSUE TITLE
关闭 "读取和修改您复制和粘贴的数据" 的权限的选项

### ISSUE THREAD

**Issue by phantomk** [hcfyapp/crx-selection-translate#1673]
**没有这个功能（改进）的时候，你遇到了什么问题？**
不想要给 "读取和修改您复制和粘贴的数据" 的权限

**你想要如何解决你的问题？**
可以给个选择关闭这个权限吗

**Comment by lmk123** [comment]
如果你是不希望独立翻译窗口在打开时自动粘贴剪切板的文本并翻译，你可以在设置中将“自动翻译剪切板内的文本”功能设为“不翻译”。

如果你确实是希望划词翻译不要有这个权限——Chrome 插件安装时提示的权限（即“永久权限”）无法在安装之后临时关闭，Chrome 插件没有提供将永久权限在安装后去掉的能力。

不过，我确实可以在之后的版本中将这个权限改为“可选权限”，即类似于划词翻译的通知权限，需要用户在设置页手动授权之后才能用，但这就意味着那些使用了“自动翻译剪切板内的文本”功能的用户会突然发现他们的独立窗口不会自动粘贴并翻译剪切板了，复制翻译结果到剪切板的按钮也会不能用。考虑到划词翻译的用户基数，这个改动造成的影响是比较大的，我都可以想象会有很多不知道发生了什么事情的用户去给划词翻译刷差评的情景了 :joy:

我暂时可能不会对这个权限做改动。划词翻译尊重用户的隐私，见[划词翻译会侵犯我的隐私吗？
](https://hcfy.app/docs/faqs/safe)
