### ISSUE TITLE
可以音视频翻译支持115网盘页面吗？

### ISSUE THREAD

**Issue by menheng** [hcfyapp/crx-selection-translate#1678]
我能识别出来原句但是不能实时翻译，它说识别不到一个完整的句子。

可以增加这个小小的网页支持吗？

**Comment by menheng** [comment]
![E@CC4(8F2 LLC7PYJC %R E](https://user-images.githubusercontent.com/109516293/226170177-ae09270d-101c-4fce-bdbe-1d1905b16474.png)

**Comment by lmk123** [comment]
这其实不是 115 网盘页面的问题，而是腾讯云语音识别断句的问题，这一点在文档里有说明，见 https://hcfy.app/docs/guides/video 里的【实时翻译】里的红色说明。

如说明里所说，未来会通过添加别的实时语音识别服务来改善这个问题。
