### ISSUE TITLE
Edge dev版本pdf选中无颜色

### ISSUE THREAD

**Issue by lf624** [hcfyapp/crx-selection-translate#1679]
## 基本信息

划词翻译版本：9.4.0
浏览器版本：112.0.1722.11 (正式版本) dev (64 位)
操作系统：win10

## 重现问题的步骤

1.打开划词翻译的pdf-viewer
2.把pdf文件拖到里面打开
3.鼠标选中文本，无颜色

### 预期行为
我在edge浏览器中使用时鼠标选中应该是紫色的
### 实际行为
在edge dev中鼠标选中无色

**Comment by lmk123** [comment]
dev 版本的浏览器不在划词翻译的支持范围以内，因为之前发生过几次在 dev 里有问题但到了正式版本又没有问题了的情况，这种情况下，无法区分是浏览器本身有问题还是划词翻译的问题。如果更新到了正式版仍然有这个问题，欢迎反馈。
