### ISSUE TITLE
在“文本筛选”中选择“忽略中文”时不忽略日文

### ISSUE THREAD

**Issue by wjz2001** [hcfyapp/crx-selection-translate#1682]
**没有这个功能（改进）的时候，你遇到了什么问题？**
当选中日文内容时无法弹出翻译按钮。

**你想要如何解决你的问题？**
当选中的内容包含日本汉字或者假名时不忽略。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
没有。

**Comment by lmk123** [comment]
这个问题其实很早就有人提了 :joy: 见 #868

我提高一下优先级
