### ISSUE TITLE
ChatGPT 的服务密钥没有导出

### ISSUE THREAD

**Issue by seafood2017** [hcfyapp/crx-selection-translate#1683]
如题, edge同步到chrome时, 发现服务密钥并未同步. 手工导出导入也不行(有bug?). 

能否直接同步服务密钥到服务器端.

**Comment by lmk123** [comment]
密钥是不会同步到划词翻译服务器的，这一点在官网有过解释：https://hcfy.app/docs/faqs/safe#safe-key

手工导入导出我试一下看看是不是正常的，稍后回复

**Comment by lmk123** [comment]
我试了一下，ChatGPT 的密钥确实没有导出，这是个 bug，会在下个版本修复。

其它服务的导出是正常的。
