### ISSUE TITLE
PDF翻译选择词句后不标识所选内容，无翻译标记

### ISSUE THREAD

**Issue by BFF-LEI-Lei** [hcfyapp/crx-selection-translate#1684]
## 基本信息

划词翻译版本：v9.6.0
浏览器版本：Microsoft Edge
版本 112.0.1722.11 (正式版本) dev (64 位)
操作系统：win10

## 重现问题的步骤

1.打开PDF翻译测试链接：测试链接：https://arxiv.org/pdf/2104.13030.pdf
2.划选想要翻译的字段——所选内容无法标识，无翻译按键浮现，可通过快捷键翻译
3.

**Comment by lmk123** [comment]
你是不是没有在划词翻译的内置 PDF 阅读器里打开？

dev 版本不在兼容范围内，所以我使用 Edge 版本 111.0.1661.51 (正式版本) (arm64) 试了一下，是正常的，如下图

<img width="553" alt="截屏2023-03-22 11 42 07" src="https://user-images.githubusercontent.com/5035625/226796554-093e084d-5d3e-4a30-9ff5-3f51912f8dc1.png">

**Comment by LovesAsuna** [comment]
什么时候考虑兼容dev版本？实测这个问题确实是正式版没问题，但是在dev版本出现划词没高亮

**Comment by lmk123** [comment]
如果是只在 dev 里有问题，那我就不解决了。

> 什么时候考虑兼容dev版本？

我从未打算兼容 dev 版本，以后估计也是。

dev 版本的很多问题我更倾向于是浏览器自己的问题，花额外的时间去兼容浏览器的问题是很吃力不讨好的事情。
