### ISSUE TITLE
全文翻译增加一个 提醒效果，正在翻译中

### ISSUE THREAD

**Issue by woxiqingxian** [hcfyapp/crx-selection-translate#1685]
**没有这个功能（改进）的时候，你遇到了什么问题？**
用 deepl 和 chatgpt 全文翻译的时候，因为翻译接口很慢，所以在页面上显示也比较慢，但是有些时候，我都不知道到底是翻译慢还是我根本就没有点全文翻译按钮，还是说全文翻译出现故障。

**你想要如何解决你的问题？**
在点击全文翻译后，可以有个 loading 的提醒，提醒当前用户，正在翻译中。如果有显示翻译时间和进度，那就更棒了。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
无

**补充信息**
无

**Comment by lmk123** [comment]
实际上我曾经加过，但后来又取消掉了 :joy:

这是因为大部分翻译服务速度很快，这就会导致“正在翻译……”的提示会频繁的出现 / 消失，我感觉体验不太好。当然，对于 DeepL 和 ChatGPT 来说，这个提示倒确实有用。

我想想要怎么改进一下吧
