### ISSUE TITLE
把translate.googleapis.com加到V2RayN的PAC代理里面并不管用

### ISSUE THREAD

**Issue by Eacls** [hcfyapp/crx-selection-translate#1687]
## 基本信息

把translate.googleapis.com加到V2RayN的PAC代理里面并不管用，没有设置过镜像地址，是V2RayN的问题还是我个人操作问题呢？

划词翻译版本：最新
浏览器版本：edge最新
操作系统：Windows11

**Comment by lmk123** [comment]
我没用过 V2RayN，所以我不太清楚，但我这边使用梯子是能正常使用谷歌翻译的。
