### ISSUE TITLE
重设密码无效

### ISSUE THREAD

**Issue by duanfuxiang0** [hcfyapp/crx-selection-translate#1688]
## 基本信息
换了电脑无法登录账号，修改密码，已经试了多次也无效
划词翻译版本：v9.6.0
浏览器版本：Edge 
操作系统：windows10

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
目前为止，反馈说登陆提示“密码错误”且修改密码时提示”邮箱不存在的”全都是因为记错了账号，最常见的情况是注册账号的那个邮箱 A 被设置了邮件转发，转发到了另一个邮箱 B，所以真实的划词翻译账号其实是邮箱 A 而你以为是邮箱 B。

你可以找一下你注册账号时收到的验证码的邮件，看看到底是发给哪个邮箱的。如果还是不行，你可以在公众号提供给我你购买划词翻译会员的支付记录截图，我可以在后台帮你找到你的账号。
