### ISSUE TITLE
“翻译这段文本”功能无法使用

### ISSUE THREAD

**Issue by zhilulingguan** [hcfyapp/crx-selection-translate#1690]
## 基本信息

划词翻译版本：V9.7.1
浏览器版本：Google Chrome 111.0.5563.147
操作系统：win 10 专业版

## 重现问题的步骤
前提：以下测试都在梯子 全局模式下进行
1. 在网页中选择相应的词汇，点击划词翻译
2.在划词翻译的结果中显示"速度慢、准确率高的谷歌翻译暂时不可用，请在设置中切换为“速度快、准确率低”。"
3.切换到“速度快，准确率低”模式
4.提示远程服务器无响应
5.在“速度慢，准确率高”的状态下，当翻译不出结果时点击“查看详细信息”，可以链接到谷歌翻译，并输出结果

### 补充信息

1.网页全文翻译功能正常

**Comment by lmk123** [comment]
我也是用的梯子，而我的谷歌翻译是能正常使用的：

<img width="287" alt="image" src="https://user-images.githubusercontent.com/5035625/228820795-7daf11f7-65c5-4f06-a78e-430caa94df9e.png">

我猜测有以下几种可能：

- 你之前填写过谷歌翻译的镜像地址，没有删掉
- 你之前配置过 hosts，没有删掉配置

如果不是以上两种情况，那么估计还是你的梯子配置的不对，因为梯子是一定能恢复谷歌翻译的。有种可能是你用的是浏览器扩展形式的全局模式，而划词翻译发起的请求可能没有被你的梯子代理到。

**Comment by zhilulingguan** [comment]
您好，我重新安装了划词翻译后在全局模式下可以使用。现在我查看了我的PAC配置文件，“||googleapis.com”已经被添加，，但是在PAC模式下是不能用划词翻译的，并且在点击测试谷歌翻译是否正常的连接(https://translate.googleapis.com/translate_a/element.js)时，返回了类似于网页源代码的内容。
例如：
“// go/mss-setup#7-load-the-js-or-css-from-your-initial-page
    if(!window['_DumpException']) {
      const _DumpException = window['_DumpException'] || function(e) {
        throw e;
      };
      window['_DumpException'] = _DumpException;
    }
  "use strict";this.default_tr=this.default_tr||{};(function(_){var window=this;
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
/*

 SPDX-License-Identifier: Apache-2.0”
请问这可能是什么原因造成的。期待您的回复。 
            谢谢！！

**Comment by lmk123** [comment]
你好，每个梯子的配置 / 使用方式都不同，而我用的梯子跟你用的不一样（我的梯子无需任何配置就已经自动代理了谷歌翻译），所以我也不知道你的问题该如何解决，抱歉。
