### ISSUE TITLE
chatgpt增加仅汉译英功能

### ISSUE THREAD

**Issue by biaji443** [hcfyapp/crx-selection-translate#1691]
chatgpt api费用不低，英译汉没必要调用chatgpt，但汉译英需要，所以我建议给chatgpt增加仅汉译英的选项。

**Comment by lmk123** [comment]
这或许可以做成一个通用设置，即根据一些条件判断要启用哪些翻译服务，比如翻译单词的时候只启用必应词典、翻译为英语的时候才启用 ChatGPT 等

**Comment by lmk123** [comment]
此 issue 已合并至 #1693
