### ISSUE TITLE
无法修改密码

### ISSUE THREAD

**Issue by lthon-tse** [hcfyapp/crx-selection-translate#1695]
## 基本信息

划词翻译版本：9.7.1
浏览器版本：Chrome Version 111.0.5563.146 (Official Build) (64-bit)
操作系统：archlinux

## 重现问题的步骤

1.https://hcfy.app/forget.html
2.重设密码
3.

### 预期行为
修改成功

### 实际行为
弹窗 I'm a teapot

### 补充信息

#1155

**Comment by lmk123** [comment]
我试了一下，是正常的。之前有用户反馈，如果安装了 AdGuard 之类的软件就会导致注册不成功，你看看你是不是也安装了类似的软件，如果有的话，把它们关掉后再试试

**Comment by lthon-tse** [comment]
感谢回复，我换没装任何东西的火狐浏览器修改成功了。
