### ISSUE TITLE
划词翻译按钮被其它插件的按钮遮住了

### ISSUE THREAD

**Issue by islercn** [hcfyapp/crx-selection-translate#1697]
## 基本信息

划词翻译版本：9.7.1
浏览器版本：Chome 111.0.5563.112
操作系统：Win 10

## 重现问题的步骤

1. 同时安装本插件和[openai-translator](https://github.com/yetone/openai-translator)
2. 在网页上滑动选择文字后松开鼠标

### 预期行为
同时弹出两个插件的图标
### 实际行为
只弹出openai-translator的图标，本插件图标没出现

**Comment by lmk123** [comment]
确实如此，划词翻译的按钮被它的按钮遮住了。我看看要怎么解决。

在解决之前，你可以在划词翻译设置中调整一下按钮的位置。

**Comment by lmk123** [comment]
尝试解决了一下，发现这个问题无法从根本上避免。显示按钮的插件都会将层级设为最高，所以要么是我挡住它，要么是它挡住我。

唯一解决方案目前只能是在划词翻译设置里调整按钮的位置，避免遮挡的情况出现
