### ISSUE TITLE
【v9.7.2 已修复此问题】DeepL 找不到[dl-test="translator-source-input"]

### ISSUE THREAD

**Issue by xanadus0** [hcfyapp/crx-selection-translate#1698]
# 已发布离线安装包 v9.7.2 修复此问题，见 https://hcfy.app/blog/2023/04/04/deepl

以下是原文

-------------

## 基本信息

划词翻译版本：9.7.1
浏览器版本：Firefox 111.0.1
操作系统：Windows 10

## 重现问题的步骤

划词翻译DeepL
![图片](https://user-images.githubusercontent.com/35560692/229669686-00c409d4-2aae-4245-bec9-b3944ea5795d.png)

### 补充信息

DeepL改用d-textarea标签，属性名改为data-testid
![图片](https://user-images.githubusercontent.com/35560692/229670041-2a36517a-1bbb-4048-a05f-dc3a6db6d88c.png)

**Comment by lmk123** [comment]
正在修复中，修复完成后将立刻发布一个新版本

**Comment by lmk123** [comment]
正在发布新版本

**Comment by lmk123** [comment]
已发布离线安装包 v9.7.2 修复此问题，见 https://hcfy.app/blog/2023/04/04/deepl
