### ISSUE TITLE
DeepL翻译失效, 显示: 找不到[dl-test="translator-source-input"]

### ISSUE THREAD

**Issue by dujinpeng0249** [hcfyapp/crx-selection-translate#1699]
## 基本信息

划词翻译版本：9.7.1
浏览器版本：Edge 111.0.1661.62
操作系统：win11 22H2 22621.1413

## 重现问题的步骤

1. 随便找一段英文
2. 选中, 然后点击翻译图标
3. DeepL翻译失效, 显示: 找不到[dl-test="translator-source-input"]

### 预期行为
出现对应的中文翻译
### 实际行为
DeepL翻译失效, 显示: 找不到[dl-test="translator-source-input"]
### 补充信息
关闭代理没用, 没有修改权限
在deepl官方网页可以完成翻译

**Comment by lmk123** [comment]
感谢反馈，后续进展将更新至 #1698
