### ISSUE TITLE
添加proxy设置

### ISSUE THREAD

**Issue by f4tb3e** [hcfyapp/crx-selection-translate#1700]
我不喜欢开启全局的代理，一般是把每一个要用代理的东西设置好，这样比较有条理。
希望增加一个代理设置，可以直接设置插件走的代理，甚至是单独设置某个翻译服务的代理。

**Comment by lmk123** [comment]
扩展程序不像桌面端应用程序，它是没有单独设置代理服务器的能力的 :joy:
