### ISSUE TITLE
添加密钥窗口优化

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1701]
**没有这个功能（改进）的时候，你遇到了什么问题？**
没啥大问题，纯属功能改进建议

**你想要如何解决你的问题？**
增加密钥重复判断（提示），密钥添加页面添加滚动条

简单点么就：
```javascript
height: 500px;
overflow-y: scroll;
```

**Comment by lmk123** [comment]
可

> 密钥添加页面添加滚动条

好奇你这是添加了多少个密钥到了要加滚动条的程度 :joy:

**Comment by scruel** [comment]
时不时就加一个加两个（
