### ISSUE TITLE
全文翻译对每一个译文元素增加右键菜单

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1704]
**没有这个功能（改进）的时候，你遇到了什么问题？**
译文只能统一更改翻译引擎，而无法单独调整某一块的翻译引擎。

**你想要如何解决你的问题？**
如题，同时还可以考虑在菜单中提供一些额外的选项。

**Comment by lmk123** [comment]
这么做似乎没有必要。如果想要对比，那么你只需要划选一下原文就可以了

**Comment by lmk123** [comment]
由于 issue 长期不活跃，所以我暂时关闭了。如果你有更多想法（比如想要在译文右键菜单添加的一些具体的选项）可以继续留言，我会 reopen 并继续跟进
