### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by Genihoust** [hcfyapp/crx-selection-translate#1706]
## 基本信息

划词翻译版本：v9.7.1
浏览器版本：chrome 111.0.5563.148
操作系统：Windows 11  22H2

## 重现问题的步骤

1.右键
2.网页全文翻译
3.提示  找不到[dl-test="translator-source-input"]

### 预期行为
全文翻译

### 实际行为
提示  找不到[dl-test="translator-source-input"]

**Comment by lmk123** [comment]
此问题已经修复了，升级到 v9.7.2 即可，见 https://hcfy.app/blog/2023/04/04/deepl
