### ISSUE TITLE
ChatGPT支持stream（打字机模式）

### ISSUE THREAD

**Issue by cesaryuan** [hcfyapp/crx-selection-translate#1707]
**没有这个功能（改进）的时候，你遇到了什么问题？**
ChatGPT响应较慢，要等很久从能看到翻译结果

**你想要如何解决你的问题？**
支持stream模式，这样的话ChatGPT的翻译速度和我们的阅读速度正好一致，完美解决了问题

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
无

**补充信息**
有一个扩展叫做chatGPTbox实现了这个功能，下面是录屏

https://user-images.githubusercontent.com/35998162/230565630-c29adb22-87a9-4f62-83d6-dce2b70340ae.mp4

**Comment by lmk123** [comment]
已加入开发计划，后续进展可以关注 #1674
