### ISSUE TITLE
在Linux中使用eSpeak作为系统语音

### ISSUE THREAD

**Issue by FortiterInRe** [hcfyapp/crx-selection-translate#1709]
**在Linux系统下无系统语音**

**可否使用eSpeak作为系统语音?**

**或将其整合入该项目**

_eSpeak项目:https://github.com/espeak-ng/espeak-ng_

**Comment by lmk123** [comment]
看了一下这个项目，划词翻译应该没法用 :joy:

划词翻译是一个浏览器扩展程序，没有能力调用这种原生应用。除非它支持 HTTP 接口啥的，但翻了一遍文档，应该是不支持。
