### ISSUE TITLE
记录 chatgpt conversation id

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1710]
**没有这个功能（改进）的时候，你遇到了什么问题？**
每次翻译都会创建新的会话，造成列表里很乱。

**你想要如何解决你的问题？**
记录并自动选择指定的 conversation id，支持配置的话更好。

**Comment by lmk123** [comment]
下个版本对 ChatGPT 进行了优化，将只会产生一次会话

**Comment by scruel** [comment]
@lmk123
是不是有bug，首次会这样：
![img](https://user-images.githubusercontent.com/16933298/231161050-6e67e08d-8a52-47ed-b852-8671b1383d7b.png)

**Comment by lmk123** [comment]
确实算是 bug，但这已经是我能做到的最好的效果了 :joy:

**Comment by scruel** [comment]
> 确实算是 bug，但这已经是我能做到的最好的效果了 :joy:

Ok，问题不大
