### ISSUE TITLE
语音朗读：始终使用系统语音 对DeepL 翻译不起作用

### ISSUE THREAD

**Issue by Langeeker** [hcfyapp/crx-selection-translate#1711]
在划词选项界面，已经选择了始终使用系统语音朗读，但对 DeepL 不起作用，仍然使用的是 DeepL 网页版的朗读声音（针对翻译后的文字），非常机械的TTS声音，很难听。谷歌翻译使用正常，DeepL 出现 bug，配置不奏效。

划词翻译版本：v9.7.2
浏览器版本：chrome

## 重现问题的步骤

1. 选定一段文字，使用划词翻译
2. 在 DeepL 对话框内，使用朗读。
3. 出现了机械的TTS声音，经验证与DeeL官网页面翻译框下的朗读声音一致。

**Comment by lmk123** [comment]
我确认了一遍我的代码，无论是否选择“始终使用系统语音”，DeepL 一直都是使用系统语音来朗读的。也许跟 DeepL 官网的朗读声音一致是个巧合？你可以试试在划词翻译系统语音里切换一个语音看看声音有没有变化

**Comment by Langeeker** [comment]
> 我确认了一遍我的代码，无论是否选择“始终使用系统语音”，DeepL 一直都是使用系统语音来朗读的。也许跟 DeepL 官网的朗读声音一致是个巧合？你可以试试在划词翻译系统语音里切换一个语音看看声音有没有变化

我更改声音后，重复测试了几次，确定不是系统声音。有两点需要注意：
1  我说的是 DeepL 翻译后的文字朗读，不是源文本朗读。
2  我使用了 DeepL api ，这个对朗读功能有影响吗？

举例，比如随便翻译一个短句，https://www.deepl.com/translator#en/zh/openCopiedUrlInCurrentTab，在我设置了系统声音后，朗读的声音是这个网址里的机械男声。

这个出现在mac系统上，我又打开 windows 笔记本测试了一下，确定DeepL使用的不是系统声音，是网站的tts声音。如果翻译后是中文，朗读的是网站的TTS男声，翻译后的英文是是网站的TTS女声。

**Comment by lmk123** [comment]
我知道是什么原因了—— DeepL 网站跟划词翻译一样，使用的都是浏览器提供的语音来进行朗读的。

如果你知道如何使用 Chrome 浏览器的开发者工具的话，你可以先打开开发者工具的“网络”面板，然后在 DeepL 网站上点击朗读按钮，你就会发现网络里并没有出现加载音频流的 HTTP 请求，但确实有声音，这也就意味着 DeepL 也是使用了由浏览器提供的语音。

另外，在开启“始终使用系统语音”之后，我使用谷歌翻译和 DeepL 朗读汉字“爱”时，听到的是一样的声音，都是机械式的女声。这一点也可以证明这个选项是有按照预期工作的。

**Comment by lmk123** [comment]
顺带一提，在这个过程中我发现了另一个 bug，可能跟你说的情况有关：#1716

**Comment by Langeeker** [comment]
> 我知道是什么原因了—— DeepL 网站跟划词翻译一样，使用的都是浏览器提供的语音来进行朗读的。
> 
> 如果你知道如何使用 Chrome 浏览器的开发者工具的话，你可以先打开开发者工具的“网络”面板，然后在 DeepL 网站上点击朗读按钮，你就会发现网络里并没有出现加载音频流的 HTTP 请求，但确实有声音，这也就意味着 DeepL 也是使用了由浏览器提供的语音。
> 
> 另外，在开启“始终使用系统语音”之后，我使用谷歌翻译和 DeepL 朗读汉字“爱”时，听到的是一样的声音，都是机械式的女声。这一点也可以证明这个选项是有按照预期工作的。

问题就出现在这里，浏览器是可以获取操作系统自带声音的，Windows 里有 huihui，kangkang、Zira，Mark 等等中英文语音，MacOS 里自带的就更多了。而且浏览器如果是 Edge，那 Edge  可以跨平台获取微软自家云 Azure 里的更 Natural 的声音，著名的云扬、云曦之类的等等。对于谷歌翻译来说，我怎么设置语音来源就怎么读，声音和平台语音一致，DeepL 怎么设置都是一种男/女的TTS声音。

这个和 DeepL 网站本身有没有传音频流的 HTTP 请求无关，而是划词插件用了 DeepL 的语音发音，导致我怎么设置都无效，都是一种机械的TTS声音，谷歌翻译则是正常切换我选择的语音。

**Comment by Langeeker** [comment]
顺便，我又问了一个使用划词插件的朋友，他测试后和我一样。DeepL 发音不变，不能按照语音朗读的设置来发音。

**Comment by Langeeker** [comment]
> > 我知道是什么原因了—— DeepL 网站跟划词翻译一样，使用的都是浏览器提供的语音来进行朗读的。
> > 如果你知道如何使用 Chrome 浏览器的开发者工具的话，你可以先打开开发者工具的“网络”面板，然后在 DeepL 网站上点击朗读按钮，你就会发现网络里并没有出现加载音频流的 HTTP 请求，但确实有声音，这也就意味着 DeepL 也是使用了由浏览器提供的语音。
> > 另外，在开启“始终使用系统语音”之后，我使用谷歌翻译和 DeepL 朗读汉字“爱”时，听到的是一样的声音，都是机械式的女声。这一点也可以证明这个选项是有按照预期工作的。
> 
> 问题就出现在这里，浏览器是可以获取操作系统自带声音的，Windows 里有 huihui，kangkang、Zira，Mark 等等中英文语音，MacOS 里自带的就更多了。而且浏览器如果是 Edge，那 Edge 可以跨平台获取微软自家云 Azure 里的更 Natural 的声音，著名的云扬、云曦之类的等等。对于谷歌翻译来说，我怎么设置语音来源就怎么读，声音和平台语音一致，DeepL 怎么设置都是一种男/女的TTS声音。
> 
> 这个和 DeepL 网站本身有没有传音频流的 HTTP 请求无关，而是划词插件用了 DeepL 的语音发音，导致我怎么设置都无效，都是一种机械的TTS声音，谷歌翻译则是正常切换我选择的语音。

再加一张我的设置图，Edge 里面的语音朗读设置如下：
<img width="856" alt="123" src="https://user-images.githubusercontent.com/41421063/230900654-1562e862-d4b7-41ca-974d-5fc7fd0d4001.png">

**Comment by Langeeker** [comment]
这个语音设置对 DeepL 无效。

**Comment by lmk123** [comment]
我理解你的意思了。根据你的描述，我整理了一下此问题的重现步骤到 #1718，你可以看一下，应该就是你想表达的问题。

这个 issue 我就先关闭了。

顺带一提，Edge 升级到 v112 之后就没有 Yunxi 这个选项了，这是 Edge 把它去掉了，不是划词翻译去掉的 :joy:
