### ISSUE TITLE
给全文翻译添加“逐句”翻译模式

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1712]
**没有这个功能（改进）的时候，你遇到了什么问题？**

全文翻译现在是“批量”翻译模式，即尽可能将多段文本合并成一段文本发送给翻译服务处理。

这种模式的好处是速度快，但也因此带来了很多问题：

- 多段文本相互之间会成为翻译上下文，从而影响翻译结果。
  - 经常有用户询问为什么划词翻译时的结果跟全文翻译的结果不一样
- 多段文本中如果有多个语种则会出现英译英的情况。
- ChatGPT 无法确保翻译结果的换行符跟原文的个数一样，导致在全文翻译模式中译文匹配不上原文，相关 issue：
  - #1671 
  - #1666
- 一次性给 ChatGPT 处理大量文本很容易就会产生“输出中断”的情况，如 #1714

**你想要如何解决你的问题？**

添加“逐句”翻译模式，即每一段话单独发送给翻译服务处理。这样做的好处是能解决以上三个问题，但坏处是处理速度慢，因为翻译服务一般都有使用频率限制，例如百度翻译限制一秒调用 10 次。

举个例子，假设一共有 15 段文本需要翻译，那么批量翻译模式下只需要调用
2 次，花费 0.5 秒不到，而逐句模式则需要调用 15 次，考虑到一秒调用 10 次的间隔，则需要 2 秒才能完成。

**Comment by kingofotaku** [comment]
我觉得可以设置一个阈值：即文本量不超过xx字时启用逐句翻译。当然也可以分别允许手动指定发送方式。

**Comment by yuliang1997** [comment]
我觉得没有最好的解决方案的时候就给用户选择就好了。我平常用全文翻译通常是用来阅读文档，实际上我是从上至下一点点看的，这时候批量翻译的等待时间就非常长了，尤其是ChatGPT。我觉得可以考虑按上下顺序同时发送多个请求，哪个返回了就及时反馈到页面上，这是体验最好的情况了
