### ISSUE TITLE
chatGPT源-全文翻译-图片后的内容-译文出现在了原文上方

### ISSUE THREAD

**Issue by JingchengLi** [hcfyapp/crx-selection-translate#1713]
## 基本信息

划词翻译版本：v9.6.0
浏览器版本：chrome版本 110.0.5481.177（正式版本） (arm64)
操作系统：MacOS Monterey 12.3

## 重现问题的步骤
打开下面这个链接，并选择chatGPT源进行全文翻译
https://www.clues.life/post/subtraction-not-addition
![image](https://user-images.githubusercontent.com/5918144/230811152-63dbeddc-7d24-42ac-9001-63f8ae706e32.png)
如图所示，图片下面的内容，出现翻译和原文错位的情况，译文出现在了原文上方。

### 预期行为
图片下面的内容，译文应在原文下方。

**Comment by lmk123** [comment]
这个跟你之前提的这个 https://github.com/hcfyapp/crx-selection-translate/issues/1671#issuecomment-1501363069 是同一个情况 :joy:
