### ISSUE TITLE
chatGPT源-全文翻译-译文末尾内容不全

### ISSUE THREAD

**Issue by JingchengLi** [hcfyapp/crx-selection-translate#1714]
## 基本信息

划词翻译版本：v9.6.0
浏览器版本：chrome版本 110.0.5481.177（正式版本） (arm64)
操作系统：MacOS Monterey 12.3

## 重现问题的步骤
在翻译下面的网页时，出现**译文内容不全**的情况：
https://www.clues.life/post/subtraction-not-addition
<img width="780" alt="image" src="https://user-images.githubusercontent.com/5918144/230812350-bdc2c95b-143e-45df-a380-b01f790ec604.png">

**Comment by lmk123** [comment]
你应该是使用的 v9.8.0 里新增的无需填写 API Key 的 ChatGPT。

我用你提供的网址试了一下，虽然我没有重现这个问题（在我这里这句话是完整翻译了的），但我知道这个问题确实有发生的可能，因为 https://chat.openai.com 网页版本的 ChatGPT 经常会发生“输出中断”的情况，即一旦它输出的字符数超过了一定的数量，它就中断了不输出了，除非你再给它发送一次”继续”，它才会接着输出完剩下的内容。

我会想办法解决这个问题。
