### ISSUE TITLE
能否支持 OpenAI api 的代理接口

### ISSUE THREAD

**Issue by wonderful259** [hcfyapp/crx-selection-translate#1715]
**没有这个功能（改进）的时候，你遇到了什么问题？**
目前使用的 OpenAI 是和朋友一起合购的，为了解决代理的问题我们搭建了一个中转网站，所以目前使用的都是key+代理网站这样的模式，这个在划词翻译里还用不了。

**你想要如何解决你的问题？**
希望划词翻译的 ChatGPT 支持 api 代理，类似opencat 和沉浸式翻译提供的选项。

**Comment by lmk123** [comment]
这个选项已经有了，在划词翻译设置 - 第三方服务 - ChatGPT 里

**Comment by UlyssesWu** [comment]
@lmk123 选项虽有，但似乎无效。即使配置了其他“镜像地址”，划词后依然在请求openai。我怀疑这个设置并没有生效。
