### ISSUE TITLE
DeepL 朗读时没有遵循语音设置

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1718]
## 基本信息

划词翻译版本：v9.8.0
浏览器版本：Edge 版本 112.0.1722.39 (正式版本) (arm64)
操作系统：macOS 13.3.1

## 重现问题的步骤

1. 在划词翻译设置 - 语音朗读中，选择“始终使用系统语音”，并确保“英语”的口音设置为了“自动”
2. 使用谷歌翻译和 DeepL 翻译一段英文，例如 `HoloInsight is a cloud-native observability platform with a special focus on real-time log analysis and AI integration.`
3. 分别使用谷歌翻译和 DeepL 的朗读按钮朗读这段英文，留意发出的声音。
4. 现在，在划词翻译设置 - 语音朗读中，将“英语”的口音设置为”英语（美国）”，然后将“英语（美国）”的语音设置为”Microsoft Aria Online (Natural) - English (United States) - 网络语音” 
5. 再次分别使用谷歌翻译和 DeepL 的朗读按钮朗读这段英文，留意发出的声音。

### 预期行为

由于两次朗读使用了不同的设置，所以听到的声音应该是不一样的。
### 实际行为
谷歌翻译两次朗读的声音是不一样的，但 DeepL 两次朗读的声音是一样的。
### 补充信息

此问题的详细上下文见 https://github.com/hcfyapp/crx-selection-translate/issues/1711

可能也跟 #1716 有关

**Comment by Langeeker** [comment]
这个 bug 哪个版本会修复？

**Comment by lmk123** [comment]
具体会在哪个版本修复我没法保证，不过我已经提升了优先级，后面的版本会优先解决此问题

**Comment by lmk123** [comment]
下个版本 v10.0.1 修复了此问题。

<details>
  <summary>开发者备注：出现问题的原因以及 v10.1.0 做了什么修复</summary>

造成谷歌翻译和 DeepL 对同一段文本产生了不同读音的原因是因为，谷歌翻译提供了检测出的源语种，而 v10.0.0 以及之前版本的 DeepL 没有提供。

在选择了“始终使用系统语音”之后，谷歌翻译和 DeepL 都是用的浏览器提供的阅读器来朗读文本的。

在朗读文本时，由于谷歌翻译检测出了文本是英语，所以在朗读前会给浏览器的阅读器设置一个语种，类似于 `speaker.lang = 'en'`

而用 DeepL 朗读文本时，由于它没有提供检测出的语种，所以没有上面那个设置语种的步骤。

而这就导致浏览器的阅读器出现了两种不同的读音。

所以，v10.1.0 中，划词翻译给 DeepL 提供了检测出的源语种，也就有了跟谷歌翻译一样的设置语种的步骤，那么读出来的语音就是一样的了。
</details>
