### ISSUE TITLE
复制PDF内文本并采用独立窗口翻译时翻译结果未消除回车

### ISSUE THREAD

**Issue by WrennCool** [hcfyapp/crx-selection-translate#1721]
## 基本信息

划词翻译版本：9.72
浏览器版本：edge 版本 112.0.1722.39 (正式版本) (64 位)

操作系统：win11

## 重现问题的步骤

1. 在edge浏览器中打开一pdf文件，如https://scholar.google.com/scholar_url?url=https://link.aps.org/pdf/10.1103/PhysRevE.96.042310&hl=zh-CN&sa=X&ei=cbc4ZML0AcyR6rQPsqeXSA&scisig=AJ9-iYucAb9RXvR9k5suB7-9iRxr&oi=scholarr （附件）
2. 复制PDF内文本
3.选用独立窗口选项进行翻译，翻译结果为分散的几句话而非复制的一整个段落

### 预期行为
删去复制内容的回车、并将复制文本视作一个完整段落以进行翻译
### 实际行为
该操作在PDF内复制文本中出现，不同文献内段落其复制结果存在大量回车，因此回车部分被翻译器识别并用以分割翻译结果，原本完整的一段被分割成了分散的几句话
### 补充信息

[Epidemic spreading on activity-driven networks with attractiveness.pdf](https://github.com/hcfyapp/crx-selection-translate/files/11228353/Epidemic.spreading.on.activity-driven.networks.with.attractiveness.pdf)

**Comment by lmk123** [comment]
感谢反馈，我已重现你的问题。

划词翻译的独立翻译窗口没法判断复制文本的来源，如果文本来自于其它程序而用户复制的确实是多段文本，此时自动去掉复制内容的回车就不符合预期了。

因此，划词翻译提供了一个额外的选项，在[划词翻译设置页](https://hcfy.app/docs/guides/options) -【翻译面板】-【源文本处理】-【去掉换行符】。当你需要的时候，你可以勾选【去掉换行符】，那么划词翻译将为你自动去掉复制内容里的换行符，也就可以解决你的问题了。

注意，【源文本处理】功能目前需要开通会员才能使用。
