### ISSUE TITLE
希望能支持国际版的必应词典

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1724]
因为要使用bing AI 所以Bing的东西都走了国外，导致国内版用不了。
https://www.bing.com/dict/search?q=welcome&cc=cn

**Comment by lmk123** [comment]
厉害啊……我以前就想解决 cn.bing.com/dict 不支持国外 IP 的问题，但我试过用 https://www.bing.com/dict/search?q=welcome 是没有翻译结果的，没想到在后面跟个 `&cc=cn` 就可以了。。

**Comment by ghost** [comment]
> 厉害啊……我以前就想解决 cn.bing.com/dict 不支持国外 IP 的问题，但我试过用 https://www.bing.com/dict/search?q=welcome 是没有翻译结果的，没想到在后面跟个 `&cc=cn` 就可以了。。

我打开就这个啊。。。我不懂
