### ISSUE TITLE
ChatGPT 只有用API才能用，模拟网页的方式显示403

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1727]
## 基本信息

划词翻译版本：9.8.1.1（firefox）   9.8.1（brave）
浏览器版本：brave 或者 firefox
操作系统：win11

## 重现问题的步骤
用API可以，但是网页版不行，我已经登录而且正常访问。
 
### 预期行为
出现翻译
### 实际行为
403
### 补充信息
已经排除杀毒软件 广告过滤插件。网络全局代理也不行。

**Comment by ghost** [comment]
~~感觉是Chameleon引发的，但是brave没有这个插件啊。~~
关闭Chameleon后正常了。

**Comment by lmk123** [comment]
方便提供一下你说的“Chameleon”这个软件的具体链接吗？我搜了一下，有太多软件叫这个名字了，我想把这个案例写进文档里

**Comment by ghost** [comment]
> 方便提供一下你说的“Chameleon”这个软件的具体链接吗？我搜了一下，有太多软件叫这个名字了，我想把这个案例写进文档里

https://addons.mozilla.org/zh-CN/firefox/addon/chameleon-ext/

**Comment by ghost** [comment]
有时候还是需要重新开openai的网站，貌似每隔一段时间openai就要重新验证一次，太麻烦了。还是期待bing吧，没那么多限制。
