### ISSUE TITLE
希望文本筛选能支持自定义单词

### ISSUE THREAD

**Issue by user-GitHub-user** [hcfyapp/crx-selection-translate#1730]
**没有这个功能（改进）的时候，你遇到了什么问题？**
我主要用在计算机领域，一些专有名称的翻译，翻译出来既不准确，也没有必要，比如：Hive 翻译为：配置单元，Spark翻译为：火花
 等等
**你想要如何解决你的问题？**
一些专用的单词，可由用户在文本筛选中配置为不翻译

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
~

**补充信息**
比较实用，且目前有过滤中文的功能，可基于该功能改进

**Comment by lmk123** [comment]
这个功能其实是术语表，这个过程是需要翻译服务来调节的，划词翻译对此无能为力。划词翻译的筛选是如果有特定文本那就不要触发翻译，你的需求是在翻译结果中不翻译这些特定单词。

如果你使用自行申请的翻译服务的话，有些翻译服务是支持术语表的，比如百度翻译：https://hcfy.app/docs/services/baidu-api#s
