### ISSUE TITLE
允许设置网页全文翻译的默认源语言为指定语言

### ISSUE THREAD

**Issue by noriole** [hcfyapp/crx-selection-translate#1733]
目前网页全文的默认源语言为自动检测
而我经常需要在含有同时含有中文和英文的网页中使用全文翻译服务，每次都要手动将全文翻译的源语言改成英语，这样很麻烦
希望能增加设置网页全文翻译的默认源语言为指定语言的功能，比如英语

**Comment by lmk123** [comment]
下个版本将会记住你每次选择的源语种，在下次开启全文翻译时会默认使用上次选择的源语种，就像目标语种那样。
