### ISSUE TITLE
增加gpt翻译源

### ISSUE THREAD

**Issue by CarsonLam** [hcfyapp/crx-selection-translate#1734]
**没有这个功能（改进）的时候，你遇到了什么问题？**
现有翻译没有gpt翻译准确。

**你想要如何解决你的问题？**
增加各类ai模型api或者翻译源功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
无

**Comment by lmk123** [comment]
目前已经支持 ChatGPT 源了。其它源（例如 New Bing）也在计划当中，见 #1720
