### ISSUE TITLE
翻译pdf时,无法将多行文字连在一起翻译, 而是每行文字单独翻译

### ISSUE THREAD

**Issue by omymenzies** [hcfyapp/crx-selection-translate#1736]
## 基本信息

划词翻译版本：9.8.1
浏览器版本：Microsoft Edge Version 112.0.1722.64 (Official build) (64-bit)
操作系统：Windows 10 
## 重现问题的步骤
用Adobe Acrobat打开一个pdf文件. 使用独立翻译窗口翻译pdf中的一段英文, 得到下图的结果:
<image src="https://user-images.githubusercontent.com/115856305/235424998-ff8bace0-cbe9-47c5-b6c4-6f69693211eb.png" width=70%>
### 预期行为
将多行文字作为一段完整的话来翻译
### 实际行为
每行文字单独翻译

**Comment by lmk123** [comment]
这段文本应该确实是包含换行符的。你可以把 Adobe Acrobat 里复制的文本粘贴在记事本里，看看有没有换行符。

划词翻译的独立翻译窗口没法判断复制文本的来源，如果文本来自于其它程序而用户复制的确实是多段文本，此时自动去掉复制内容的回车就不符合预期了。

因此，划词翻译提供了一个额外的选项，在[划词翻译设置页](https://hcfy.app/docs/guides/options) -【翻译面板】-【源文本处理】-【去掉换行符】。当你需要的时候，你可以勾选【去掉换行符】，那么划词翻译将为你自动去掉复制内容里的换行符，也就可以解决你的问题了。

注意，【源文本处理】功能目前需要开通会员才能使用。
