### ISSUE TITLE
多次使用ChatGPT后网页版有很多条会话，但按照预期应该只有一条才对

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1737]
隔壁这个已经实现了。
https://github.com/josStorer/chatGPTBox/issues/185

**Comment by lmk123** [comment]
现在划词翻译仅仅只会创建一条会话，并不至于打乱你的会话列表，所以我个人反倒是希望这条会话能被保留的，这样可以看到划词翻译的翻译记录

你可以解释一下为什么你想要删掉这条会话吗？如果理由充分的话，我可以加个选项，在每次翻译后自动删除会话

**Comment by ghost** [comment]
留记录也应该是这个插件的事情，用google翻译或者deepl也没有记录啊。
而且在我浏览器，有很多个New Chat
![图片](https://github.com/hcfyapp/crx-selection-translate/assets/11383988/b431bf17-d59a-41da-934e-6ea868fbd248)

**Comment by lmk123** [comment]
那这就是一个 bug 了，我确认一下

**Comment by lmk123** [comment]
据我这段时间的使用，我发现现在 ChatGPT 网页版又只有一条会话了，所以这个 issue 我就先关闭了。

我没有做任何改动，猜测是 ChatGPT 那边做了啥改动，给恢复了。
