### ISSUE TITLE
购买过永久会员但被告知非会员

### ISSUE THREAD

**Issue by lixinyipuhaha** [hcfyapp/crx-selection-translate#1738]
去年买的永久会员，时隔很久重新使用划词翻译，居然跳出“非会员每天只能使用3次网页全文翻译功能，成为会员即可解除此限制。购买会员”的提示。请修复。

**Comment by lixinyipuhaha** [comment]
我被提示会员过期，但我记得我购买的是终身会员。发公众号即可是吗？好的，我现在操作。再有，这个帖子有无可能在解决完毕后隐藏，即仅自己可见。

**Comment by lmk123** [comment]
如果你希望的话，我可以删掉这个帖子
