### ISSUE TITLE
在部分网页下控制台报

### ISSUE THREAD

**Issue by TMaize** [hcfyapp/crx-selection-translate#1739]
## 基本信息

划词翻译版本：v9.8.1
浏览器版本：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
操作系统：Mac

## 重现问题的步骤

1.在这个链接下控制台报错，关闭翻译插件正常

https://user-images.githubusercontent.com/16556693/236126882-007c76ae-f976-49d9-940e-12252707f740.svg

caught TypeError: Cannot use 'in' operator to search for 'animation' in undefined

### 预期行为

控制台不报错

### 实际行为

控制台报错

**Comment by lmk123** [comment]
先说结论：这个问题没法从划词翻译这边解决。

以下是详细分析过程。

这个报错出现在这里：

https://github.com/facebook/react/blob/v18.2.0/packages/react-dom/src/events/getVendorPrefixedEventName.js#L85

其中，`style` 的值是 `undefined`，导致运行 `styleProp in style` 时报了这个错。

`style` 的值来自这里：

https://github.com/facebook/react/blob/v18.2.0/packages/react-dom/src/events/getVendorPrefixedEventName.js#L51

经过确认，我发现 `document.createElement('div').style` 在你提供的链接当中是 `undefined`，而在别的网站中是正常的 CSS 对象，所以出现了这个问题。

我注意到你提供的这个网站使用了 CSP 限制了对 inline-style 的使用：

```
Content-Security-Policy:
default-src 'none'; script-src 'none'; img-src 'self'; media-src 'self'; sandbox;
```

控制台一开始也有相关的报错：

```
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-JrDBRKQ1OabwgqSGLyTwIGPNLIwaoNO2Poj4fS6sPhI='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```

这才导致 `document.createElement('div').style` 的值变成了 `undefined`

**Comment by lmk123** [comment]
给 React 提了个 issue https://github.com/facebook/react/issues/26777
