### ISSUE TITLE
腾讯翻译君能否增加音标

### ISSUE THREAD

**Issue by huangming** [hcfyapp/crx-selection-translate#1740]
必应词典是有音标的,为什么腾讯翻译君没有音标呢?
很多场景比如图书馆,公司办公室,我希望查询翻译后直接看音标了解怎么读音,不想听电脑读.必应是有音标的,但是腾讯翻译君没有,这个是因为第三方接口不支持么?必应网速响应没有腾讯翻译君快,还是想要腾讯翻译也支持.

**Comment by lmk123** [comment]
> 这个是因为第三方接口不支持么?

划词翻译使用的是腾讯翻译君官方 API，而它就是不提供词典 / 音标的，见[腾讯翻译君 API 输出参数](https://cloud.tencent.com/document/product/551/15619#3.-.E8.BE.93.E5.87.BA.E5.8F.82.E6.95.B0)

我会向腾讯翻译君官方 API 的工作人员反馈这一情况，看看他们能否加上音标。
