### ISSUE TITLE
关于网页划词翻译功能：希望添加能够让翻译面板弹窗显示在划词下面的选项

### ISSUE THREAD

**Issue by Antislumber** [hcfyapp/crx-selection-translate#1741]
就像翻译按钮一样 显示在被划语句的下面或一旁，能更方便的对原文和翻译进行比对学习，而不是只固定在一个位置上，不方便查看

**Comment by lmk123** [comment]
划词之后的翻译面板本身就是显示在划词下面的，我猜测你是点击过面板左上角的图钉按钮，导致面板变成了固定模式。
