### ISSUE TITLE
网页全文翻译无法翻译特定网站：web of science

### ISSUE THREAD

**Issue by kadenjiangse** [hcfyapp/crx-selection-translate#1742]
## 基本信息

划词翻译版本：V9.8.2
浏览器版本：Chrome 113.0.5672.93
操作系统：windows 64

## 重现问题的步骤

1.进入web of science
2.开启网页全文翻译

### 预期行为
翻译网页内容
### 实际行为
只是把网页内容复制了一遍，并没有翻译

**Comment by lmk123** [comment]
我没有这个网站的账号，但是从你的描述来看，你遇到的问题应该是这个：[多语言混合的页面翻译结果有误](https://hcfy.app/docs/guides/page#yyy)

你可以根据上面链接中的方法调整一下源文本试试。

如果不是这个问题，欢迎继续留言，我会重新跟进。

**Comment by kadenjiangse** [comment]
解决了，感谢！
