### ISSUE TITLE
为什么我开了-自动翻译剪切版的文本-但是却没反应

### ISSUE THREAD

**Issue by jxadcx** [hcfyapp/crx-selection-translate#1743]
开启了独立翻译窗口,然后勾选了自动翻译剪切板的文本,复制文本后却没反应,而旁边的yomichan就可以读取剪切板文本

**Comment by lmk123** [comment]
复制文本后还需要再按一次独立翻译窗口的快捷键才行。划词翻译是浏览器扩展程序，无法像桌面软件那样自动监听剪切板的内容变动

**Comment by lmk123** [comment]
我猜你是希望在复制文本之后就立刻弹出翻译，不过划词翻译目前在复制文本之后，还需要再按一下打开独立翻译窗口的快捷键才会触发翻译。

我来试一下 yomichan，看看它是怎么做到一复制就读取到剪切板的

**Comment by lmk123** [comment]
下个版本 v10.3.0 给独立翻译窗口添加了一个新的选项“持续监听剪切板”，开启后，一旦剪切板内容变化，独立窗口就会自动翻译
