### ISSUE TITLE
无法执行全文翻译

### ISSUE THREAD

**Issue by chenyz1984** [hcfyapp/crx-selection-translate#1744]
## 基本信息

划词翻译版本：9.8.2
浏览器版本：Edge 113.0.1774.50 (正式版本) (64 位)
操作系统：Windows 11

## 重现问题的步骤

如下链接只能翻译标签页，无法翻译正文内容。
https://cwiki.apache.org/confluence/display/Hive/GettingStarted

![image](https://github.com/hcfyapp/crx-selection-translate/assets/20869868/7aa36245-3f22-4ca1-b855-310bbf25bf71)

**Comment by lmk123** [comment]
我试了一下，是正常的，如下图。你可以重启浏览器后再试试

<img width="978" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/ef46f61d-69e7-4d90-bcc8-ecb3c03a378c">
