### ISSUE TITLE
在Macbook的edge最新版，划词后点击浮标 无效

### ISSUE THREAD

**Issue by kson34** [hcfyapp/crx-selection-translate#1745]
## 基本信息

划词翻译版本：v9.8.2
浏览器版本：edge 版本 113.0.1774.50 (正式版本)
操作系统：macos 10.15.7

## 重现问题的步骤

1. 划词后点击浮标 无效

**Comment by lmk123** [comment]
我就在现在这个页面，用 macOS edge 试了一下，是正常的。

你可以重启浏览器后再试试。如果还是不行，麻烦提供一下更详细的重现步骤，比如具体是在哪个网页中出现了这个问题。

当你提供了详细重现步骤后，我会重新打开这个 issue
