### ISSUE TITLE
我是永久会员，截图翻译和一个漫画油猴插冲突，会让我退出漫画阅读模式并页面回到顶部，请修复

### ISSUE THREAD

**Issue by AnduinZZ** [hcfyapp/crx-selection-translate#1746]
## 基本信息
https://github.com/hymbz/ComicReadScript
划词翻译版本：9.9.0
浏览器版本：
操作系统：Win11

## 重现问题的步骤

1.用油猴插件进入漫画阅读模式
2.用快捷键激活截图ORC翻译
3.完成截图

### 预期行为
出现独立翻译窗口，漫画界面仍处于漫画阅读模式
### 实际行为
出现独立翻译窗口，漫画界面退出了漫画阅读模式，并回到了页面顶部

**Comment by AnduinZZ** [comment]
<html>
<body>


Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by AnduinZZ** [comment]
https://sleazyfork.org/zh-CN/scripts/374903-comicread

**Comment by lmk123** [comment]
看样子另一边已经解决这个问题了 :joy:
