### ISSUE TITLE
独立窗口上方工具栏消失

### ISSUE THREAD

**Issue by DH455** [hcfyapp/crx-selection-translate#1747]
## 基本信息

划词翻译版本：9.9.0
浏览器版本：Microsoft Edge版本 115.0.1866.1 (正式版本) dev (64 位)
操作系统：win11

## 重现问题的步骤
1. 启动独立窗口

### 实际行为
独立窗口上方包含最小化、最大化、关闭按钮的工具栏消失，也无法通过拖动移动独立窗口。
<img width="797" alt="2023-05-25_163712" src="https://github.com/hcfyapp/crx-selection-translate/assets/102397427/5040b548-4700-41c4-8cbb-fb27a87dc15d">

### 补充信息
此问题发现于05.24，05.23尚可正常使用

**Comment by lmk123** [comment]
我在 windows 11 试了下，是正常的。

我注意到你提供的 edge 版本是 115，而我在 windows 11 上看了下，stable 渠道的 edge 最新版本是 113。根据以往使用 dev 渠道浏览器的用户的反馈情况，你遇到的问题是 dev 渠道的 edge 的问题，不是划词翻译的问题。

如果以后在 stable 渠道有这个问题，欢迎反馈，我会第一时间修复。
