### ISSUE TITLE
[Feature] 支持插件内独立配置代理

### ISSUE THREAD

**Issue by Philogag** [hcfyapp/crx-selection-translate#1748]
**没有这个功能（改进）的时候，你遇到了什么问题？**
不支持独立配置代理，无法在不启用系统全局代理的情况下使用谷歌等接口

**你想要如何解决你的问题？**
支持选择 跟随系统/手动代理
手动代理支持 SOCK5/HTTP/HTTPS，选择协议，端口，用户密码（可选）

**实现方式**
这是一个成熟的需求，大部分Ajax封装库都原生提供了此功能
JQuery：
```
ajaxProxy.proxy.url = "http://your proxy";
ajaxProxy.proxy.credentials.username = "proxy username";
ajaxProxy.proxy.credentials.password = "proxy password";
$.ajax({
    type: "GET",
    url: "https://ICANHAZIP.COM",
    headers: ajaxProxy.proxyHeaders(),
    dataType: "text"
}).done (function (data) {
    console.log(data);
});
```
Axios:
```
 proxy: {
    protocol: 'https',
    host: '127.0.0.1',
    port: 9000,
    auth: {
      username: 'mikeymike',
      password: 'rapunz3l'
    }
  },
```

**Comment by lmk123** [comment]
这个需求我加进了开发列表，但经过初步调研，这个需求可能不太好实现。

划词翻译目前是 Manifest V2 版本的扩展程序，但未来迟早会变成 Mainfest V3，届时背景页将不再支持 DOM 环境，也就不会再有 XMLHTTPRequest，这意味着 jQuery、axios 这类库都不能用了，只能使用 fetch API（或基于 fetch 的库）

然后，fetch 目前似乎不支持设置 proxy server。我谷歌搜了一会儿，得到的结论是 fetch api 在目前的设计中就是不支持的。

总结来说就是，划词翻译目前使用的是 Manifest V2，确实可以实现代理功能，但未来迟早是要升级到 Manifest V3 的，这就会导致一个原本存在的功能无法存在了，从用户体验来说，不如一开始就不存在 :joy:

**Comment by lmk123** [comment]
另外，扩展程序是遵循浏览器的代理设置的，而浏览器使用的是操作系统里的代理。

“系统代理”跟”全局代理”并不是绑定在一起的。比如我用的 clash for windows，开启系统代理后，还是可以选择使用“全局代理”（Global）还是”规则代理”（Rule）。

开启系统代理其实就是将代理地址写入了操作系统的代理中，比如在 macOS 里是如下图的样子，但你仍然可以额外控制是全局（Global）还是规则（Rule）。

<img width="650" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/45ebc65e-591d-483c-8c8e-0c1f5f2e8cbe">

**Comment by lmk123** [comment]
又进一步做了些调研，发现这个功能即使是在 Manifest V2 里也无法实现。

看了下 ajaxproxy 的源码（[https://www.ajaxproxy.com/js/ajaxproxy.js](https://www.ajaxproxy.com/js/ajaxproxy.js)），它的原理是通过一个 AWS 服务器转发请求，但如果你的梯子是在本地（即 127.0.0.1），那么显然这个 AWS 服务器是没法把请求转发到你本地的

axios 的 proxy 选项只支持在 Node.js 端使用，在浏览器端会忽略。你可以查看一下目前 axios 的最新版本 v1.4.0 的 xhr.js，里面就没有读取过 `proxy` 选项：

https://github.com/axios/axios/blob/v1.4.0/lib/adapters/xhr.js

作为对比，http.js（也就是 node.js 端的实现）里是读取过的：

https://github.com/axios/axios/blob/v1.4.0/lib/adapters/http.js

综上所述，在浏览器端实现代理功能应该是不太可能的
