### ISSUE TITLE
申请增加账户数据上传功能以便上传密钥、设置等数据到云端。

### ISSUE THREAD

**Issue by Huaweidev** [hcfyapp/crx-selection-translate#1749]
**没有这个功能（改进）的时候，你遇到了什么问题？**
在不同电脑需要重复设置密钥、参数设置。

**你想要如何解决你的问题？**
增加一个云端账户数据存储功能，一个账户也只会占用很少的数据量。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
密钥信息有导入导出，设置参数信息目前没有办法实现。

**补充信息**
无。

**Comment by lmk123** [comment]
当你成为会员后，就会自动在多个浏览器之间同步设置。

**Comment by lmk123** [comment]
密钥信息是特意设计成不上传到划词翻译服务器的，原因见 https://hcfy.app/docs/faqs/safe
