### ISSUE TITLE
划词翻译会在页面添加一个高度非常高的div标签导致页面过长

### ISSUE THREAD

**Issue by SmallSquare** [hcfyapp/crx-selection-translate#1750]
在例如LeetCode或者jupyter notebook等样式大小固定的页面上，通常整个样式是固定于屏幕显示大小的，但是开启划词翻译后，划词翻译会创建一个div标签导致整个页面的高度扩张，导致本身设计为固定的页面可以向下滚动，标签内含内容为光标选中的文本
```
<div style="pointer-events: none; visibility: hidden; position: absolute; box-sizing: border-box; top: 181px; left: 593px; width: 1px; padding: 0px; border: 0px solid black; line-height: 18px; font-size: 13px; font-family: Consolas, &quot;Courier New&quot;, monospace;">class Solution:<br>         </div>
```

**Comment by lmk123** [comment]
> 例如LeetCode或者jupyter notebook等样式大小固定的页面上

可以提供一个具体的网址吗？

**Comment by SmallSquare** [comment]
比如任意的LeetCode的一道题目的编辑区
https://leetcode.cn/problems/two-sum/
光标选中编辑区内的文本之后可复现

**Comment by lmk123** [comment]
我使用 macOS Chrome 版本 113.0.5672.126（正式版本） (arm64)、划词翻译 v9.9.0，在你提供的网页 https://leetcode.cn/problems/two-sum/ 里选中了文本编辑区域里的“target”，但是没有出现网页可以往下滚动的情况。

麻烦新开一个 issue，确保你按照要求完整填写了重现问题所需要的信息，例如浏览器版本、操作系统等
