### ISSUE TITLE
添加选项，让翻译弹窗在固定模式下也能单击页面任意地方后自动隐藏

### ISSUE THREAD

**Issue by Subp66** [hcfyapp/crx-selection-translate#1753]
划词翻译结果的弹窗，在鼠标单击页面任意地方后可以自动隐藏

希望可以在设置中增加此选项

比如我把翻译弹窗固定在右上方位置
每次看完翻译结果后，我还要移动鼠标到右上角去关闭这个结果

如果我能点击一下页面任意位置，翻译弹窗就关闭，那便捷性就大大提升，我在设置中没有找到有这个功能

**Comment by lmk123** [comment]
目前的设计确实是这样的，即“固定模式下不会在单击任意地方后隐藏”。非固定的模式下，是会在单击任意地方后隐藏的。

我加个设置吧，允许设置固定模式下要不要单击任意地方后隐藏。

**Comment by lmk123** [comment]
v10.3.0 在【划词翻译设置】-【网页划词翻译】-【网页划词面板】里加了一个选项“为固定模式添加默认行为”，取消勾选后即可在点击任意地方后隐藏面板。
