### ISSUE TITLE
是否可以支持chatgpt可编辑prompt的功能

### ISSUE THREAD

**Issue by huadaonan** [hcfyapp/crx-selection-translate#1755]
主要是想利用划词功能的便利性，然后结合各种提示词，更多角度的理解具体划的词。
比如在配置页面里面或者实时的在页面设定好prompt，然后每次划词的时候把这个词作为变量放到prompt里面，显示结果

**Comment by lmk123** [comment]
已有功能，在划词翻译设置 - 第三方服务 - ChatGPT -【翻译命令】
