### ISSUE TITLE
在鼠标 hover 的段落左侧显示翻译该段落的按钮

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1756]
**没有这个功能（改进）的时候，你遇到了什么问题？**
划词翻译没有点击来的方便

**你想要如何解决你的问题？**
如题

**Comment by lmk123** [comment]
我正在开发一个功能，即点击段落时显示翻译结果，我觉得这个应该更方便一些，详细说明见 https://github.com/hcfyapp/crx-selection-translate/issues/1351#issuecomment-1075121072

**Comment by lmk123** [comment]
由于长时间没有反馈，所以我先关了。如果你有新的想法，欢迎留言，届时我会重新打开。

**Comment by scruel** [comment]
@lmk123 这个 issue 其实需求上和我提的另一个 [issue](https://github.com/hcfyapp/crx-selection-translate/issues/1704) 有点相关性，主要就是希望能有一个方便的途径，临时更改某个段落所用的翻译引擎，划词功能用的很少了，因为确实交互上会比较麻烦
