### ISSUE TITLE
无法对独立翻译窗口做拖动位置等操作

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1757]
## 基本信息

划词翻译版本：10.0.0
浏览器版本：Edge Dev 115.0.1880.3 
操作系统：Win11

## 重现问题的步骤

1. 快捷键打开独立翻译窗口
2. 尝试按住标题栏拖动位置

### 预期行为
拖动能够改变窗口的位置，右上角有叉叉图标能关闭窗口

### 实际行为
相反

### 补充信息
![图片](https://github.com/hcfyapp/crx-selection-translate/assets/16933298/0877e691-6278-480a-a9b9-08c2e14b267c)

**Comment by lmk123** [comment]
见 https://github.com/hcfyapp/crx-selection-translate/issues/1747#issuecomment-1565514908
