### ISSUE TITLE
能否增添翻译积分对于 ChatGPT 的支持？

### ISSUE THREAD

**Issue by Konjac-XZ** [hcfyapp/crx-selection-translate#1759]
**没有这个功能（改进）的时候，你遇到了什么问题？**
有这个想法是因为现在 ChatGPT 的免费试用实在是有点慢，而且中国内地买 OpenAI 的 API 也不方便。

**你想要如何解决你的问题？**
增添一个 ChatGPT 的翻译积分开关。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
增添一个打字机效果。

![image](https://github.com/hcfyapp/crx-selection-translate/assets/71483384/7515fca7-681b-42e3-b949-e7b72cd6a6a3)

**Comment by lmk123** [comment]
ChatGPT 对信用卡的限制太严了，我没法保证能稳定提供 ChatGPT 的翻译积分，所以我暂时没法加入

打字机效果在开发计划中了，见 #1674
