### ISSUE TITLE
以Excel格式导出收藏内容（有图）

### ISSUE THREAD

**Issue by oogleabcd** [hcfyapp/crx-selection-translate#1760]
看懂原文，理解原文。始终是最重要的，翻译工具再好用，也会遇到它无法适应的环境。例如，我是一名船员，在海上航行的时候，网络慢信号差，甚至没有。

所以，我希望划词可以开发这样一个功能：以Excel格式导出收藏夹内容，好让我把内容导入第三方软件。

你的产品很好用，我买了永久。我平时用anki 欧路词典学英文。

我期望表格内容是这样铺排的：
![image](https://github.com/hcfyapp/crx-selection-translate/assets/46415168/b2d66c3b-40ef-41d4-adfc-bdbd8376dcbd)

**Comment by lmk123** [comment]
很好的建议。

------

另外，有用户在公众号反馈，anki 需要的导入格式也是 excel 文件，第一列（A 列）为英文单词，第二列（B 列）为译文

或许我可以先做个简单的导出格式，然后根据用户反馈逐渐添加新的格式

**Comment by oogleabcd** [comment]
> 很好的建议。
> 
> 另外，有用户在公众号反馈，anki 需要的导入格式也是 excel 文件，第一列（A 列）为英文单词，第二列（B 列）为译文
> 
> 或许我可以先做个简单的导出格式，然后根据用户反馈逐渐添加新的格式

不支持导入Excel，我提议导出Excel是为了方便管理。
![image](https://github.com/hcfyapp/crx-selection-translate/assets/46415168/83ea7d46-6280-40ee-9ba7-9fa17b58fe16)

**Comment by oogleabcd** [comment]
谢谢，Anki对分隔符比较敏感，它可以根据分隔符进行导入管理，哪一列是中英关系不大。
----
![image](https://github.com/hcfyapp/crx-selection-translate/assets/46415168/2b6fb052-ac2a-4d2f-aa33-6e0b6e5bccf9)

**Comment by xiaotianhu** [comment]
Excel希望是CSV格式，纯文本 比较好处理，自己想处理下随便写点脚本代码或者叫chatGPT处理下都很方便，就可以导入到很多背单词的软件里了。
目前最想使用的还是氢刻 这个产品，也是支持Anki导入的。

**Comment by lmk123** [comment]
@oogleabcd 在 v10.4.0 当中我添加了导出为 .csv 和 .json 的功能。我目前不知道 CSV 格式能否满足你的需求，如果不满足的话，我可以再添加导出为 .xlsx 的功能

之所以现在没有加入是因为导出 .xlsx 的功能需要引入一个体积很大的代码包 :joy:
