### ISSUE TITLE
全文翻译功能在 reddit 中失效

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1761]
## 基本信息

划词翻译版本：v10.0.0
浏览器版本：Chrome 114.0.5735.106（正式版本） (arm64)
操作系统：macOS

## 重现问题的步骤

1. 打开https://www.reddit.com/r/apolloapp/comments/147a8xb/as_the_subreddit_blackout_begins_i_wanted_to_say/
2. 开启全文翻译
3.

### 预期行为
出现译文
### 实际行为
没有出现译文
### 补充信息

译文实际上是在网页当中的，但是不知为何文字颜色跟背景色融为了一体，导致看不见了。

尝试过分别使用浅色模式和深色模式都是如此。之前是没有这个问题的，应该是 reddit 最近对样式做了一些改版

**Comment by ghost** [comment]
sh.reddit.com 这是新版
