### ISSUE TITLE
全文翻译github的代码页面时不断闪烁

### ISSUE THREAD

**Issue by heheda123123** [hcfyapp/crx-selection-translate#1763]
## 基本信息

划词翻译版本：最新
浏览器版本：chrome 最新
操作系统：win 11

## 重现问题的步骤

https://github.com/electronicarts/EASTL/blob/master/include/EASTL/vector.h
全文翻译github类似含有代码的页面，往下划一点，顶栏一直闪烁

![image](https://github.com/hcfyapp/crx-selection-translate/assets/97490782/f9e2cf42-36cc-43dc-9544-88f7804207bf)

**Comment by lmk123** [comment]
感谢反馈。应该跟 #1758 是同一个问题

**Comment by lmk123** [comment]
你好 @heheda123123  ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
