### ISSUE TITLE
google翻译无法使用了

### ISSUE THREAD

**Issue by tangm421** [hcfyapp/crx-selection-translate#1772]
## 基本信息

划词翻译版本：v10.0.0
浏览器版本：Google Chrome 114.0.5735.135（正式版本） （64 位）
操作系统：Win10 LTSC 1809

### 补充信息
1. 我已将translate.googleapis.com代理了，
2. google翻译的接口类型为 `速度快、准确率低` 
3. 测试该地址无响应，报ERR_CONNECTION_CLOSED。https://translate.googleapis.com/translate_a/element.js
4. 使用代理直接访问该地址，OK。https://translate.google.com/

**Comment by lmk123** [comment]
我试了下，是正常的，且这个地址我是能看到响应的。

推测是你填写了镜像地址 / 设置了 hosts 没删，又或者是你的梯子没配置好。

<img width="317" alt="截屏2023-06-29 11 38 39" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/fc6dc52a-0189-4ef1-b1ab-bd0a6b1f8ec6">

**Comment by tangm421** [comment]
现在又恢复正常了

**Comment by tangm421** [comment]
猜测是google翻译服务器的短时问题。
