### ISSUE TITLE
我的 [网页全文翻译]使用的翻译服务 不正确.

### ISSUE THREAD

**Issue by Dssssds** [hcfyapp/crx-selection-translate#1773]
## 问题描述
* 我使用了[网页全文翻译],
* 但是使用的翻译服务,确实阿里云, 我只选择了 腾讯的.
### 查看以下图片
![image](https://github.com/hcfyapp/crx-selection-translate/assets/17268259/2f12453f-f7a8-47f6-9d0a-4da384cdfd4f)

**Comment by lmk123** [comment]
你好，选择翻译服务的地方在启用全文翻译后，网页右下角的划词翻译图标里，如下图。你截图的这个地方只是为了减少选择服务时的可选项。

<img width="600" alt="截屏2023-07-02 14 48 10" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/835c8b6c-dcd6-4ea0-9d97-d1568a8dca53">

**Comment by Dssssds** [comment]
好的,感谢.可以了.
