### ISSUE TITLE
打开独立窗口无效

### ISSUE THREAD

**Issue by heloook** [hcfyapp/crx-selection-translate#1774]
![图片_20230703222603](https://github.com/hcfyapp/crx-selection-translate/assets/27837566/b60b3d0a-f5f7-46c9-a365-663eb627cf2d)
这里设置了快捷键，选中了文本时，打不开独立窗口

![image](https://github.com/hcfyapp/crx-selection-translate/assets/27837566/757ae1d3-aa04-43d0-877f-ac38f7ea7156)
而没有选中文本时，打开“独立翻译窗口”是有效的

**Comment by lmk123** [comment]
我试了一下，在网页中选中文本后，然后按下“Ctrl Shift 3”，会正常弹出独立窗口，并且翻译的确实就是选中的文本。

我猜测你出现这个问题的原因是你在别的程序选中了文本。在这个快捷键中，“选中的文本”必须是网页当中选中的文本，因为扩展程序做不到获取其它程序里选中的文本。

如果你确实是在网页内选中了文本但没弹出独立窗口，那么麻烦新开一个 issue 并完整填写一下 bug 反馈模版（浏览器版本、详细重现步骤等）
