### ISSUE TITLE
ChatGPT 全文翻译对gpt3.5-16k 模型支持

### ISSUE THREAD

**Issue by zhangchaoxinq** [hcfyapp/crx-selection-translate#1775]
使用ChatGPT做全文翻译，速度不理想。软件似乎不能特别支持gpt3.5-16k这样的大容量token模型

**Comment by lmk123** [comment]
速度不理想的原因是因为划词翻译目前不支持流式输出，这一点会在未来改进 https://github.com/hcfyapp/crx-selection-translate/issues/1674
