### ISSUE TITLE
网页全文翻译中，外观选择引用，文字默认是白色，而白色字体在大部分网页下不显示，需要手动调节成黑色

### ISSUE THREAD

**Issue by linkwoodworking** [hcfyapp/crx-selection-translate#1777]
## 基本信息

划词翻译版本：v10.1.0
浏览器版本：Chrome  114.0.5735.199（正式版本） （64 位），Opera 99.0.4788.88
操作系统：Windows10

## 重现问题的步骤

1.打开完整设置
2.外观-网页全文翻译-译文样式（选择引用）
3.可以看到下方的显示里，默认译文为白色（不可见）

### 预期行为
黑色字体

### 实际行为
白色字体

**Comment by lmk123** [comment]
我没看到你的图 :joy: 不过我明白你的意思了。

“引用”样式确实默认是白色，你可以前往【划词翻译设置】-【外观】-【网页全文翻译】中自行将文字颜色调成黑色的。

<img width="397" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/156e798c-eaa7-467d-8905-efa5601d3489">
