### ISSUE TITLE
DeepL翻译加载超时

### ISSUE THREAD

**Issue by angle5037** [hcfyapp/crx-selection-translate#1779]
## 基本信息

划词翻译版本：最新版
浏览器版本：vavaldi 最新版
操作系统：win11
网络环境：padawan hiboy最新版，SS代理模块正常启动，海外IP走代理的策略，各种网站均正常访问。

## 重现问题的步骤

1.浏览器中安装最新版划词翻译插件
2.登录已购永久会员账户，同步云配置
3.随便打开一个网页，选择一段文字应用划词翻译，等待10秒

### 预期行为
DeepL翻译正常显示结果。

### 实际行为
DeepL翻译显示加载超时。

### 补图
![image](https://github.com/hcfyapp/crx-selection-translate/assets/31230994/462d966f-7774-4620-9c5b-a365f936365c)

**Comment by lmk123** [comment]
我这边是正常的，如下图。你可以点一下“查看解决方案”，根据问题排查步骤确认一下是什么原因，如果有任何不明白的，可以继续留言。

<img width="312" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/f73f2b7f-707a-47a9-988d-8175ed1bd21e">

**Comment by angle5037** [comment]
我试着切换其他浏览器，也都一样不行，切换节点也不行，我参考了查看解决方案里的各种选项，关掉路由器代理直接用Clash客户端也不行，你能教教我怎样配置划词翻译直连吗？谢谢

**Comment by angle5037** [comment]
好像上述各种操作就涵盖了不用代理直连的情况，也是不行

**Comment by lmk123** [comment]
> 好像上述各种操作就涵盖了不用代理直连的情况，也是不行

那我就不太清楚会是什么原因了 :joy: 我再次确认了一下，我这边 DeepL 是正常的，也没有收到其它用户反馈说 deepl 不能用了

<img width="444" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/84cdf7de-3b02-4953-9bc5-4032371e974a">
