### ISSUE TITLE
会员功能范围

### ISSUE THREAD

**Issue by Sunovn** [hcfyapp/crx-selection-translate#1783]
## 基本信息

划词翻译版本：最新
浏览器版本：最新
操作系统：win10

## 重现问题的步骤

1.
![1111](https://github.com/hcfyapp/crx-selection-translate/assets/91693891/ab25a6f6-12de-49d8-a25a-114b3db30674)

2.
![2222](https://github.com/hcfyapp/crx-selection-translate/assets/91693891/fbddcafa-96a0-4c90-b183-ecbafe3a2546)

3.这两个地方自相矛盾，不知道哪个是对的

**Comment by lmk123** [comment]
这是因为对会员功能范围的调整还在进行中，而目前还没有对“自定义翻译源”这一功能进行调整，也就是说：

1. 目前为止，自定义翻译源功能仍然是有且只有永久会员可以使用
2. 在未来（大概一个月内），这个功能会变成免费用户可用
