### ISSUE TITLE
独立翻译窗口无法翻译包含一些特殊字符的文本

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1784]
## 基本信息

划词翻译版本：10.1.1
浏览器版本：版本 116.0.1938.16 (正式版本) dev (64 位)
操作系统：Win10

## 重现问题的步骤

1. 打开独立翻译窗口
2. 输入文本 `Vec<i32>` 后按回车

### 预期行为
翻译给定的文本

### 实际行为
无任何反应

**Comment by lmk123** [comment]
我这边是有反应的，如下图。猜测你可能是使用了“源文本处理”把这类文本给过滤掉了。如果你确认这是划词翻译的问题，麻烦提供一下能让我稳定重现此问题的方法，届时我会重新打开此 issue

<img width="172" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/760dbc6e-8110-4b7c-bb7c-ea1b67e4cd87">
