### ISSUE TITLE
全文翻译网页功能不起作用

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1785]
## 基本信息

划词翻译版本：10.1.1
浏览器版本：版本 116.0.1938.16 (正式版本) dev (64 位)
操作系统：Win10

## 重现问题的步骤

1. 打开 http://amid.fish/humble-gumbel
2. 激活全文翻译功能
3. 等待结果

### 预期行为
网页可见内容被分段翻译

### 实际行为
只有标题部分被翻译，正文内容始终无法被翻译

**Comment by lmk123** [comment]
同 #1219 

P.S. 如果你懂代码的话，可以在新标签页中打开 iframe 的内容，就可以翻译了，比如你提供的这个链接，正文内容其实是在 http://amid.fish/assets/gumbel.html

**Comment by scruel** [comment]
> 同 #1219
> 
> P.S. 如果你懂代码的话，可以在新标签页中打开 iframe 的内容，就可以翻译了，比如你提供的这个链接，正文内容其实是在 http://amid.fish/assets/gumbel.html

倒是没注意去看一下页面的源码，处理 iframe 确实有点棘手，谢谢~
