### ISSUE TITLE
在谷歌学术界面采用全文翻译时与easyscholar插件不兼容情况

### ISSUE THREAD

**Issue by WrennCool** [hcfyapp/crx-selection-translate#1786]
## 基本信息

划词翻译版本： v10.1.0
浏览器版本：edge 版本 114.0.1823.82 (正式版本) (64 位)
操作系统：win11

## 重现问题的步骤

1.打开谷歌学术链接，如https://scholar.google.com/scholar?cites=6717337700712447179&as_sdt=2005&sciodt=0,5&hl=zh-CN
2.启用全文翻译功能
3.

### 预期行为
网页中每一个英文结构都被翻译，包括论文的标题都被翻译成中文

### 实际行为
仅部分非论文标题网页部分被翻译，论文标题被翻译成英文，即一模一样的英文转英文

### 补充信息

我安装了easyscholar插件，实测禁用该插件或在该插件自动生成论文评价信息前启用全文翻译时可用

**Comment by lmk123** [comment]
这个问题其实是因为 easyscholar 插件注入了中文进网页，导致网页变成了一个中英混合的网页，按照下方链接的说明将源语种由”自动检测”调整成“英文”即可：

https://hcfy.app/docs/guides/page#yyy
