### ISSUE TITLE
翻译面板的音标显示怎么没有了？？

### ISSUE THREAD

**Issue by KamenRevice** [hcfyapp/crx-selection-translate#1787]
**记得之前版本的翻译面板有显示音标的，最新的10.1.0版本没有了**
![Snipaste_2023-07-18_17-11-13](https://github.com/hcfyapp/crx-selection-translate/assets/36665957/4cd7a8a1-9d25-4406-aae0-d3907ffe7744)

**外观设置页**
![Snipaste_2023-07-18_17-11-27](https://github.com/hcfyapp/crx-selection-translate/assets/36665957/1b3ba6e2-114c-4502-9af2-c725f8ca9870)

**翻译面板设置页**
![Snipaste_2023-07-18_17-11-35](https://github.com/hcfyapp/crx-selection-translate/assets/36665957/8a9cd848-8545-4b4c-8122-9f23f725342b)

**补充信息**
设置项没有找到，是藏起来了吗？

**Comment by lmk123** [comment]
很早之前的版本曾经加过一个选项，在【第三方服务】-【谷歌翻译】-【隐藏音标】，目测你是勾选了这个选项了。

如果不是，欢迎继续留言。

**Comment by KamenRevice** [comment]
没有勾选关闭，但部分单词翻译还是不出现音标，百度翻译和DeepL一直没有音标
![Snipaste_2023-07-19_08-17-23](https://github.com/hcfyapp/crx-selection-translate/assets/36665957/e50b9e9b-7886-4e05-adea-8d6a5d8610bc)![Snipaste_2023-07-19_08-17-35](https://github.com/hcfyapp/crx-selection-translate/assets/36665957/b52b3d9c-e418-4ec8-96c5-edbe5b61a75c)

**Comment by lmk123** [comment]
谷歌翻译网页版本身就是没有对 “opened” 这个单词提供音标的，见 https://translate.google.com/?sl=auto&tl=zh-CN&text=opened&op=translate

DeepL 和百度翻译是没有提供音标的。建议使用“必应词典”，基本都有音标

**Comment by KamenRevice** [comment]
确实原始单词google是提供音标的，非常感谢，顺便问下不考虑deepl和百度翻译加入音标吗

**Comment by lmk123** [comment]
DeepL 本身就不提供音标，我也没法变出来 :joy:

百度虽然网页在线版 fanyi.baidu.com 是有音标的， 但划词翻译用的是 API 接口，它是不提供音标的，所以我还是没法变出来 :joy:
