### ISSUE TITLE
gpt api能否增加可以使用第三方接口的功能。

### ISSUE THREAD

**Issue by lxd1028** [hcfyapp/crx-selection-translate#1789]
无法使用镜像网站购买的api密钥。

**Comment by lmk123** [comment]
已有功能，在划词翻译设置 - 第三方服务 - ChatGPT - 镜像地址

**Comment by lxd1028** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
