### ISSUE TITLE
【v10.1.2 已修复】能够正常登录OpenAI 但是翻译依旧报错 Cannot read properties of undefined (reading 'author')

### ISSUE THREAD

**Issue by Greymuno** [hcfyapp/crx-selection-translate#1790]
作者的话：

此问题已在 v10.1.2 中修复，详细说明见 https://hcfy.app/blog/2023/07/22/chatgpt

以下是原文

-----------------------------------------

## 基本信息

划词翻译版本：v10.1.1
浏览器版本：Version 114.0.5735.199 (Official Build) (64-bit)
操作系统：Win10 19042.508

## 重现问题的步骤

1. 密钥额度过期，配置页面API Key已删除
2. 正常登录chat.openai.com，确保chatGPT能够收到划词内容，且能正常回复
3. 任一网站划词，打开翻译面板

### 预期行为
翻译面板正常出现翻译结果
### 实际行为
返回结果
Cannot read properties of undefined (reading 'author')

### 补充信息
1. 尝试变更梯子节点和供应商，均可以正常登录chat.openai.com，但是返回的错误结果相同
2. 错误首次出现在7月20日。7.20之后每次划词会生成新的会话窗口，7.20之前不会
3. 尝试生成新的密钥（额度已过期），翻译面板报错变更为:

> 尝试通过密钥、免费试用使用ChatGPT时均失败了。
> 
> 密钥报错信息：“远程服务器返回了错误的 HTTP 响应码：429。请前往ChatGPT的官方平台确认密钥是否填写正确以及免费额度是否已用完。”
> 
> 免费试用报错信息：“Cannot read properties of undefined (reading 'author')”[查看解决方案](https://hcfy.app/docs/services/free#chatgpt)

**Comment by lmk123** [comment]
感谢你提供如此详尽的报告。

看样子是 ChatGPT 调整了网页接口，得重新做适配了。

**Comment by chenjuntong** [comment]
同一个问题，我也遇到了。

**Comment by chenjuntong** [comment]
> 感谢你提供如此详尽的报告。
> 
> 看样子是 ChatGPT 调整了网页接口，得重新做适配了。

同一个问题，我也遇到了，已完全不可用，可以的话辛苦提高下优先级，感谢

**Comment by chenjuntong** [comment]
> 



> 感谢你提供如此详尽的报告。
> 
> 看样子是 ChatGPT 调整了网页接口，得重新做适配了。

同一个问题，我也遇到了，已完全不可用，烦请提高修复优先级，感谢💕

**Comment by yuanjypku** [comment]
同一个问题，插件能将翻译请求输入到网页端但无法读取结果。希望能得到解决

**Comment by lmk123** [comment]
v10.1.2 已解决此问题，我将立刻发布此新版本。

**Comment by ghost** [comment]
为什么火狐的一直不更新啊，都一个月了
