### ISSUE TITLE
bug? 现在关闭浏览器 独立翻译窗口不会关

### ISSUE THREAD

**Issue by asdabbx** [hcfyapp/crx-selection-translate#1791]
## 基本信息

划词翻译版本：10.1.1
浏览器版本：Chrome 115.0.5790.102,CentBrowser 102.0.5005.167
操作系统：win11

## 重现问题的步骤

1.打开独立翻译窗口
2.浏览器主界面点右上角X

### 预期行为
独立翻译窗口关闭
### 实际行为
独立翻译窗口还在

### 补充信息
已取消勾选"关闭 Chrome 后继续运行后台应用"
我记得以前是会关的 
主要是影响到用的SessionBuddy了

**Comment by lmk123** [comment]
理论上是不会被跟着关闭的，因为独立翻译窗口相当于一个新的浏览器窗口，它不是从属于浏览器主界面的窗口，这俩之间是相互独立的
