### ISSUE TITLE
快捷键中“使用独立窗口翻译选中的文本”能否设置成全局。或者全局的独立窗口能否设置成，选中即可翻译，而不是复制之后在用快捷键调用独立翻译窗口翻译

### ISSUE THREAD

**Issue by ldk-ldk** [hcfyapp/crx-selection-translate#1792]
全局的独立窗口能否设置成，选中即可翻译，而不是复制之后在用快捷键调用独立翻译窗口翻译。

**Comment by ldk-ldk** [comment]
快捷键中“使用独立窗口翻译选中的文本”能否设置成全局。

**Comment by lmk123** [comment]
不能。

扩展程序没有能力读取到在别的软件里的选中文本，只有读取剪切板的能力，所以“选中即可翻译”也是做不到的。

未来会做一项改进，会监听剪切板，一旦剪切板变化就触发翻译。https://github.com/hcfyapp/crx-selection-translate/issues/1743
