### ISSUE TITLE
Deepl 和 ChatGPT 速度慢

### ISSUE THREAD

**Issue by peilonia** [hcfyapp/crx-selection-translate#1793]
有的抄袭划词翻译的，却比较快

https://github.com/hcfyapp/crx-selection-translate/assets/136886254/c318b261-7a61-4503-9ffd-214b27c84e45

**Comment by lmk123** [comment]
你说的“抄袭划词翻译”的具体是指的哪个？我可以看一下它们调用 DeepL / ChatGPT 的方式，如果它们真的比较快，我可能可以加入进划词翻译

**Comment by peilonia** [comment]
http://getquicker.net/Sharedaction?code=04393db9-f4bc-4871-7fb6-08db2506d1ed

**Comment by lmk123** [comment]
这个触及到我的盲区了，它不是用我所熟悉的语言开发的 :joy:

ChatGPT 慢是因为划词翻译的 ChatGPT 目前不支持流式输出，所以感觉上会慢，以后的版本会加入流式输出；

DeepL 这个我还真不了解它是怎么做到的，不过市面上调用 DeepL 接口的虽然快但一般不太稳定，划词翻译属于比较稳定的了。

**Comment by peilonia** [comment]
划词翻译美观、可折叠，只要知道了划词翻译，还是会选择划词翻译。

@lmk123
