### ISSUE TITLE
控制台报Minified React error错误时，划词翻译不生效

### ISSUE THREAD

**Issue by syunaht** [hcfyapp/crx-selection-translate#1794]
## 基本信息

划词翻译版本：v10.1.1
浏览器版本：115.0.1901.183
操作系统：Win1122621.1992

## 重现问题的步骤

打开[测试网站](https://maxroll.gg/lost-ark/build-guides/glaivier-chaos-dungeon-cube-guide)
经过多次Ctrl+F5，发现偶尔失效偶尔正常运行，且报错失效的几率较高，功能失效包括：无法划词翻译、无法自动翻译剪贴板文字（成功复制后独立窗口无响应）

控制台未报`Minified React error #423`错误，正常运行
![Snipaste_2023-07-23_13-51-52](https://github.com/hcfyapp/crx-selection-translate/assets/35628460/522f467f-d810-4197-a1c6-9f691958db56)

控制台报错，划词翻译失效
![Snipaste_2023-07-23_13-52-08](https://github.com/hcfyapp/crx-selection-translate/assets/35628460/50699a2f-8edb-47d4-91cd-d12a3148caf5)

**Comment by lmk123** [comment]
经确认跟 #1689 是同一个问题
