### ISSUE TITLE
希望全文翻译像chrome右键全文翻译一样，翻译完成后 链接还能点击

### ISSUE THREAD

**Issue by helloktity** [hcfyapp/crx-selection-translate#1795]
目前的全文翻译，如果网页文字中本身是点击链接，翻译后也会变成文字，而不是点击链接，
如果使用chrome的右键 翻译成中文 则会保留原网页的 点击链接， 希望咱们的也能这么智能，谢谢！

**Comment by lmk123** [comment]
感谢反馈！目前确实存在这一问题，我会在未来对此进行改进
