### ISSUE TITLE
翻译按钮隐藏

### ISSUE THREAD

**Issue by DreamcatcherGJ** [hcfyapp/crx-selection-translate#1796]
**希望可以隐藏翻译按钮，且不直接弹出翻译结果**
大多数场景下划词是为了复制并不需要翻译，翻译按钮展示会显得多余。
现在的翻译按钮可以不展示，但会直接弹出翻译结果，并不是我想要的。

**你想要如何解决你的问题？**
我希望可以单独出个隐藏翻译按钮的开关，我仅使用快捷键翻译。

**Comment by lmk123** [comment]
在划词翻译设置 - 网页划词翻译 中勾选【在所有网站中禁用网页划词】即可
