### ISSUE TITLE
支持配置 Tesseract OCR 默认的语言

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1797]
**没有这个功能（改进）的时候，你遇到了什么问题？**
默认不是中文，导致 OCR 使用很不方便

**你想要如何解决你的问题？**
如题

**Comment by lmk123** [comment]
其实我很早以前就想过要改进这一场景，但是一直没开发 :joy: 见 #1129 应该是能满足你的需求的
