### ISSUE TITLE
gpt3.5的key的填写位置

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [hcfyapp/crx-selection-translate#1799]
**没有这个功能（改进）的时候，你遇到了什么问题？**
![image](https://github.com/hcfyapp/crx-selection-translate/assets/59086082/f388539e-b034-4c94-8d74-9adc6abc8537)

**你想要如何解决你的问题？**
因为这种填key一般是填一次可能就不动了，但是gpt由于防火墙原因，可能经常会换第三方的域名之类的，我是第二次填key了，又找了好久
我建议把服务申请 补充成(服务申请api填写之类的)
或者把填写gpt域名的位置补充上一个key的填写

**Comment by lmk123** [comment]
好的，我会在这里给个明确的提示 + 跳转
