### ISSUE TITLE
 网页全文翻译 - 译文样式: 引用 文本默认颜色异常

### ISSUE THREAD

**Issue by dousybox** [hcfyapp/crx-selection-translate#1800]
## 基本信息

划词翻译版本：
  划词翻译 v10.1.2
浏览器版本：
  Microsoft Edge
  版本 114.0.1823.43 (正式版本) (64 位)
操作系统：
  Windows 10

## 重现问题的步骤

1. 完整设置菜单 - 外观 - 网页全文翻译 - 译文样式 : 引用

### 预期行为
译文文本框字体颜色为网页默认配置色

### 实际行为
译文文本框字体颜色为硬编码的白色

### 补充信息
css 选择器 .__hcfy-result-comparison__ hcfy-result-content 中的样式规则写死了白色.
{
  color: var(--hcfy-result-text-color, white);
}
选择其他几个译文样式默认 unset.

**Comment by lmk123** [comment]
好细心！下个版本就改
