### ISSUE TITLE
全文翻译的时候部分段落无法翻译完全

### ISSUE THREAD

**Issue by flyfishsn** [hcfyapp/crx-selection-translate#1801]
在pubmed或者其他论文网站用全文翻译的时候，部分段落无法翻译完全，下方是一个例子：

> Periodontitis (PD) is an inflammatory illness of the oral cavity caused by bacterial infection of the periodontal tissue, leading to the resorption of alveolar bone and tooth loss eventually ([8](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8825874/#B8)). PD is one of the most common chronic inflammatory diseases which affects 46% of the United States population according to the National Health and Nutrition Examination Survey and severe PD affect 10-15% of the population globally ([9](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8825874/#B9), [10](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8825874/#B10)). PD can be classified as the Grade C periodontitis, known as aggressive periodontitis (AgP) in 1999 classification and a slowly progressive form of periodontitis which is formerly known as chronic periodontitis (CP) ([11](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8825874/#B11)). AgP is a severe and early-onset form of PD with a high progression rate and a prevalence of ~0.1% ([12](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8825874/#B12)). CP is the more frequent phenotype, affecting an older population with a slow disease progression. PD is reported to be associated with several diseases, including stroke ([13](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8825874/#B13)), cardiovascular disease ([14](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8825874/#B14)), and pneumonia ([15](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8825874/#B15)).
牙周炎（PD）是由细菌感染牙周组织引起的口腔炎症性疾病，最终导致牙槽骨吸收和牙齿脱落(8)。牙周炎是最常见的

It has long been recognized that there are significant parallels between PD and arthritis. Inflammatory cytokines such as tumor necrosis factor (TNF) and interleukin-6 (IL-6), as well as initial activation of the innate immune system play a crucial role in both

**Comment by lmk123** [comment]
我使用 DeepL 全文翻译了 https://pubmed.ncbi.nlm.nih.gov/34129956/  这个网页，没有出现你反馈的这种情况。

麻烦你重新开一个 issue，确保按照要求填写了具体的重现步骤（划词翻译版本、浏览器版本、具体是在哪个网址、使用的哪个翻译服务等），我需要能重现你的问题，才能解决 :joy:
