### ISSUE TITLE
插件开启时不能通过Ctrl+C复制文字到外部应用

### ISSUE THREAD

**Issue by Gujielangtu** [hcfyapp/crx-selection-translate#1804]
## 基本信息

划词翻译版本：V10.1.0
浏览器版本：114.0.1823.43（正式版本）（64位）
操作系统：win 10 专业版 21H2

## 重现问题的步骤

1. 我也不确定这是不是bug，或许就是这么设计的。就是我在开启翻译插件之后，想要通过Ctrl+C复制一些文字或者网页的网址的时候，翻译插件会对复制的文字进行翻译，这个是正常的功能，感觉不太正常的地方就是我到外部应用（包括浏览器内部搜索引擎搜索）无法粘贴，或者粘贴的是上一次正常复制的文字；
2. 当我关闭插件，上述问题就解决了；其它解决办法就是通过鼠标右键复制；关闭插件或者使用鼠标复制很不方便，希望改进一下。

**Comment by lmk123** [comment]
我没法重现你的问题 :joy: 

另外，可否展开说一下这个部分：“就是我在开启翻译插件之后，想要通过Ctrl+C复制一些文字或者网页的网址的时候，翻译插件会对复制的文字进行翻译”

**Comment by lmk123** [comment]
因为划词翻译是没有一按下 Ctrl + C 就自动翻译的功能的，即使是独立翻译窗口也是需要先 Ctrl + C，再按下【打开独立翻译窗口】的快捷键才会翻译的

**Comment by Gujielangtu** [comment]
> 因为划词翻译是没有一按下 Ctrl + C 就自动翻译的功能的，即使是独立翻译窗口也是需要先 Ctrl + C，再按下【打开独立翻译窗口】的快捷键才会翻译的

具体我也不太清楚，我电脑上是我在网页上按下Ctrl+C之后，这个插件就自动翻译了。我专门录了屏幕，并找了能够显示键鼠操作的软件，方便的话可以查看一下视频确认一下。L Ctrl为左侧Ctrl键
视频链接如下：
【划词翻译故障，借用平台传一下视频】 https://www.bilibili.com/video/BV1rV4y1e7Sy/?share_source=copy_web&vd_source=2a57642407a3a19f18163009170866f2

**Comment by Gujielangtu** [comment]
新发现，键鼠操作显示，一直有个F22操作按下，不太清楚是不是跟这个有关，实体按键中也没有这个按键。
....
好像跟这个没啥关系，现在不显示F22了，没有改变。

**Comment by lmk123** [comment]
很感谢你提供视频，对我排查问题很有帮助！我仔细看过了，我的猜测如下：

你是不是在键盘快捷键里将划词翻译的【翻译选中的文本】设为了 `Ctrl + C`，所以才会出现按下复制快捷键的同时也触发了翻译的情况

如果是的话，那么这个快捷键会取代原本 `Ctrl + C` 默认的复制操作，也就是它变成了划词翻译的翻译快捷键，不再复制文本到剪切板了。你可以清除这个快捷键之后再试试能不能复制文本到外部应用

如果不是以上情况，那么我也想不出其它可能了 :joy:

**Comment by Gujielangtu** [comment]
> 很感谢你提供视频，对我排查问题很有帮助！我仔细看过了，我的猜测如下：
> 
> 你是不是在键盘快捷键里将划词翻译的【翻译选中的文本】设为了 `Ctrl + C`，所以才会出现按下复制快捷键的同时也触发了翻译的情况
> 
> 如果是的话，那么这个快捷键会取代原本 `Ctrl + C` 默认的复制操作，也就是它变成了划词翻译的翻译快捷键，不再复制文本到剪切板了。你可以清除这个快捷键之后再试试能不能复制文本到外部应用
> 
> 如果不是以上情况，那么我也想不出其它可能了 😂

根据上述描述，我查看了下划词翻译的快捷键，确实是【翻译选中的文本】的快捷键是Ctrl+C，（我不记得有设置这个快捷键），把快捷键改了之后，确实能够正常复制了，问题解决了，感谢。

**Comment by lmk123** [comment]
以后遇到问题了也欢迎反馈～
