### ISSUE TITLE
我希望能够显示单词的完整信息

### ISSUE THREAD

**Issue by bails404** [hcfyapp/crx-selection-translate#1805]
[现状]
目前在网页中单击一个单词，只能够看到它的中文翻译，但这个中文意思有可能并不是我想要的，而且我还需要知道这个单词发音、词性、更多的意思。
在使用 Google 与BiYing 时有时能够显示读音，但由于网络原因，大部分情况下我使用的是百度，以上问题也是在百度翻译的过程中遇到的。

[需求]
我希望能够在选中单词后，能够看到该单词的读音、词性、多个意思。我不知道现有功能中是否有满足我需求的功能，我没有找到可配置的位置，如果有请告知我。

**Comment by lmk123** [comment]
百度翻译接口仅仅会在使用【尊享版】的时候才提供单词的完整信息，而尊享版需要企业资质。

这也是为什么我会单独加入必应词典的原因，目前必应词典是能完整显示单词信息的，如果你不能用必应词典的话，那就没办法了 :joy:
