### ISSUE TITLE
DeepL 全文翻译的时候部分段落无法翻译完全

### ISSUE THREAD

**Issue by flyfishsn** [hcfyapp/crx-selection-translate#1806]
解决方案见 https://hcfy.app/docs/faqs/deepl-limit

--------------------------

## 基本信息

划词翻译版本：10.1.2
浏览器版本：Microsoft Edge  版本 115.0.1901.200 (正式版本) (64 位)
操作系统：windows10企业版LTSC

## 重现问题的步骤

1.https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10368999/   DeepL网页全文翻译，双语对照

### 预期行为
网页全文段落翻译双语对照
### 实际行为
2.1. Data sources中划词翻译9.8.1是第二段不翻译，升级到10.1.2是第一段不翻译

> This meta-analysis was performed according to the Preferred Reporting Items for Systematic Reviews and Meta-Analyses (PRISMA) guidelines published in 2021. We systematically conducted an electronic literature retrieval to search all available studies published up to July 2022 that were related to the correlation between DKK-1 serum levels and AS. The online searchable literature libraries included Embase, PubMed, Web of Science, WANFANG DATA, VIP, and the China National Knowledge Infrastructure (CNKI). Our search terms included ankylosing spondylitis, AS, DKK-1, Dickkopf-1, and Dickkopf-Related Protein 1, using subject terms and keywords. Inclusion criteria for the study were as follows: (1) the study was an observational study; (2) cases were patients with AS diagnosed by clear diagnostic criteria, and controls were healthy participants; (3) the study provided data on serum DKK-1 levels in AS patients and controls, such as mean and standard deviation (mean ± SD) or mean and standard error of the mean (mean ± SEM) or median and interquartile range (median (IQR)); (4) the article was written in English or Chinese. Exclusion criteria for the study were as follows: (1) the study was a conference abstract, review, meta-analysis, etc.; (2) the study had no sufficient data; (3) the study was based on animal models or only PBMCs; (4) the study used duplicate data. Moreover, references to the included literature and related reviews were searched to supplement any relevant studies.
本荟萃分析是根据 2021 年发布的《系统综述和荟萃分析首选报告项目》（Preferred Reporting Items for Systematic Reviews and Meta-Analyses，PRISMA）指南进行的。我们系统地进行了电子文献搜索
Single-nucleotide polymorphisms (SNPs) associated with DKK-1 were screened from genome-wide association studies (GWAS) with 21,758 individuals as instrumental variables (IV), including 13, 102 756 variant loci ([32](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10368999/#B32)). SNPs associated with the risk of AS were extracted from a European population study, which included 1,476 AS cases and 386,2[33](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10368999/#B33) controls. The GWAS was derived from the exome sequencing data of the UK Biobank (UKB) Exome Sequencing Consortium, an organization that concentrates on each protein-coding gene in the genome by examining the exome sequences of 454,787 UKB participants (33). All data were downloaded from the publicly available GWAS Catalog database at https://www.ebi.ac.uk/.
与 DKK-1 相关的单核苷酸多态性（SNPs）是从以 21,758 人为工具变量（IV）的全基因组关联研究（GWAS）中筛选出来的，包括 13,102,756 个变异位点（32）。与强直性脊柱炎风险相关的 SNPs 来自一项欧洲人群研究，其中包括 1,476 例强直性脊柱炎病例和 386,233 例对照。GWAS来自英国生物库（UKB）外显子组测序联盟（UKB Exome Sequencing Consortium）的外显子组测序数据，该组织通过检查454787名英国生物库参与者（33）的外显子组序列，集中研究基因组中的每个蛋白编码基因。所有数据均从 https://www.ebi.ac.uk 公开的 GWAS Catalog 数据库下载。

### 补充信息

升级和重新翻译都不行

**Comment by lmk123** [comment]
看样子是 DeepL 最近做了限制，如果不登陆 DeepL 账号则只能翻译 1500 个字符，登陆之后才能翻译 5000 个，如下图：

<img width="1393" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/c9aace6b-d098-4baf-aca6-f0ccefd70fc6">

**Comment by lmk123** [comment]
我试过了，登录账号之后就正常了。我会发个公告说明这一情况。

**Comment by flyfishsn** [comment]
应该不是，同样的操作
https://www.frontiersin.org/articles/10.3389/fimmu.2023.1174656/full
这篇论文中的25 Statistical analyses的第二段不翻译，另外两段翻译不完全

> To test for causal effects of exposure on outcome, we performed MR analyses using five methods, namely inverse variance weighting (IVW) ([26](https://www.frontiersin.org/articles/10.3389/fimmu.2023.1174656/full#B26)), weighted median ([27](https://www.frontiersin.org/articles/10.3389/fimmu.2023.1174656/full#B27)), MR-Egger ([28](https://www.frontiersin.org/articles/10.3389/fimmu.2023.1174656/full#B28)), Wald Ratio(for IL-8, because only one SNP was available), and MR pleiotropic residuals and outliers (MR-PRESSO) ([29](https://www.frontiersin.org/articles/10.3389/fimmu.2023.1174656/full#B29)). These five methods make different assumptions and use different strategies to deal with IVs with horizontal pleiotropy effects. The IVW method relies on the assumption that there is no pleiotropy and assumes that all SNPs are valid genetic tools ([26](https://www.frontiersin.org/articles/10.3389/fimmu.2023.1174656/full#B26)). The weighted median method assumes that at least 50% of the IVs are valid ([27](https://www.frontiersin.org/articles/10.3389/fimmu.2023.1174656/full#B27)). The MR-Egger method provides causal estimates even if all IVs are invalid ([28](https://www.frontiersin.org/articles/10.3389/fimmu.2023.1174656/full#B28)). The MR-PRESSO method detects possible IV outliers by global testing and provides unbiased causal estimates by removing the identified outliers ([29](https://www.frontiersin.org/articles/10.3389/fimmu.2023.1174656/full#B29)).
为了检验暴露对结果的因果效应，我们采用了五种方法进行 MR 分析，即反方差加权法（IVW）（26）、加权中位数法（27）、MR-Egger 法（28）、Wald 比值法（对于 IL-8，因为只有一个 SNP 可用）以及 MR 多向残差和异常值法（MR-PRESSO）（29）。这五种方法做出了不同的假设，并采用不同的策略来处理具有水平的 IV

Heterogeneity in causal estimates among instrumental variables indicates a potential violation of the assumptions of MR analysis. The Cochran’s Q test was used to examine the heterogeneity in causal estimates, and we used both the causal estimates of fixed effects IVW method and MR-Egger regression to detect heterogeneity. The heterogeneities were quantified using Cochran’s Q statistics and a P-value smaller than 0.05 was considered significant heterogeneity. To assess the potential pleiotropic effects of instrumental variables, the MR-Egger regression was used. The directional horizontal pleiotropy in the causal estimates may be indicated by the intercept term in MR-Egger regression. Additionally, we performed a leave-one-out analysis where we excluded each SNP in turn and then ran MR analysis on the remaining SNPs in order to detect potentially outlying instrumental variables.
因果关系的异质性

All results are expressed as effect size (ES) and corresponding 95% confidence intervals (CI). All statistical analyses were two-sided. A p-value was considered statistically significant when less than 0.006 (0.05/8 adjusted with the Bonferroni method) and was considered suggestively significant between 0.006 and 0.05. All analyses were performed using the TwoSampleMR and MR-PRESSO packages in R version 4.2.2.
所有结果均以效应大小 (ES) 和相应的 95% 置信区间 (CI) 表示。所有统计分析均为双侧分析。当 p 值小于 0.006 时（用 Bonferroni 方法调整为 0.05/8），则认为具有统计学意义；当 p 值介于 0.006 和 0.05 之间时，则认为具有提示意义。所有分析均使用 R 4.2.2 版中的 TwoSampleMR 和 MR-PRESSO 软件包进行。

**Comment by lmk123** [comment]
登陆账号之后需要完全重启浏览器，划词翻译才会使用登陆后的 DeepL，你重启下浏览器试试

**Comment by lmk123** [comment]
我试过了，是正常的

<img width="601" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/b450eb9f-a7d3-45ec-80a8-db74ac4cf995">

**Comment by flyfishsn** [comment]
应该是重启浏览器的问题，一开始没登录重启浏览器后翻译还是同样的问题，登陆重启后就可以了

**Comment by yonee77** [comment]
富文本官网也是翻译不全的
