### ISSUE TITLE
使用积分并启用的情况下，无法使用有道翻译

### ISSUE THREAD

**Issue by amchii** [hcfyapp/crx-selection-translate#1807]
## 基本信息

划词翻译版本：10.1.2
浏览器版本：chrome 15.0.5790.170（正式版本） (arm64)
操作系统：macOS 13.5

使用积分的情况下，无法使用有道翻译：
![image](https://github.com/hcfyapp/crx-selection-translate/assets/26922464/1a5ba6dd-c31d-4b1a-b558-8a32dd5505e4)
积分仍有余额
![image](https://github.com/hcfyapp/crx-selection-translate/assets/26922464/e321a8a2-8b0d-48b1-877e-b3f19bfec01b)
昨天是正常的，今天升级了Chrome

**Comment by lmk123** [comment]
我的有道翻译账户欠费了 :joy: 刚才已经充了值，应该已经恢复了
