### ISSUE TITLE
【v10.2.1 已解决】DeepL 报错“找不到.lmt__translations_as_text”

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1808]
## 基本信息

划词翻译版本：v10.1.2
浏览器版本：Chrome 115
操作系统：macOS

## 重现问题的步骤

1. 使用DeepL 翻译任意文本
2.
3.

### 预期行为
有翻译结果
### 实际行为
报错

**Comment by lmk123** [comment]
奇怪的是这个问题目前似乎只有我自己遇到了，没有收到任何其他用户的反馈。可能是 DeepL 目前对这个改动只进行了小部分的灰度更新，然后恰好我被灰度到了。

**Comment by LimingZhangBj** [comment]
same for me

**Comment by lmk123** [comment]
> same for me

@LimingZhangBj  你目前是第二个反馈的 :joy: 我都不知道这个问题该不该修，我怕修了之后对没这个问题的人产生影响 :joy:

**Comment by seafood2017** [comment]
我也遇到了, windows11 浏览器Edge

**Comment by RubiksCubei** [comment]
公司电脑遇到了这个问题了。但家用电脑没有遇到这个问题。   windows10 chrome浏览器 10.1.2插件版本

**Comment by lmk123** [comment]
下个版本 v10.2.1 解决了这个问题，预计在这周日前发布。

**Comment by lmk123** [comment]
v10.2.1 的离线安装包已上传，希望大家都能帮我测试一下，并在这里反馈是否有解决你的问题。 https://hcfy.app/docs/install/#offline

**Comment by seafood2017** [comment]
win11 Edge浏览器 已解决
