### ISSUE TITLE
ChatGPT返回418错误

### ISSUE THREAD

**Issue by Seraphli** [hcfyapp/crx-selection-translate#1809]
## 基本信息

划词翻译版本：v10.1.2
浏览器版本：Version 115.0.5790.170 (Official Build) (64-bit)
操作系统：Manjaro

## 重现问题的步骤

1. 使用ChatGPT进行翻译

### 实际行为

![image](https://github.com/hcfyapp/crx-selection-translate/assets/1586755/8ba13a90-efbb-48ec-9f6e-098ccd1246d8)

### 补充信息

ChatGPT本身页面打开，也尝试过同样的翻译片段，没有问题。

**Comment by ghost** [comment]
Windows firefox 同样的问题

**Comment by lmk123** [comment]
我自己试了下，是正常的 :joy:

<img width="572" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/892ae196-c0e0-45a6-a8de-e500895a9d36">

**Comment by lmk123** [comment]
猜测跟梯子有关

**Comment by Seraphli** [comment]
能正常访问ChatGPT的情况下，还会和梯子有关吗？不是走相同的代理规则的吗？

**Comment by lmk123** [comment]
由于 ChatGPT 网页版接口大幅度提升了逆向难度，ChatGPT 的免费试用方式无法再做到扩展程序里的。因此，关闭所有跟 ChatGPT 免费试用方式有关的 issue。
