### ISSUE TITLE
如果无翻译结果，希望可以不显示这个引擎的窗口，只显示有翻译结果的窗口。

### ISSUE THREAD

**Issue by ruinmi** [hcfyapp/crx-selection-translate#1811]
![image](https://github.com/hcfyapp/crx-selection-translate/assets/61036380/f07d5ef6-101b-4367-b36c-44aa99490aef)

**没有这个功能（改进）的时候，你遇到了什么问题？**
`  因为bing翻译不能翻译句子，然后就显示无翻译结果。
`

**你想要如何解决你的问题？**
```
  方案1：
  希望翻译句子时，直接就不使用bing，也可以提供一个设置：
  1.针对翻译句子使用的引擎
  2.针对翻译单词使用的引擎

  方案2：
  希望可以设置如果某个引擎无翻译结果，可以不显示这个引擎的窗口，只显示有翻译结果的窗口，当所有都无翻译结果都没有的时候才显示无翻译结果。

```

**Comment by ruinmi** [comment]
作者怎么不理我

**Comment by lmk123** [comment]
> 作者怎么不理我

因为我偶尔会看漏一些 issue。。

放心，你提出的“方案 1”已经在开发计划当中了
