### ISSUE TITLE
DeepL 在划词翻译中显示找不到 source 的语种下拉框

### ISSUE THREAD

**Issue by pxy0592** [hcfyapp/crx-selection-translate#1812]
## 基本信息

划词翻译版本：v10.1.2
浏览器版本：Mozilla Firefox 116.0.2
操作系统：macOS 13.4.1

## 重现问题的步骤

1. 在划词翻译的快捷设置中选中DeepL
2. 翻译目标语言设置成中文(简体)
3. 在划词翻译中翻译英文单词，比如: excerpts

### 预期行为
显示翻译结果

### 实际行为
DeepL显示找不到 source 的语种下拉框
![image](https://github.com/hcfyapp/crx-selection-translate/assets/7930555/5460904c-fc17-4c7f-9ca3-6ef750e134cb)

### 补充信息
n/a

**Comment by lmk123** [comment]
跟 #1808 是同一个问题，将在下个版本修复

**Comment by lgdsgd2000** [comment]
@lmk123 这个问题又出现了，firefox和edge都有，均为最新版

**Comment by lmk123** [comment]
这个报错是网络加载错误导致的，重试几次就好
