### ISSUE TITLE
百度翻译音标显示

### ISSUE THREAD

**Issue by okfy** [hcfyapp/crx-selection-translate#1815]
**没有这个功能（改进）的时候，你遇到了什么问题？**
(1) 默认谷歌翻译时，是韦氏音标，但是一直以来，像牛津 、朗文字典以及教学课本使用DJ音标。所以很多人都习惯用DJ音标，谷歌翻译的韦氏音标读起来非常不习惯。
(2) 申请了百度翻译的密钥，添加到划词插件中，没有音标显示
**你想要如何解决你的问题？**
(1)  划词插件接入百度翻译、有道翻译时，能够显示出音标  （他们应该是DJ音标，而不是韦氏音标）。

**Comment by lmk123** [comment]
原来 DJ 音标是这个意思……

百度翻译有且仅有尊享版才提供音标，所以除非你自己开一家公司并在申请密钥时提供公司信息，否则百度翻译就不提供音标。它不提供那我当然也没法变出来 :joy:

所以，划词翻译特地增加了必应词典，它的音标应该就是你说的 DJ 音标。
