### ISSUE TITLE
全局快捷键无法使用

### ISSUE THREAD

**Issue by RubiksCubei** [hcfyapp/crx-selection-translate#1824]
## 基本信息
划词翻译版本：10.2.1
浏览器版本：116.0.5845.111
操作系统：windows 10 22H2

### 补充信息
已经勾选谷歌浏览器的【关闭Google Chrome后继续运行后台应用】
关闭谷歌浏览器后，任务托盘内无谷歌图标，全局快捷键无法使用。

**Comment by detiam** [comment]
我也遇到了这个问题，有什么解决办法吗？

**Comment by lmk123** [comment]
这个问题属于谷歌浏览器的问题，即关闭 Chrome 后它并没有保留在后台 :joy:

目前的临时方案就是不要关闭 chrome，而是最小化它

**Comment by detiam** [comment]
> 这个问题属于谷歌浏览器的问题，即关闭 Chrome 后它并没有保留在后台 😂
> 
> 目前的临时方案就是不要关闭 chrome，而是最小化它

是吗，不过隔壁沙拉查词似乎没问题，关了chrome窗口也可以呼出

**Comment by lmk123** [comment]
今天有用户反馈了同样的问题，我才意识到问题出在哪 :joy:

在勾选浏览器的“关闭 Google Chrome 后继续运行后台应用”选项后，还需要进入划词翻译的设置页勾选“让划词翻译在后台持续运行”，但是由于一个 bug，这个选项目前是找不到的。

我会在下个版本中修复这个 bug，后续进展可以关注 #1878

**Comment by lmk123** [comment]
此问题已解决，等我发布 v10.4.2 之后就可以按照这里的步骤开启了：https://hcfy.app/docs/guides/extra#close-browser
