### ISSUE TITLE
内置pdf阅读器和浏览器pdf在划词翻译设置在所有网站可用时冲突

### ISSUE THREAD

**Issue by ElsaScarlet** [hcfyapp/crx-selection-translate#1825]
## 基本信息

划词翻译版本：10.1.2
浏览器版本：星愿浏览器7.1.1000.2008 ( Chromium: 80.0.3987.163 Res: 2006.405 ) 
操作系统：win10

## 重现问题的步骤

1.划词翻译右键-“可读取和更改数据的网站”选择“所有网站”
2.打开任一网站pdf，会发现跳转内置pdf阅读器不显示pdf，且导致浏览器的自带pdf阅读工具也不能显示
3.划词翻译右键-“可读取和更改数据的网站”选择“当您点击此扩展时”
4.则浏览器自带pdf阅读器可以运行

### 预期行为
1.在划词翻译设置为“所有网站”时候，点击pdf跳转内置pdf阅读器或浏览器自带pdf阅读工具都可以

### 实际行为
不跳转且与自带pdf阅读器冲突，导致pdf无法观看。调整成点击此拓展时可以看pdf，但是翻译pdf又要一次一次点，很麻烦。

**Comment by lmk123** [comment]
划词翻译目前只对 Chrome、Edge、Firefox 三种浏览器做了全面兼容和测试，所以我用 Chrome 116 试了一下你的问题

首先我确认了我的划词翻译权限是【所有网站】，然后我在 https://hcfy.app/docs/guides/pdf 里点了这条 pdf 链接 https://arxiv.org/pdf/2104.13030.pdf 划词翻译正常在内置 PDF 阅读器中打开了它

> 会发现跳转内置pdf阅读器不显示pdf

我猜测是因为你的 Chrome 版本太低了的缘故。内置 PDF 阅读器目前应该是要 Chrome 85 及以上才能正常使用

**Comment by lmk123** [comment]
你可以在划词翻译设置页的左侧菜单里找到【PDF】，然后取消勾选【自动打开 PDF】，这样就会用浏览器自带的 PDF 阅读器打开
