### ISSUE TITLE
在Remix官方文档划词翻译不生效(准确的说是不出现小悬浮翻译按钮图标)

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [hcfyapp/crx-selection-translate#1826]
## 基本信息

划词翻译版本：10.1.2
浏览器版本： 116.0.5845.110
操作系统：macOs12.5.1

## 重现问题的步骤

![image](https://github.com/hcfyapp/crx-selection-translate/assets/59086082/bc532978-494e-4a64-8bcb-f1631864ebcc)
![image](https://github.com/hcfyapp/crx-selection-translate/assets/59086082/0e9b3a4b-b852-452f-ace9-56e6c27539e8)

**Comment by lmk123** [comment]
无法重现。你可以试试关闭所有其他插件只保留划词翻译，如果还是不行，那么再卸载了重装试试。我猜测要么是跟其他插件冲突了，要么就是你的划词翻译设置里设置了不在 remix 网站里显示。

如果仍有疑问，欢迎继续留言

<img width="248" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/65b6b25a-7d11-4ec0-bfdf-bf2bcccd72c2">

**Comment by duoluodexiaoxiaoyuan** [comment]
> 无法重现。你可以试试关闭所有其他插件只保留划词翻译，如果还是不行，那么再卸载了重装试试。我猜测要么是跟其他插件冲突了，要么就是你的划词翻译设置里设置了不在 remix 网站里显示。
> 
> 如果仍有疑问，欢迎继续留言
> 
> <img alt="image" width="248" src="https://user-images.githubusercontent.com/5035625/264089576-65b6b25a-7d11-4ec0-bfdf-bf2bcccd72c2.png">

大佬问个问题，我设置了剪切板内容自动翻译，然后勾选了以后默认不提示。但是我发现剪切板内容会一直在然后就会一直消耗gpt,所以我想改成默认不翻译，我设置了里面找了半天没找到在哪里

**Comment by lmk123** [comment]
在划词翻译设置 - 【翻译面板】-【自动化】里

**Comment by duoluodexiaoxiaoyuan** [comment]
> 在划词翻译设置 - 【翻译面板】-【自动化】里

感谢回复，我发现重开浏览器以后这个东西就又出现了，好像没有存到本地，按照我的理解应该是点击一次就一直生效的。

**Comment by lmk123** [comment]
确实是点一次就一直生效的。我试了一下将选项从【询问】改为了【不翻译】，然后就没再出现翻译提示了。

如果你觉得这是个 bug，麻烦新开一个 issue，详细描述一下重现步骤，比如具体是哪个选项之类的

**Comment by duoluodexiaoxiaoyuan** [comment]
> 确实是点一次就一直生效的。我试了一下将选项从【询问】改为了【不翻译】，然后就没再出现翻译提示了。
> 
> 如果你觉得这是个 bug，麻烦新开一个 issue，详细描述一下重现步骤，比如具体是哪个选项之类的
感谢回复，因为我昨天是找不到，然后今天打开又询问了，刚才我又操作了一遍，是正常的，我后面再观察一下
