### ISSUE TITLE
网页翻译遗漏内容

### ISSUE THREAD

**Issue by xiaowhang** [hcfyapp/crx-selection-translate#1827]
## 基本信息

划词翻译版本：v10.1.2
浏览器版本：edge 116.0.1938.62 (正式版本) (64 位)
操作系统：window11

## 重现问题的步骤

1.打开网址https://vjudge.csgrandeur.cn/problem/HDU-2602
2.开启网页全文翻译

### 预期行为

全文翻译（至少题目内容进行翻译）

### 实际行为

题目信息全都没有翻译

### 补充信息

题目的译文并没有出现在任何地方

**Comment by lmk123** [comment]
经确认跟 #1219 属于同一个问题

正文内容在 iframe 里，链接是 https://vjudge.csgrandeur.cn/problem/description/1462486368?1693510919000
