### ISSUE TITLE
阿里专业版异常，网页翻译http翻译问题

### ISSUE THREAD

**Issue by yonee77** [hcfyapp/crx-selection-translate#1828]
## 基本信息

划词翻译版本：v10.2.1
浏览器版本：firefox 117
操作系统：win11

## 重现问题的步骤，有以下两个问题
网站https://www.youtube.com/watch?v=6iv2cIAFOTI

1.网页翻译，能否不要翻译http链接
_BLUE BARDOT BIKINI - [https://www.zaful.com/floral-knotted-...]_
翻译成了
_蓝色BARDOT比基尼-https://www.zaful.com/碎花-..._

2.网页翻译，阿里专业版正常使用，独立窗口翻译，阿里专业版不正常，配置了同一个key

**Comment by lmk123** [comment]
> 网页翻译，阿里专业版正常使用，独立窗口翻译，阿里专业版不正常，配置了同一个key

为了方便管理，不同的问题最好分别开 issue，不然混在一起了很不容易捋清。麻烦新开一个 issue，描述一下“独立翻译窗口 阿里翻译专业版不正常”具体是怎么个不正常的表现，比如是报了什么错还是别的什么

> 网页翻译，能否不要翻译http链接

这个新功能有在考虑中了，未来会添加选项，允许用户自行设置什么样的内容可以不翻译
