### ISSUE TITLE
更改chatgpt翻译源后不登陆插件无法显示

### ISSUE THREAD

**Issue by honece** [hcfyapp/crx-selection-translate#1829]
## 基本信息

划词翻译版本：v10.2.1
浏览器版本：（chrome）116.0.5845.141
操作系统：windows10

## 重现问题的步骤

1. 右键全文翻译
2. 选择chatgpt
3. 出现"非会员每天只能使用 3 次网页全文翻译功能，成为会员即可解除此限制。"
4. 不登陆的话永远无法使用网页全文翻译

### 预期行为
正常翻译，点击X后可以正常显示插件框

### 实际行为
被固定在了chatgpt的翻译源，而且无法更改回来，点击X后就不会再显示正常的插件框
![right](https://github.com/hcfyapp/crx-selection-translate/assets/86614445/a12950d5-db01-4fb3-8e90-be0fef071f34)
![QQ截图20230904150544](https://github.com/hcfyapp/crx-selection-translate/assets/86614445/1feb0791-bbb1-41d2-8e7f-30437fbcc294)

**Comment by lmk123** [comment]
如这个提示所说，全文翻译功能是有免费使用限制的，如果你没有购买会员，那么每天只能使用 3 次，这跟你是否选择 ChatGPT 没有关系。

如果这不是你想表达的意思，欢迎继续补充，我会继续跟进。

**Comment by honece** [comment]
我是想说，我没有办法切换到别的翻译源了，整个翻译页面的功能没有了

**Comment by honece** [comment]
正常的翻译选项被那个框给抵消掉了，翻译选项就消失了

**Comment by lmk123** [comment]
全文翻译功能切换翻译源的选项仅仅影响全文翻译功能，你已经不能用全文翻译功能的话，也不需要再切换它吧。。

在网页上划词时的翻译源是单独的选项，切换全文翻译的翻译源并不会影响到它

**Comment by honece** [comment]
> 全文翻译功能切换翻译源的选项仅仅影响全文翻译功能，你已经不能用全文翻译功能的话，也不需要再切换它吧。。
> 
> 在网页上划词时的翻译源是单独的选项，切换全文翻译的翻译源并不会影响到它

可是我应该可以用google进行全文翻译啊，现在不让我切换，我找不到页面根本就不能全文翻译了

**Comment by honece** [comment]
或者我可以给您发个录屏？

**Comment by lmk123** [comment]
全文翻译功能的次数限制跟你选择哪个翻译源没有关系。无论你选择哪个翻译服务，只要使用满了 3 次就会弹这个提示

**Comment by honece** [comment]
哦，是这样啊....那好吧，有点先入为主以为是因为我切到了chatgpt才会有3次的限制
