### ISSUE TITLE
使用ChatGPT网页双语模式全文翻译译文位置与原文位置不匹配

### ISSUE THREAD

**Issue by hr567** [hcfyapp/crx-selection-translate#1830]
## 基本信息

划词翻译版本：v10.1.2
浏览器版本：MS Edge 116.0.1938.69
操作系统：MacOS 13.5.1 (22G90)

## 重现问题的步骤

1.打开英文网页（例如 https://lwn.net/Articles/943498/ ）
2.右键空白区域选择划词翻译网页全文翻译，模式选择双语
3.出现翻译文字与原文错位的情况

### 预期行为
翻译文字为对应位置原文的翻译。

### 实际行为
翻译文字为对应位置上一段或下一段的翻译。

### 补充信息

仅在使用ChatGPT进行全文翻译时出现该情况。反复（通常只需要一次）关闭网页全文翻译后重新进行网页全文翻译可以修复文字位置异常问题。

**Comment by lmk123** [comment]
感谢你的详细反馈！

确实可能会出现这个问题，但是实际上我没法修复 :joy:

 出现这个问题是因为 ChatGPT 给我的翻译后的文本没有严格按照“一个段落一行”的规则来提供。ChatGPT 作为一个对话式 AI 工具，经常会出现这种情况，其它不受控制的情况还有会自顾自的对某些名词进行多余的解释等等。

我目前确实不知道要怎么写 prompt 才能做到让 ChatGPT 严格执行“一个段落一行”的规则或者不做多余解释。如果你试出来了，可以提供给我，我会考虑作为默认 prompt。

**Comment by hr567** [comment]
哦哦，好的，感谢回复。理解问题出现在哪里了，我自己也研究一下如何调教ChatGPT让他能够更好地输出翻译结果。
