### ISSUE TITLE
为啥不能同步密钥？买了会员就是不想买次去平台查找这些ID

### ISSUE THREAD

**Issue by JXA-a** [hcfyapp/crx-selection-translate#1831]
**没有这个功能（改进）的时候，你遇到了什么问题？**
为啥不能同步密钥？买了会员就是不想买次去平台查找这些ID

**你想要如何解决你的问题？**
希望能有这个同步功能

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
比如，如果划词翻译无法添加 PDF 标记功能，那么至少允许我在别的 PDF 软件里进行划词翻译。

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。

**Comment by lmk123** [comment]
原因见 https://hcfy.app/docs/faqs/safe#safe-key
