### ISSUE TITLE
输入特定中文字符导致的窗口消失bug

### ISSUE THREAD

**Issue by SnowGuest** [hcfyapp/crx-selection-translate#1836]
## 基本信息

划词翻译版本： v10.1.2
浏览器版本：chrome 116.0.5845.187
操作系统：win11

## 重现问题的步骤

1. 打开插件
2. 输入”奖品“ 
3. 点击翻译

### 预期行为
成功翻译
### 实际行为
变成个白色框框
### 补充信息

这里是复现视频

https://github.com/hcfyapp/crx-selection-translate/assets/59474029/9d218ee2-d7ec-497b-93eb-fa53d770bcfc

**Comment by lmk123** [comment]
感谢反馈，跟 #1835 是同一个问题

**Comment by lmk123** [comment]
我刚才发布了 v10.2.3 尝试修复这个问题。v10.2.3 的离线安装包已上传到网盘 https://hcfy.app/docs/install/#offline

由于我无法重现这个问题，所以希望你能在使用之后给我一个反馈，让我确认问题确实修复了

**Comment by SnowGuest** [comment]
> 我刚才发布了 v10.2.3 尝试修复这个问题。v10.2.3 的离线安装包已上传到网盘 https://hcfy.app/docs/install/#offline
> 
> 由于我无法重现这个问题，所以希望你能在使用之后给我一个反馈，让我确认问题确实修复了

我发现了问题，似乎是我的浏览器VPN插件导致的无法返回谷歌翻译内容导致的崩溃问题，当我关闭VPN插件的时候则不会出现崩溃问题，我会尝试使用你发的离线包再次复现一遍

**Comment by lmk123** [comment]
好的，期待你的反馈

**Comment by SnowGuest** [comment]
> 好的，期待你的反馈

已经通过测试了，切换VPN节点开关，断网测试都通过了，暂时没有复现之前的bug，可以确认被解决了

**Comment by lmk123** [comment]
感谢你的反馈，如果之后又遇到了崩溃问题，麻烦尽快提交到这里，我会第一时间处理
