### ISSUE TITLE
谷歌翻译连挂梯子都用不了

### ISSUE THREAD

**Issue by Bill-Gets** [hcfyapp/crx-selection-translate#1837]
## 基本信息

划词翻译版本：10.1.2
浏览器版本：116.0.1938.81
操作系统：Windows 11

## 重现问题的步骤

1.随便在网页上划词
2.点击悬浮按钮

### 预期行为
划词翻译界面成功显示谷歌翻译翻译后的文本

### 实际行为
显示“远程服务器没有相应。”

### 补充信息
Google能打开，好奇为什么用不了了

**Comment by Bill-Gets** [comment]
原来是用了镜像地址，但是那三个镜像地址我挂梯子都用不了，关了镜像地址就能用了

**Comment by lmk123** [comment]
估计是这三个镜像地址屏蔽了国外 IP，我在公告里加个提醒
