### ISSUE TITLE
Edge浏览器点击划词翻译工具栏，输入英文翻译成中文回车之后自动关闭面板。

### ISSUE THREAD

**Issue by Barryzp** [hcfyapp/crx-selection-translate#1838]
## 基本信息

划词翻译版本：10.1.2
浏览器版本：Edge 116.0.1938.76 (正式版本) (64 位)
操作系统：Win 11

## 重现问题的步骤

1.
![image](https://github.com/hcfyapp/crx-selection-translate/assets/34881368/76acae9d-80b2-48db-851e-894d817a599b)

2.
![image](https://github.com/hcfyapp/crx-selection-translate/assets/34881368/e70bb75a-3843-4ed2-b081-c9e121ab78a6)

3.面板关闭，出现黑色小块
![image](https://github.com/hcfyapp/crx-selection-translate/assets/34881368/19a1a6cf-e5ae-4ed4-9d45-47bc063570f3)

### 预期行为
生成翻译结果
### 实际行为
面板关闭，

**Comment by FDrag0n** [comment]
macos edge也出现相同问题

**Comment by lmk123** [comment]
见 https://hcfy.app/blog/2023/09/13/ggcrash
