### ISSUE TITLE
Firefox 英翻中时窗口会消失，中翻英时没问题

### ISSUE THREAD

**Issue by everyx** [hcfyapp/crx-selection-translate#1840]
## 基本信息

划词翻译版本：划词翻译 v10.1.2
浏览器版本：117.0.1 (64 位)
操作系统：Arch Linux

## 重现问题的步骤

1. 任意网站，点击插件图标，并输入英文翻译

### 预期行为
窗口高度正常

### 实际行为
窗口高度变成 0

### 补充信息

[录屏 2023-09-15 09-50-30.webm](https://github.com/hcfyapp/crx-selection-translate/assets/1665522/01ba41e7-5a6e-4ba4-9be8-6ede718ab421)

**Comment by tangm421** [comment]
同上！

chrome (64bit)  117.0.5938.62/63 也有这种问题，只要系统剪贴板有内容或者在插件翻译窗口中翻译英译中点击翻译或者回车翻译窗口都会变成窄条，独立窗口则是变成全空白！中译英没问题


https://github.com/hcfyapp/crx-selection-translate/assets/26132858/afa34cdb-436a-48d4-9e15-2bc78333cb2b

**Comment by tangm421** [comment]
我的划词翻译版本是v10.1.2，已经确认是和 #1835 原因相同，只能等google商店的v10.2.3版本了
@everyx

**Comment by lmk123** [comment]
跟 #1835 是同样的问题，详细说明见 https://hcfy.app/blog/2023/09/13/ggcrash

google 商店的 v10.2.3 已通过审核

edge 和 firefox 的 v10.2.3 正在审核中
