### ISSUE TITLE
无法翻译role这个单词

### ISSUE THREAD

**Issue by deahui** [hcfyapp/crx-selection-translate#1842]
## 基本信息

划词翻译版本：v10.1.2
浏览器版本：95.0.4638.69
操作系统：win11

## 重现问题的步骤

打开浏览器翻译，输入role，点翻译就会变成这样，其它单词都行
![image](https://github.com/hcfyapp/crx-selection-translate/assets/24301844/62d455b1-f167-4e63-9093-05badd25491b)

独立窗口也会出现这个问题
我试了edge、360都这样

**Comment by lmk123** [comment]
https://hcfy.app/blog/2023/09/13/ggcrash
