### ISSUE TITLE
选中单个单词无法翻译

### ISSUE THREAD

**Issue by ShirahaneSuoh** [hcfyapp/crx-selection-translate#1843]
## 基本信息

划词翻译版本：v10.1.2
浏览器版本：Firefox 117.0.1 (64 位)
操作系统：windows 11

## 重现问题的步骤

1. 选中*一个*单词（即单个单词，包括a在内，其他单个字母或一段话没问题）
2. 点击弹出的翻译按钮
3. 翻译窗口出现后迅速消失
4. 选中文本后不再出现翻译按钮，刷新后才出现

### 补充信息

问题是突然出现的，在我卸载重装两次后也没有改变。在Chrome安装这个插件，没有这个问题。在Firefox隐私窗口只打开这个插件，仍然如此。可能与我在9月12日更新的firefox最新版本相关，但我并不确定。

**Comment by ShirahaneSuoh** [comment]
抱歉，之前没看到公告，应该是9月13日公告中提到的问题，但我根据“Firefox 手动更新的步骤”操作后，没有10.2.3的版本，在附加插件管理的显示是：
版本
10.1.2
上次更新
2023年9月16日

**Comment by lmk123** [comment]
火狐没法提供离线安装包，所以只能等它通过审核了😂大概10工作日，或者你先临时换用chrome
