### ISSUE TITLE
翻译弹窗在查看翻译的时候自动消失

### ISSUE THREAD

**Issue by oodzchen** [hcfyapp/crx-selection-translate#1845]
## 基本信息

划词翻译版本：v10.1.2
浏览器版本：Firefox 117.0.1
操作系统：openSUSE Tumbleweed (KDE X11)

## 重现问题的步骤

1. 点击扩展栏的划词翻译图标，显示弹窗
2. 翻译服务选择谷歌、yandex、必应
3. 输入“hawk”，按Enter

### 预期行为
显示翻译结果

### 实际行为
翻译结果还没显示出来，弹窗自动消失隐藏，但是能看到图标还是聚焦状态，弹窗的上边阴影还存在

### 补充信息

页面划词按钮翻译也遇到了同样的情况，比如我在[这个网页](https://www.postgresql.org/docs/current/tutorial-window.html)随便选中一个单词，出现翻译按钮，点击按钮后弹窗只是闪现了以下，看不到翻译结果。

我在该页面打开浏览器开发者工具，查看Console信息，在点击翻译按钮之后出现报错信息，如下

> TypeError: e.terms is undefined

今天开始看到的，之前都没有这些问题

**Comment by lmk123** [comment]
https://hcfy.app/blog/2023/09/13/ggcrash
