### ISSUE TITLE
无法使用, 报错 Cannot read properties of undefined (reading 'join')

### ISSUE THREAD

**Issue by lizehua-cn** [hcfyapp/crx-selection-translate#1848]
## 基本信息

划词翻译版本：
浏览器版本：chrome 117.0.5938.62
操作系统：mac 13.5.1

## 重现问题的步骤
最近使用的时候, 经常会报错, 

输入 aaa 翻译正常, 输入 stop 就报错

是因为系统/浏览器版本升级的原因吗

### 实际行为

<img width="1257" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/20222085/aab926a9-0428-405d-b918-ce8dcd045290">

![2023-09-18 17 03 15](https://github.com/hcfyapp/crx-selection-translate/assets/20222085/b6b667ed-1c5e-4b55-834a-d3473b70ed53)

### 补充信息

翻译短语正常, 随便一个单词却不行

**Comment by lizehua-cn** [comment]
### 谷歌翻译的问题, 不用谷歌就好了

**Comment by lmk123** [comment]
这是一个很值得重视的问题 :joy:

前两天由于谷歌翻译接口做了调整，在翻译单词时翻译接口没了 `terms` 字段，导致会报错 `Cannot read properties of undefined (reading 'terms')`，这个问题我已在 v10.2.3 中修复，关于此问题的详细情况见 https://github.com/hcfyapp/crx-selection-translate/issues/1835

 但是，你现在反馈谷歌翻译报了个新的错误 `reading 'join'`，这意味着谷歌翻译接口可能又做了别的变化。

希望你能点一下下面这个链接，浏览器会下载一个 json 文件，把 json 文件提交到这里，我需要看一下谷歌翻译接口在你这里具体返回了什么数据结构

https://translate.googleapis.com/translate_a/single?client=webapp&sl=auto&tl=zh-CN&dj=1&ie=UTF-8&oe=UTF-8&source=icon&dt=t&dt=bd&dt=qc&dt=rm&dt=ex&dt=at&dt=ss&dt=rw&dt=ld&q=stop&tk=160194.351997

**Comment by lizehua-cn** [comment]
好嘞 明天去公司试试，公司网自带VPN 可能返回数据会有一定差别
________________________________
发件人: lmk123 ***@***.***>
发送时间: Monday, September 18, 2023 11:15:31 PM
收件人: hcfyapp/crx-selection-translate ***@***.***>
抄送: 李泽华 ***@***.***>; State change ***@***.***>
主题: Re: [hcfyapp/crx-selection-translate] 无法使用, 报错 Cannot read properties of undefined (reading 'join') (Issue #1848)


这是一个很值得重视的问题 😂

前两天由于谷歌翻译接口做了调整，在翻译单词时翻译接口没了 terms 字段，导致会报错 Cannot read properties of undefined (reading 'terms')，这个问题我已在 v10.2.3 中修复，关于此问题的详细情况见 #1835<https://github.com/hcfyapp/crx-selection-translate/issues/1835>

但是，你现在反馈谷歌翻译报了个新的错误 reading 'join'，这意味着谷歌翻译接口可能又做了别的变化。

希望你能点一下下面这个链接，浏览器会下载一个 json 文件，把 json 文件提交到这里，我需要看一下谷歌翻译接口在你这里具体返回了什么数据结构

https://translate.googleapis.com/translate_a/single?client=webapp&sl=auto&tl=zh-CN&dj=1&ie=UTF-8&oe=UTF-8&source=icon&dt=t&dt=bd&dt=qc&dt=rm&dt=ex&dt=at&dt=ss&dt=rw&dt=ld&q=stop&tk=160194.351997

**Comment by lmk123** [comment]
不对，我刚看了一下 #1835，原来 v10.2.3 修复的报错就是 `reading 'join` :joy:

这样的话你只需要把划词翻译升级到 v10.2.3 就行了，这是详细说明 https://hcfy.app/blog/2023/09/13/ggcrash

如果升级之后还有问题，欢迎反馈！

**Comment by lizehua-cn** [comment]
👌
________________________________
发件人: lmk123 ***@***.***>
发送时间: Monday, September 18, 2023 11:23:44 PM
收件人: hcfyapp/crx-selection-translate ***@***.***>
抄送: 李泽华 ***@***.***>; State change ***@***.***>
主题: Re: [hcfyapp/crx-selection-translate] 无法使用, 报错 Cannot read properties of undefined (reading 'join') (Issue #1848)


不对，我刚看了一下 #1835<https://github.com/hcfyapp/crx-selection-translate/issues/1835>，原来 v10.2.3 修复的报错就是 reading 'join 😂

这样的话你只需要把划词翻译升级到 v10.2.3 就行了，这是详细说明 https://hcfy.app/blog/2023/09/13/ggcrash

如果升级之后还有问题，欢迎反馈！

**Comment by lizehua-cn** [comment]
v10.2.3 谷歌翻译可用, 感谢
