### ISSUE TITLE
使用谷歌翻译时遇到某些词会崩溃

### ISSUE THREAD

**Issue by sdjdd** [hcfyapp/crx-selection-translate#1849]
## 基本信息

划词翻译版本：10.1.2
浏览器版本：116.0.5845.179
操作系统：macOS 12.4

## 重现问题的步骤

1. 在设置中勾选谷歌翻译
2. 划词或在扩展程序菜单中手动输入某些词汇，比如： `dispute`
3. 窗口消失

### 预期行为

显示翻译文本

### 实际行为

窗口消失

### 补充信息

（无）

**Comment by lmk123** [comment]
https://hcfy.app/blog/2023/09/13/ggcrash
