### ISSUE TITLE
点翻译之后窗口缩小了

### ISSUE THREAD

**Issue by zhcnandy** [hcfyapp/crx-selection-translate#1850]
## 基本信息

划词翻译版本：09-13
浏览器版本：chrome 117.0.5938.62（正式版本） (arm64)
操作系统：macos m2

## 重现问题的步骤

1. github.io网站点翻译
2. 之后窗口消失
![image](https://github.com/hcfyapp/crx-selection-translate/assets/129083614/83d84aba-9723-4b6e-ad4e-724ff67a5a8e)

**Comment by lmk123** [comment]
https://hcfy.app/blog/2023/09/13/ggcrash
