### ISSUE TITLE
当前默认高度太低，希望能够增加高度设置，在翻译大段文字的时候不用滚动就能完整阅读

### ISSUE THREAD

**Issue by fu7100** [hcfyapp/crx-selection-translate#1852]
希望能够增加高度设置，在翻译大段文字的时候不用滚动就能完整阅读。

**Comment by lmk123** [comment]
目前高度是根据翻译结果内容长度自动判断的。在翻译大段文字的时候，你可以把宽度拉长，或者将窗口设为固定模式，然后将窗口拖放在浏览器右上角 / 左上角，这样就能占满整个浏览器窗口的高度了
