### ISSUE TITLE
全文翻译这个按钮太窄了 缩到滚动条里了，无法触发

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1853]
![图片](https://github.com/hcfyapp/crx-selection-translate/assets/11383988/515fc46e-273b-4bbd-ba2d-3ff6561264c1)

但是目前有缓解的办法就是勾选
这两个之一
![图片](https://github.com/hcfyapp/crx-selection-translate/assets/11383988/a5c2ef04-3d71-4e52-92f7-ed3e36a60414)
应该就是宽度计算有问题。

**火狐浏览器**

**Comment by lmk123** [comment]
我在 macOS 13.5.2、Firefox 117.0、划词翻译 10.2.3、网址 https://hcfy.app 中开启了全文翻译功能，没有重现你的问题，如下图：

<img width="366" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/7e306080-d666-470c-a689-5b24a010df79">

麻烦新开一个 issue，按照提供 bug 的模版填写具体的信息，当我能重现的时候，我就会修复问题。

**Comment by lmk123** [comment]
我试着只保留谷歌翻译和 DeepL，确实重现了你的问题，已新开了一个 issue #1854 用于追踪此问题
