### ISSUE TITLE
全文翻译的右下角控制面板缩到太里面了

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1854]
## 基本信息

划词翻译版本：10.2.3
浏览器版本：firefox 117.0.1
操作系统：macos

## 重现问题的步骤

1. 在【划词翻译设置】-【网页全文翻译】-【可供选择的翻译服务】中只保留谷歌翻译和DeepL
2. 打开 https://hcfy.app
3. 开启全文翻译

### 预期行为
网页右下角应该完整显示触发按钮
### 实际行为
只显示了一小部分，如 #1853 的图所示
### 补充信息

Chrome 上试了一下，没有这个问题

**Comment by ghost** [comment]
开任何一个专业版就可以正常，名字长一点？

**Comment by lmk123** [comment]
> 名字长一点？

你还别说，确实是因为它们名字长才避免了这个问题 :joy: 不过我已经修复这个 bug 了，下个版本起，无论选不选专业版都不会有这个问题了
