### ISSUE TITLE
Deepl不能翻译，发现问题已经有2天时间

### ISSUE THREAD

**Issue by linexu** [hcfyapp/crx-selection-translate#1855]
![image](https://github.com/hcfyapp/crx-selection-translate/assets/47073986/f549e7ba-0b1c-48b0-b596-2c1432a50f8e)

## 基本信息
**大概两天前开始，Deepl不能翻译，提示：找不到 source 的语种下拉框。[查看解决方案](https://hcfy.app/docs/faqs/why-services-always-loading#deepl-only)**
划词翻译版本：**划词翻译 v10.2.3**
浏览器版本：**Brave 已是最新版本，版本 1.58.131 Chromium: 117.0.5938.92（正式版本） （64 位）**
操作系统：**Windows 10 专业版 22H2**

## 重现问题的步骤

1.**只要是通过划词翻译就不能翻译，提示：找不到 source 的语种下拉框。[查看解决方案](https://hcfy.app/docs/faqs/why-services-always-loading#deepl-only)**
2.**使用Deepl客户端正常。**
3.

### 预期行为
**希望能尽快修复，谢谢。**

**Comment by lmk123** [comment]
deepl加载不稳定导致的，按照“查看解决方案”里的步骤尝试即可

**Comment by lmk123** [comment]
我在下个版本里延长一下检测时间吧，现在是 5 秒检测不到就报错了，但是 DeepL 经常 15 秒才加载好。下个版本会把这个检测时间延长至 15 秒

**Comment by linexu** [comment]
刚才突然发现翻译正常了，以为是您修复好了，才打开看到您的回复，很感谢您第一时间的回复。
