### ISSUE TITLE
在内置的PDF阅读器里选取文本比较困难,能否改进一下?

### ISSUE THREAD

**Issue by elongwz** [hcfyapp/crx-selection-translate#1859]
多行选取经常变成选取本页
不容易选中
空白处不能作为选取的开始位置

**Comment by lmk123** [comment]
确实有这些问题，但其实内置 PDF 阅读器是一个第三方软件，这些问题只能等这个第三方软件修复，我能做的就是在它更新版本之后尽快升级划词翻译里的内置 PDF 阅读器版本 :joy:
