### ISSUE TITLE
独立翻译窗口, "打开面板时自动翻译剪切板内的文本/图片"的设置, 改成"获得焦点时自动翻译剪切板内的文本/图片"

### ISSUE THREAD

**Issue by seafood2017** [hcfyapp/crx-selection-translate#1860]
遇到的麻烦:
独立翻译窗口用来翻译其他软件里的内容还是挺好的. 
但是每次在别的软件中复制/截图完, 切过来还要粘贴一下, 还是挺麻烦的.
改进:
既然可以设置成"打开面板时自动翻译剪切板内的文本/图片", 改成"获得焦点时自动翻译剪切板内的文本/图片", 应该也不难.

**Comment by lmk123** [comment]
你在别的软件里复制文本后，可以按下呼出独立窗口的快捷键（默认值是 Ctrl + Shift + 1），它就会自动读取剪切板并粘贴，不需要你自己去粘贴的

另外，下个版本给独立翻译窗口加了一个新功能，可以自动检测剪切板内容变动，一旦剪切板内容有变动就会自动翻译，这样连按下快捷键的步骤也省了

如果仍有疑问，欢迎继续留言
