### ISSUE TITLE
驼峰翻译助手 百度 error:54000

### ISSUE THREAD

**Issue by windwhim** [hcfyapp/crx-selection-translate#1861]
## 基本信息

划词翻译版本：VS Code驼峰翻译助手 v0.13.48
浏览器版本：VS Code 1.83.0
操作系统：Windows 11

## 重现问题的步骤

1.同时开通了百度垂直翻译和百度的通用文本翻译，驼峰翻译助手提示error 54000

### 预期行为
无
### 实际行为
无

**Comment by lmk123** [comment]
你找错人了，你说的这个软件不是我开发的😂
