### ISSUE TITLE
网页全文翻译的时候，用chatgpt会乱码

### ISSUE THREAD

**Issue by meidong007** [hcfyapp/crx-selection-translate#1863]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
没有重现 :joy:

麻烦按照提问模版完整填写重现的环境与步骤，只有当我能重现你的问题了，我才能解决你的问题 :joy:
