### ISSUE TITLE
【v10.4.3 已修复】ChatGPT 翻译结果空白

### ISSUE THREAD

**Issue by Bruce105** [hcfyapp/crx-selection-translate#1868]
划词翻译作者的留言：

v10.4.3 已修复此问题，在通过审核之前，可以直接通过离线安装包安装，见 https://hcfy.app/docs/installv2/offline

-----------------------

ChatGPT 在近期调整了它们的网页接口，导致包括划词翻译在内的所有基于 ChatGPT 网页接口的浏览器插件都不能正常使用了。

我正在重新适配当中，但此次调整后大幅增加了适配难度，所以预计需要更长的时间完成适配。

**Comment by xming521** [comment]
好像白屏了

**Comment by lmk123** [comment]
我试了一下是正常的，如下图。请先确认一下你能否正常打开 chat.openai.com 且能正常对话

<img width="357" alt="截屏2023-10-22 11 14 50" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/ae75a4d3-df8b-4f1e-988e-c0d346d3e439">

**Comment by xming521** [comment]
![image](https://github.com/hcfyapp/crx-selection-translate/assets/32786500/e013873d-ea93-486b-bd1a-0ca9ae3f40f1)
![image](https://github.com/hcfyapp/crx-selection-translate/assets/32786500/0d50e7bd-09ee-47b5-a534-b9219b0a1d91)

**Comment by lmk123** [comment]
应该是 ChatGPT 网页版做了灰度发布，将新的接口灰度到了部分用户。

但目前我没有被灰度到，也就无法重现，等我能重现的时候，我会重新做适配

**Comment by justsonghua** [comment]
我也遇到了这个问题。

网页划词的时候，看不到GPT返回的内容。而且在GPT页面可以看到我的问题被分到了GPT4.0，但是我设置的是GPT3.5 TURBO。

另外**歪楼**问下，现在每次翻译都要新开一个"new chat"吗？我记得之前有段时间，翻译的对话内容不会在历史记录里变成一溜"new chat"的呀，还是我设置错了什么？

**Comment by xming521** [comment]
> 我也遇到了这个问题。
> 
> 网页划词的时候，看不到GPT返回的内容。而且在GPT页面可以看到我的问题被分到了GPT4.0，但是我设置的是GPT3.5 TURBO。
> 
> 另外**歪楼**问下，现在每次翻译都要新开一个"new chat"吗？我记得之前有段时间，翻译的对话内容不会在历史记录里变成一溜"new chat"的呀，还是我设置错了什么？

@lmk123

**Comment by valens7** [comment]
> 我也遇到了这个问题。
> 
> 网页划词的时候，看不到GPT返回的内容。而且在GPT页面可以看到我的问题被分到了GPT4.0，但是我设置的是GPT3.5 TURBO。
> 
> 另外**歪楼**问下，现在每次翻译都要新开一个"new chat"吗？我记得之前有段时间，翻译的对话内容不会在历史记录里变成一溜"new chat"的呀，还是我设置错了什么？

我也碰到同样的问题，之前一直没有这个问题. 
1. 网页划词，看不到ChatGPT返回的内容。而在ChatGPT官网的对话页面可以看到翻译的内容
2. 出现很多的new chat, 以前是翻译内容都在一个 new chat里. 
<img width="782" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/35646496/1c09e2e5-258e-4b6c-a4d7-5cb05c12756c">

**Comment by samanhappy** [comment]
+1

**Comment by mffxbb** [comment]
+1 划词之后GPT空白，回到gpt界面之后能看到对话，但是出不了运算结果，点击重新计算的话gpt才出结果但无法在翻译面板上显示出来
<img width="1440" alt="截屏2023-10-27 13 31 59" src="https://github.com/hcfyapp/crx-selection-translate/assets/149137899/aaad8a22-9764-4234-9bf5-4344de5b8df2">
<img width="298" alt="截屏2023-10-27 13 35 17" src="https://github.com/hcfyapp/crx-selection-translate/assets/149137899/1272fb0e-9b38-4d42-ae1f-0030ba176373">

**Comment by lmk123** [comment]
已重现，正在修复中

**Comment by operasnk** [comment]
g'p't官网界面
![image](https://github.com/hcfyapp/crx-selection-translate/assets/103368492/76f3e9f8-48b1-4c86-bd25-408a64df76da)
翻译框
![image](https://github.com/hcfyapp/crx-selection-translate/assets/103368492/c348c240-c53b-47fc-98d1-685563038b95)

**Comment by hong-tm** [comment]
我也遇到了该问题,界面没有返回结果,在openai页面需要重新生成才能看到,等待大佬修复

![youtube-translate](https://github.com/hcfyapp/crx-selection-translate/assets/51999870/3ed47a2a-577f-4590-a07a-23fdb726304d)
翻译尝试,但是没有结果

![openai-page](https://github.com/hcfyapp/crx-selection-translate/assets/51999870/38e3a45e-363d-4063-8d61-b96195c8894d)

**Comment by maoqishuxi** [comment]
同碰到这样的问题

**Comment by lmk123** [comment]
各位，v10.4.3 已经修复了此问题，可以直接通过离线安装包安装，见 https://hcfy.app/docs/installv2/offline

安装之后，确保你的浏览器能打开 https://chat.openai.com 且能正常对话，然后你可以试一下划词翻译的 ChatGPT 有没有恢复正常，我这边测试过之后是恢复了的。

希望大家安装后能给我一个反馈

**Comment by samanhappy** [comment]
我这边测试正常

**Comment by operasnk** [comment]
不太行，一直出不来结果，chatgpt每次问问题都要验证是否是真人，是梯子的问题吗
![image](https://github.com/hcfyapp/crx-selection-translate/assets/103368492/06550813-bf19-4663-b175-53399e1bcbef)
![image](https://github.com/hcfyapp/crx-selection-translate/assets/103368492/dfa4dda9-a11f-412a-809f-04c67236d168)

**Comment by lmk123** [comment]
> 不太行，一直出不来结果，chatgpt每次问问题都要验证是否是真人，是梯子的问题吗

@operasnk ChatGPT 检测出来机器行为了（划词翻译调用 ChatGPT 网页接口就属于机器行为的其中一种），这个检测规则是非常复杂且不透明的，要从划词翻译这边规避掉是不可能的，只能祈祷不被检测到了，目前我没有被检测到，但要怎么做才能不被检测到我就不知道了 :joy:

**Comment by operasnk** [comment]
我现在直接在官网问问题也是每次都要真人验证😭

**Comment by maoqishuxi** [comment]
@lmk123 翻译空白已经没有问题了。但是默认GPT3.5的模型，怎么都改不了。是否可以增加选择其它的模型

**Comment by hong-tm** [comment]
Chrome extension 上,还是10.4.2版本,还没有更新😗

**Comment by justsonghua** [comment]
> Chrome extension 上,还是10.4.2版本,还没有更新😗

你需要直接用zip包的方式安装新的测试版，按照前面给出的方法就行。

**Comment by lmk123** [comment]
> Chrome extension 上,还是10.4.2版本,还没有更新

@hong-tm @justsonghua v10.4.3 有离线安装包了，可以直接安装离线安装包，这样以后也能自动更新，见 https://hcfy.app/docs/installv2/offline

> 默认GPT3.5的模型，怎么都改不了。是否可以增加选择其它的模型

@maoqishuxi 这就是另一个主题了，已开 issue https://github.com/hcfyapp/crx-selection-translate/issues/1883
