### ISSUE TITLE
翻译提示找不到 source 的语种下拉框。

### ISSUE THREAD

**Issue by ldwdg** [hcfyapp/crx-selection-translate#1870]
## 基本信息
通过选中词汇进行翻译，提示找不到 source 的语种下拉框。检索解决方案发现只有 v8.7.9的更新日志提到了这个问题：
    修复了在且仅在 Firefox 中 DeepL 报错“找不到source语种下拉框”的问题。
原网页不支持点击选择词汇，使用Allow Copy插件后允许选中复制文字后，进行翻译就出现了这个“找不到source语种下拉框”的问题。

划词翻译版本：10.3.0
浏览器版本：Firefox 118.0.2
操作系统：windows10

## 重现问题的步骤
1、打开网址https://www.photopea.com/；
2、原网页不支持点击选择词汇，使用Allow Copy插件后允许选中复制文字后，进行翻译就出现了这个“找不到source语种下拉框”的问题。可能是allow copy的插件导致的。

**Comment by ldwdg** [comment]
今天在zhihu.com复现了这个问题，deepl.com是可以正常打开的，也没有使用Allow Copy插件，但还是出现了找不到source的语种下拉框的提示。
![image](https://github.com/hcfyapp/crx-selection-translate/assets/65357924/ae56a8a8-0b28-4d47-b625-8dce82a5cb47)

**Comment by E1nzbern** [comment]
这个问题我也遇到过，基本上每次打开浏览器后的第一次翻译都会出现，点击重试或者再翻译一次就正常了，猜测是deepl网页加载比较慢导致的

**Comment by lmk123** [comment]
@E1nzbern 确实如此。我新开了一个 issue，计划解决这个问题 #1872
