### ISSUE TITLE
有道翻译api增加领域选项

### ISSUE THREAD

**Issue by huangyc0618** [hcfyapp/crx-selection-translate#1871]
有道翻译api里可以传domain字段，选项包括：computers	计算机，medicine	医学，finance	金融经济，game	游戏。详见：
https://ai.youdao.com/DOCSIRMA/html/trans/api/wbfy/index.html

功能需求原因：有道翻译的计算机版本在翻译专业文章的时候效果确实好不少，专业名词翻译更准确

**Comment by lmk123** [comment]
已加入开发计划，后续进展可以关注 #1782
