### ISSUE TITLE
打开浏览器后首次使用 DeepL 大概率会报错“找不到 source 的语种下拉框”，重试之后就会恢复

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1872]
## 基本信息

划词翻译版本：v10.3.0
浏览器版本：chrome 117
操作系统：macos

## 重现问题的步骤

1. 彻底关闭浏览器
2. 打开浏览器后，在浏览器设置-【隐私和安全】（chrome://settings/privacy）点击【清除浏览数据】，仅勾选【缓存的图片和文件】，然后点击【清除数据】按钮
3. 打开任意网页后，使用一次 DeepL

### 预期行为
正常显示翻译结果
### 实际行为
100% 会出现一次报错，不过重试之后就会恢复

**Comment by xanadus0** [comment]
我个人测试在Windows 11的Firefox浏览器119.0中，在浏览器启动时，如果划词翻译v10.3.0与篡改猴（Tampermonkey）v4.19.0已同时启用（即使篡改猴没有任何用户脚本），则划词翻译DeepL会报错“找不到 source 的语种下拉框。”。

我不确定这是否是个例，希望大家可以帮忙测试。

**Comment by lmk123** [comment]
@xanadus0 我确认过了，跟其它插件没有关系，是划词翻译自己的 bug。

下个版本 v10.4.1 修复了这个 bug
