### ISSUE TITLE
提议添加排除网站功能和关闭自动翻译截图功能

### ISSUE THREAD

**Issue by nukewarrior** [hcfyapp/crx-selection-translate#1874]
1. 排除网站功能：
  有些网站并不需要翻译功能，尤其是自己部署的一些web服务，在这些页面上希望能关闭划词翻译功能
2. 关闭自动翻译截图功能：
  目前打开独立窗口的时候，如果剪贴板第一个是截图，会自动ocr并翻译，我没找到在哪里可以关闭这个功能，希望能添加，因为并不是每次打开独立翻译窗口都是想要翻译截图

谢谢🙏

**Comment by lmk123** [comment]
> 排除网站功能

目前是有的，只需要点一下地址栏旁边的划词翻译图标，然后再点一下“此页面已启用网页划词”，然后你就可以在这个网页 / 网站上禁用掉网页划词了

> 关闭自动翻译截图功能

在 划词翻译设置（）- 【翻译面板】（chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/settings.html#/panel）-【自动化】-【打开面板时自动翻译剪切板里的图片】改为“不翻译”即可

----

如果仍有问题，欢迎继续留言
