### ISSUE TITLE
Arc 浏览器中选中文本翻译会打开小窗口

### ISSUE THREAD

**Issue by hughfenghen** [hcfyapp/crx-selection-translate#1876]
## 基本信息

划词翻译版本：v10.4.0
浏览器版本：
Arc Version 1.14.0 (42789)
Chromium Engine Version 118.0.5993.117
操作系统：MacOS

## 重现问题的步骤

使用 **Arc 浏览器** 在任意网页中选中英文词汇，点击划词翻译 icon

### 实际行为
页面出现翻译弹窗，同时也打开了一个独立的 Arc 小窗口，URL为谷歌翻译页面，且自动填充了需要翻译的内容
翻译完成后会自动关闭弹出的小窗口

### 预期行为
不会弹窗小窗口，而是在网页内的悬浮层现实翻译结果，跟Chrome 浏览器的行为一致

### 补充信息
这个现象时近期出现的

**Comment by lmk123** [comment]
当你选择了“速度慢、准确率高”的谷歌翻译时，就是会打开这个小窗口的，这里有说明：https://hcfy.app/docs/faqs/why-result-different

但是，如果是 Chrome 浏览器的话，这个小窗口是在后台打开的，不会遮挡任何 app。看样子 Arc 浏览器并没有实现这一功能，导致这个小窗口遮挡住了你，但这是 Arc 的问题，无法从划词翻译这边解决

**Comment by hughfenghen** [comment]
@lmk123 
> 这个小窗口是在后台打开的

请问是那个 API 后台打开窗口啊？
有详细信息，可以尝试向 Arc 浏览器反馈试试

**Comment by lmk123** [comment]
`chrome.windows.create({ focused: false })`

https://developer.chrome.com/docs/extensions/reference/windows/#method-create

**Comment by hughfenghen** [comment]
好的，感谢
