### ISSUE TITLE
Chrome没有在后台运行

### ISSUE THREAD

**Issue by cesaryuan** [hcfyapp/crx-selection-translate#1878]
## 基本信息

划词翻译版本：10.40.0
浏览器版本：119.0.6045.106
操作系统：Windows 10

## 重现问题的步骤

1. 安装扩展
2. 开启Chrome的`关闭 Google Chrome 后继续运行后台应用`选项
3. 设置全局快捷键

### 预期行为

预期弹出以下通知，并且Chrome在托盘显示，即Chrome在后台运行
![image](https://github.com/hcfyapp/crx-selection-translate/assets/35998162/a767fbde-fb69-4932-bcc3-997deece3f02)

### 实际行为

实际Chrome没有在后台运行，通知也没有弹出

### 补充信息
手动打开`划词翻译`后台页的控制台然后输入`chrome.permissions.request({permissions: ['background']})`，通知弹出，Chrome才得以在后台运行。

![image](https://github.com/hcfyapp/crx-selection-translate/assets/35998162/e905fb3a-5d6b-4203-8974-15a83f042b0a)

**Comment by lmk123** [comment]
感谢反馈，其实是还需要在划词翻译设置里勾选一个选项才行的（这个选项其实就是执行了上面这个代码），但是我刚才确认的时候发现不知为何这个选项不在设置页里了 :joy:

这算是一个 bug，我会尽快修复

**Comment by lmk123** [comment]
此问题已解决，等我发布 v10.4.2 之后就可以按照这里的步骤开启了：https://hcfy.app/docs/guides/extra#close-browser
