### ISSUE TITLE
使用谷歌翻译划词后会弹出浏览器窗口

### ISSUE THREAD

**Issue by HY1492** [hcfyapp/crx-selection-translate#1879]
## 基本信息

划词翻译版本：10.4.0
浏览器版本：119.0.6045.106
操作系统：Windows 10

## 重现问题的步骤

1.打开划词翻译选项-通用设置-第三方服务，谷歌翻译选择“速度慢、准确率高”
2.打开任一英文网站，例如：https://en.wikipedia.org/wiki/SpaceX
3.任选一段内容进行翻译，会弹出浏览器的窗口，窗口一闪过后消失

### 预期行为
使用谷歌翻译，划词后只出现翻译面板，不弹出浏览器窗口
### 实际行为
[使用“速度慢、准确率高”的谷歌翻译，划词后会先弹出浏览器窗口闪过，才出现翻译面板](url)
### 补充信息
10.4.0之前的版本中没有出现此问题
![划词后弹出浏览器窗口](https://github.com/hcfyapp/crx-selection-translate/assets/73172021/965bff3e-4585-404f-b124-97a09db21aa9)

https://github.com/hcfyapp/crx-selection-translate/assets/73172021/1dd83472-0aa1-445b-aa27-88854d0dcf1b

**Comment by lmk123** [comment]
确实是有这个窗口的，但是，这个窗口应该是在后台静默打开，不会显示在屏幕上才对，我使用 macOS、Chrome 119 确认过

我有机会了在 Windows 系统上试试

**Comment by HY1492** [comment]
> 确实是有这个窗口的，但是，这个窗口应该是在后台静默打开，不会显示在屏幕上才对，我使用 macOS、Chrome 119 确认过
> 
> 我有机会了在 Windows 系统上试试

我又重新装了10.3.0的，不会弹出这个浏览器窗口，更新到10.4.0时会出现

**Comment by lmk123** [comment]
v10.3.0 及之前的划词翻译是没法用“速度慢、准确率高”的谷歌翻译的。你在 v10.4.0 把谷歌翻译切换回“速度**快**、准确率**低**”的话也是不会弹窗的。

**Comment by Emily-0616** [comment]
> v10.3.0 及之前的划词翻译是没法用“速度慢、准确率高”的谷歌翻译的。你在 v10.4.0 把谷歌翻译切换回“速度**快**、准确率**低**”的话也是不会弹窗的。

具体要怎么设置？现在很苦恼..

**Comment by JuHoMA** [comment]
我更新到10.4.2之后，也出现了该问题

**Comment by lmk123** [comment]
出现这个情况是因为你们把谷歌翻译切换为了“速度**慢**、准确率**高**”，打开划词翻译选项 - 通用设置 - 第三方服务，把谷歌翻译的接口类型选择“速度快、准确率低”就行了。

**Comment by lmk123** [comment]
即将发布的 v10.4.4 已经尽可能将这个窗口隐藏了，理论上用户不会再看到这个弹出的浏览器窗口了。

**Comment by Emily-0616** [comment]
> 即将发布的 v10.4.4 已经尽可能将这个窗口隐藏了，理论上用户不会再看到这个弹出的浏览器窗口了。

![image](https://github.com/hcfyapp/crx-selection-translate/assets/32790186/e2d2d0b6-3cbd-4684-baf0-26854ed4404e)
chrome 最新版，划词翻译是v10.4.4，仍出现该问题。

**Comment by lmk123** [comment]
> chrome 最新版，划词翻译是v10.4.4，仍出现该问题。

@Emily-0616 

划词翻译理论上应该是会在**后台**创建一个 **1 x 1 像素** 的浏览器窗口，我在我的 macOS 和 WIndows Chrome 119 上都测试过了，确实是基本不可见的，但是为什么在你这里还是能看到我就不知道了 😂

**Comment by Jenernana** [comment]
我现在用的edge也出现这个一样的问题，而且还会在任务栏创建一个窗口然后消失，edge版本号是 119.0.2151.58，划词翻译是v10.4.4，以前从来没有这种情况，不知道是Chromium更新的问题还是划词翻译更新的问题

**Comment by lmk123** [comment]
@Jenernana 你把谷歌翻译切换成速度慢准确率高的时候下面就有一行提示，切了之后每次使用谷歌翻译都会弹一个浏览器窗口。在我的电脑中这个窗口确实是不可见的，但不同系统和浏览器的表现确实不一样，暂时没法做到完全隐藏。如果实在介意，重新切回速度快准确率低的谷歌翻译即可。

**Comment by Jenernana** [comment]
好的谢谢👌


lmk123 ***@***.***>于2023年11月14日 周二18:11写道：

**Comment by slanterns** [comment]
(Firefox on Windows 也观察到同样的问题了

**Comment by lmk123** [comment]
@slanterns 好像一直有人反馈这个问题。。但是弹窗只有在把谷歌翻译切换为“速度慢、准确率高”之后才会出现，而切换的时候在下方也有过明确的提示，切换了就会弹窗。

你出现这个问题是因为划词翻译自动给改成了速度慢的谷歌翻译吗？

**Comment by slanterns** [comment]
> 你出现这个问题是因为划词翻译自动给改成了速度慢的谷歌翻译吗？

我这边应该之前就选择了“速度慢”，但这两天发现出现了弹窗的问题。

但单纯弹窗的话可能也就不管它了，现在更严重的问题是，划词之后会出现弹窗，然后翻译窗口会持续卡在等待状态一直不动，10秒之后提示超时错误（但手动查看弹窗里的话会发现内容应该是已经被翻译出来了的），这就导致“速度慢”完全无法使用了。

![图片](https://github.com/hcfyapp/crx-selection-translate/assets/10987206/29796b6e-7cb9-4e00-b236-eadc0893a1ed)

![图片](https://github.com/hcfyapp/crx-selection-translate/assets/10987206/17ecd491-7bd1-4f9c-a6bc-c67a582dd528)

**Comment by lmk123** [comment]
这就很奇怪了，因为在至少一年前，速度慢的谷歌翻译就不能用了，划词翻译会报错”速度慢的谷歌翻译暂时不可用，请切换为速度快的谷歌翻译”，难道你这一年以来用的都是速度慢的谷歌翻译且一直没报错吗 :joy:

你使用速度慢的谷歌翻译，翻译任意文本都会报这个错吗？如果是的话，我感觉又是一个只有 firefox 才有的问题。。你可以试试在 chrome 里是不是正常的

**Comment by slanterns** [comment]
![图片](https://github.com/hcfyapp/crx-selection-translate/assets/10987206/a50fb9a5-9a1f-450e-ae6b-841e83b8058a)

之前选择的是什么我记错了也有可能，现在就是如果选择“速度慢” Firefox 下任意文本都会报错；Chrome 下还真是没问题（虽然可以看到新窗口一闪而过）

**Comment by DDMse** [comment]
特地登录说明一下问题，最近Chrome的划词翻译总跳那个十分恼人的小窗口，还要卡很久才能出结果，并且这种机制导致修改Google Translate API的hosts的方式完全失效，因为根本和API没关系。我同时也是划词翻译在Firefox上的用户，今天开始FIrefox上的划词翻译也开始蹦小窗口了，FIrefox比Chrome更糟糕的是那个窗口一直显示超过10秒，然后划词翻译直接显示超时error，换句话说就是Firefox上的划词翻译100%失效了。
作者有提到可以选用“较快的”那个Google翻译选项，但据我多年的使用经验，这个选项给出的英文单词的中文翻译往往只有一个字，而且是中国人普遍不认识更不会使用的那种字，并不能算作是真正的翻译。这导致我一直选择使用“较慢但准确”的那个Google翻译选项 。
我从15年至今一直在使用划词翻译，划词翻译真的是我最喜欢的翻译插件没有之一，真心希望作者可以攻克目前的这个问题呜呜呜，我学英语真的一直靠您开发的这款插件来着，省去了我复制到Google Translate才能翻译的麻烦！

**Comment by lmk123** [comment]
@slanterns @DDMse “速度慢、准确率高”的谷歌翻译在 Firefox 里会报错的问题已新开了一个 issue：

- #1894

另外我知道你们为什么会出现这个问题了 :joy:

先说总结：你们可以放心的切换回“速度快、准确率低”的谷歌翻译，因为这个类型也是会优先返回准确率高的结果的。

然后我解释一下你们为什么会出现这个问题 :joy:

划词翻译里其实有**三种**谷歌翻译接口，除了在设置里标出来的“速度快、准确率低”和”速度慢、准确率高”的两种，其实还有一种“**速度快、准确率也高**”的接口。

这个“速度快、准确率也高”的谷歌翻译有一个缺点，就是有使用频率限制，在使用大概半小时之后就会报错了，需要两三个小时的时间才能恢复，所以以前划词翻译使用谷歌翻译的逻辑是这样的：

1. 无论设置里选择的是哪种谷歌翻译，都优先尝试使用“速度快、准确率也高”的谷歌翻译
2. 如果报错了，再根据设置里的“接口类型”来确定要用“速度快、准确率低”还是”速度慢、准确率高”

所以如果你在之前的版本里选择了”速度慢、准确率高”的接口类型，其实也仍然是在优先使用“速度快、准确率也高”的谷歌翻译，如果你始终没有超过它的频率限制，那么在你们看来你们就是一直能正常使用”速度慢、准确率高”的接口类型的 :joy: （但我猜测你们应该也超出过它的使用频率限制，然后你们就会看到““速度慢、准确率高的谷歌翻译暂时不可用，请在设置中切换为“速度快、准确率低””的这句报错信息了。

但是这次重新上线之后，我把这个调用逻辑给改了，如果选择的是”速度慢、准确率高”，现在不会优先尝试使用“速度快、准确率也高”的谷歌翻译了，会直接使用新的、会弹窗的”速度慢、准确率高”的谷歌翻译，于是你们发现升级版本后，谷歌翻译突然开始弹窗了 :joy:

我会在下个版本把这个逻辑改回来，即无论选择哪种类型，都优先尝试使用”速度快、准确率也高”的谷歌翻译

**Comment by slanterns** [comment]
okk谢谢！

**Comment by lmk123** [comment]
已将这三种谷歌翻译的详细说明更新在了 https://hcfy.app/docs/faqs/why-result-different

**Comment by DDMse** [comment]
哇噢！非常感谢～💓

**Comment by HY1492** [comment]
感谢~
