### ISSUE TITLE
ChatGPT密钥建议增加自定义 API Key从第三方服务网站

### ISSUE THREAD

**Issue by JiangWater** [hcfyapp/crx-selection-translate#1881]
**没有这个功能（改进）的时候，你遇到了什么问题？**
目前ChatGPT的API从第三方中转站购买，非OpenAI官方API，而当前密钥管理无法镜像站代理API，因此无法使用ChatGPT翻译服务。

**你想要如何解决你的问题？**
增加从其他第三方服务获取API渠道，通过设置自定义 API 接口地址，完成ChatGPT翻译服务。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
无

**补充信息**
沉浸式翻译，能够自定义APIKey，可在OpenAl, Azure OpenAl,或其他第三方服务获取。

**Comment by lmk123** [comment]
已有功能，在划词翻译设置 - 第三方服务 里

**Comment by lmk123** [comment]
不对，我想你想表达的意思是增加更多接口吧，比如 Azure OpenAl……

目前 Azure OpenAl 已经加入开发计划了，其它的陆续加吧 :joy:

**Comment by JiangWater** [comment]
> 已有功能，在划词翻译设置 - 第三方服务 里

可以了！谢谢！
