### ISSUE TITLE
ChatGPT 添加对 GPT 4 的支持

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1883]
**没有这个功能（改进）的时候，你遇到了什么问题？**
目前的 ChatGPT 只能用 3.5，但对于开通了 GPT 4 的用户，肯定是倾向于使用 GPT 4

**Comment by maoqishuxi** [comment]
开通了GPT4，也只能用GPT3.5翻译

**Comment by lmk123** [comment]
目前 ChatGPT Web 接口已经不能用了，所以 close
