### ISSUE TITLE
【bug】v10.4.4 在与 Group Tabs By Domain 扩展共同使用时不会自动关闭 translate.google.com 标签页

### ISSUE THREAD

**Issue by xsw0** [hcfyapp/crx-selection-translate#1889]
## 基本信息

划词翻译版本：10.4.4
浏览器版本：Edge Version 119.0.2151.58 (Official build) (x86_64)
操作系统：macOS 13.6.1

## 重现问题的步骤

1. 安装 [Group Tabs By Domain](https://chrome.google.com/webstore/detail/group-tabs-by-domain/icmbnkmjhdapliaologdghjfpcmcimln)
2. 选择【速度慢、准确率高】的 google 翻译接口

### 预期行为

正确关闭弹出的窗口

### 实际行为

没有正确关闭

### 补充信息
旧版本没有这个问题，目前只能使用【速度快、准确率低】的 google 接口或关闭 Group Tabs By Domain 扩展

**Comment by lmk123** [comment]
我试着安装了一下，没有找到解决办法。这个问题应该由 Group Tabs By Domain 扩展来解决，我这边正常执行了关闭标签页的逻辑，是 Group Tabs By Domain 扩展拦截了这一操作，我绕不开。
