### ISSUE TITLE
请问网页全文翻译用的是谷歌,URL地址是多少?因为我用的指纹浏览器,我想让网页翻译走本地网络,这样翻译更快

### ISSUE THREAD

**Issue by hiroot199** [hcfyapp/crx-selection-translate#1890]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，现有 PDF 不支持标记功能，导致我无法在 pdf 上标记内容。

**你想要如何解决你的问题？**
比如，添加 PDF 标记功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
比如，如果划词翻译无法添加 PDF 标记功能，那么至少允许我在别的 PDF 软件里进行划词翻译。

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。

**Comment by lmk123** [comment]
谷歌翻译的接口地址有以下两个：

- 速度慢、准确率高的谷歌翻译：https://translate.google.com
- 速度快、准确率低的谷歌翻译：https://translate.googleapis.com
