### ISSUE TITLE
能正常访问网页chatGPT，但使用插件翻译，GPT不返回内容，网页也没有生成对话。

### ISSUE THREAD

**Issue by RubiksCubei** [hcfyapp/crx-selection-translate#1892]
## 基本信息

划词翻译版本：10.4.4
浏览器版本：119.0.6045.160
操作系统：Windows 10

## 重现问题的步骤

1.任选一段文字
2.使用翻译

### 预期行为
chatGPT成功翻译
### 实际行为
网页GPT能正常访问和对话
chatGPT一直在载入。打开网页chatGPT也没有生成相对应的对话。
![image](https://github.com/hcfyapp/crx-selection-translate/assets/48173817/f9715282-361b-4f2c-b322-5b2d003a4105)
![image](https://github.com/hcfyapp/crx-selection-translate/assets/48173817/3d2d1b84-fcda-47b9-9381-ac7ecd96029e)

**Comment by lmk123** [comment]
我试了一下，我这边是正常的 :joy:

而且我注意到我的 ChatGPT 界面和你长的不一样：

<img width="913" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/5d33540f-4267-4210-ada1-f82c1cf55de7">

我猜测是不是你还没有被灰度到新版本，因为大概在半个月前 ChatGPT 改过接口，导致大部分用户反馈 ChatGPT 没法用了，所以我做过适配，见 #1868

**Comment by RubiksCubei** [comment]
> 我试了一下，我这边是正常的 😂
> 
> 而且我注意到我的 ChatGPT 界面和你长的不一样：
> 
> <img alt="image" width="913" src="https://user-images.githubusercontent.com/5035625/283298287-5d33540f-4267-4210-ada1-f82c1cf55de7.png">
> 我猜测是不是你还没有被灰度到新版本，因为大概在半个月前 ChatGPT 改过接口，导致大部分用户反馈 ChatGPT 没法用了，所以我做过适配，见 #1868

刚试了一下发现可以了。  进网页看。我网页也变了。 😂

**Comment by RubiksCubei** [comment]
今天这个问题又出现了。  同样能打开网页，插件无法正常使用。

**Comment by lmk123** [comment]
@yuehongcheng 我是正常的，如下图

<img width="523" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/85a841c8-6876-4728-b7fb-144a74718844">

**Comment by lmk123** [comment]
你好 @RubiksCubei ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
