### ISSUE TITLE
希望增加对Deepl渠道的镜像接口配置

### ISSUE THREAD

**Issue by msghost** [hcfyapp/crx-selection-translate#1896]
对于这个需求的请求，原因是目前有一些项目可以实现对Deepl的代理访问并通过多节点分布的方式来规避免费请求过多的问题。因此希望能够增加对Deepl渠道的镜像地址配置

**没有这个功能（改进）的时候，你遇到了什么问题？**
无法利用自建或者第三方Deepl翻译API

**你想要如何解决你的问题？**
如同谷歌和Chatgpt一样，提供镜像地址的配置

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
暂无

**补充信息**
暂无补充，只需要有镜像地址的配置即可

**Comment by lmk123** [comment]
> 有一些项目可以实现对Deepl的代理访问并通过多节点分布的方式来规避免费请求过多的问题

我对这些项目不太了解，可以提供一些我看看具体是什么吗？

**Comment by msghost** [comment]
> > 有一些项目可以实现对Deepl的代理访问并通过多节点分布的方式来规避免费请求过多的问题
> 
> 我对这些项目不太了解，可以提供一些我看看具体是什么吗？

你好，类似于这种：https://github.com/OwO-Network/DeepLX

**Comment by Copy2Translator** [comment]
希望作者能支持一下 DeepLX

**Comment by jalenzz** [comment]
+1

**Comment by miku2365** [comment]
+1

**Comment by a15355447898a** [comment]
+1

**Comment by heheda123123** [comment]
希望能支持deeplx。现在沉浸式翻译，简约翻译，pot-app等等都支持deeplx接口了

**Comment by Teda9** [comment]
+1

**Comment by lmk123** [comment]
DeepL 的镜像地址配置功能已在 v10.8.0 当中添加，大家可以试一下将 DeepLX 的镜像地址填写进去后能不能正常使用，如果不能，那我就单独添加对 DeepLX 的支持

**Comment by lmk123** [comment]
注意：除了填写 DeepLX 的镜像地址，还需要在 DeepL 管理密钥那里随便填写一个密钥，否则不会调用到

**Comment by ixxc** [comment]
> 注意：除了填写 DeepLX 的镜像地址，还需要在 DeepL 管理密钥那里随便填写一个密钥，否则不会调用到

还是不能正常使用，我可以把我的第三方链接发给你测试，但是不知道发到哪里
更希望的还是额外对 DeepLX 支持，因为那样可以做到填多个地址并发请求缓解接口被限制

**Comment by lmk123** [comment]
我还是单独支持一下 DeepLX 吧，后续更新在 #2040
