### ISSUE TITLE
【v10.4.6 已修复】chagpt试用翻译 一直加载

### ISSUE THREAD

**Issue by xming521** [hcfyapp/crx-selection-translate#1899]
v10.4.6 已修复此问题，可以通过离线安装包立刻升级，见 https://hcfy.app/docs/installv2/offline

--------------------------------

## 基本信息

划词翻译版本：v10.4.4
浏览器版本：Cent Browser版本 5.0.1002.354（正式版本） （64 位） (Chromium 102.0.5005.167)
操作系统：win11

## 重现问题的步骤

1.任意翻译一句

### 实际行为
![image](https://github.com/hcfyapp/crx-selection-translate/assets/32786500/f5e3b7e4-ad7b-4b72-8837-b129ce36c869)
![image](https://github.com/hcfyapp/crx-selection-translate/assets/32786500/e47d6903-33f4-4e3d-9cb7-72078f640b94)
以前在chatgpt网页还能看见翻译的记录，现在也看不到新的记录了

**Comment by lmk123** [comment]
重现了 :joy: 我看看

**Comment by hong-tm** [comment]
同样遇到此问题,感觉是gpt又偷偷更新了🫠

**Comment by maoqishuxi** [comment]
同遇到此问题

**Comment by justsonghua** [comment]
同样遇到这个问题，大概就是21号下午3点左右就不行了(东一时区)。

**Comment by leozww** [comment]
同样出现了此问题. 感觉GPT又动了什么手脚

**Comment by lmk123** [comment]
v10.4.6 已修复此问题。

**Comment by justsonghua** [comment]
大佬，在哪里可以找到 v10.4.6 的包呐？

**Comment by lmk123** [comment]
> 在哪里可以找到 v10.4.6 的包呐？

@justsonghua  稍等 5 分钟，正在发布，发布完之后我会在这里留言

**Comment by lmk123** [comment]
v10.4.6 已修复此问题，可以通过离线安装包立刻升级，见 https://hcfy.app/docs/installv2/offline
