### ISSUE TITLE
MacOS网页全文翻译时，会跳转到谷歌翻译页面

### ISSUE THREAD

**Issue by chaniqure** [hcfyapp/crx-selection-translate#1900]
## 基本信息

划词翻译版本：v10.4.4
浏览器版本：chrome 119.0.6045.159（正式版本） (arm64)，edge 119.0.2151.72 (正式版本) (arm64)

操作系统：MacOS

## 重现问题的步骤

1.在进行网页全文翻译操作时

### 预期行为
翻译整个页面

### 实际行为
页面会切到谷歌翻译页面，然后再退回来，页面倒是翻译了，只是每次滑动到没有翻译的地方时，又会跳转到谷歌翻译界面
<img width="1141" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/25723223/dec01525-c910-46eb-bc20-10f0f9935572">

**Comment by chaniqure** [comment]
https://github.com/hcfyapp/crx-selection-translate/assets/25723223/5aee453e-cb57-405a-9354-137dc269d6db

**Comment by chaniqure** [comment]
https://github.com/hcfyapp/crx-selection-translate/assets/25723223/f108a6ef-41a1-4a2c-92b4-baa8a5c803a7

**Comment by lmk123** [comment]
原因是你启用了“速度慢、准确率高”的谷歌翻译，切换回”速度快、准确率低”即可，切换方法及详细说明见 https://hcfy.app/docs/faqs/why-result-different
