### ISSUE TITLE
DeepL 翻译经常会漏掉一段

### ISSUE THREAD

**Issue by SouthWindLoki** [hcfyapp/crx-selection-translate#1903]
## 基本信息

划词翻译版本：最新版本
浏览器版本：Chromium Engine Version 119.0.6045.159
操作系统：macos 14.1

## 重现问题的步骤

1.https://every.to/p/how-to-build-a-better-social-network 打开这个网站，然后开启全文翻译
2.选择DeepL
3.

### 实际行为
![image](https://github.com/hcfyapp/crx-selection-translate/assets/46105304/63a7a2ab-f622-41aa-9fd8-032e16ea63ec)
这部分只翻译了一半

**Comment by lmk123** [comment]
你需要登录 DeepL 账号：https://hcfy.app/docs/faqs/deepl-limit

<img width="748" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/164ab80e-aefb-47a1-babe-5622b6658963">
