### ISSUE TITLE
使用划词翻译内置PDF阅读器添加文字注释并保存后无法在其他软件看到注释内容或出现乱码

### ISSUE THREAD

**Issue by Wapitisang** [hcfyapp/crx-selection-translate#1906]
## 基本信息

划词翻译版本：v10.4.5
浏览器版本：Chrome 版本 118.0.5993.117（正式版本） （64 位）
操作系统：Ubuntu 20.04

## 重现问题的步骤

1.在内置pdf阅读器中添加注释（如在侧边添加文字）后保存的文件在其他软件（如wps pdf和系统自带pdf阅读器、chrome阅读器）无法看见注释，但该文件通过内置pdf重新打开能够正确显示注释
![image](https://github.com/hcfyapp/crx-selection-translate/assets/97203875/71a02f40-5ca4-4c0e-b2ef-452cd504d859)
上图为添加的注释，下图为在其他地方打开的pdf版本
![image](https://github.com/hcfyapp/crx-selection-translate/assets/97203875/5c121a1a-8543-4064-9a71-7c84b93e9f21)

### 预期行为
正确显示注释文字
### 实际行为
注释文字缺失或乱码
### 补充信息
文字不显示的问题可能与文字大小有关，我使用最小的注释文字大小通过其他软件打开pdf无法看见注释，但将注释文字调大后重新测试其他软件内显示的注释为乱码

**Comment by lmk123** [comment]
我试了一下，注释在 Chrome 自带 PDF 阅读器不会显示，在  macOS 的“预览” APP 里会显示。

但这个问题我没法解决 :joy:

内置 PDF 阅读器是一个单独的第三方软件，不是我自研的，我能做的就是在它发布新版本之后尽快更新进来 :joy:
