### ISSUE TITLE
请不要未经允许的情况下偷偷用我的GPTToken，会导致我GPT封号的

### ISSUE THREAD

**Issue by cuuc20072008** [hcfyapp/crx-selection-translate#1908]
![image](https://github.com/hcfyapp/crx-selection-translate/assets/37201595/b529a24b-90b5-4f6d-b998-d71171915e48)
我现在已经卸载了，希望好好改进这个问题，我现在对它的安全性很失望！！

**Comment by lmk123** [comment]
之所以出现这条消息，是因为你在划词翻译启用了 ChatGPT（划词翻译默认是不会启用的）且没有填写 OpenAI Token，所以划词翻译使用了 ChatGPT 网页版（也就是你截图里的 chat.openai.com）接口，相当于自动在 ChatGPT 网页版发送了翻译命令，然后获取到翻译结果。

这几乎是所有免 Token 使用 ChatGPT 的方式，不存在“偷偷”，这跟安全性没太大关系，毕竟这里面的消息都是你自己触发的翻译，划词翻译并没有擅自发送别的消息。

如果你不希望这里出现消息，那么不要启用 ChatGPT，或者你自己去申请一个 OpenAI Token 填写进划词翻译。

**Comment by oodzchen** [comment]
@lmk123 提两个建议
1. 把 ChatGPT 和 OpenAI API 分开称呼，避免混淆了，毕竟对 OpenAI 官方来说这也是两个服务，用的是两套付费渠道
2. 建议报错的时候在页面某个地方显示接口返回的错误代码等数据，有可能是网络错误也有可能是接口使用超额了，暴露错误一方面方便用户自己排查，一方面反馈给你们的时候也更详细

**Comment by lmk123** [comment]
@oodzchen 

1. 已新开 issue #1930
2. 这个其实已经有计划了 😂 #1575
