### ISSUE TITLE
增加一个纯文本的格式，此模式下将待翻译文本中的所有换行、空格去掉，但保留空格，然后提交给API进行翻译

### ISSUE THREAD

**Issue by xiangjunchao** [hcfyapp/crx-selection-translate#1910]
**没有这个功能（改进）的时候，你遇到了什么问题？**
现在的划词翻译，在我翻译从PDF文件中复制的多行文本，或者是源代码中的多行注释的时候，由于没有去掉默认含有的回车，制表符和注释符号等，导致翻译效果很不好。一个个手动删除又太麻烦，在记事本里替换也要多开一个窗口。

**你想要如何解决你的问题？**
可以增加一个纯文本格式，此格式下自动过滤“\n”、“\t”和“#”，这样就解决了问题。

**Comment by lmk123** [comment]
其实这个模式已经有了。

你可以把这些文本保存成 .txt 文件，然后在 chrome 浏览器里打开，然后开启全文翻译。划词翻译在对 .txt 文件内容进行全文翻译时，会自动去掉换行符（但会保留两个及以上的连续换行符）

又或者，你可以在划词翻译的设置里开启【源文本处理】里的【去掉换行符】。

你可以先试一下上面说的这两个办法，如果还是觉得不够好，可以继续留言，我看看要怎么改进

**Comment by lmk123** [comment]
由于长时间无反馈，所以默认已解决。
