### ISSUE TITLE
百度翻译专业版汉译英报错

### ISSUE THREAD

**Issue by radian-ing** [hcfyapp/crx-selection-translate#1912]
## 基本信息
划词翻译版本：10.4.6
浏览器版本：Google Chrome
版本 119.0.6045.200（正式版本） （64 位）
操作系统：windows 10 

## 重现问题的步骤

1.打开划词翻译输入中文
2.百度翻译专业版汉译英异常
3.但是百度翻译专业版英译汉可以正常工作,希望汉译英也可以正常工作
![image](https://github.com/hcfyapp/crx-selection-translate/assets/62878451/3140616a-e379-4e74-af95-099d8279e875)

### 预期行为
百度翻译专业版 汉译英可以正常翻译
### 实际行为
百度翻译专业版 报错
![image](https://github.com/hcfyapp/crx-selection-translate/assets/62878451/c33bb029-9b75-4bcd-8b5b-bd7101405fde)

**Comment by lmk123** [comment]
感谢反馈，这是因为百度翻译专业版更新了领域类别，需要划词翻译同步更新，预计下个版本更新完毕

相关链接：https://fanyi-api.baidu.com/doc/22
