### ISSUE TITLE
新版本的内置PDF阅读器没有了总页数信息和搜索时匹配数信息

### ISSUE THREAD

**Issue by PGuardRing** [hcfyapp/crx-selection-translate#1914]
**没有这个功能（改进）的时候，你遇到了什么问题？**
旧版本的PDF阅读有这两项信息，我可以只用划词翻译看PDF，现在我必须开一个浏览器原生PDF阅读器窗口用来查找，另一个划词翻译PDF阅读器窗口用来翻译

**你想要如何解决你的问题？**
总页数信息比如
![图片](https://github.com/hcfyapp/crx-selection-translate/assets/102495819/966a2b24-a892-4b1c-ab5e-8ad029da1803)
搜索时匹配数量信息比如
![截图_20231219095734](https://github.com/hcfyapp/crx-selection-translate/assets/102495819/56820d2e-1af0-417e-8dab-dc0d0adad10e)
**补充信息**
总页数信息没什么用，但是搜索功能的残缺让我觉得这个PDF阅读器无法使用

**Comment by lmk123** [comment]
感谢反馈，我已重现此问题，将在下个版本中修复

**Comment by lmk123** [comment]
另外，同样的问题也造成了内置 PDF 阅读器没有显示中文界面，一并解决了。

**Comment by lmk123** [comment]
修复后会以如下方式显示匹配数量，且界面变成了中文

<img width="796" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/946e9caf-58c2-410b-b1c7-93794a382490">

**Comment by lmk123** [comment]
v10.5.0 离线安装包已发布，你可以立刻升级到这个版本 https://hcfy.app/docs/installv2/offline
