### ISSUE TITLE
ChatGPT 支持更改openai的endpoint

### ISSUE THREAD

**Issue by horizon86** [hcfyapp/crx-selection-translate#1915]
**没有这个功能（改进）的时候，你遇到了什么问题？**
有国内供应商提供openai兼容的接口，但是endpoint不是openai的，是自己的。避免打广告这里就不说是哪家了。

**你想要如何解决你的问题？**
支持更改chatgpt发起请求使用的url，而不是固定为https://api.openai.com

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
我觉得这个方案可以实现

**补充信息**
购买正品openai key很麻烦很困难，没有信用卡没法弄

**Comment by lmk123** [comment]
已有功能，在划词翻译设置 - 第三方服务 - ChatGPT - 镜像地址 里

**Comment by yylt** [comment]
![image](https://github.com/hcfyapp/crx-selection-translate/assets/34183906/ff74e209-3393-4207-8d12-7c6b8b48b1ca)

设置镜像地址，但是并未生效，

版本 v10.5.1

**Comment by lmk123** [comment]
我明白了，你说的是 API Endpoint 吧，那我下个版本加一个选项

**Comment by lmk123** [comment]
已新开了一个 issue #1954，后续进展可以关注此 issue

**Comment by lmk123** [comment]
下个版本将支持修改 ChatGPT 镜像地址的 Endpoint，详细说明见 https://hcfy.app/docs/log/#10-5-2
