### ISSUE TITLE
输入框文字 [直接翻译并替换] 功能

### ISSUE THREAD

**Issue by wangmos** [hcfyapp/crx-selection-translate#1916]
**没有这个功能（改进）的时候，你遇到了什么问题？**
现在是输入完,全部选中,然后翻译.
翻译完后,选择复制,再粘贴到输入框替换.

**你想要如何解决你的问题？**
增加一个快捷键,或者定义触发按键,一键将输入框文字翻译为目标语言.

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
应该可以的.沉浸式翻译有这个功能.连敲三个空格可以实现.

**补充信息**
参考沉浸式翻译这个插件.咱们可以设置快捷键或者触发键.

**Comment by lmk123** [comment]
这个功能其实已经有人提过了 :joy: 已提高此功能优先级，见 #1513
