### ISSUE TITLE
可以增就 Gemini 谷歌翻译么

### ISSUE THREAD

**Issue by lhj5426** [hcfyapp/crx-selection-translate#1917]
目前是免费的  1分钟60次
https://makersuite.google.com/app/apikey 
有时候翻译 挺接地气的 
不知道开发者能不能安排上

**Comment by lmk123** [comment]
可以

**Comment by oubeichen** [comment]
+1 确实需要这个，在隔壁插件用了下挺好用的

**Comment by yemingshen** [comment]
是这样的，好多人都推荐**Gemini**，作者只要把加入**Gemini API**的接口做出来就可以了！

**Comment by psstores** [comment]
可以添加gemini 接口的翻译功能

**Comment by realDGD** [comment]
同求 Gemini

**Comment by lmk123** [comment]
v10.6.0 已增加 Gemini

**Comment by lhj5426** [comment]
![image](https://github.com/hcfyapp/crx-selection-translate/assets/30548000/54caffb3-8d56-4dc7-80c3-a34f04d5d00a)
3Q
