### ISSUE TITLE
网页全文翻译的时候提供选择翻译区域的选项

### ISSUE THREAD

**Issue by oodzchen** [hcfyapp/crx-selection-translate#1918]
**没有这个功能（改进）的时候，你遇到了什么问题？**
使用ChatGPT进行网页全文翻译的时候，经常会把整个网页都翻译了，但其实我只需要翻译文章主体内容（即article元素里的内容），但是却经常把推荐列表、导航、菜单等内容也翻译了，这些地方一般没有什么翻译价值，重复翻译这些内容反而浪费token了

**你想要如何解决你的问题？**
在翻译之前自动选择文章主体部分，并让用户调节选中区域的大小，类似Evernote网页剪藏功能，然后只翻译用户选择的区域

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
暂无

**补充信息**
Evernote的剪藏功能，我觉得实现的很好，效果如下：
![Screenshot_20231225_152351](https://github.com/hcfyapp/crx-selection-translate/assets/9650699/d7e1dd1b-926d-4856-8971-72e78444a658)

**Comment by lmk123** [comment]
这个功能其实已经在开发计划当中了 :joy: #1406 

只是最近忙于更新 Manifest V3 所以功能更新估计要暂停了
