### ISSUE TITLE
网页全文翻译出现个别段落没有翻译全的问题

### ISSUE THREAD

**Issue by vzhentian97** [hcfyapp/crx-selection-translate#1920]
## 基本信息

划词翻译版本：v10.4.6
浏览器版本：120.0.2210.91 
操作系统：Windows

### 预期行为
<img width="581" alt="Snipaste_2023-12-25_17-21-52" src="https://github.com/hcfyapp/crx-selection-translate/assets/38022237/242b0b90-0681-46df-ac15-46ef3d02783f">

### 实际行为
<img width="528" alt="Snipaste_2023-12-25_17-22-26" src="https://github.com/hcfyapp/crx-selection-translate/assets/38022237/38dc1fd4-64fe-4fa0-b272-bc16362f8735">

### 补充信息
似乎以前没发生过类似情况

**Comment by lmk123** [comment]
见 https://hcfy.app/docs/faqs/deepl-limit
