### ISSUE TITLE
deepl朗读功能失效，google的第一次朗读缺少字母，第二次才是完整的

### ISSUE THREAD

**Issue by ironald** [hcfyapp/crx-selection-translate#1921]
deepl朗读功能失效，google的第一次朗读缺少字母，第二次才是完整的

**Comment by lmk123** [comment]
虽然你关闭了这个 issue 但我还是试了一下 :joy:

我翻译了 “I went to a concert yesterday, but it rained.”，测试结果如下：

- DeepL 是能正常朗读的
- 谷歌翻译的朗读是正常的，没有出现“第二次才完整”的问题

如果你仍然有这些问题，麻烦提供一下更详细的重现步骤，比如你翻译了什么文本、使用什么操作系统 / 浏览器、划词翻译里的语音设置有没有改过等等
