### ISSUE TITLE
右键网页全文翻译无反应

### ISSUE THREAD

**Issue by jmgaooo** [hcfyapp/crx-selection-translate#1922]
## 基本信息

划词翻译版本：10.4.6
浏览器版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
操作系统：windows

## 重现问题的步骤

1.浏览器打开https://api.dart.dev/stable/3.2.4/dart-html/dart-html-library.html
2.右键划词翻译

### 预期行为
执行全文翻译动作
### 实际行为
无反应

**Comment by lmk123** [comment]
已重现，但是这个问题意外的棘手……

<details>
<summary>详细说明</summary>

报错的地方在 axios 里的下面这段代码：

```js
const hasStandardBrowserWebWorkerEnv = (()=>{
  return (typeof WorkerGlobalScope !== 'undefined' && // eslint-disable-next-line no-undef
    self instanceof WorkerGlobalScope && typeof self.importScripts === 'function');
}
)();
```

而报错的原因是因为这个网页上有一个 id 正好是 `WorkerGlobalScope` 的 html 元素，所以这段代码里的 `WorkerGlobalScope` 不是 `undefined`

要解决这个问题，目前看来只有完全替换掉 axios :joy: 这工作量就大了
</details>

**Comment by jmgaooo** [comment]
😂id这个特性太坑了，覆盖这些特殊的全局变量可能会简单点

**Comment by lmk123** [comment]
机智！已经用覆盖全局变量的方式修复了此问题
