### ISSUE TITLE
在使用了 React SSR 技术的网站无法正常翻译

### ISSUE THREAD

**Issue by CodFrm** [hcfyapp/crx-selection-translate#1923]
## 基本信息

划词翻译版本：10.4.6
浏览器版本：Edge 120.0.2210.91
操作系统：MacOS

## 重现问题的步骤

访问remix文档站，划词翻译：https://remix.run/docs/en/main/start/quickstart

### 预期行为

可以显示出翻译按钮，进行翻译

### 实际行为

不显示翻译按钮 无法翻译

**Comment by lmk123** [comment]
重现了，且控制台报“Minified React error”错误，目测跟 Remix 使用了 React SSR 有关

相关问题：#1689
