### ISSUE TITLE
划词翻译出来的结果里面只有英语  为啥没有美语

### ISSUE THREAD

**Issue by haobarry** [hcfyapp/crx-selection-translate#1926]
如题

**Comment by lmk123** [comment]
划词翻译只是翻译服务的搬运工，如果翻译服务没提供，那么划词翻译也没法造一个出来。

如果你确认翻译服务有美音但划词翻译没显示出来，那麻烦提供更详细的说明，比如“我在必应词典 dict.bing.com/dict 翻译单词test的时候它提供了美音，但划词翻译没有”
