### ISSUE TITLE
全文翻译规则 选择翻译或者不翻译的规则

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1928]
CSS选择器决定要翻译那些，比如看reddit没必要把别人用户名翻译
一些翻译插件有云规则和自定义规则[源代码](https://github.com/fishjar/kiss-translator)

**Comment by lmk123** [comment]
此功能已在开发计划中 :joy:

**Comment by lmk123** [comment]
ref: #1406
