### ISSUE TITLE
选中文本无法翻译

### ISSUE THREAD

**Issue by lengmianshi** [hcfyapp/crx-selection-translate#1929]
## 基本信息

划词翻译版本：v10.4.4
浏览器版本：chrome v120.0.6099.129
操作系统：mac

选中文本，没有自动弹出翻译按钮，右键翻译选中的文本也无法弹出翻译窗口

比如这个页面：https://reactrouter.com/en/main/start/tutorial

**Comment by lmk123** [comment]
感谢反馈，已确认跟 #1923 是同一个问题
