### ISSUE TITLE
VIP账号，但配置的KEY不能同步；

### ISSUE THREAD

**Issue by Cazaea** [hcfyapp/crx-selection-translate#1931]
## 基本信息

划词翻译版本：

- 划词翻译 v10.5.0

浏览器版本：

- Edge版本：      120.0.2210.91 (正式版本) (64 位)
- Chrome版本： 120.0.6099.130（正式版本）（64 位）

操作系统：

- 版本	                Windows 11 专业版
- 版本	                23H2
- 安装日期	‎        2022.‎09.‎29
- 操作系统版本	22631.2861
- 体验	                Windows Feature Experience Pack 1000.22681.1000.0

## 重现问题的步骤

1.购买了永久会员并登录了账号；
2.Chrome配置了各平台翻译平台API的key；
3.Edge浏览器下载插件，登录账号key不能同步；

### 预期行为
登录账号，自动同步配置信息；

### 实际行为
配置的key不能同步；

### 补充信息

无补充。

**Comment by lmk123** [comment]
这是特意为之的，跟是否是会员没有关系 :joy: 详细说明见 https://hcfy.app/docs/faqs/safe#safe-key

**Comment by Cazaea** [comment]
这样确实看起来很安全，但我失去了开通VIP的意义，哈哈。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hcfyapp/crx-selection-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月2日(星期二) 中午1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hcfyapp/crx-selection-translate] VIP账号，但配置的KEY不能同步； (Issue #1931)





 
这是特意为之的，跟是否是会员没有关系 😂 详细说明见 https://hcfy.app/docs/faqs/safe#safe-key
