### ISSUE TITLE
独立翻译窗口同时勾选“自动复制”与“持续监听剪切板”导致中英循环互译

### ISSUE THREAD

**Issue by LdsDante** [hcfyapp/crx-selection-translate#1932]
## 基本信息

划词翻译版本：10.5.0
浏览器版本：chrome 120.0.6099.130
操作系统：windows 10

## 重现问题的步骤

1. 在独立翻译窗口同时勾选“自动复制”与“持续监听剪切板”选项
2. 复制任意待翻译英文文本

### 预期行为
复制待翻译英文文本后，独立翻译窗口正确翻译为中文并将翻译结果复制至剪切板中
### 实际行为
翻译成功后，因自动将翻译结果复制至剪切板中，导致重新对翻译结果执行翻译功能，将其翻译回英文后进入互译的循环
### 补充信息
建议标识执行了“自动复制”行为，并不对此剪切板中的内容进行翻译

**Comment by LdsDante** [comment]
![example](https://github.com/hcfyapp/crx-selection-translate/assets/49384840/b7c8ff40-5d52-46b3-9df0-df5aaaccefda)

**Comment by lmk123** [comment]
感谢反馈，确实有这个问题，将尽快修复
