### ISSUE TITLE
点击扩展按钮和从任务栏托盘启动时时弹出独立翻译窗口

### ISSUE THREAD

**Issue by cgldimo** [hcfyapp/crx-selection-translate#1933]
如题，由于经常将外部程序和划词翻译配合使用，因此希望在点击扩展按钮时直接打开独立翻译窗口

此外，在从任务栏的Edge图标中点击划词翻译时，自动打开的是设置界面，希望这里也可以配置成打开独立翻译窗口

**Comment by lmk123** [comment]
> 在点击扩展按钮时直接打开独立翻译窗口

可以，我会加个选项

> 从任务栏的Edge图标中点击划词翻译时

这个我没有理解，我主要用 macOS 系统，然后任务栏的 Edge 图标是没法打开划词翻译的。。可否提供一下截图之类的让我明白具体是怎样打开的划词翻译？

**Comment by cgldimo** [comment]
<img width="474" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/151028427/0fdbf9ab-f78b-4f64-895f-f1cabaf72bf3">

类似如此的情况，划掉的是后台运行的其他扩展

在此处点击划词翻译会打开设置

（但下面那个扩展我试着点了一下也是打开设置，这里是不是有特殊的说法……？）

**Comment by lmk123** [comment]
原来是这里，明白了。这里的点击行为我猜测是改不了的，但我会尝试一下。

<details>
<summary>备注：具体描述</summary>

1. 使用 Windows 操作系统
2. 勾选划词翻译的【关闭浏览器后继续运行划词翻译】，然后关闭 Edge 后，Edge 图标会出现在任务栏托盘里
3. 右键单击 Edge 的托盘图标，可以在【个人】菜单项里看到在后台运行的所有扩展程序，其中包括划词翻译，见上一条评论的图
4. 点击【划词翻译】，会打开划词翻译的设置页，需要尝试一下能否改成其它页面

</details>

**Comment by lmk123** [comment]
下个版本在【划词翻译设置】-【其它】-【扩展按钮】添加了一个新的选项【打开独立翻译窗口】

从任务栏的 Edge 图标中点击划词翻译时的行为没法改变 :joy:
