### ISSUE TITLE
使用【必应词典】会导致无法使用 Bing AI

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#1934]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

使用必应词典功能时，似乎会浏览到国内的bing网站，给edge浏览器增加国内bing的cookie。这会导致使用bingAI失效。请问能不能加一个功能，将bing翻译的选项设置成走代理或者走国际版bing？

### 补充信息

来源：@HugoXANA https://github.com/hcfyapp/crx-selection-translate/issues/1271#issuecomment-1878161962

**Comment by lmk123** [comment]
必应词典其实就相当于用浏览器访问了一次 https://www.bing.com/dict/search?q=test&cc=cn 这样的网页，但是这个网址本身应该就属于国际版的 bing 才对

我没有用过 Bing AI，可否提供一下更详细的说明，比如 bing ai 具体指哪里、“失效”具体表现是报错了还是别的什么？

**Comment by HugoXANA** [comment]
## 基本信息
划词翻译版本：10.4.6
浏览器版本：edge-beta 版本 121.0.2277.4 (正式版本) beta (64 位)
操作系统：win11
此问题在ubuntu22.04上也有出现。
## bingAI无法连接
在国内使用BingAI，不论是网页版，还是edge侧边栏版本，需要保证浏览器内没有bing.com的cookie。即不访问国内的bing。
如果浏览器内有任何bing.com的cookie，则网页版bing会重定向回国内的bing页面，chat窗口及chat(或copilot)选项会消失。而侧边栏版本会直接提示类似“很抱歉，目前无法连接到服务。请稍后重试或刷新”之类的话。
## 实际行为
在使用edge浏览器清除所有关于bing的cookie后，     
+ 根据@lmk123的描述，访问 https://www.bing.com/dict/search?q=test&cc=cn 网页，
+ 使用划词翻译插件内的必应词典功能，
+ 在搜索引擎中搜索“必应词典”，并点击进入必应词典页面后，     

浏览器内会重新出现 bing.com的多个cookie，bingAI会立即无法连接。

遇到此种情况，清除与bing有关的所有cookie，重启edge浏览器后，bingAI可再次连接。
尝试过在浏览器中使用微软翻译功能，此时虽然会留下与bing有关的cookie，但是bingAI仍然可以连接。

**Comment by lmk123** [comment]
很感谢你的详细重现步骤。

> 将bing翻译的选项设置成走代理

浏览器扩展程序没有提供让特定 url 的访问走代理的功能，所以这一点无法做到 :joy:

如果你有梯子的话，可以加一条规则，让 www.bing.com 通过国外 IP 访问。

> 或者走国际版bing

最开始的时候，划词翻译是通过 `cn.bing.com` （即 [https://cn.bing.com/dict/search?q=test](https://cn.bing.com/dict/search?q=test)）访问必应词典的，国内版的必应词典有个限制，只能使用国内的 IP 访问才有结果。

然后有人反馈说可以改为使用国际版必应词典：

- https://github.com/hcfyapp/crx-selection-translate/issues/1724

国际版必应词典无论是不是国内 IP 都有结果，所以我改成了 `www.bing.com`（即
[https://www.bing.com/dict/search?q=test&cc=cn](https://www.bing.com/dict/search?q=test&cc=cn)）。

你可以试一下访问国内版必应词典 [https://cn.bing.com/dict/search?q=test](https://cn.bing.com/dict/search?q=test) 后看看 Bing AI 能不能正常使用，如果能的话，我可以加个选项，允许用户选择这两个网址的其中一个来访问必应词典。

如果用国内版必应词典还有这个问题，那么这个问题是没法从划词翻译这边解决的 :joy:

**Comment by lmk123** [comment]
我用 edge 128 试了一下：

- 打开 Edge 浏览器后，访问 https://www.bing.com/dict/search?q=test&cc=cn ，然后打开浏览器右上角的 bing ai 会提示“该服务在你所在的地区不可用”；完全重启 edge 浏览器后，直接打开 bing ai 没有这个提示了。
- 打开 Edge 浏览器后，先打开 bing ai，再访问链接，然后在 bing ai 尝试对话，是正常的。

这属于 bing ai 的限制了，如果要划词翻译来做的话，需要多一个 cookies 权限，这估计会引来用户质疑。

未来我打算加入更多词典源，届时换用其它词典就不会有这个问题了
