### ISSUE TITLE
希望可以优化一下翻译的网页排版和语言识别

### ISSUE THREAD

**Issue by halw001** [hcfyapp/crx-selection-translate#1937]
**没有这个功能（改进）的时候，你遇到了什么问题？**
1.网页全文翻译会遇到排版错误
2.有时候会出现已经选择了目标语言为中文，但是英文网页点击全文翻译的结果还是英文
![t1](https://github.com/hcfyapp/crx-selection-translate/assets/23332715/78febe22-fb94-4bf5-92e6-70ab08f157bc)
![t3](https://github.com/hcfyapp/crx-selection-translate/assets/23332715/ef7eb788-5ddc-4718-a7f7-50e36f5be3b5)

**你想要如何解决你的问题？**
优化一下上面出现的两个问题

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
“沉浸式翻译”这个插件好像对一些常见网站有专门的适配，希望可以对谷歌，脸书，推特，discord，telegram，reddit，stackover flow等常用网站做一下排版适配。

**补充信息**
用“沉浸式翻译”这个插件就没有这些问题
![t2](https://github.com/hcfyapp/crx-selection-translate/assets/23332715/1cb75af6-2bdf-4db2-a442-171010460c06)

**Comment by lmk123** [comment]
其实也在开发计划里了 :joy: #1913
