### ISSUE TITLE
希望可以添加自动翻译特定域名网站的功能

### ISSUE THREAD

**Issue by halw001** [hcfyapp/crx-selection-translate#1938]
**没有这个功能（改进）的时候，你遇到了什么问题？**
希望可以自动翻译某些网站

**你想要如何解决你的问题？**
![t4](https://github.com/hcfyapp/crx-selection-translate/assets/23332715/f162f3f8-7e9e-4467-b374-8adddd040926)

**补充信息**
最近同时使用划词翻译和沉浸式翻译这两个插件，有些不错的功能希望作者可以参考一下

**Comment by lmk123** [comment]
已在开发计划当中 :joy: #1519
