### ISSUE TITLE
github上 网页翻译没有反应

### ISSUE THREAD

**Issue by visiLi** [hcfyapp/crx-selection-translate#1939]
## 基本信息
与部分GitHub功能相关的油猴脚本应该存在冲突！
划词翻译版本：v10.4.6
浏览器版本：谷歌121
操作系统：win11

## 重现问题的步骤

![image](https://github.com/hcfyapp/crx-selection-translate/assets/42717403/cd0aeb8b-6bc0-4f42-a851-b0cf441849b7)

### 补充信息

原因很明确 停用这两个脚本 即可回复翻译功能

**Comment by lmk123** [comment]
我觉得这个问题不属于划词翻译的范围。。

划词翻译不可能兼容所有这种可能造成问题的油猴脚本或者插件，而且这些插件的代码会随时变动，它们变了那么划词翻译也得跟着改兼容代码，效率太低了。
