### ISSUE TITLE
安装扩展后，edge无法使用后台运行功能

### ISSUE THREAD

**Issue by scruel** [hcfyapp/crx-selection-translate#1941]
## 基本信息

划词翻译版本：10.5.1
浏览器版本：Microsoft Edge 版本 121.0.2277.4 (正式版本) dev (64 位)
操作系统：Win 11 Workstation edition

## 重现问题的步骤

1. 安装划词翻译，并在 设置-系统 中启用“在 Microsoft Edge 关闭后继续运行后台扩展和应用”功能
2. 点击右上角 x 关闭浏览器
3. 检查任务管理器，发现 msedge 进程全部消失
4. 禁用划词翻译，重复步骤 2 关闭浏览器，msedge 进程正常保留，其他插件的全局热键也都保持有效

### 预期行为
使用划词翻译插件时，edge 能正常在后台运行，并且支持使用全局热键呼出独立窗口

### 实际行为
使用划词翻译插件时，edge 无法后台运行（即便相关功能已启用），且会导致后续 edge 直接无法打开

### 补充信息
后续还导致 edge 无法打开，错误报告：
[Report.txt](https://github.com/hcfyapp/crx-selection-translate/files/13875189/Report.txt)

**Comment by lmk123** [comment]
错误报告翻了一下，看不懂 :joy:

你似乎没有在划词翻译里勾选【让划词翻译在后台持续运行】，你勾选一下试试？ https://hcfy.app/docs/guides/extra#close-browser

**Comment by scruel** [comment]
可行了，重装忘记改这个设置了，不过为啥会这样（

**Comment by lmk123** [comment]
我感觉是edge的bug，毕竟chrome没出现过这样奇怪的问题:joy:

**Comment by lmk123** [comment]
你好 @scruel ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
