### ISSUE TITLE
同一个页面多种语言翻译问题

### ISSUE THREAD

**Issue by SagiriChen1** [hcfyapp/crx-selection-translate#1942]
## 基本信息

划词翻译版本：划词翻译 v10.4.6
浏览器版本：Microsoft Edge 版本 120.0.2210.121 (正式版本) (64 位)
操作系统：win10

## 重现问题的步骤

1.打开一个网页，内含日语和英语
2.打开翻译功能，翻译日语和英语

### 预期行为 
将日语和英语翻译为目标语言

### 实际行为 
 仅有一种语音翻译为目标语音，另一种语音不会翻译为目标语言

**Comment by lmk123** [comment]
这里有对这个问题的说明 https://hcfy.app/docs/guides/page#yyy

后续会加个新的模式【逐句模式】来彻底解决这个问题， 但它可能会造成翻译服务暂停使用的问题，这里有详细说明 

- https://github.com/hcfyapp/crx-selection-translate/issues/1712
