### ISSUE TITLE
DeepL 的认证密钥和验证密钥是一回事吗？我按照认证教程没有找到认证密钥

### ISSUE THREAD

**Issue by elijahchan2019** [hcfyapp/crx-selection-translate#1943]
<img width="705" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/51269401/8907d16c-06b9-434a-91a0-fcb276fad1b2">
<img width="1214" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/51269401/f1ca777b-9655-42df-aebe-2788e3612adb">

如图所示，只能看到账号的验证密钥，而按照教程进去的网页上，认证密钥是空的

**Comment by lmk123** [comment]
感谢反馈，试了一下，【认证密钥】那里确实没有了。

其实【验证密钥】就是划词翻译 DeepL 需要的【Authentication Key】，我刚才更新了文档（可能要 5 分钟后才会看到改变） https://hcfy.app/docs/services/deepl

**Comment by elijahchan2019** [comment]
好的，其实昨天我已经按照验证密钥去设置，但是今天看到我的用量依旧是0，以为没有成功使用密钥，所以才来发问。（用量更新比较慢？我已经翻译了好几个网页了

**Comment by lmk123** [comment]
有两种可能：

- DeepL 官方的用量更新慢，但这一点我不确定
- 如果划词翻译在使用你的 DeepL 密钥时报错了，那么会改为使用划词翻译内置的免密钥 DeepL 进行翻译。
    - 也就是说你的密钥可能有问题无法正常使用，所以其实一直都没有用密钥在使用 DeepL

**Comment by elijahchan2019** [comment]
但是在使用过程中，确实没有发现报错的情况。今天查了下用量，还是0，太神奇了。

**Comment by lmk123** [comment]
DeepL 密钥报错的时候，如果划词翻译内置的免密钥 DeepL 没报错，那就会正常显示翻译结果，你也不知道密钥有没有报错 :joy:

除非内置的免密钥 DeepL 也报错了，那你才会看到报错消息
