### ISSUE TITLE
截图翻译的意见

### ISSUE THREAD

**Issue by msxqqq** [hcfyapp/crx-selection-translate#1944]
目前的效果：目前的截图翻译是识别文字之后，直接在文本框中翻译。不够直观，排版乱。

我希望的：截图之后直接在图片文字原本的位置翻译。（参考：QQ截图翻译，微信截图翻译，企业微信截图翻译）

改后的好处：更加直观的看到翻译结果，方便对照。

（碎碎念：为啥截图翻译开了全局快捷键还是只能在edge里面用啊？）

**Comment by lmk123** [comment]
你想要的其实是图片翻译成图片的效果，这需要接入额外的翻译接口。这一点其实已经在开发计划里了，将会在我完成对划词翻译的 Manifest V3 改造后加入进去。

> 为啥截图翻译开了全局快捷键还是只能在edge里面用啊？

因为扩展程序没有提供截取电脑桌面的能力 :joy:

**Comment by msxqqq** [comment]
那可真是太好了，希望能早日完成。针对《扩展程序没有提供截取电脑桌面的能力》这个是不是只有浏览器支持才能解决啊

**Comment by lmk123** [comment]
> 《扩展程序没有提供截取电脑桌面的能力》这个是不是只有浏览器支持才能解决啊

是的，浏览器扩展程序现在只提供了对浏览器内的网页进行截图的能力
