### ISSUE TITLE
有计划支持通用的AI接口吗

### ISSUE THREAD

**Issue by oodzchen** [hcfyapp/crx-selection-translate#1946]
**没有这个功能（改进）的时候，你遇到了什么问题？**
向在翻译插件上配置Gemini Pro或者其他AI接口，但是没有相关选项

**你想要如何解决你的问题？**
可以自定义AI接口，包括自定义接口URL、密钥等等

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
暂无

**补充信息**
暂无

**Comment by lmk123** [comment]
我感觉这是个已有功能：自定义翻译源 https://hcfy.app/docs/services/custom-api

你可以先看看这个能不能满足你的需求

**Comment by lmk123** [comment]
你好 @oodzchen  ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
