### ISSUE TITLE
ChatGPT翻译，无返回内容并每次都会新建对话窗口

### ISSUE THREAD

**Issue by justsonghua** [hcfyapp/crx-selection-translate#1949]
## 基本信息

划词翻译版本：v10.5.1
浏览器版本：Chrome 121.0.6167.140
操作系统：Win11 23H2 22631.3085

## 重现问题的步骤

1. 网页选中文本或是PDF选中文本
2. 选择翻译

### 预期行为

1. 翻译窗口中显示翻译后的文本
2. 在ChatGPT界面，只使用一个对话窗口，而不是现在这样，每次翻译都新建对话。

### 实际行为
![image](https://github.com/hcfyapp/crx-selection-translate/assets/41994375/91e70bc0-ada9-47ec-af9c-a46c62702f81)

![image](https://github.com/hcfyapp/crx-selection-translate/assets/41994375/8546f894-013d-4953-a079-03352a59d218)

![image](https://github.com/hcfyapp/crx-selection-translate/assets/41994375/169e9fe8-5a63-4ba2-b481-06a501de4c3f)

**Comment by Delon9Z** [comment]
请问你找到解决方法了吗？我之前用的很好的，2月15号那天突然就不返回内容了，chatgpt页面都还显示翻译的内容，但是返回不到翻译窗口

**Comment by lmk123** [comment]
目测是 ChatGPT 又改通信格式了，需要划词翻译重新做适配 :joy:

**Comment by FlameKm** [comment]
我也是，因为想用gpt翻译英语并纠正语法，很依赖这项功能。但是失效了两周了还没修复，烦恼

**Comment by Delon9Z** [comment]
> 我也是，因为想用gpt翻译英语并纠正语法，很依赖这项功能。但是失效了两周了还没修复，烦恼

目前的解决方法只能是用api，付费

**Comment by FlameKm** [comment]
> > 我也是，因为想用gpt翻译英语并纠正语法，很依赖这项功能。但是失效了两周了还没修复，烦恼
> 
> 目前的解决方法只能是用api，付费

使用镜像也不行么

**Comment by Delon9Z** [comment]
> > > 我也是，因为想用gpt翻译英语并纠正语法，很依赖这项功能。但是失效了两周了还没修复，烦恼
> > 
> > 
> > 目前的解决方法只能是用api，付费
> 
> 使用镜像也不行么

镜像是啥呀 。。。

**Comment by Delon9Z** [comment]
> > > > 我也是，因为想用gpt翻译英语并纠正语法，很依赖这项功能。但是失效了两周了还没修复，烦恼
> > > 
> > > 
> > > 目前的解决方法只能是用api，付费
> > 
> > 
> > 使用镜像也不行么
> 
> 镜像是啥呀 。。。

而且我看网上说可能有封号风险，吓得我改用api了

**Comment by lmk123** [comment]
我建议使用第三方中转服务（也就是上面说的“镜像”，具体说明见 https://hcfy.app/docs/services/chatgpt ），现在 ChatGPT 给 Web API 加了很强的机器人验证，以后估计很难做到以前那种只要登录 ChatGPT 账号就能用的样子了 :joy:

**Comment by Delon9Z** [comment]
> 我建议使用第三方中转服务（也就是上面说的“镜像”，具体说明见 https://hcfy.app/docs/services/chatgpt ），现在 ChatGPT 给 Web API 加了很强的机器人验证，以后估计很难做到以前那种只要登录 ChatGPT 账号就能用的样子了 😂

哦哦，明白了，看起来比api便宜哦

**Comment by rty813** [comment]
我现在用的是付费API，依然出现这种情况
![image](https://github.com/hcfyapp/crx-selection-translate/assets/22488813/abb7ec7b-7255-4f07-b75f-0c57b618cf61)

**Comment by lmk123** [comment]
> 我现在用的是付费API，依然出现这种情况

@rty813 那就是你的付费 API 报错了，然后划词翻译回退到了默认的通过 ChatGPT 网页 API 的方式。你可以确认一下你的付费 API 是否能正常使用

**Comment by lmk123** [comment]
由于 ChatGPT 网页版接口大幅度提升了逆向难度，ChatGPT 的免费试用方式无法再做到扩展程序里的。因此，关闭所有跟 ChatGPT 免费试用方式有关的 issue。
