### ISSUE TITLE
EDGE上能登录，Chrome上不能登录，请问是什么原因呢？

### ISSUE THREAD

**Issue by gaoderjean** [hcfyapp/crx-selection-translate#1952]
## 基本信息

划词翻译版本：EDGE 10.4.6; Chrome 10.5.1
浏览器版本：EDGE 121.0.2277.128 (正式版本) (64 位); Chrome 121.0.6167.185（正式版本）（64 位）
操作系统：Win11

## 重现问题的步骤

1. EDGE，可以登录
2. Chrome，登录时提示“用户名或密码不正确”

**Comment by gaoderjean** [comment]
用户名：gaoder@hotmail.com

**Comment by lmk123** [comment]
两个可能：

1. 账号是区分大小写的，确认一下你在 Chrome 登录的时候有没有输错大小写
2. 你记错密码了，你可以重新设置一个密码 https://hcfy.app/forget.html
