### ISSUE TITLE
11点左右DEEPL全局翻译一直加载无法使用，划词也一直加载无法使用。

### ISSUE THREAD

**Issue by bendanoo66** [hcfyapp/crx-selection-translate#1955]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
无法重现，如下图：

<img width="377" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/8b756e5f-f431-434e-bcb9-f099de82ea99">

麻烦先按照这里的说明排查一下：

https://hcfy.app/docs/services/free#deepl

**Comment by lmk123** [comment]
由于长时间没反馈，我猜测应该是网络原因造成的。这个问题我就先关闭了，如果仍有问题，可以继续留言，我会重新打开。
