### ISSUE TITLE
增加显示音标的功能，便于拼读

### ISSUE THREAD

**Issue by zhukelili** [hcfyapp/crx-selection-translate#1962]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，现有 PDF 不支持标记功能，导致我无法在 pdf 上标记内容。
选中一个单词后，在弹窗页面默认没有显示音标，导致我想学习单词时无法进行拼读，因为功能学习还是很重要的

**你想要如何解决你的问题？**
选中单个单词翻译时，在弹窗页面，默认展示出当前单词对应的音标

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
无

**补充信息**
无

**Comment by zhukelili** [comment]
目前看到google翻译，比如global有/ˈɡlōbəl/，DeepL完全没有,写法与标准的注音有点差别
global | BrE ˈɡləʊbl, AmE ˈɡloʊb(ə)l |

**Comment by lmk123** [comment]
DeepL 没有音标是因为它确实没有提供音标，比如对 test 的翻译：https://www.deepl.com/translator#en/zh/test

划词翻译只是翻译服务的“搬运工”，如果翻译服务本身不提供音标，那么划词翻译也没法变出来 :joy:

**Comment by lmk123** [comment]
谷歌翻译也是同理，你在网页版谷歌翻译里翻译 global 时，它提供的“音标”就是 `/ˈɡlōbəl/`，见 https://translate.google.com/?sl=auto&tl=en&text=global&op=translate

**Comment by zhukelili** [comment]
谢谢解答
