### ISSUE TITLE
OpenAI第三方API翻译，出现报错Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by forkmax** [hcfyapp/crx-selection-translate#1965]
OpenAI第三方API翻译，出现报错Cannot read properties of undefined (reading '0')。
自带ChatGPT翻译，则无法显示翻译内容。

划词翻译版本：10.5.2

## 重现问题的步骤

1. 扩展提供的ChatGPT翻译，无法显示翻译内容。因此选择向第三方购买api
2. 填入接口地址和密钥
3. 选择任一模型
4. 划词，翻译，报错Cannot read properties of undefined (reading '0')

**Comment by lmk123** [comment]
我自己在淘宝上买了个官方的 OpenAI 密钥试了下，是能正常翻译的。我初步判断是你购买的这个第三方 API 没有完全兼容 OpenAI 的官方 API。

或者，如果可以的话，可否通过公众号的方式私信告诉我你所购买的第三方 API 的【接口地址】和【密钥】，我在我这边重现一下。

等我重现完之后，你在第三方 API 那边应该是可以重置密钥的，如果不能的话那还是别给我重现了 :joy:

**Comment by forkmax** [comment]
> 我自己在淘宝上买了个官方的 OpenAI 密钥试了下，是能正常翻译的。我初步判断是你购买的这个第三方 API 没有完全兼容 OpenAI 的官方 API。
> 
> 或者，如果可以的话，可否通过公众号的方式私信告诉我你所购买的第三方 API 的【接口地址】和【密钥】，我在我这边重现一下。
> 
> 等我重现完之后，你在第三方 API 那边应该是可以重置密钥的，如果不能的话那还是别给我重现了 😂

已经发送到您的公众号，烦请查收。我依然报错Cannot read properties of undefined (reading '0')，麻烦验证一下。

**Comment by lmk123** [comment]
我没有收到你的私信，如下图。注意：我在公众号后台只能收到文本和图片类型的私信，其它类型的（比如链接转发）我是看不到的 :joy:

![wwww](https://github.com/hcfyapp/crx-selection-translate/assets/5035625/eab2fa32-bbbf-437f-8978-d51f4ed7f0cb)

**Comment by lmk123** [comment]
已在公众号私信内解决此问题，记得重置你发给我的密钥 :joy:

备注：出现此问题的原因是这个第三方服务提供的接口地址仅仅是一个域名，而真正的接口地址是需要加上后缀 `/v1/chat/completions` 的。已在文档内更新这种情况的说明： https://hcfy.app/docs/services/chatgpt

**Comment by yylt** [comment]
我这里还是有这个问题，版本 10.5.2，输入文本翻译有该问题，但是图片翻译没有问题

这里怎么给大佬发送密钥呢？

**Comment by lmk123** [comment]
@yylt 出现这个问题说明你接口地址填错了，再确认一下你的第三方网站提供的接口地址

**Comment by yylt** [comment]
> @yylt 出现这个问题说明你接口地址填错了，再确认一下你的第三方网站提供的接口地址

这个可以确定没有填错，因为也用于chatbot。

或者哪里能 api 或者 swagger，后端是我提供的，也许response可以更合理，另外 最后一个 sse 数据是 data:[DONE]
