### ISSUE TITLE
新增浏览器外部选中翻译（不需要先复制）

### ISSUE THREAD

**Issue by Archipes** [hcfyapp/crx-selection-translate#1967]
**没有这个功能（改进）的时候，你遇到了什么问题？**
比如，现有 PDF 不支持标记功能，导致我无法在 pdf 上标记内容。

**你想要如何解决你的问题？**
比如，添加 PDF 标记功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
比如，如果划词翻译无法添加 PDF 标记功能，那么至少允许我在别的 PDF 软件里进行划词翻译。

**补充信息**
任何你觉得对这个功能（改进）有帮助的信息，例如别的软件是怎么做的、你觉得这个功能的实用程度如何等。

**Comment by Archipes** [comment]
现在使用外部选中翻译需要将外部的内容先复制，然后control+shift+1， 我想鼠标选中后直接control+shift+1就能翻译。类似于deepL的control+C+C

**Comment by lmk123** [comment]
划词翻译作为浏览器的扩展程序，没有能力做到类似于 Control + C + C 的形式（虽然实际上 DeepL 也是先 Control + C 复制了一下）

但是划词翻译支持另一种形式：“持续监听剪切板”，开启后会在复制文本时自动弹出翻译，具体做法见 https://hcfy.app/docs/guides/extra
