### ISSUE TITLE
能否添加ChatGpt翻译对Cloudflare AI Gateway的支持？

### ISSUE THREAD

**Issue by Removable** [hcfyapp/crx-selection-translate#1970]
能否添加对[AI Gateway](https://developers.cloudflare.com/ai-gateway/)的支持？
通过AI Gateway，可以获得一些统计功能，以及缓存功能，对节省费用有不错的帮助

谢谢！

**Comment by lmk123** [comment]
我没搞懂这个要怎么添加支持。。是不是只要在划词翻译里把【镜像地址】填成 AI Gateway 的地址就行了？

附注：划词翻译内 ChatGPT 镜像地址的说明 https://hcfy.app/docs/services/chatgpt

**Comment by Removable** [comment]
我尝试了，替换后虽然获得了翻译结果，但是似乎是因为镜像地址出错，回调到默认openai地址获得的结果。
我通过抓包发现ai gateway的请求确实失败了，是因为url拼接错误（看起来是在结尾处多了一个`v1`）：
![image](https://github.com/hcfyapp/crx-selection-translate/assets/7271713/868470ed-1622-4389-a015-22b5c33e7db6)

![image](https://github.com/hcfyapp/crx-selection-translate/assets/7271713/24718482-dd66-410a-aa5b-6634cc4e040a)

附[官方文档](https://developers.cloudflare.com/ai-gateway/providers/openai/)

**Comment by lmk123** [comment]
v10.5.1 以及之前的划词翻译确实会默认给你填写的镜像地址加上  /v1/chat/completions 这个后缀，不过 v10.5.2 开始就不会了。

换句话说，你应该只需要将划词翻译升级到 v10.5.2 就能成功用上 ai gateway 了

**Comment by lmk123** [comment]
看了文档之后，给出一个准确的使用 ai gateway 的步骤：

1. 将划词翻译升级到 v10.5.2 及以上版本
2. 在镜像地址里填写 `https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai/chat/completions`（其中 `ACCOUNT_TAG` 和 `GATEWAY` 替换为你自己的）

完成

**Comment by Removable** [comment]
多谢，检查了一下确实没有在最新版本。目前更新后已通过抓包确认可以正常使用了！
再次感谢！
