### ISSUE TITLE
网页全文翻译内容丢失

### ISSUE THREAD

**Issue by xujz520** [hcfyapp/crx-selection-translate#1971]
## 基本信息

划词翻译版本：v10.5.1
浏览器版本：谷歌浏览器 122.0.6261.129（正式版本） （64 位）
操作系统：win10

## 重现问题的步骤

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/DefiningClasses/DefiningClasses.html#//apple_ref/doc/uid/TP40011210-CH3-SW1

![image](https://github.com/hcfyapp/crx-selection-translate/assets/22070188/d1541b68-9c25-4643-9566-eabead0d75b8)

**Comment by lmk123** [comment]
DeepL 翻译结果不全的解决方案见 https://hcfy.app/docs/faqs/deepl-limit
