### ISSUE TITLE
 ChatGPT已登录且能对话   但面板中显示“远程服务器返回了错误的 HTTP 响应码：400。”

### ISSUE THREAD

**Issue by kakushou** [hcfyapp/crx-selection-translate#1973]
版本 10.5.2             edge和chrome    同报错误 400

请问该如何解决 400错误 ？？？                             ChatGPT的免费试用需要填写Secret Key吗？？？

**Comment by lmk123** [comment]
由于 ChatGPT 官网对部分用户调整了通信方式，所以划词翻译里的 ChatGPT 免费试用现在对部分人（比如你）是失效的。目前我正在重新适配最新的通信方式，还需要一定的时间。

鉴于 ChatGPT 的免费试用不太稳定，我建议通过第三方中转的方式使用 ChatGPT，见说明：https://hcfy.app/docs/services/chatgpt
