### ISSUE TITLE
ChatGPT 突然出行错误提示, 远程服务器返回了错误的 HTTP 响应码：400

### ISSUE THREAD

**Issue by leozww** [hcfyapp/crx-selection-translate#1977]
## 基本信息

划词翻译版本：10.5.2
浏览器版本：123.0.6312.59（正式版本） （64 位）
操作系统：win10-21H2

## 重现问题的步骤

1. ChatGPT 突然出行错误提示, 远程服务器返回了错误的 HTTP 响应码：400
2. 已反复卸载/重装划词插件, 已确定GPT在线并登陆, 仍无法解决问题
3.

### 实际行为
突然发生的, 除了谷歌浏览器外, 也在360极速浏览器上出现故障, 不记得是怎么引起的

**Comment by lmk123** [comment]
划词翻译内的免费试用 ChatGPT 从 2 月分开始已经陆续不能用了，这是因为 ChatGPT 网页版（chat.openai.com）更改了通信协议，需要划词翻译重新适配。

我其实已经尝试重新适配过了，但是这次难度很大，能不能成功适配还未知 :joy: 建议通过第三方中转的方式使用 ChatGPT，见 https://hcfy.app/docs/services/chatgpt
