### ISSUE TITLE
网页全文翻译, 只翻译指定css选择器的内容, 强力建议!!!

### ISSUE THREAD

**Issue by xujz520** [hcfyapp/crx-selection-translate#1979]
https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app?language=objc

![image](https://github.com/hcfyapp/crx-selection-translate/assets/22070188/c2b2f438-77f0-4689-93c5-a02a6e070e44)

**Comment by lmk123** [comment]
已在开发计划中 :joy: 见 #1406

**Comment by lmk123** [comment]
你好 @xujz520 ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
