### ISSUE TITLE
Gemini: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Greymuno** [hcfyapp/crx-selection-translate#1981]
## 基本信息

划词翻译版本：v10.6.1
浏览器版本：Chrome 123.0.6312.86 64x
操作系统：Windows 11

## 重现问题的步骤

1. 重新申请API
2. 任一网页划词
3. ![image](https://github.com/hcfyapp/crx-selection-translate/assets/41647695/c591e402-a04a-413d-8126-fc565916a1b5)

### 补充信息

![image](https://github.com/hcfyapp/crx-selection-translate/assets/41647695/466dab30-8e98-4ccb-8b57-d3740f6a259d)
![image](https://github.com/hcfyapp/crx-selection-translate/assets/41647695/13186a0e-63a6-4d08-acfc-5db77a5ed5d8)

**Comment by lmk123** [comment]
先说结论：从你的补充信息来看，是你的 Gemini API 被封禁了，划词翻译无能为力 :joy:

从“此项目似乎通过将一个项目分为多个项目的方式来规避我们的配额限制”这句话，我猜测你是不是申请了多个 Gemini API key，然后填写进了不同的软件使用？

**Comment by Greymuno** [comment]
![image](https://github.com/hcfyapp/crx-selection-translate/assets/41647695/ca571084-01a3-4b56-bdfd-89bec9b2fd9f)
并没有。三月份申请过一个用在别的应用上但是很离奇的无法使用。4月2日把原key添加到划词后报reading 0，此时我也只申请过一个api key。重新申请新key并删除旧的也是一样的反馈。
申诉提交了，我等等看回复

**Comment by lmk123** [comment]
如果谷歌有回应了希望可以在这里说明一下，我可以把相关信息写进文档里，提醒其他人不要遇到这个问题

**Comment by Staygold97** [comment]
我也遇到了这个问题 即使是新创建的api也会跳出相同错误 不知道是不是因为我还在gemini advanced的试用期内的缘故

**Comment by Greymuno** [comment]
04.08收到appeal denied，但是没有解释原因。我尝试更新结算账号，再次提交申诉。目前还未收到回复。
![image](https://github.com/hcfyapp/crx-selection-translate/assets/41647695/e7a4ddcd-4a42-4ae8-8fff-b344c92d81da)
My Console页面的报错置顶在结算更新后一天消失，但是依然无法使用划词。
![image](https://github.com/hcfyapp/crx-selection-translate/assets/41647695/b3c4f109-f45c-457a-be4c-144b145b93be)

**Comment by ziofat** [comment]
说一下我这边的结论：这是由于 generativelanguage.googleapis.com 限制了访问地域，如果你的节点不属于 https://ai.google.dev/available_regions#available_regions 列出的范围，则无法使用（注意香港不属于可用地域）。

**Comment by Greymuno** [comment]
> 说一下我这边的结论：这是由于 generativelanguage.googleapis.com 限制了访问地域，如果你的节点不属于 https://ai.google.dev/available_regions#available_regions 列出的范围，则无法使用（注意香港不属于可用地域）。

我不认为是这个原因，首先我更换过几个节点反馈是一样的，其次如果是地域问题我应该无法打开ai studio？
![image](https://github.com/hcfyapp/crx-selection-translate/assets/41647695/0834cada-fd16-4b6b-a68d-ef5fed831d84)

**Comment by Greymuno** [comment]
> 说一下我这边的结论：这是由于 generativelanguage.googleapis.com 限制了访问地域，如果你的节点不属于 https://ai.google.dev/available_regions#available_regions 列出的范围，则无法使用（注意香港不属于可用地域）。

我不认为是这个原因。首先我更换过几个节点，反馈相同，其次如果是地域限制，是不是无法打开AI Studio？
![image](https://github.com/hcfyapp/crx-selection-translate/assets/41647695/e98e6128-f61f-401b-8b87-70fb9b95c403)

**Comment by ziofat** [comment]
@Greymuno 具体原因可能需要自己试一下。我刚也遇到这个问题，然后查了报错，就我自己来说是这个原因。
具体方法如下：
1、进入扩展管理（chrome://extensions/），打开扩展开发者模式，调试划词翻译扩展页面：
<img width="170" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/8521174/5d454965-b9ef-4378-8fd8-a5761114f064">

<img width="418" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/8521174/c15bfb8f-666d-4032-8e3f-9e765b528f17">

2、定位到 Network Tab，并在其他网页上触发一次划词翻译，你会看到对 Gemini 的网络请求：
<img width="817" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/8521174/32b1d589-0ab6-438b-b586-9d2097610729">

3、根据返回的原因定位问题。

**Comment by lmk123** [comment]
@ziofat 给力。我下个版本把错误信息抛出来

**Comment by Greymuno** [comment]
@ziofat 感谢
看了一下我的情况，code: 429，报超限。
一直以为是API Key的问题，刚才看了一下project的警告还在（虽然还是不知道报滥用的原因）
删了当前project重新申请新的，可以正常使用了。

> {error: {code: 429,…}}
error
: 
{code: 429,…}
code
: 
429
details
: 
[{@type: "type.googleapis.com/google.rpc.ErrorInfo", reason: "RATE_LIMIT_EXCEEDED",…},…]
message
: 
"Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:7530'."
status
: 
"RESOURCE_EXHAUSTED"

**Comment by Greymuno** [comment]
今早谷歌终于反馈了，问了具体原因但是没给，这个项目我也都已经删了
![image](https://github.com/hcfyapp/crx-selection-translate/assets/41647695/acf58e0a-9321-4b1f-850e-db62bd167612)
