### ISSUE TITLE
网页全文翻译失效

### ISSUE THREAD

**Issue by zylona** [hcfyapp/crx-selection-translate#1982]
## 基本信息

划词翻译版本：
浏览器版本：Version 123.0.6312.105 (Official Build) (64-bit)
操作系统：debian 12

## 重现问题的步骤

当以 file:// 协议打开本地html ， 使用网页全文翻译时，翻译失效

### 预期行为

可以跟使用http协议时效果一样，能够正常全文翻译

### 实际行为

一点效果没有

### 补充信息

使用python http.server 搭建本地服务器环境后，能够正常使用

**Comment by lmk123** [comment]
见 https://hcfy.app/docs/faqs/file-url
