### ISSUE TITLE
建议增加对以“#”号开头的行的直接翻译支持

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1983]
**没有这个功能（改进）的时候，你遇到了什么问题？**
很多代码、参数的注释都是以“#”号开头的段落，如果直接划词翻译，会导致混乱

**你想要如何解决你的问题？**
在进行划词翻译时，是否可以使用正则表达式将“#”号替换为空格，或者直接删除该符号？

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
直接划词翻译是最方便的，其他方法都比较麻烦

**补充信息**
有一个Issue也提出了类似的问题，作者回复说将内容复制下来并放到TXT文档中，再用谷歌浏览器打开进行翻译，在注释很多的情况下，这样会很繁琐

**Comment by lmk123** [comment]
> 在进行划词翻译时，是否可以使用正则表达式将“#”号替换为空格

现在是有这个功能的，在划词翻译设置 - 翻译面板 - 源文本处理 - 添加正则表达式。

你可以先试试这个功能能否解决你的问题，如果不能，欢迎继续留言，我会 reopen
