### ISSUE TITLE
Firefox版本已经4个月没有更新了

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1985]
我只用Firefox浏览器，我要是购买的时候知道更新这么慢就不买了。我还是128原价买的。

**Comment by lmk123** [comment]
先道个歉，我确实很久没更新 Firefox 了 :joy: 我可以为你退款

再说说原因……

上次在 Firefox 提交 v10.5.1 时，Firefox 又又又又没审核通过。从我的角度来看，Firefox：

- 用户数最少，只有 6 万，而其它浏览器平台至少 30 万
- 审核最麻烦，经常审核不通过，要修改代码适配它，而其它浏览器平台几乎没有出现过这样的问题
- 不完全支持 Manifest V3，等到划词翻译在 Chrome / Edge 更新为 Manifest V3 之后，Firefox 的划词翻译将会一直停留在 v10 版本，直到 Firefox 完全支持 Manfest V3。

所以即使我现在花费精力把 FIrefox 的划词翻译更新到了 v10.6.2，以后转 Manifest V3 的时候还是要一直停留在 v10 版本，再加上用户数这么少，我又忙着转 Manifest V3，就出现了 Firefox 4 个月没更新的局面 :joy:

如果你需要退款，请继续留言。

**Comment by sijitang** [comment]
你好claude 模型名没法保存这个bug 我看其他浏览器都更新了。原来firefox更新有困难。我也是付费用户，不过没关系，能提供本地更新包吗？我本身就是linux用户，主要用了很多很多年firefox习惯了不想用别的浏览器。谢谢
我现在的版本

Version
10.14.1
Last Updated
August 12, 2024

**Comment by lmk123** [comment]
现在没更新是因为 Firefox 没有完全兼容 Chrome 的 Manifest V3，所以划词翻译的 v11 版本无法运行在 Firefox 之上，所以也没法提供本地更新包

**Comment by sijitang** [comment]
> 现在没更新是因为 Firefox 没有完全兼容 Chrome 的 Manifest V3，所以划词翻译的 v11 版本无法运行在 Firefox 之上，所以也没法提供本地更新包

明白，可以理解，如果有时间能否只把这个bug （model名无法保存，使用）在firefox v10 版本直接解决（不换成Manifest V3前提下）？也就是再出一个无bug的v10版本的ff。然后之后ff就不用再更新了。

**Comment by xianghongai** [comment]
@lmk123 我也是深度 Firefox 用户，我说怎么同步功能几个设备间就没成功过，看 Firefox 扩展中心评论才知道有这事。。。

**Comment by xianghongai** [comment]
@lmk123 另，是划词翻译永久会员。
