### ISSUE TITLE
chatgpt报400错误，ChatGPT网页可以正常打开登陆

### ISSUE THREAD

**Issue by iristech123** [hcfyapp/crx-selection-translate#1986]
## 基本信息

划词翻译版本：划词翻译 v10.6.2
浏览器版本：123.0.6312.59
操作系统：macos

## 重现问题的步骤

1. chatgpt报400错误，ChatGPT网页可以正常打开登陆
2.
3.

**Comment by lmk123** [comment]
由于 ChatGPT 网页版接口大幅度提升了逆向难度，ChatGPT 的免费试用方式无法再做到扩展程序里的。因此，关闭所有跟 ChatGPT 免费试用方式有关的 issue。
