### ISSUE TITLE
找回密码的时候输入邮箱显示邮箱不存在

### ISSUE THREAD

**Issue by lenny-mo** [hcfyapp/crx-selection-translate#1987]
## 基本信息

划词翻译版本：划词翻译 v10.6.2
浏览器版本：chrome Version 123.0.6312.87 (Official Build) (arm64)
操作系统：darwin arm64

## 重现问题的步骤

1. 退出登陆
2. 找回密码，输入你的登陆邮箱

### 预期行为
1. 给我的邮箱发送验证码

### 实际行为
1. 显示邮箱不存在

**Comment by lmk123** [comment]
有以下几种可能：

1. 邮箱是区分大小写的，你没输对
2. 你记错你的登录邮箱了

如果你实在记不得了，你可以在公众号发送给我你购买会员时的支付账单，我可以根据交易单号找到你的邮箱
