### ISSUE TITLE
是否可以提供个LLama.cpp 翻译接口， 类似于ChatGPT

### ISSUE THREAD

**Issue by yanite** [hcfyapp/crx-selection-translate#1992]
**没有这个功能（改进）的时候，你遇到了什么问题？**
没有这个功能使用不了llama.cpp AI翻译

**你想要如何解决你的问题？**
添加一个使用llama.cpp 接口， 类似于ChatGPT
URL:  http://127.0.0.1:8080/
Post: {"stream":true,"n_predict":400,"temperature":0.12,"stop":["</s>","Llama:","User:"],"repeat_last_n":256,"repeat_penalty":1.18,"top_k":100,"top_p":0.5,"min_p":0.05,"tfs_z":1,"typical_p":1,"presence_penalty":0,"frequency_penalty":0,"mirostat":0,"mirostat_tau":5,"mirostat_eta":0.1,"grammar":"","n_probs":0,"image_data":[],"cache_prompt":true,"slot_id":-1,"prompt":"请将下面文本翻译为{{target}}:\n{{text}}"}

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
暂无

**补充信息**
不想用收费的。 没钱啊

**Comment by lmk123** [comment]
你可以自定义翻译服务 ：https://hcfy.app/docs/services/custom-api

如果自定义翻译服务满足不了你的需求，欢迎继续留言
