### ISSUE TITLE
建议添加一个功能：结合自定义术语进行翻译

### ISSUE THREAD

**Issue by davidliu1210** [hcfyapp/crx-selection-translate#1996]
**没有这个功能（改进）的时候，你遇到了什么问题？**
机器翻译按照一般理解进行翻译，有些是客户统一的术语，已经有固定译文了，不允许修改，有时候这样的术语能有几百个。

**你想要如何解决你的问题？**
我先上传一个txt文件，其中是客户规定好的术语译文。机器翻译时，对于出现的匹配的原文，按照这个上传文件中的译文版本进行翻译。

**Comment by lmk123** [comment]
这一步没法由划词翻译来做，而是需要各个翻译服务自行根据术语表来对翻译结果进行干预。目前已知以下服务是支持术语表的，点击链接可以看到它们的术语表上传方式：

- [百度翻译](https://hcfy.app/docs/services/baidu-api#s)
- [阿里翻译](https://hcfy.app/docs/services/ali-api#s)

**Comment by lmk123** [comment]
你好 @davidliu1210 ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
