### ISSUE TITLE
划词翻译内置语音转文字：没有检测到语音

### ISSUE THREAD

**Issue by blacksheepaul** [hcfyapp/crx-selection-translate#1997]
## 基本信息

划词翻译版本：10.6.2
浏览器版本：Chrome Version 124.0.6367.91 (Official Build) (arm64)
操作系统：MacOS 14.4.1 (23E224)

## 重现问题的步骤

1. 打开划词翻译独立窗口
2. 点击左上角的音频
3. 对着电脑说话

### 预期行为
语音转成文字
### 实际行为
划词翻译独立窗口 弹窗 “没有检测到语音。”
### 补充信息
[浏览器设置中已经给了划词翻译麦克风权限](chrome://settings/content/siteDetails?site=chrome-extension%3A%2F%2Fikhdkkncnoglghljlkmcimlnlhkeamad%2F&search=microphone)

MacOS 系统的 [seting] - [privacy & security] 中也给了浏览器microphone权限

系统外网是通的

在独立窗口打开浏览器控制台，网络中没有任何活动。

**Comment by lmk123** [comment]
我使用 macOS 14.4.1 (23E224)、Chrome 124.0.6367.119（正式版本） (arm64)，在卸载并重新安装划词翻译之后，没有重现你的问题。

出现“没有检测到语音”的报错，说明麦克风长时间没有接收到语音，我猜测有没有可能是你的麦克风坏了或者堵住了之类的？如果不是的话我也不知道是啥原因了 :joy:

**Comment by blacksheepaul** [comment]
我用同一台电脑重试，恢复正常了...和麦克风应该没关系，可能和当时的运行环境有关，但我实在想不起来了，先这样吧
