### ISSUE TITLE
建议增加小牛翻译接口

### ISSUE THREAD

**Issue by iseeyo** [hcfyapp/crx-selection-translate#1998]
**没有这个功能（改进）的时候，你遇到了什么问题？**
翻译东南亚小语种不准确

**你想要如何解决你的问题？**
翻译东南亚小语种

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
增加小牛翻译接口

**补充信息**
别的翻译软件有小牛翻译接口

**Comment by lmk123** [comment]
其实已经加进开发计划了，只是一直没动手 :joy:

cc #1019
