### ISSUE TITLE
使用ChatGPT翻译时，出现错误

### ISSUE THREAD

**Issue by bian2022** [hcfyapp/crx-selection-translate#2000]
## 基本信息

划词翻译版本：v10.6.2
浏览器版本：Chrome 124.0.6367.92
操作系统：win11

# 问题：
## 使用ChatGPT翻译时，出现错误
> Cannot read properties of undefined (reading '0')
刷新网页  重试
出现 Extension context invalidated 错误时刷新网页即可恢复。
![image](https://github.com/hcfyapp/crx-selection-translate/assets/101516281/b9b0b79d-2725-49a2-9009-2cf6389256fd)

使用的是第三方api
在火狐浏览器上，可以正常使用；但Google Chrome上，哪怕关了广告拦截等插件，重新安装划词翻译后，也无法正常使用

**Comment by bian2022** [comment]
> ## 基本信息
> 划词翻译版本：v10.6.2 浏览器版本：Chrome 124.0.6367.92 操作系统：win11
> 
> # 问题：
> ## 使用ChatGPT翻译时，出现错误
> > Cannot read properties of undefined (reading '0')
> > 刷新网页  重试
> > 出现 Extension context invalidated 错误时刷新网页即可恢复。
> > ![image](https://private-user-images.githubusercontent.com/101516281/327553345-b9b0b79d-2725-49a2-9009-2cf6389256fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NzY0MDcsIm5iZiI6MTcxNDY3NjEwNywicGF0aCI6Ii8xMDE1MTYyODEvMzI3NTUzMzQ1LWI5YjBiNzlkLTI3MjUtNDlhMi05MDA5LTJjZjYzODkyNTZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxODU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYThjOTRjZGI0NDQyMTEyYjE0OGExYjc4YjQ5ZDA0ODMwODg4MTZhOTY3YWY5MWFlZjlkZjNkYzcwYjY4ZjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bLAPqhUAWfPOxuZDN8Wha7a0OTLfM74V5lQLh0WRezc)
> 
> 使用的是第三方api 在火狐浏览器上，可以正常使用；但Google Chrome上，哪怕关了广告拦截等插件，重新安装划词翻译后，也无法正常使用

浏览器开了个新用户，插件只安装了划词，但使用还是报错

**Comment by lmk123** [comment]
这就奇怪了，划词翻译在 chrome 和在 firefox 上的 chatgpt 代码是一样的啊 :joy:

可否公众号私信我一下第三方 api 的【镜像地址】和【密钥】给我，我在我这边试一下，等我试完之后你重置下密钥

**Comment by bian2022** [comment]
> 这就奇怪了，划词翻译在 chrome 和在 firefox 上的 chatgpt 代码是一样的啊 😂
> 
> 可否公众号私信我一下第三方 api 的【镜像地址】和【密钥】给我，我在我这边试一下，等我试完之后你重置下密钥

感谢作者可以及时回复
可否提供个邮箱，我给您发到相关邮箱发到邮箱里

**Comment by lmk123** [comment]
发到这个邮箱吧 support@hcfy.app

**Comment by bian2022** [comment]
> 发到这个邮箱吧 [support@hcfy.app](mailto:support@hcfy.app)

已发邮件

**Comment by lmk123** [comment]
你填写的镜像地址没有带 `/v1/chat/completions` 后缀，这里有过说明 https://hcfy.app/docs/services/chatgpt#%E7%AC%AC%E4%B8%89%E6%96%B9-chatgpt-%E4%B8%AD%E8%BD%AC%E6%9C%8D%E5%8A%A1%E7%9A%84%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F

记得重置密钥

**Comment by bian2022** [comment]
> 你填写的镜像地址没有带 `/v1/chat/completions` 后缀，这里有过说明 https://hcfy.app/docs/services/chatgpt#%E7%AC%AC%E4%B8%89%E6%96%B9-chatgpt-%E4%B8%AD%E8%BD%AC%E6%9C%8D%E5%8A%A1%E7%9A%84%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F
> 
> 记得重置密钥

可以了，谢谢
但为什么火狐浏览器就不用填？

**Comment by lmk123** [comment]
从 v10.5.2 的时候做过改动，需要加上 `/v1/chat/completions` 后缀了 https://hcfy.app/docs/log/v10#10-5-2

然而火狐里的划词翻译目前停留在 v10.5.0 :joy:

**Comment by bian2022** [comment]
> 从 v10.5.2 的时候做过改动，需要加上 `/v1/chat/completions` 后缀了 https://hcfy.app/docs/log/v10#10-5-2
> 
> 然而火狐里的划词翻译目前停留在 v10.5.0 😂

奥奥
发之前我还看一下**常见问题**，但没找到，原来是在更新日志里有啊
