### ISSUE TITLE
添加设置选项支持翻译窗口在鼠标移动后自动关闭.

### ISSUE THREAD

**Issue by KickRooster** [hcfyapp/crx-selection-translate#2001]
**没有这个功能（改进）的时候，你遇到了什么问题？**
每次划词之后还需要点一下X,很麻烦.

**你想要如何解决你的问题？**
在设置中支持可以开启翻译窗口在鼠标移动后自动关闭.

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
或者翻译窗口可以固定而不受滑动条滚动的影响.

**补充信息**

**Comment by lmk123** [comment]
> 每次划词之后还需要点一下X,很麻烦.

不需要。只要点一下除窗口以外的任意地方都可以关闭窗口。

> 翻译窗口可以固定而不受滑动条滚动的影响.

已有功能。只需要点一下窗口左上角的图钉按钮。

综上所述，我觉得你想要实现的需求已经都有方案了，如果你仍觉得“支持翻译窗口在鼠标移动后自动关闭”是有必要的，可以继续留言。

**Comment by KickRooster** [comment]
谢谢回复。
“不需要。只要点一下除窗口以外的任意地方都可以关闭窗口。”
如你所说，这还是需要点击一次鼠标，这看起来不麻烦，但是如果每天都要看很多内容，这确实有些麻烦。
我之前使用灵格斯翻译家，它就是我所描述的工作机制，但是它最近在我的电脑上不能正常工作，我找到了这个插件，它非常好用，并且我毫不犹豫地购买了终身会员希望能够长久使用，我希望它能满足我的工作习惯。谢谢。

**Comment by lmk123** [comment]
那我加一个吧。

希望能提供一下“鼠标移动后自动关闭”这一功能更详细的描述，比如：

- ”移动后”是指移动到哪里，比如是移出窗口外面还是移动到特定位置
- 关闭时机有要求吗？比如是移出后立刻就关闭，还是等待 1 秒后再关闭

**Comment by KickRooster** [comment]
谢谢大佬~

**Comment by KickRooster** [comment]
”移动后”是指移动到哪里，比如是移出窗口外面还是移动到特定位置
和双击后弹出翻译窗口时的鼠标位置不一致即判定为"移动",无论在不在窗口里面.

关闭时机有要求吗？比如是移出后立刻就关闭，还是等待 1 秒后再关闭
移动后立刻关闭即可.

这些习惯来自于灵格斯翻译家,那个用起来确实挺爽的.

**Comment by KickRooster** [comment]
大佬,预计哪个版本可以支持?

**Comment by KickRooster** [comment]
啥情况?连句话也不回

**Comment by lmk123** [comment]
抱歉，GitHub 上通知较多，之前其实我看到你 5 天前的提问了，但是在思考要把这项改进安排在什么时间段的时候被其它事情打断了，结果忘回了，再加上点开过所以变成了已读状态，所以之后我看通知的时候都没有注意到未回复你的问题。

我还是要澄清一下，我并不是故意不回，你可以看我之前的回复以及其他人的回复，应该都是回复的比较认真的。

另外，这项改进工作量不大，预计可以在下一个版本也就是 v10.10.0 支持

**Comment by KickRooster** [comment]
好的，谢谢，希望可以改进得越来越好。
我个人的确对已读不回非常在意，同时也对你的解释表示理解，再次对大佬积极解决问题表示感谢～

**Comment by lmk123** [comment]
老哥，又要跟你说声抱歉了 😂

我写了一天的代码，终于把国内的 10 个 AI 服务全接进了划词翻译。现在凌晨 4 点了，我实在写不动了，所以把你的这个需求移到下个版本 v10.11.0 了 😂 

这次真的不变了，v10.11.0 的时候一定上线你的需求

**Comment by lmk123** [comment]
v10.11.0 已加入此功能，见[更新日志](https://hcfy.app/docs/log/v10#10-11-0)

**Comment by KickRooster** [comment]
牛皮呀,大佬能编又能肝,真是厉害~
非常感谢~ : ) 😂

**Comment by KickRooster** [comment]
0 0 问题是下个版本什么时候上线?

**Comment by lmk123** [comment]
这个版本估计要延迟一些了，目测 20 号左右

**Comment by KickRooster** [comment]
好吧

**Comment by lmk123** [comment]
v10.11.0 提前发布了， 现在已经放出来离线安装包了，见 https://hcfy.app/docs/installv2/offline

**Comment by KickRooster** [comment]
牛皮,非常开心的一个周末!
