### ISSUE TITLE
全大写英文单词无法正常朗读, 希望文本处理添加全大写英文单词转换为全小写英文单词的功能

### ISSUE THREAD

**Issue by omymenzies** [hcfyapp/crx-selection-translate#2003]
**没有这个功能（改进）的时候，你遇到了什么问题？**
遇到全大写英文字母的情况, 比如I Like FISHIMINEA , 无法正常朗读, 必须将全大写英文单词转换为小写I Like  fishiminea 才能正常朗读
**你想要如何解决你的问题？**
文本处理添加全大写英文单词转换为全小写英文单词的功能

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
不知道
**补充信息**
尝试使用正则功能, 但似乎无法实现
![image](https://github.com/hcfyapp/crx-selection-translate/assets/115856305/d8240fdf-d7f8-44b3-be52-1b5a93fdd498)
![image](https://github.com/hcfyapp/crx-selection-translate/assets/115856305/60a4c2c7-876d-476a-a65d-7442d7db5d31)

**Comment by lmk123** [comment]
已加入开发计划。

备注：JavaScript 里的正则表达式不支持 `\L$1` 这种语法，所以这个功能得单独写代码来实现

**Comment by lmk123** [comment]
你好 @omymenzies ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
