### ISSUE TITLE
增加通义千问的支持，或者支持自定义openai模型的服务地址和模型名

### ISSUE THREAD

**Issue by finemi** [hcfyapp/crx-selection-translate#2008]
**没有这个功能（改进）的时候，你遇到了什么问题？**
通义千问每百万tokens才0.5元，使用openai等会贵十几倍

**你想要如何解决你的问题？**
支持通义千问

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
支持自定义openai模型的服务地址和模型名，因为通义千问的最新模型兼容openai的调用方式，只是服务地址和模型名不一致。

**补充信息**
参考“沉浸式翻译”插件

**Comment by lmk123** [comment]
> 支持自定义openai模型的服务地址和模型名

已有功能，在划词翻译设置 - 第三方服务 里

**Comment by lmk123** [comment]
通义千问也加入开发计划了，后续进展可以关注 #2009

**Comment by lmk123** [comment]
v10.9.0 已加入通义千问
