### ISSUE TITLE
能不能给火狐更新Gemini啊

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#2014]

**Comment by lmk123** [comment]
我已经尝试提交 v10.7.0 的版本给火狐审核了，希望能顺利通过😂

**Comment by lmk123** [comment]
虽然关闭了但还是更新下进展 :joy:

v10.7.0 提交上去的时候还是被拒绝了，然后跟审核详细交流了一番，现在问题已经解决，不过得修改代码然后提交一个新版本。我预计会在 5 天内提交新的版本 v10.9.0
