### ISSUE TITLE
增加DeepL的第三方中转支持

### ISSUE THREAD

**Issue by leslietoo** [hcfyapp/crx-selection-translate#2015]
目前已经有些第三方实现的deepl api的中转服务，例如deepl-pro.com，其接口规范和官方保持一致。
官方api pro订阅的接口为api.deepl.com，api free订阅的接口为api-free.deepl.com，而这个中转方的api订阅接口为api.deepl-pro.com，直接换下接口地址即可，其他完全一样。价格也便宜。对于无法注册deepl的或者需要deepl pro api又囊中羞涩的用户来说是个好选择。

**Comment by lmk123** [comment]
感谢提议，下个版本就支持
