### ISSUE TITLE
添加 Claude

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#2017]

**Comment by leslietoo** [comment]
期待，国外三大主流AI就差这个了

**Comment by leslietoo** [comment]
什么时候才能添加Claude支持啊？一直想体验Claude 3.5 Sonnet炸裂的效果头发胡子都等白了。。。

**Comment by letttop** [comment]
+1

**Comment by lmk123** [comment]
Claude 的 API 我看了一下，得企业才能申请 :joy:

我可以参考 API 文档和别人的代码尝试接入进来，不过我自己没法验证它能不能正常用

**Comment by leslietoo** [comment]
> Claude 的 API 我看了一下，得企业才能申请 😂
> 
> 我可以参考 API 文档和别人的代码尝试接入进来，不过我自己没法验证它能不能正常用

我给个Claude中转key给你测试？你邮箱多少？

**Comment by lmk123** [comment]
claude的中转服务跟claude官方接口是一样的吗？我咋记得claude的中转服务现在用的是openai的接口格式

**Comment by leslietoo** [comment]
> claude的中转服务跟claude官方接口是一样的吗？我咋记得claude的中转服务现在用的是openai的接口格式

不一定，有的用openai通道有的是claude通道， 比如 https://www.gptapi.us 这个是跟claude官方接口一样的，我可以发你key，或者你去花几块钱冲点额度也够测试用了

**Comment by lmk123** [comment]
这个好，我自己充一点测试

**Comment by lmk123** [comment]
v10.14.0 已支持 Claude，现已发布。
