### ISSUE TITLE
检测网页中的PDF检测到about:blank

### ISSUE THREAD

**Issue by HuaHuaY** [hcfyapp/crx-selection-translate#2019]
## 基本信息

划词翻译版本：10.8.1
浏览器版本：Microsoft Edge 125.0.2535.92
操作系统：Linux 6.9.2-arch1-1 x86_64

## 重现问题的步骤

1. 划词翻译不勾选“自动打开PDF”，勾选“检测网页中的PDF”
2. 打开任意PDF（来自网上的连接或本地的都行）

### 预期行为

右下角询问是否在划词翻译内置的阅读器打开PDF，并提供正确的地址

### 实际行为

管理扩展里无论是否勾选“允许访问文件URL”都这样。

提供的地址错误，显示为about:blank，导致内置阅读器页面打开后没有内容，打开后url为`extension://ikhdkkncnoglghljlkmcimlnlhkeamad/pdf-viewer/web/viewer.html?file=about%3Ablank`

![image](https://github.com/hcfyapp/crx-selection-translate/assets/41586196/e6825043-3edd-424b-a7be-e488ccf5fc29)

### 补充信息

如果勾选“自动打开PDF”，可以在自动使用内置阅读器的同时从正确的地址载入PDF。

**Comment by lmk123** [comment]
在 macOS 上分别使用 Edge 和 Chrome 试了一下，均没有重现，一会儿我试试 Windows。

我猜测这是一个只会在 Linux 上出现的问题 :joy:

<img width="521" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/d87ba786-b78d-423d-9496-4ceaaabef4d9">

**Comment by HuaHuaY** [comment]
之前是ArchLinux+AUR上的Edge，今天换了一台Ubuntu+微软源的Edge，也有这个问题。之前用10.7版本也有这个问题，才尝试升级的10.8.1。

划词翻译版本：10.8.1
浏览器版本：Microsoft Edge 125.0.2535.67
操作系统：6.5.0-35-generic 35~22.04.1-Ubuntu

**Comment by HuaHuaY** [comment]
我从AUR上下载了Chrome，没有这个问题。说明这可能是个Linux + Edge的问题。

划词翻译版本：10.8.1
浏览器版本：Google Chrome 125.0.6422.141
操作系统：Linux 6.9.3-arch1-1

**Comment by lmk123** [comment]
我在 Windows 上分别试了 Chrome 和 Edge，也没有这个问题。

方便截图一下你在 Linux + Edge 里打开 pdf 时的开发者工具里的源码吗，就像下图这样，可以看到 pdf 文件的地址的那种，如果能找到特征的话，我就可以尝试适配一下

<img width="939" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/1e733997-fe74-4c92-beac-6bfedf5e53c3">

**Comment by HuaHuaY** [comment]
找到问题的原因了，在截图的过程中突然意识到，我在Chrome上只装了划词翻译，那也可能是有其他插件的影响。

定位到把两个油猴脚本[网页限制解除（改）](https://greasyfork.org/zh-CN/scripts/28497-%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4-%E6%94%B9)、[视频网页全屏](https://greasyfork.org/zh-CN/scripts/4870-maximize-video)关闭后，检测pdf的url就正常了。开启任意一个，都会变成检测到about:blank。

![2024-06-11_11-48-20](https://github.com/hcfyapp/crx-selection-translate/assets/41586196/13a0ac09-5119-4e97-b0d1-e96600927b56)

我把`*pdf*`加到油猴脚本的排除规则后，这两个脚本在pdf页面不启用，检测url也正常了。

**Comment by lmk123** [comment]
感谢解惑，原来是受其它脚本影响了，这个案例我会写进文档里
