### ISSUE TITLE
添加鼠标悬浮翻译特定段落的建议

### ISSUE THREAD

**Issue by silv3rarr0w** [hcfyapp/crx-selection-translate#2024]
https://www.bilibili.com/video/BV1h64y1V7Hy
具体功能见视频3：30 s处，该功能相比全文翻译更节约字符，相比划词翻译更方便灵活，是个很不错的功能，希望开发者考虑为划词翻译添加该功能。

**Comment by lmk123** [comment]
好的， 我已新开了 #2025 来详细描述这个功能，后续进展可以关注 #2025
