### ISSUE TITLE
网页划词无法拖动

### ISSUE THREAD

**Issue by mato2021** [hcfyapp/crx-selection-translate#2026]
## 基本信息

划词翻译版本：10.9
浏览器版本：Chrome  126.0.6478.57（正式版本） （64 位）
操作系统：win11

![屏幕截图 2024-06-13 224806](https://github.com/hcfyapp/crx-selection-translate/assets/91864835/a079f27a-7c7f-44ab-8883-a5e7f2698285)

这个按住拖动无法使用，按了无法移动。昨天重装系统，重新安装了划词，发现这个功能无法使用了。之前可以使用，但是我忘记划词用的是什么版本了。

**Comment by lmk123** [comment]
昨天发布的 v10.9.2 已经修复了这个问题，Chrome 现在审核通过了，你可以手动更新，或者下载离线安装包，见 https://hcfy.app/docs/installv2/update

**Comment by mato2021** [comment]
速度真快
