### ISSUE TITLE
能否支持基于本地的配置导出导入功能？

### ISSUE THREAD

**Issue by ThemanRonin** [hcfyapp/crx-selection-translate#2030]
能否支持基于本地的配置导出导入功能？我看了下之前的issues有提到类似问题，说的差不多是后期可能会添加，但是我现在翻遍了所有的设置，只能导出密钥和导入密钥，设置配置这些是无法本地导出导入的。

因为我如果更换浏览器或者电脑的话，自己配置的那些第三方服务的内容就需要全部重新填入一遍

（会员有这个功能，是基于导出云端的。本地导出导入的我想问一下有没有）

https://github.com/hcfyapp/crx-selection-translate/issues/997
https://github.com/hcfyapp/crx-selection-translate/issues/1501
https://github.com/hcfyapp/crx-selection-translate/issues/1041

**Comment by lmk123** [comment]
目前确实没有基于本地的配置导出导入功能 :joy:

如果加入了就会关闭掉 #997，如果没关闭就说明没加入
