### ISSUE TITLE
除了OpenAI，其他通义千问和豆包等模型导出或导入密钥时无效

### ISSUE THREAD

**Issue by mlkt** [hcfyapp/crx-selection-translate#2032]
划词翻译版本：10.10.0
浏览器版本：360安全浏览器 15
操作系统：Windows10

1.在Chrome配置好通义千问和豆包等模型的秘钥后点击导出
2.在360浏览器内点击导入，粘贴配置后，这些模型的秘钥没有被导入成功

**Comment by lmk123** [comment]
确实有这个问题，下个版本修复

**Comment by tesla4321** [comment]
现在已经修复了吧，这个问题还没关闭
