### ISSUE TITLE
文心一言无法使用

### ISSUE THREAD

**Issue by pdone** [hcfyapp/crx-selection-translate#2034]
## 基本信息

划词翻译版本：划词翻译 v10.10.0
浏览器版本：Microsoft Edge 126.0.2592.61 (正式版本) (64 位)
操作系统：Windows 10 企业版 22H2 19045.4474

## 重现问题的步骤

1. 正确配置文心一言密钥
2. 选中网页文字后点击翻译按钮

### 预期行为

正确显示翻译结果

### 实际行为

如图

![image](https://github.com/hcfyapp/crx-selection-translate/assets/34151215/0b6220ef-2cee-4fbf-a83e-91bdb66afbc5)

**Comment by lmk123** [comment]
我试了一下，是正常的，如下图。

可否麻烦你按照[这条评论](https://github.com/hcfyapp/crx-selection-translate/issues/1981#issuecomment-2058755915)里的步骤，看一下文心一言的接口具体返回的是啥内容吗 :joy:

<img width="379" alt="image" src="https://github.com/hcfyapp/crx-selection-translate/assets/5035625/57f560b8-65bb-433d-902f-7fd00bd67812">

**Comment by pdone** [comment]
我配置的是自己新申请的apikey 而且百度云已经实名认证 但提示这个
![image](https://github.com/hcfyapp/crx-selection-translate/assets/34151215/96cb863c-a433-4704-854b-ac116507628e)

**Comment by pdone** [comment]
![image](https://github.com/hcfyapp/crx-selection-translate/assets/34151215/8332dea4-65db-4ec6-bd87-d03921aebd12)

**Comment by pdone** [comment]
已解决，在计费管理同免费开通即可

**Comment by lmk123** [comment]
感谢反馈，我会将你的方案写进文档当中。
