### ISSUE TITLE
字符额度不明问题

### ISSUE THREAD

**Issue by is7706** [hcfyapp/crx-selection-translate#2037]
**没有这个功能（改进）的时候，你遇到了什么问题？**
我无法知道在翻译时收起是否会使用字符额度，或者我想在额度不够时可以关闭它。比如，有翻译源A有限量的翻译字符额度，翻译源B则完全免费。平时收起时我不希望使用翻译源A，不希望消耗额度，只在特定情况下展开它来得到地道的翻译

**你想要如何解决你的问题？**
说明在翻译时收起是否会使用字符额度，实现收起时不使用该网站翻译

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
向我说明在翻译时收起是否会使用字符额度

**补充信息**
目前非会员无法同步，其实可以使用webdav

**Comment by lmk123** [comment]
> 向我说明在翻译时收起是否会使用字符额度

不会。收起时不会执行翻译操作。

> 目前非会员无法同步

其实已经计划添加导入 / 导出配置的功能了，等 mv3 弄完之后就会加

**Comment by is7706** [comment]
目前edge canary已经可以使用扩展了,对手机的适配和同步问题或许可以提上日程
