### ISSUE TITLE
接入硅基流动免费模型

### ISSUE THREAD

**Issue by ou525** [hcfyapp/crx-selection-translate#2038]
感谢这么好的工具
据https://mp.weixin.qq.com/s/QkrJ86WZcOz_M_aoQOqF8w 消息
硅基流动为国内开发者献上一份前所未有的大礼：Qwen2 (7B)、GLM4 (9B)、Yi1.5（9B）等顶尖开源大模型永久免费
其中接口和openai兼容，看评价速度也比较快，期待加入
from openai import OpenAI

client = OpenAI(api_key="YOUR_API_KEY", base_url="https://api.siliconflow.cn/v1")

response = client.chat.completions.create(
    model='alibaba/Qwen1.5-110B-Chat',
    messages=[
        {'role': 'user', 'content': "抛砖引玉是什么意思呀"}
    ],
    stream=True
)

for chunk in response:
    print(chunk.choices[0].delta.content)

**Comment by lmk123** [comment]
看起来不错，我考虑看看

p.s. https://siliconflow.cn/zh-cn/pricing

**Comment by Nikoyyy** [comment]
这个不需要单独接入吧，只需要加入一个兼容openai接口的配置方式，让用户自行配置就可以了。现在大部分服务商都是兼容openai接口的，包括这个硅基流动
