### ISSUE TITLE
接入文心的帮助文档不够完善

### ISSUE THREAD

**Issue by Leng-Nanlyu** [hcfyapp/crx-selection-translate#2039]
# 问题
在接入文心的帮助文档 (https://hcfy.app/docs/services/wenxin) 中，第二步获取API Key和Secret Key之后，似乎还需要在百度云控制台中进行**实名认证**以及**开通付费**才能成功调用，否则会调用失败。**即使调用的api是免费的**，例如ernie-lite-8k，也需要开通付费。
在百度云控制台中可以查看到该api的错误信息为：“错误码: 17; 错误信息: Open api daily request limit reached; 描述: 【用户配额超限】API未开通付费，或者当前账户已欠费，导致请求失败。每天请求量超限额，已上线计费的接口，请直接在控制台开通计费，调用量不受限制；未上线计费的接口，请在百度云控制台内提交工单反馈”

# 建议
在接入文心的帮助文档里添加一步，即进行实名认证并开通对应模型的付费（即使是免费的api也需要开通）
进行实名认证的方法为：在控制点击头像进入个人页面，点击实名认证
开通付费的方法为：在控制台中选择计费管理，找到需要的api开通付费

**Comment by lmk123** [comment]
感谢反馈！文档已更新
