### ISSUE TITLE
增加兼容openai接口的api配置方式

### ISSUE THREAD

**Issue by Nikoyyy** [hcfyapp/crx-selection-translate#2044]
**没有这个功能（改进）的时候，你遇到了什么问题？**
有很多支持openai接口的语言模型服务商无法使用，且价格更便宜，例如“https://cloud.siliconflow.cn/”

**你想要如何解决你的问题？**
服务配置里可以自行配置

**Comment by lmk123** [comment]
好的

**Comment by lmk123** [comment]
我写了一篇文档，描述了如何利用划词翻译内兼容 OpenAI 接口的服务改为别的 AI 服务，见 https://hcfy.app/docs/faqs/openai-compatibilty

这算是一个临时方案，未来我会给出更直观灵活的配置选项
