### ISSUE TITLE
希望能在窗口的翻译源选项当中隐藏不需要的选项

### ISSUE THREAD

**Issue by Konjac-XZ** [hcfyapp/crx-selection-translate#2046]
**没有这个功能（改进）的时候，你遇到了什么问题？**  
由于某种原因（好吧，其实是心疼 Token），我想要频繁地启用/禁用 ChatGPT 的翻译，但是自从哪个版本大批量加入对于国产大模型的支持之后，这个界面里面的内容实在是太多了！看着很烦。叠个甲：不是说国产大模型不好的意思。  
![image](https://github.com/hcfyapp/crx-selection-translate/assets/71483384/5eaabb01-3be3-490e-8b6b-42ef5cd04f25)

**你想要如何解决你的问题？**
![image](https://github.com/hcfyapp/crx-selection-translate/assets/71483384/e6962e2e-2043-4eea-a852-6f41209e277d)
我觉得这样就挺好（这是那个网页全文翻译“精简下拉框”的选项）。建议给独立翻译窗口也做一个。 

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
单纯就我这个需求而论，我觉得还可以加入一个选项：免费试用的 Google 和 DeepL 直接触发翻译，需要掉 Token 的各种 AI 服务先不急，加上一个“点击此处确认发送”。

**Comment by lmk123** [comment]
这里全部加上只是目前的权宜之计 :joy: 未来是会准备把现有的服务申请整个重构一番的，其中就包括可以自定义要把哪些服务放在快捷选项里

二次确认的功能已新开 #2053

**Comment by lmk123** [comment]
你好 @Konjac-XZ ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
