### ISSUE TITLE
希望可以支持deepl翻译反代

### ISSUE THREAD

**Issue by bian2022** [hcfyapp/crx-selection-translate#2049]
一方面可以解决deepl有时候在国内无法连接的情况
另一方面，可以用始皇（ChatGPT潘多拉作者）的DeepLX 
![image](https://github.com/hcfyapp/crx-selection-translate/assets/101516281/7e42361e-ffae-40e6-a163-89225d4ea8aa)
（小声说一句：隔壁的翻译已经支持了 
![image](https://github.com/hcfyapp/crx-selection-translate/assets/101516281/b5232528-bd05-46e6-b32d-819e15f1d14f)
）

**Comment by lmk123** [comment]
已在开发计划中：#2040

**Comment by lmk123** [comment]
另外，其实你现在已经可以反代 DeepL 了，根据文档 https://hcfy.app/docs/services/deepl 的说明，填镜像地址的时候填你图里说的这个地址，就可以了

**Comment by bian2022** [comment]
> 另外，其实你现在已经可以反代 DeepL 了，根据文档 https://hcfy.app/docs/services/deepl 的说明，填镜像地址的时候填你图里说的这个地址，就可以了

OK，谢谢

**Comment by bian2022** [comment]
> 另外，其实你现在已经可以反代 DeepL 了，根据文档 https://hcfy.app/docs/services/deepl 的说明，填镜像地址的时候填你图里说的这个地址，就可以了

我看到好像在找第三方deepl，我可以免费提供一些额度来供大家使用

**Comment by lmk123** [comment]
> 我可以免费提供一些额度来供大家使用

啊，真的吗 😳

是类似于图里的那种自行部署 deeplx 的形式吗，能经得住几万人同时使用吗 :joy:
