### ISSUE TITLE
希望可以优化下ChatGPT翻译第三方反代

### ISSUE THREAD

**Issue by bian2022** [hcfyapp/crx-selection-translate#2050]
能不能实现支持多个反代地址，并且不同的反代地址对应不同的密钥啊
麻烦了

**Comment by lmk123** [comment]
现阶段，你可以通过“兼容 OpenAI 接口的服务”来实现，见 https://hcfy.app/docs/faqs/openai-compatibilty

未来会对服务配置做改进，允许为同一个服务添加多个不同配置并同时显示在翻译结果中

**Comment by lmk123** [comment]
你好 @bian2022  ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
