### ISSUE TITLE
第三方 DeepL 中转服务速度很慢

### ISSUE THREAD

**Issue by renaissancecode** [hcfyapp/crx-selection-translate#2051]
如题，使用的是第三方deepl api（deeplx），在其他软件中调用速度很快（例如沉浸式翻译）。
但按照官方教程（https://hcfy.app/docs/services/deepl）设置，翻译速度很慢。

**Comment by lmk123** [comment]
应该是第三方中转配置报错了，然后划词翻译就改为使用了内置的 DeepL，而内置的就会比 DeepL X 慢。

方便截图看一下你的 DeepL 镜像地址填的是什么吗，另外有没有填密钥？

**Comment by renaissancecode** [comment]
> 应该是第三方中转配置报错了，然后划词翻译就改为使用了内置的 DeepL，而内置的就会比 DeepL X 慢。
> 
> 方便截图看一下你的 DeepL 镜像地址填的是什么吗，另外有没有填密钥？

镜像地址是“https://api.deeplx.org/***此处为个人识别码***/translate”，密钥按照教程没有留空（填的abc），应该没有填错吧
能否像沉浸式翻译一样，单独搞一个deeplx的接口？

**Comment by lmk123** [comment]
没有填错。那说明 DeepLX 的接口格式跟官方的 DeepL 接口是不一样的，需要单独适配。

还是等我单独适配吧 :joy: 后续进展 #2040

**Comment by renaissancecode** [comment]
> 没有填错。那说明 DeepLX 的接口格式跟官方的 DeepL 接口是不一样的，需要单独适配。
> 
> 还是等我单独适配吧 😂 后续进展 #2040

感谢，期待适配！

**Comment by vay1314** [comment]
> 没有填错。那说明 DeepLX 的接口格式跟官方的 DeepL 接口是不一样的，需要单独适配。
> 
> 还是等我单独适配吧 😂 后续进展 #2040

期待适配
