### ISSUE TITLE
希望增加流式传输功能

### ISSUE THREAD

**Issue by Nikoyyy** [hcfyapp/crx-selection-translate#2052]
**没有这个功能（改进）的时候，你遇到了什么问题？**
在使用 Qwen2-72B-Instruct 指定Prompt：“逐个解释每个单词在句中的含义”，回复后的内容比较长，等待时间比较久，非常影响用户体验

**你想要如何解决你的问题？**
增加流式传输，避免用户过长时间的等待。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
一定要想办法，加油

**补充信息**
 pot-desktop  就实现了流式传输功能，用户可以选择打开与否，可以一边查看一边生成

**Comment by lmk123** [comment]
好的。已加入开发计划，后续进展关注 #2031

**Comment by lmk123** [comment]
你好 @Nikoyyy  ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！另外，流式输出的功能在【划词翻译 Next】里有实现

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
