### ISSUE TITLE
希望可以固定翻译面板的窗口缩放比例

### ISSUE THREAD

**Issue by Nikoyyy** [hcfyapp/crx-selection-translate#2054]
**没有这个功能（改进）的时候，你遇到了什么问题？**
在不同的网站有不同的缩放比例，都是为了让文字看的更舒适。这就导致划词翻译在不同页面也有不同的大小，所以需要频繁设置划词翻译的字体大小

**你想要如何解决你的问题？**
希望增加一个选项可以固定缩放比例，即便在设置了不同缩放比例的网站里，划词翻译的翻译面板也能固定一个大小

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**

**补充信息**

**Comment by lmk123** [comment]
我重新描述一下你的需求：

1. 你希望缩放比例【小、中、大】的选择在不同的标签页之间互相独立、互不影响
2. 你希望下次再进入一个网站时，缩放比例能保持为上次在这个网站设置的比例

这么描述对吗

**Comment by Nikoyyy** [comment]
我的本意是，划词翻译的缩放比例【小、中、大】可以不受网页缩放比例的影响，在所有网页可以保持同一个大小。如果在不同标签页之间相互独立，也无法将划词翻译设置为完全相同的大小，感觉不是太好的方案。如果实现不了，也只能用这种方式了。毕竟划词翻译字体设置为小，在不同缩放比例的网页却又是完全不同的大小，确实有点难绷。

**Comment by Nikoyyy** [comment]
> 我的本意是，划词翻译的缩放比例【小、中、大】可以不受网页缩放比例的影响，在所有网页可以保持同一个大小。如果在不同标签页之间相互独立，也无法将划词翻译设置为完全相同的大小，感觉不是太好的方案。如果实现不了，也只能用这种方式了。毕竟划词翻译字体设置为小，在不同缩放比例的网页却又是完全不同的大小，确实有点难绷。

**Comment by lmk123** [comment]
也就是说你不希望划词翻译的文字大小、尺寸啥的受到浏览器的缩放设置（比如 150%）的影响。

从技术上来讲，这是很难办到的，毕竟弹窗属于网页的一部分。

或者，我做一个新功能，在网页上划词，但是调用独立翻译窗口来展示结果，这样是不是也可以？

**Comment by Nikoyyy** [comment]
是的，调用独立窗口来展示结果也可以。但是独立窗口一天只有80次哈哈哈哈就有点难受了哈哈哈

**Comment by lmk123** [comment]
等升级到 mv3 后会加个侧边翻译的功能，就是在网页上划词，但通过一个单独的侧边栏显示结果，也可以解决这个问题。

顺带一提，从最新的 v10.11.0 开始，使用次数周期由 1 天改为了 7 天，比如独立翻译窗口由 80 / 天 改为了 500 次 / 7 天，这样也许会比一天的体验好一些 :joy:

**Comment by Nikoyyy** [comment]
好的感谢
