### ISSUE TITLE
百度翻译不可用，貌似换了新的域名

### ISSUE THREAD

**Issue by sdnuchen** [hcfyapp/crx-selection-translate#2058]
## 基本信息

划词翻译版本：v10.10.0
浏览器版本：Firefox 128.0 (64 位)
操作系统：Windows 11 23H2

## 重现问题的步骤

1.百度翻译失败，打不开帮助文档提供的网址，经自查发现域名更换了

**Comment by lmk123** [comment]
我试了一下，https://hcfy.app/docs/services/baidu-api 这里面的百度翻译的链接都是能打开的，我试试接口能不能用

**Comment by lmk123** [comment]
接口我也试了，是正常的，估计是你网络出问题了

**Comment by sdnuchen** [comment]
> 我试了一下，https://hcfy.app/docs/services/baidu-api 这里面的百度翻译的链接都是能打开的，我试试接口能不能用

我刚试出来了，挂着梯子用不了百度，我的问题，没事了，谢谢作者大大
