### ISSUE TITLE
在 target 语种选择下拉框中找不到语种 zh 的选项。

### ISSUE THREAD

**Issue by delcompan** [hcfyapp/crx-selection-translate#2059]
没更新（10.10）之前一直好用，更新到10.11后，显示：在 target 语种选择下拉框中找不到语种 zh 的选项。

**Comment by lmk123** [comment]
我试了一下，是正常的，如下图。

如果你仍然有这个问题，麻烦重开一个 issue，按照提问模版填写。一旦我能重现问题，我就能解决。

<img width="396" alt="image" src="https://github.com/user-attachments/assets/68815303-1761-4a6f-91a5-341caba8f7b2">

**Comment by lmk123** [comment]
已确认此 bug 需要将英文翻译成中文时才会出现，详细信息及修复后续见 #2060
