### ISSUE TITLE
DeepL 报错：“在 target 语种选择下拉框中找不到语种 zh 的选项”

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#2060]
## 基本信息

划词翻译版本：v0.11.0
浏览器版本：chrome 126
操作系统：macos

## 重现问题的步骤

1. 使用 DeepL 翻译英文，如 `hello, how are you?`
2.
3.

### 预期行为
正常显示中文的翻译结果
### 实际行为
报错了：在 target 语种选择下拉框中找不到语种 zh 的选项
### 补充信息

用 DeepL 把中文翻译成英文时是正常的。

cc #2059

**Comment by nancycxx** [comment]
遇到了同样滴问题，求问是怎么解决的呀？

**Comment by lmk123** [comment]
> 遇到了同样滴问题，求问是怎么解决的呀？

@nancycxx https://hcfy.app/blog/2024/07/16/deepl
