### ISSUE TITLE
Deepl 无法正常使用

### ISSUE THREAD

**Issue by raymond20200212** [hcfyapp/crx-selection-translate#2062]
我使用的是 Windows 11 Version 126.0.6478.115 (Official Build) (32-bit) 和划词翻译  v10.11.0，今天我发现网页 翻译功能中的DEEPL不能用了。重现问题的步骤如下:
打开经济学人英语网页：https://www.economist.com/finance-and-economics/2024/07/09/how-strongmen-abuse-tools-for-fighting-financial-crime，使用划词翻译中的DEEPL插件时提示以下错误：
在 target 语种选择下拉框中找不到语种 zh 的选项。[查看解决方案](https://hcfy.app/docs/faqs/why-services-always-loading#deepl-only)

**Comment by lmk123** [comment]
https://hcfy.app/blog/2024/07/16/deepl
