### ISSUE TITLE
截图翻译报错：“如果设置了 count 和 date.duration，那么必须设置 date.start“

### ISSUE THREAD

**Issue by ljsmith111** [hcfyapp/crx-selection-translate#2064]
解决方案：通过离线安装包的方式升级到 v10.12.1 即可，安装方式：https://hcfy.app/docs/installv2/offline#download

或者等待 5 工作日左右，浏览器会自动升级

-----------------------------------------------

## 基本信息

划词翻译版本：v10.12.0
浏览器版本：Chrome 版本 126.0.6478.183（正式版本） （64 位）
操作系统：win10

## 重现问题的步骤

1.打开任意网页并使用截图翻译功能或使用读取剪贴板内的图片功能
2.选择并确定

### 实际行为：显示“从图片中提取文字时发生了一个错误：如果设置了 count 和 date.duration，那么必须设置 date.start。”
![5 Q0D(KY~JV9{(Y AA54M 6](https://github.com/user-attachments/assets/718b34d3-4c22-4f9c-8c31-48a3761ae68f)

**Comment by lmk123** [comment]
收到，我赶紧修复一下 :joy: 由于我没法重现这个问题，一会儿我修好了把开发包发在这里，你方便帮忙测试一下吗

**Comment by ljsmith111** [comment]
omg这么快 可以的当然没问题

**Comment by lmk123** [comment]
我这边重现了，稍等 5 分钟我发个离线安装包出来

**Comment by lmk123** [comment]
v10.12.1 的离线安装包发布到网盘里了，安装方式：https://hcfy.app/docs/installv2/offline#download

我这边测试应该是修复了，不过还是希望你能试一下给我一个反馈

**Comment by ljsmith111** [comment]
完全修复了！非常感谢你！谢谢！！
