### ISSUE TITLE
截图翻译出现如下

### ISSUE THREAD

**Issue by makqiang** [hcfyapp/crx-selection-translate#2065]
## 基本信息

划词翻译版本：v10.12.0
浏览器版本：edge 版本 109.0.1518.140 (正式版本) (64 位)
操作系统：win7

## 重现问题的步骤
![image](https://github.com/user-attachments/assets/a68566b0-f0e8-4e33-8c04-5188d5252d5b)
某天突然出现了截图中的描述，不知道是划词翻译的问题还是百度识图的问题，在划词翻译和百度识图中均未找到错误说明。

**Comment by makqiang** [comment]
![image](https://github.com/user-attachments/assets/54f06536-b334-4d4f-bce0-f83f365bedff)
哦哦 找到了和我出现同样问题的帖子了

**Comment by lmk123** [comment]
解决方案：通过离线安装包的方式升级到 v10.12.1 即可，安装方式：https://hcfy.app/docs/installv2/offline#download

或者等待 5 工作日左右，浏览器会自动升级

**Comment by makqiang** [comment]
谢谢 已经解决了
