### ISSUE TITLE
希望优化下网页翻译排版

### ISSUE THREAD

**Issue by tangqiu0205** [hcfyapp/crx-selection-translate#2068]
**没有这个功能（改进）的时候，你遇到了什么问题？**
开启网页翻译后,排版变得些许难受, 从其他语言翻译成中文时, 同时也会把中文再翻译一遍.影响体验

**你想要如何解决你的问题？**
遇到中文不用再翻译一遍, 排版可以参考下沉浸式翻译https://github.com/immersive-translate/immersive-translate/

**补充信息**
本软件:
![image](https://github.com/user-attachments/assets/d46c1ba4-11ec-4bdd-9864-ee37c07c0cd1)

沉浸式翻译:
![image](https://github.com/user-attachments/assets/bd00f2be-f297-4d4d-b8c6-24e3f2b7bbdc)

**Comment by lmk123** [comment]
这是个工作量比较大的事情，原理需要给每个网站配置一个规则，规定翻译哪些区域、不翻译哪些区域 :joy:

先待定

**Comment by lmk123** [comment]
或者等待我完成 #1406 吧 :joy:

**Comment by lmk123** [comment]
你好 @tangqiu0205  ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！另外，在【划词翻译 Next】中，排版效果已有较大改善，并会持续改进。

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />

**Comment by tangqiu0205** [comment]
好啊好啊
