### ISSUE TITLE
PDF文件修改后在内置PDF阅读器中浏览的还是旧内容

### ISSUE THREAD

**Issue by mortaltom** [hcfyapp/crx-selection-translate#2073]
## 基本信息

划词翻译版本：10.12.1
浏览器版本：127.0.2651.74 (正式版本) (64 位)
操作系统：win11

## 重现问题的步骤

1.PDF拖入内置PDF阅读器
2.修改PDF
3.重新在内置PDF阅读器打开

### 预期行为
PDF阅读器更新到修改后的内容
### 实际行为
PDF阅读器依旧显示旧内容

**Comment by lmk123** [comment]
这不是 bug。你修改 pdf 后（加文字、划线等）需要自行保存，这些修改是不会自动应用到原 pdf 文件上的。
