### ISSUE TITLE
有时候双击一段英文，会把换行符选中，就无法翻译了（翻译后还是英文）

### ISSUE THREAD

**Issue by halw001** [hcfyapp/crx-selection-translate#2074]
如果手动选中这段英文，不要选中最后一小格空白（这一小格空白应该是换行符吧？），就可以正常翻译成中文。

**Comment by lmk123** [comment]
我模拟了你说的场景，如下段落：

```
Hello, how are you?

```

连同最后的一小格空白一起选中，是能正常翻译的，如下图。可否提供稳定的重现步骤，比如你是在哪个网站、双击选中了什么文本之类的，我需要能稳定重现才能解决你的问题

**Comment by lmk123** [comment]
![1111](https://github.com/user-attachments/assets/d01a0c1d-cd3a-47a9-9150-47dfaac03282)

**Comment by halw001** [comment]
> 我模拟了你说的场景，如下段落：
> 
> ```
> Hello, how are you?
> ```
> 
> 连同最后的一小格空白一起选中，是能正常翻译的，如下图。可否提供稳定的重现步骤，比如你是在哪个网站、双击选中了什么文本之类的，我需要能稳定重现才能解决你的问题

https://www.youtube.com/watch?v=9VlvbpXwLJs
比如youtube上这条置顶留言，双击选中后就无法翻译，手动选中就正常
![微信截图_20240801230051](https://github.com/user-attachments/assets/dad46e7e-e771-4916-bdfa-db1c323ca629)
![微信截图_20240801230227](https://github.com/user-attachments/assets/ba099453-4fda-4169-a864-5d9f60b49a4c)

**Comment by lmk123** [comment]
这是符合预期的。

双击这段话的时候，你其实是连同下面的“翻译成中文（中国）”一起选中了，所以你实际上翻译的文本是：

```
Let me know your key takeaways from this mega video!
翻译成中文（中国）
```

你可以勾选“显示文本框”，你就能看到你实际选中的文本。

而对于中英文混合的文本，谷歌翻译确实是不能正确识别并翻译的，详细说明见下面这篇文档里的“为什么划词翻译无法解决此问题？”

https://hcfy.app/docs/guides/page#yyy

**Comment by lmk123** [comment]
你好 @halw001  ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
