### ISSUE TITLE
自己配置的DeepL不能使用

### ISSUE THREAD

**Issue by zhy7201** [hcfyapp/crx-selection-translate#2076]
划词翻译版本：10.13.0
浏览器版本： FireFox 128
操作系统：Win 11

## 重现问题的步骤如下图
![绘图1](https://github.com/user-attachments/assets/d7cf8cf4-2784-4980-9507-09fd7b579e67)

**Comment by lmk123** [comment]
我试了下，是正常的。虽然我的接口类型是 Free 但应该跟这个没关系

你可以去你的 DeepL 账号管理里看看，看是不是有啥报错之类的，比如信用卡被封禁了啥的

**Comment by lmk123** [comment]
啊不对，才看到你的截图。你这个密钥不是用于 API 的，你这个是专门给 CAT 工具用的密钥。你需要再申请一个用于 DeepL API （不是 CAT 工具）的密钥。

或者建议用划词翻译新推出的套餐包，6 元 / 100 万字符，很便宜

**Comment by ikkyusan123** [comment]
> 啊不对，才看到你的截图。你这个密钥不是用于 API 的，你这个是专门给 CAT 工具用的密钥。你需要再申请一个用于 DeepL API （不是 CAT 工具）的密钥。
> 
> 或者建议用划词翻译新推出的套餐包，6 元 / 100 万字符，很便宜

以前也是用的这个密钥啊，为什么现在用这个不行了？

**Comment by lmk123** [comment]
> 以前也是用的这个密钥啊

@ikkyusan123 这是不可能的。

划词翻译从始至终接入的是 DeepL API，而用于 CAT 工具的密钥是订阅 DeepL Pro 生成的，这完全是两个不同的东西。

附官方文档：

https://support.deepl.com/hc/zh-cn/articles/360020675420-%E6%94%AF%E6%8C%81-CAT-%E5%B7%A5%E5%85%B7%E7%9A%84-DeepL-Pro-%E8%AE%A2%E9%98%85

> 请注意：DeepL Pro 计划不包括访问 DeepL 的 API。如果你想在非 CAT 工具的应用程序中集成 DeepL 的翻译技术，你则需要订阅 [DeepL API](https://www.deepl.com/pro#developer) 计划。
