### ISSUE TITLE
无法使用翻译积分

### ISSUE THREAD

**Issue by Thong2537** [hcfyapp/crx-selection-translate#2077]
## 基本信息

划词翻译版本：v10.13.0
浏览器版本：Firefox，Chrome
操作系统：Windows

## 重现问题的步骤

1. 购买翻译积分
2. 使用任意需要翻译积分的功能：如有道，Chatgpt
![图片](https://github.com/user-attachments/assets/42dcf7bf-c517-401b-ab1b-f6862a8db637)

### 预期行为
能够正常使用

### 实际行为
全部显示翻译报错
![图片](https://github.com/user-attachments/assets/ad671b3f-4830-48e0-a3e7-c1fdcae1440d)

### 补充信息

尝试过重新安装插件，更换Firefox或Chrome浏览器，都无法解决问题，怀疑我的账号有异常。

**Comment by lmk123** [comment]
首先，翻译积分不支持 chatgpt，chatgpt 是在最近新推出的“套餐包”里。未来套餐包会逐步替代翻译积分。

然后，有道翻译报错是因为我忘记给我的有道翻译充值了 :joy: 刚才重新充了值，现已恢复，感谢反馈

**Comment by Thong2537** [comment]
> 首先，翻译积分不支持 chatgpt，chatgpt 是在最近新推出的“套餐包”里。未来套餐包会逐步替代翻译积分。
> 
> 然后，有道翻译报错是因为我忘记给我的有道翻译充值了 😂 刚才重新充了值，现已恢复，感谢反馈

建议更改一下文本，大部分服务都写的可以使用翻译积分
![图片](https://github.com/user-attachments/assets/7d197042-b1a2-4404-90b8-327f5c12b38b)

**Comment by lmk123** [comment]
好的，下个版本改

**Comment by lmk123** [comment]
你好 @Thong2537 ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
