### ISSUE TITLE
我是付费用户，为什么我的chatgpt翻译功能总是不能用。

### ISSUE THREAD

**Issue by westernmaitian** [hcfyapp/crx-selection-translate#2079]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

你好，我是付费用户，为什么我的chatgpt翻译功能总是不能用？总是提示以下内容：

【ChatGPT】尝试通过密钥、翻译积分使用ChatGPT时均失败了。点击重试

**Comment by lmk123** [comment]
你应该是购买了 20 元 / 月的套餐包。刚才后台的 chatgpt 服务在更新，现在已经恢复了。

如果你仍然没有恢复或者不是购买的套餐包，欢迎继续留言。

**Comment by lmk123** [comment]
顺带一提，使用 chatgpt 进行网页全文翻译可能会遇到译文跟原文对不上的问题，这是因为 chatgpt 作为一个对话式 AI，它做不到严格保留原文的换行符数量 :joy: 

这个问题以后会修复的，现在建议使用 DeepL 进行全文翻译 :joy:
