### ISSUE TITLE
配置 ChatGPT 密钥时增加自定义 API 接口地址的功能

### ISSUE THREAD

**Issue by LinLin00000000** [hcfyapp/crx-selection-translate#2082]
**没有这个功能（改进）的时候，你遇到了什么问题？**
我是在手机上使用划词翻译的，手机一般不开 VPN，但又无法裸连 OpenAI。我有中转或者代理的方法，但是你这不支持配置，相当于无法使用，

**你想要如何解决你的问题？**
增加功能。

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
那我只能换其他的软件使用了。

**补充信息**
沉浸式翻译这个插件做的配置就很不错。功能十分全面，ChatGPT 配置项非常多，还能自定义模版 prompt，现在我只能用那个软件来替代划词翻译。

利益相关：划词翻译永久会员

**Comment by lmk123** [comment]
已有功能，在划词翻译设置 - 第三方服务 - ChatGPT 找 翻译命令 和 镜像地址
