### ISSUE TITLE
 恳请大家帮忙测试划词翻译 V11.0.0（Manifest V3）

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#2083]
我最近完成了将划词翻译迁移为 Manifest V3 的工作，但由于改动过大，我自己测试肯定不全面，所以希望大家能帮助我测试。

V11.0.0 已经提供的离线安装包，下载地址 & 安装方式见：https://hcfy.app/docs/log/v11

**Comment by lmk123** [comment]
v11.0.0 已经上线，所以不用单独安装来测试了

**Comment by ghost** [comment]
Firefox的测试呢？

**Comment by lmk123** [comment]
Firefox 从文档上看没有完全兼容 Chrome / Edge 的 Manifest V3，暂时还没有做适配
