### ISSUE TITLE
bug 控制台页面报错

### ISSUE THREAD

**Issue by 11003** [hcfyapp/crx-selection-translate#2084]
![image](https://github.com/user-attachments/assets/a5c83386-9276-4f72-8a60-b08f71199cf8)
![image](https://github.com/user-attachments/assets/96aec28e-e6ea-40fe-91c4-9e16fa60f634)

**Comment by lmk123** [comment]
光是给个报错，我没法定位问题啊 :joy:

麻烦再开一个 issue，按照模版提供一下重现步骤

**Comment by 11003** [comment]
好呢~
