### ISSUE TITLE
Deepl引擎不可用

### ISSUE THREAD

**Issue by Tobeprmn** [hcfyapp/crx-selection-translate#2089]
## 基本信息

划词翻译版本：10.14.1
浏览器版本：edge 127.0.2651.105（正式版本）
操作系统：win10 22H2

## 重现问题的步骤

你好，请问deepl引擎（非内置版）填入API后为什么无法使用了，上一个版本还能正常使用

### 补充信息

![2](https://github.com/user-attachments/assets/d0778b2b-eac3-48d8-bbca-ad21cf664001)
![1](https://github.com/user-attachments/assets/af1c42a0-f006-4d94-9cbe-f8860db9ae68)

**Comment by lmk123** [comment]
456 说明你已经用完了 50w 字符了
