### ISSUE TITLE
Could not found["[data-testid=\"translator-source-clear-button\"]","[dl-test=\"translator-source-clear-button\"]"]

### ISSUE THREAD

**Issue by JorLinWang2** [hcfyapp/crx-selection-translate#2090]
## 基本信息

划词翻译版本：
浏览器版本：
操作系统：

## 重现问题的步骤

1.
![image](https://github.com/user-attachments/assets/c48cd13e-43fd-4b70-8657-703a77feb345)

2.
3.

**Comment by lmk123** [comment]
使用 Chrome 127、划词翻译 v10.14.1，没有重现
