### ISSUE TITLE
希望添加对edge浏览器中沉浸式阅读器的适配。

### ISSUE THREAD

**Issue by Yangjx96** [hcfyapp/crx-selection-translate#2101]
当前edge浏览器版本为128.0.x，插件在沉浸式浏览器中不起作用。
更多的，在edge浏览器版本更新至最新版本后，插件在calibre的在线阅读器中也无法使用（在旧edge版本，如124.x，阅读epub格式电子书时可正常使用翻译功能）。

希望加入对edge浏览器沉浸式阅读器的适配。

**Comment by Yangjx96** [comment]
![screenshot-1724921980019](https://github.com/user-attachments/assets/1fe4e5d1-24f6-4a16-a316-a00ac2618fee)

![screenshot-1724922009396](https://github.com/user-attachments/assets/5ce0f849-92e0-4718-8192-36dd26b5e689)

例如在这两类浏览器的阅读器中，插件均不起作用。而在旧版edge浏览器中，插件在calibre的在线阅读器中是可以正常使用的。

**Comment by lmk123** [comment]
做不到。

我看了一下，Edge 浏览器的阅读器模式（以 read:// 协议开头的网址）是没法注入代码的，它属于 Edge 浏览器禁止扩展程序控制的页面之一，类似 Edge 的其它以 edge:// 协议的页面，如设置页 edge://settings
