### ISSUE TITLE
在大部分github的markdown文件页, 打开双语对照的全文翻译会反复的进入翻译状态

### ISSUE THREAD

**Issue by JOHY119** [hcfyapp/crx-selection-translate#2102]
## 基本信息

划词翻译版本：11.0.1

浏览器版本：128.0.6613.85
操作系统：windows11

## 重现问题的步骤

1. 打开一个github仓库中的markdown文件. 例如 https://github.com/google/wire/blob/main/docs/best-practices.md
2. 开启全文翻译(双语对照模式), 向下滚动一部分直到不显示文档标题或更往下.

### 预期行为
仅滚动到当前翻译部分结束才重新请求翻译
### 实际行为
不停重复翻译
### 补充信息

![动画](https://github.com/user-attachments/assets/f96585e2-7bca-45e9-9ad4-c0c1f354f82a)

已有issues #2035

**Comment by lmk123** [comment]
感谢反馈。确认了一下，确实跟 #2035 是同一个问题

所以你提的这个我就先关闭了，后续进展可以跟进 #2035
