### ISSUE TITLE
点击扩展按钮时开启网页全文翻译功能未生效

### ISSUE THREAD

**Issue by klingeling** [hcfyapp/crx-selection-translate#2110]
## 基本信息

划词翻译版本：11.1.0
浏览器版本：128.0.6613.120
操作系统：win11

## 重现问题的步骤

1.设置 扩展按钮 为点击扩展按钮时 开启网页全文翻译
2.点击扩展按钮

### 预期行为
点击扩展按钮未打开网页全文翻译
### 实际行为
点击扩展按钮应打开网页全文翻译
### 补充信息
退回到v10.14.1该功能未失效

**Comment by lmk123** [comment]
感谢反馈，将在下个版本修复
