### ISSUE TITLE
内置阅读器可以增加选中文字高亮功能吗

### ISSUE THREAD

**Issue by ATRI-Star** [hcfyapp/crx-selection-translate#2113]
内置阅读器可以增加选中文字高亮功能吗，既想要Edge阅读器自带的轻编辑，又想要划词翻译

**Comment by lmk123** [comment]
对内置阅读器进行二次开发有难度且耗时长，所以我大概不会自行开发，但是内置阅读器本身作为一个第三方软件，其实它自身已经有计划加这个功能了，我能做的就是等它发布新版本之后，尽快集成进划词翻译当中 :joy:
