### ISSUE TITLE
打开插件时访问 chatgpt.com , 网页报错 out of memory, 关闭插件就可以了

### ISSUE THREAD

**Issue by zouningujs** [hcfyapp/crx-selection-translate#2114]
## 基本信息
打开插件时访问 chatgpt.com , 网页报错 out of memory, 关闭插件就可以了
划词翻译版本：11.1.2
浏览器版本：chrome 版本 128.0.6613.138（正式版本） （64 位）
操作系统：win10 最新版

## 重现问题的步骤

1.启用翻译插件
2.访问 https://chatgpt.com
3.出现错误 out of memory

### 预期行为
能正常访问网页

### 实际行为
出现错误 out of memory
### 补充信息
关闭插件后 能够正常访问

**Comment by lmk123** [comment]
神奇的问题，但我试过之后，没有重现。

你有没有尝试过关闭别的插件再试？我猜测应该是很多插件共同造成了这一问题

**Comment by zouningujs** [comment]
确实是和其他插件共同作用引起的, 当时一个个插件关闭, 刚好关闭到这个插件就好了, 实际上是和其他插件共同作用的结果. 我关闭issue了
