### ISSUE TITLE
chatgpt接口翻译结果出现undefined

### ISSUE THREAD

**Issue by ziyunhui** [hcfyapp/crx-selection-translate#2115]
## 基本信息

划词翻译版本：v11.1.2
浏览器版本：130.0.6710.0
操作系统：win10

## 重现问题的步骤

1.使用chatgpt/openaiAPI进行翻译所有内容最后跟着undefined

### 补充信息
尝试改过提示词，没有效果。使用三方API接口，不过应该不会是接口问题
![QQ截图20240916172652](https://github.com/user-attachments/assets/31bcb6d6-af05-4915-b739-169a1587a004)

**Comment by lmk123** [comment]
你提到“应该不会是接口问题”，所以我直接使用了划词翻译套餐包里的 gpt-3.5-turbo 试了一下，没有重现这个问题，如下图。

所以我还是怀疑是你使用的中转服务的问题 :joy:

<img width="691" alt="image" src="https://github.com/user-attachments/assets/bd6337ad-e8dc-4edf-8707-afa537e39867">

**Comment by ziyunhui** [comment]
> 你提到“应该不会是接口问题”，所以我直接使用了划词翻译套餐包里的 gpt-3.5-turbo 试了一下，没有重现这个问题，如下图。
> 
> 所以我还是怀疑是你使用的中转服务的问题 😂
> 
> <img alt="image" width="691" src="https://private-user-images.githubusercontent.com/5035625/367728912-bd6337ad-e8dc-4edf-8707-afa537e39867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODk5NDksIm5iZiI6MTcyNjQ4OTY0OSwicGF0aCI6Ii81MDM1NjI1LzM2NzcyODkxMi1iZDYzMzdhZC1lOGRjLTRlZGYtODcwNy1hZmE1MzdlMzk4NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTIyNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTg3YzhkYzlkNDMzZjliNmEzMGIwODA1M2U0NWFhOGE4YmU3MDA0NzdmYTBjNTljZGYzYTg0ZjI1MDUzOWI3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XD3we4zTUJuCsnkyPm3TWRNf17HJ-f2-dQeIkEMJorE">

确实是接口问题，感谢测试
