### ISSUE TITLE
无法在 chatgpt 中弹出翻译面板

### ISSUE THREAD

**Issue by lian2299** [hcfyapp/crx-selection-translate#2116]
## 基本信息
在 chatgpt （https://chatgpt.com/*) 中，不能弹出翻译面板

划词翻译版本：
v11.1.3
浏览器版本：
128.0.6613.139
操作系统：
windows 11 , 23H2

## 重现问题的步骤
1. 在 chatgpt 任意一个会话中，选中一段文本
2. 右击，“翻译这段文本”
3. 或者使用快捷键

### 预期行为
应弹出翻译面板，出现翻译结果

### 实际行为
无法弹出翻译面板，没有任何反应。

### 补充信息
- 尝试在 Service Worker 中查看错误信息，没有看到错误信息
- 尝试在另一个 chrome profile 中测试，同样的问题

**Comment by lmk123** [comment]
感谢反馈，已重现。

~~跟 #1923 属于同一个问题~~

修复时发现不相关

**Comment by J1npen** [comment]
我也遇到了相同的问题
划词翻译版本：
v11.1.3
Chrome版本：
129.0.6668.59（正式版本）
操作系统：
Windows 11 家庭中文版, 23H2

**Comment by lmk123** [comment]
另：macOS + Edge 129 + 划词翻译 v10.14.1 没有出现这个问题（虽然控制台也有 React SSR 相关的报错
