### ISSUE TITLE
在Vivaldi浏览器中 插件在部分网站（如ChatGPT）中无法正常工作

### ISSUE THREAD

**Issue by RJSackville** [hcfyapp/crx-selection-translate#2123]
## 基本信息

划词翻译版本：v11.1.3
浏览器版本：Vivaldi 6.9.3447.48 (Stable channel)
操作系统：Windows 11 23H2

## 重现问题的步骤

1. 在ChatGPT网页中选中文字后按“翻译选中的文本”快捷键
2. 在ChatGPT网页中选中文字后在右键菜单中选择划词翻译 - 翻译这段文本
3. 启用网页划词后在网页中选中文字

### 预期行为

插件正常工作，出现悬浮翻译小图标或者悬浮翻译窗口

### 实际行为

无任何反应

### 补充信息

尝试了Edge、Chrome、Firefox都可以正常工作

**Comment by lmk123** [comment]
其实在 Chrome 中，划词翻译在 ChatGPT 也是无法正常使用的，并非特定于 Vivaldi，见 #2116 

目测是 ChatGPT 网页版正在灰度发布基于 React SSR 的网站，而由于划词翻译也是基于 React 的且修改了原 DOM，导致了这个问题。
