### ISSUE TITLE
Chatgpt 翻译的指令修改：以意译的方式进行翻译，避免直译。

### ISSUE THREAD

**Issue by brucelong-76m** [hcfyapp/crx-selection-translate#2131]
Chatgpt 翻译的指令修改：以意译的方式进行翻译，避免直译。

**Comment by lmk123** [comment]
已有功能。

在划词翻译设置页 - 【第三方服务】-【ChatGPT】-【翻译命令】。

划词翻译设置页打开方式见：https://hcfy.ai/docs/guides/options
