### ISSUE TITLE
【功能请求】翻译源新增ollama

### ISSUE THREAD

**Issue by blacksheepaul** [hcfyapp/crx-selection-translate#2132]
你可以自定义翻译服务 ：https://hcfy.app/docs/services/custom-api

如果自定义翻译服务满足不了你的需求，欢迎继续留言

_Originally posted by @lmk123 in https://github.com/hcfyapp/crx-selection-translate/issues/1992#issuecomment-2071367179_

---

试过了自定义翻译，确实满足不了需求。

<img width="737" alt="image" src="https://github.com/user-attachments/assets/00bccf38-7d02-44ff-b241-98dbc3901d5b">

**关于为什么想要：**

虽然llama的翻译质量比不上openai，但本地部署的模型翻译速度甚至比百度翻译还快，还是希望能作为一个参考项。

curl格式如下，为避免内容过长，修改了prompt：
```bash
curl http://192.168.0.115:11434/api/generate -d '{
   "model": "llama3.2:3b",
   "prompt":"Hello"
}'
```
响应格式如下：
```
{"model":"llama3.2:3b","created_at":"2024-10-03T16:15:26.470425744Z","response":"How","done":false}
{"model":"llama3.2:3b","created_at":"2024-10-03T16:15:26.470429501Z","response":" can","done":false}
{"model":"llama3.2:3b","created_at":"2024-10-03T16:15:26.470468444Z","response":" I","done":false}
{"model":"llama3.2:3b","created_at":"2024-10-03T16:15:26.470469957Z","response":" assist","done":false}
{"model":"llama3.2:3b","created_at":"2024-10-03T16:15:26.470477Z","response":" you","done":false}
{"model":"llama3.2:3b","created_at":"2024-10-03T16:15:26.470478343Z","response":" today","done":false}
{"model":"llama3.2:3b","created_at":"2024-10-03T16:15:26.470484434Z","response":"?","done":false}
{"model":"llama3.2:3b","created_at":"2024-10-03T16:15:26.470498901Z","response":"","done":true,"done_reason":"stop","context":[128006,9125,128007,271,38766,1303,33025,2696,25,6790,220,2366,18,271,128009,128006,882,128007,271,9906,128009,128006,78191,128007,271,4438,649,358,7945,499,3432,30],"total_duration":90880784,"load_duration":8884284,"prompt_eval_count":26,"prompt_eval_duration":6156000,"eval_count":8,"eval_duration":30376000}
```

**Comment by blacksheepaul** [comment]
自己加了层中转，不需要了

**Comment by lmk123** [comment]
ollama 会支持的，后续进展可以跟进 #2111

**Comment by lmk123** [comment]
你好 @blacksheepaul ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />

**Comment by blacksheepaul** [comment]
@lmk123  没打扰，没事的。

二维码已经失效了，“因分享者退群，二维码已失效”

**Comment by lmk123** [comment]
确实失效了，这是最新的二维码：

![Image](https://github.com/user-attachments/assets/4efc459d-0024-44d8-860c-642c7cc7c09d)
