### ISSUE TITLE
启用翻译插件插件导致整个网页样式错乱

### ISSUE THREAD

**Issue by hughfenghen** [hcfyapp/crx-selection-translate#2135]
## 基本信息

划词翻译版本：v11.1.3
浏览器版本：chrome 128
操作系统：MacOS

## 重现问题的步骤

1. 开启插件
2. 访问 https://dumi-theme-antd-style.arvinx.com/

### 预期行为
页面样式正常

### 实际行为
启用插件导致整个网页样式错乱，停用插件刷新页面正常

**Comment by lmk123** [comment]
感谢反馈，已重现。

跟 #2116 一样，都是由于划词翻译与 React SSR 的冲突导致的，后续进展可以关注 #2116

**Comment by lmk123** [comment]
经过确认，此问题跟 #2116 无关，所以重新开启

**Comment by lmk123** [comment]
你好 @hughfenghen ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
