### ISSUE TITLE
第三方服务claude模型信息保存不了

### ISSUE THREAD

**Issue by EEEMOOO** [hcfyapp/crx-selection-translate#2136]
划词翻译版本：划词翻译 v10.14.1
浏览器版本：Microsoft Edge 版本 129.0.2792.79 (正式版本) (64 位)
操作系统：win10专业版

## 重现问题的步骤

1.在第三方服务里填写claude自定义配置，命令和地址都能记住，就只有模型刷新后还是空着
2.已测试gpt就没有这种问题

**Comment by lmk123** [comment]
感谢反馈，已重现，将在下个版本中修复
