### ISSUE TITLE
你好，自定义的翻译源能不能带参数？

### ISSUE THREAD

**Issue by yao631029659** [hcfyapp/crx-selection-translate#2143]
你好，现在的自定义的翻译源只能支持简单的get请求，没有地方携带AppId和AppKey。这样万一接口暴露了，不是很危险。

**Comment by lmk123** [comment]
你说的自定义翻译源应该是指这个吧，但你似乎没有读完这个文档 https://hcfy.ai/docs/services/custom-api

首先，自定义翻译源不是 get 请求。

其次，自定义翻译源本身就需要你额外实现对接口的请求，你所说的 appid / appkey 都是在你自己写的代码里，你可以用任何你觉得安全的方式使用它们。

最后，划词翻译自带参数没什么意义，因为每个服务的接口格式都不一样
