### ISSUE TITLE
Claude 翻译 API 提示 header 缺失

### ISSUE THREAD

**Issue by iLtc** [hcfyapp/crx-selection-translate#2145]
## 基本信息

划词翻译版本：11.2.0
浏览器版本：Chrome 130.0.6723.70
操作系统：macOS Sequoia

## 重现问题的步骤

1. 在 服务申请中配置 Claude 密钥
2. 在翻译面板中打开 Claude
3. 尝试翻译文本

### 预期行为

Claude 应该有结果

### 实际行为

Claude API 提示 401 错误

![image](https://github.com/user-attachments/assets/7acf2fd6-d9a2-4d15-b5ef-9e56c3aa4491)

Network Console 提示缺少 `anthropic-dangerous-direct-browser-access` header

![image](https://github.com/user-attachments/assets/cac22ecf-cbd8-4441-aa62-d9eee6e56a9a)

**Comment by lmk123** [comment]
感谢反馈，将在下个版本修复。

相关链接：

https://simonwillison.net/2024/Aug/23/anthropic-dangerous-direct-browser-access/

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by lmk123** [comment]
你好 @iLtc ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />

**Comment by xiaochen1210** [comment]
你怎么自行申请密钥的，不是只有企业才能申请吗

**Comment by iLtc** [comment]
> 你怎么自行申请密钥的，不是只有企业才能申请吗

哈？个人用户在 https://platform.claude.com/ 也可以申请啊
