### ISSUE TITLE
每翻译一次就打开一个独立的Chrome页面

### ISSUE THREAD

**Issue by crystalboyice** [hcfyapp/crx-selection-translate#2146]
**没有这个功能（改进）的时候，你遇到了什么问题？**
每翻译一次就打开一个独立的Chrome页面，按Ctrl+shift+T回退关闭的页面的时候，就全回退之后变成常驻了，还得手动一个个关闭

**你想要如何解决你的问题？**
能不能出个选项，关闭这种翻译方式？或者说已经有选项了，只是我没发现？

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**

**补充信息**

**Comment by lmk123** [comment]
见 https://hcfy.ai/docs/faqs/why-result-different
