### ISSUE TITLE
如何提取出本地的历史记录？

### ISSUE THREAD

**Issue by zhang-lecheng** [hcfyapp/crx-selection-translate#2147]
**没有这个功能（改进）的时候，你遇到了什么问题？**

我希望提取出本地的翻译记录，然后用程序提取出高频生词然后专门学习。

**你想要如何解决你的问题？**

增加提取本地的历史记录的方法

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**

告诉我本地的历史记录保存路径和编码格式

**补充信息**

我查看了文档，没又找到解决方法

**Comment by lmk123** [comment]
目前要提取的话，只能通过代码的方式。

打开划词翻译设置页，然后在控制台运行代码，从 IndexedDB 里提取。IndexedDB 文档：https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

另外，未来我会加入导出历史记录的功能（类似导出收藏夹的 csv），后续进展可以跟进 #2148
