### ISSUE TITLE
希望支持Gmail邮件的划词翻译

### ISSUE THREAD

**Issue by zhukaiqiang1** [hcfyapp/crx-selection-translate#2149]
**没有这个功能（改进）的时候，你遇到了什么问题？**
Gmail邮件不支持划词翻译

**你想要如何解决你的问题？**
支持Gmail邮件的划词翻译

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
右键菜单翻译

**补充信息**
彩云小译支持

**Comment by lmk123** [comment]
我试了一下，是支持的，如下图。你可以关掉其它所有插件、仅保留划词翻译，然后重启浏览器，再在 gmail 中划词试试。如果仍然不行，那这大概是一个 bug。

<img width="708" alt="image" src="https://github.com/user-attachments/assets/00e3955c-a0ba-4f90-b641-7558a125f914">

**Comment by zhukaiqiang1** [comment]
重启后已解决，感谢
