### ISSUE TITLE
关于谷歌翻译2个接口类型 issue

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#2150]
## 基本信息

划词翻译版本：latest
浏览器版本：latest
操作系统：Ubuntu 23.04 & Windows 11 24H2

### 已将谷歌翻译做了反代（使用DNS方式）经测试Chrome内置翻译没问题

1. 划词翻译设置 -> 镜像地址`https://translate.googleapis.com/` -> 接口类型`速度慢、准确率高`
2. 通过`F12` 可以看出没有任何请求`single`谷歌翻译的网络连接，只有`options`
3. 附图
![PixPin_2024-10-31_08-55-23](https://github.com/user-attachments/assets/be31950a-8130-45fc-9357-71a36834298e)

### 成功行为
1. 划词翻译设置 -> 镜像地址`https://translate.googleapis.com/` -> 接口类型`速度快、准确率低`
2. 通过`F12` 可以看出有`single`请求谷歌的翻译。
3. 附图
![2](https://github.com/user-attachments/assets/d44ddfdb-a7f9-42bc-ada8-f6c8d0422c39)

### 补充信息

通过接口类型设置成`速度快、准确率低`
可见请求的域名是`https://translate.googleapis.com`
并且不会出现弹窗

**Comment by lmk123** [comment]
“速度慢、准确率高”是通过 translate.google.com 获取的翻译结果。

关于这两个的差别，文档里其实有说明：https://hcfy.ai/docs/faqs/why-result-different

**Comment by ghost** [comment]
我看过文档了
我的意思是呢 哪怕全局梯子整机走代理 & 软理由设置代理
“速度慢、准确率高”依然是无法使用的

lmk123 ***@***.***> 于2024年10月31日周四 09:30写道：

**Comment by ghost** [comment]
尝试多次
查看日志 TCP的 UDP的
都没有看见任何请求谷歌的请求
偶尔看见了一次... 但是是失败的 忘记保存了

**Comment by lmk123** [comment]
我觉得是你的配置问题，因为在我这里，挂上代理是可以正常使用的

**Comment by ghost** [comment]
> 我觉得是你的配置问题，因为在我这里，挂上代理是可以正常使用的

能否分享一下你设置了哪些域名或者IP呢？
我是就这个用不了.. 但是在别的程序用的谷歌翻译付费接口是可以
百思不得其解

**Comment by lmk123** [comment]
“速度快、准确率低”是通过 https://translate.googleapis.com 调用的，这是谷歌翻译的官方调用接口，包括你所说的“谷歌翻译付费接口”

“速度慢、准确率高”相当于是划词翻译帮你打开了一个 https://translate.google.com 的网页（也就是文档里说的“弹窗”），然后自动执行了翻译操作，再把翻译结果提取出来，所以如果你要用它，那么你需要确保你自己打开 https://translate.google.com 的时候是能正常翻译的。

我没有做任何配置，我用过的梯子都是会自动代理掉 google 相关的请求的，不确定你所说的“配置”指的是什么

**Comment by ghost** [comment]
是的 那真是R了狗了
我这些域名也是都有设置好的
我再去找找问题 真不好意思打扰了

lmk123 ***@***.***> 于2024年10月31日周四 13:17写道：
