### ISSUE TITLE
突然无法连接谷歌服务器，使用各种方法，在没有混用的情况下，都无法使用划词翻译

### ISSUE THREAD

**Issue by kinksaber** [hcfyapp/crx-selection-translate#2151]
上周刚使用过，没有问题，这周再用，显示无法连接谷歌服务器，单一使用提供的各种方法也没有解决。

**Comment by lmk123** [comment]
谷歌翻译退出市场已经两年了，国内的翻译服务器关的差不多了，现在唯一稳定的方案就是用梯子了。

**Comment by kinksaber** [comment]
是的，我发现只能挂梯子了，之前修改hosts还能，现在不行了
