### ISSUE TITLE
【功能改进】希望网页全文翻译的控制面板位置能多一个隐藏的选项

### ISSUE THREAD

**Issue by Archture** [hcfyapp/crx-selection-translate#2152]
![image](https://github.com/user-attachments/assets/6a831e95-3b87-422f-b42f-5999b935f672)
希望“网页全文翻译”的“控制面板位置”能多一个“隐藏”的选项，因为这个按钮有时会遮挡网页文字，如果更改不麻烦的话，提前感谢！

**Comment by lmk123** [comment]
好的，预计在近几个版本中加入

**Comment by Archture** [comment]
感谢！辛苦啦！

**Comment by 7234399** [comment]
全文翻译的控制面板确实这个按钮有时会遮挡网页文字的情况。但是这个面板里面有切换翻译服务和选择当前标签翻译的选项，现在v11.5.0 版本改成可以设置影藏之后，选择影藏的话都没办法选择这些选项了。建议把控制面板两端的白色底色去掉，只保留logo这样遮挡会小很多，另外要是控制面板能再设置成自由移动的话更好了，这样就算被遮挡也可以临时调整一下。

**Comment by Archture** [comment]
我是在隐藏前，提前先把参数设置好了，之后就一直隐藏使用。我很少会改那里面的参数，极偶尔要修改的话，先提前把隐藏取消，进行修改，再隐藏。
