### ISSUE TITLE
使用谷歌学术PDF学术阅读器时没法使用

### ISSUE THREAD

**Issue by 1489-gh** [hcfyapp/crx-selection-translate#2153]
在这个插件下阅读PDF，你的扩展程序没有任何作用。就算我右键让他翻译，都没任何翻译。

**Comment by 1489-gh** [comment]
WIN10操作系统，chrome。

**Comment by lmk123** [comment]
我猜你指的是 [Google 学术搜索 PDF 阅读器](https://chromewebstore.google.com/detail/google-%E5%AD%A6%E6%9C%AF%E6%90%9C%E7%B4%A2-pdf-%E9%98%85%E8%AF%BB%E5%99%A8/dahenjhkoodjbpjheillcadbppiidmhp?hl=zh-CN)这个插件。

划词翻译无权将代码应用到别的扩展程序内，这是 Chrome 浏览器进行的安全隔离，所以你会发现划词翻译在其它插件内是无效的。

但是，你可以通过“翻译浏览器外的内容”的方式进行翻译，详见文档 https://hcfy.ai/docs/guides/extra
