### ISSUE TITLE
已付费,但无法使用gpt翻译,提示500错误

### ISSUE THREAD

**Issue by nnop** [hcfyapp/crx-selection-translate#2154]
已购买10元/月套餐包
gpt的配置用3.5和3o-mini正常,用4o报以下错误:

<img width="488" alt="image" src="https://github.com/user-attachments/assets/7735952a-95f0-4004-add9-f7483d1f5736">

请问如何解决?

**Comment by lmk123** [comment]
出现这个错误一般是由于偶尔的网络不稳定导致的，现在应该已经恢复正常了，因为我尝试了很多次都没出现这个问题。

**Comment by lmk123** [comment]
今天 ChatGPT 确实出现了很多次的无法使用的情况，我已经定位到原因了，将在凌晨一点左右的时候更新后台服务器来解决这个问题。

**Comment by lmk123** [comment]
已经提前发布了，测试了大概 20 分钟，没有再出现报错的情况。

最后，感谢你的反馈，不然我也不会留意到这个问题！
