### ISSUE TITLE
有计划支持ios的翻译嘛

### ISSUE THREAD

**Issue by NightAsker** [hcfyapp/crx-selection-translate#2162]
**没有这个功能（改进）的时候，你遇到了什么问题？**
在ios safari中使用时，不支持网页的翻译

**你想要如何解决你的问题？**
在ios safari中使用时，能翻译网页

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
提供个ios捷径能copy翻译也行

**补充信息**
沉浸式翻译在ios商店中就有对应的app，可以支持ios safari的网页翻译

**Comment by lmk123** [comment]
我想法很多，除了 ios 翻译，还有 web 版、桌面版啥的，但是现在光是划词翻译插件这一项我就忙不过来了 :joy:

所以。。我只能说我有这个想法，但是不知道什么时候能开始动手
