### ISSUE TITLE
怎么取消鼠标悬浮取词

### ISSUE THREAD

**Issue by printfqi** [hcfyapp/crx-selection-translate#2163]
现在默认鼠标悬浮取词功能是开启的，很影响阅读，动不动就翻译，想关闭这个功能没找到位置

**Comment by lmk123** [comment]
在网页上随便划选一个词并翻译，然后会弹出翻译结果窗口，这个翻译结果窗口右上角有个齿轮图标，点一下，就能找到【鼠标悬浮取词】的开关了
