### ISSUE TITLE
chrome pdf右键选择“划词翻译”-“翻译这段文本”，操作步骤太多

### ISSUE THREAD

**Issue by TeranZhang** [hcfyapp/crx-selection-translate#2166]
增加设置：

选择文本-右键划词翻译（默认翻译这段文本）

**Comment by lmk123** [comment]
这是 chrome 自身的限制，如果同一个扩展程序有多个右键菜单项，就一定会有一个以扩展程序名称为名的二级菜单。

你可以在划词翻译设置页 - 外观 - 右键菜单中，取消勾选除了“翻译这段文本”以外的全部其它菜单项，这样就可以让“翻译这段文本”直接出现在右键菜单中了
