### ISSUE TITLE
内网的API接口返回http405无法使用

### ISSUE THREAD

**Issue by ytxing** [hcfyapp/crx-selection-translate#2168]
**没有这个功能（改进）的时候，你遇到了什么问题？**
内网部署有API接口，兼容openai接口，但填写网址和密钥后返回http405无法使用。是否因为通过了划词翻译的第三方服务器进行中转？

**你想要如何解决你的问题？**
是否可以本地实现

**Comment by lmk123** [comment]
自行填写密钥没有经过任何中转。
