### ISSUE TITLE
在vivaldi浏览器中无法使用DEEPL（内置）翻译

### ISSUE THREAD

**Issue by Zyt221** [hcfyapp/crx-selection-translate#2169]
划词翻译版本：v11.3.0
浏览器版本：[Vivaldi.7.0.3495.20.x64]
操作系统：Windows 10

## 重现问题的步骤

在Vivaldi浏览器中使用划词翻译，并且划词翻译已登录且购买会员，谷歌翻译、百度翻译、gemini等都能正常翻译，只有DEEPL（内置）一直加载不出来，长时间加载后显示A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received，无论是刷新网页还是重试多次仍是如此

### 补充信息
在设置完全相同的情况下，在Chrome浏览器中能正常加载DEEPL（内置）

**Comment by lmk123** [comment]
我确实没有多余的精力来兼容 Chrome / Edge 之外的浏览器了 :joy:

p.s. 如果你购买了套餐包，你可以勾选不带“内置”的【DeepL】使用

**Comment by lmk123** [comment]
你好 @Zyt221 ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
