### ISSUE TITLE
chrome商店中，右键选则翻译按钮无法弹出独立翻译窗口，时隔2年多又再次出现相同bug

### ISSUE THREAD

**Issue by shinesky** [hcfyapp/crx-selection-translate#2170]
## 基本信息

划词翻译版本：11.4.0
浏览器版本：百分浏览器 版本 5.1.1130.129（正式版本） （64 位） (Portable) (Chromium 118.0.5993.159)
操作系统：win10 专业版 22H2 

## 重现问题的步骤

在chrome商店中，随便选中一段文字，选则右键翻译按钮无法弹出独立翻译窗口。
必须得手动禁用划词翻译扩展，然后再重新开启，才可以右键弹出独立翻译窗口。
如果chrome商店界面刷新或者进入其他扩展窗口，仍然得再次重新开关闭划词翻译，才能使用右键翻译按钮。
2年之前我反应过这个Bug，后来修复了，这次无意使用当中又发现了，有点尴尬，动态图我就不录了，看原帖吧https://github.com/hcfyapp/crx-selection-translate/issues/1377

### 预期行为
会弹出独立翻译窗口

### 实际行为
不会弹出，需要手动开关闭一次划词翻译，再使用该功能才会弹出。

**Comment by lmk123** [comment]
感谢反馈，已在下个版本中修复此问题

**Comment by lmk123** [comment]
你好 @shinesky   ，我想邀请你加入【划词翻译 Next】的内测群。（如果打扰到你了，先道个歉 :joy:

我们最近从零开发了【划词翻译 Next】，想邀请一批长期使用划词翻译的用户做内部测试，内测群里的需求会被优先考虑，我们非常期待你的反馈和建议！

【划词翻译 Next】是一款以 AI 为主的翻译插件，目的是在保留原划词翻译的优点的情况下，实现简单、美观的使用体验。进群二维码：

<img width="606" alt="Image" src="https://github.com/user-attachments/assets/77d964d2-eb4a-4c49-ab74-3da79a0c6436" />
