### ISSUE TITLE
chrome浏览器里打开pdf 无法进入翻译pdf阅读了

### ISSUE THREAD

**Issue by SericWong** [hcfyapp/crx-selection-translate#2171]
## 基本信息
之前是可以的，最近不行了 打开pdf后显示如下：
![QQ_1733278598795](https://github.com/user-attachments/assets/7d517599-3f16-468c-a1be-c5c1df1e6141)

z总是找不到页面
划词翻译版本：最新版本
浏览器版本：最新版本
操作系统：mac

## 重现问题的步骤

1.
2.
3.

**Comment by lmk123** [comment]
麻烦提供更多信息来帮助我重现这个问题。

1. 你所使用的浏览器的版本号
2. 你的操作系统，windows 还是 macos
3. 你这个 pdf 是用哪种方式打开的？
    - 如果是点击了网页上某个指向 pdf 文件的链接，那么麻烦提供一下具体链接
    - 如果是将 pdf 文件拖放进了浏览器，那么麻烦提供一下 pdf 文件（另外我自己在 macos chrome 128 上拖放文件进去了，是正常的

**Comment by SericWong** [comment]
https://arxiv.org/pdf/2412.01253 arxiv在我这稳定复现，
chrome版本 131.0.6778.108（正式版本） (arm64)

**Comment by lmk123** [comment]
我把我的 macos chrome 升级到了最新版本 131.0.6778.10**9**（正式版本） (arm64)，跟你的版本就最后一个数字不同，但是在我这是正常的，重现视频附在末尾。

你可以尝试：

- 把其它插件全都关闭、仅保留划词翻译再试一下
- 卸载划词翻译后，重启浏览器再重新安装划词翻译，然后再试一下
- 把 PDF 页面的 DOM 结构截图我看一下（我这边的 DOM 结构截图附在末尾

附：重现视频

https://github.com/user-attachments/assets/7745223f-49d6-4315-9acb-4aae9b77837b

附：我这边的 PDF 网页 DOM 结构截图

![image](https://github.com/user-attachments/assets/6affdb69-5daf-43ec-b76c-5ca5cd0a8437)

**Comment by SericWong** [comment]
我卸载了其他几个插件，现在可以使用了，不知道和其中哪个插件冲突了
