### ISSUE TITLE
能否直接在输入法上进行划词并引流

### ISSUE THREAD

**Issue by lubyih** [hcfyapp/crx-selection-translate#2176]
希望在输入法(微软或者rime)上直接使用划词插件，也就是输入后在**候选词中**自动开启翻译功能，并弹出搜索键，或者通过快捷键搜索

**Comment by lmk123** [comment]
这需要一个对本地应用开发很熟悉的人修改输入法的功能，甚至是微软或 rime 本身要提供这个能力（例如插件能力），允许其他代码修改它的行为。

然而我完全不懂本地应用开发 :joy:
