### ISSUE TITLE
希望在'鼠标移动后自动关闭面板'的功能附加一个"同时文本高亮的部分也不再高亮"的可选项

### ISSUE THREAD

**Issue by SinbereeGit** [hcfyapp/crx-selection-translate#2179]
**没有这个功能（改进）的时候，你遇到了什么问题？**
当我选择了"鼠标移动后自动关闭面板"的功能后, 当我移动鼠标的时候, 的确, 翻译面板消失了, 但是由于选中翻译的文本仍然是高亮的, 这比较影响观感, 并且意味着我还是要点击一次屏幕来把高亮取消, 如果能同时取消高亮体验就很棒了.

**你想要如何解决你的问题？**
在'鼠标移动后自动关闭面板'的功能附加一个"同时文本高亮的部分也不再高亮"的可选项, 这样在仍然兼容原来设置的同时增加了这个舒适的功能.

**如果想要的解决方案无法实现，你觉得还有什么办法你是可以接受的？**
觉得作者应该能很容易地实现这个小功能

**补充信息**
none

**Comment by lmk123** [comment]
很好的提议，预计在近几个版本中加入

**Comment by lmk123** [comment]
v11.5.0 加了这个功能，但是没有做成一个新的选项，而是默认在关闭弹窗的同时就会清除高亮文本
