### ISSUE TITLE
收藏夹的翻译内容希望能导出数据

### ISSUE THREAD

**Issue by keashem** [hcfyapp/crx-selection-translate#860]
## 功能简介
收藏夹的有些翻译的词汇希望能进行数据的导出，方便之后的单词复习。

## 为什么你觉得需要（改进）这个功能？
收藏的单词能导出的话可以结合其他的一些背单词App来背单词。

**Comment by gnu4cn** [comment]
原来两年前就有人提过......

**Comment by twcctop** [comment]
+1  希望加上这个功能

**Comment by weicao** [comment]
+1

**Comment by lmk123** [comment]
下个版本 v10.4.0 已添加导出为 json 和 csv 的功能，如果有更具体的需求，可以再提。

cc #1760
