### ISSUE TITLE
网页翻译应当能选择源语种和目标语种

### ISSUE THREAD

**Issue by lmk123** [hcfyapp/crx-selection-translate#943]
## 功能简介
目前源语种和目标语种都是自动检测的，但部分网站内检测不成功，所以需要提供自定义源语种和目标语种的功能，就像翻译面板里的一样。

**Comment by Lirry-LR** [comment]
内置pdf阅读器应具备简单的标注功能

**Comment by Mosney** [comment]
当同时存在多个语言的网页时网页全文翻译会仅提取其中一种做翻译，并且翻译的目标语言是此页面存在的另一种语言，此时如果想要翻译成非页面语言就会非常的麻烦，至少我没有发现在网页全文翻译中有什么办法规避，只能部分选取后用划词翻译。
我觉得指定源语言和目标语言是一个翻译软件最基本的功能，虽然自动识别已经可以应对大部分使用场景，但只要还存在1%的场景无法覆盖就不应该完全摒弃手动指定翻译语言，至少也留一个开关可供开启，否则对于这1%的情况来说翻译功能是完全不可用的

**Comment by lmk123** [comment]
我正在尝试解决全文翻译在多语言混合的网页中出现英译英的问题，目前已收集到这些网址会有此问题：

- https://groups.google.com/g/rl-list/c/rv92nGy0YRk?pli=1
- https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/fbp-and-fbc
- https://www.linkedin.com/company/supabase
- https://www.youtube.com/watch?v=t5CIs0jDqC8&ab_channel=CrunchyrollCollection
- https://www.udemy.com/course/absolute-clarity-a-game-plan-for-lasting-self-fulfilment-and-happiness/

我将在修复此问题后更新此 issue

**Comment by lmk123** [comment]
v8.7.7 版本将给全文翻译加入源语种和目标语种选项。当在多语言混合的页面出现英译英的问题时，将源语种设置为英语即可解决此问题，如下图：

![yyy](https://user-images.githubusercontent.com/5035625/190401225-26d65094-d034-495d-b884-0cd4a5676dd9.gif)

**Comment by lmk123** [comment]
v8.7.7 现已提交审核，审核通过前可以通过离线安装包安装，见 https://hcfy.app/docs/install/#offline

**Comment by families** [comment]
怎么选目标语种？不能设置成源语种为自动检测，目标语种为中文吗？我只想把同一个页面中的各国语言全转中文就行了，最新版还是没有解决这个问题，如果页面有十几个国家的语种评论，你设置源语种为英文有什么用？设置第一，第二目标语种这个功能很鸡肋，就不能把检测语种这个直接交给谷歌，百度这些官方服务器识别吗？不管什么语种全丢给谷歌官方，保证目标输出为中文就行了，这才是重点功能。

**Comment by lmk123** [comment]
@families 

> 怎么选目标语种？

在设置页可以设置

> 不能设置成源语种为自动检测，目标语种为中文吗？

这就是默认设置，但是这种设置还是会出现在中英文混合的页面中英译英的问题，所以需要手动将源语种选择为英语

> 就不能把检测语种这个直接交给谷歌，百度这些官方服务器识别吗？不管什么语种全丢给谷歌官方，保证目标输出为中文就行了，这才是重点功能。

你似乎很自信的判断这是个很简单的问题。我给你解释一下这个问题的前因后果，你教一下我该怎么办吧。

你所说的本来就是默认设置——源语种默认为自动检测，翻译结果默认为中文。但是，**这些翻译服务不支持多语种的翻译**，即使将源语种设为了“自动检测”，它们也只会把所有文本识别为同一个语种，即无论一段文本里有多少个语种，都只会全部当作其中的一种来处理，这才是出现多语言混合页面问题的主要原因。

你可以自己试一下，在 https://translate.google.cn 里，将源语种设为【检测语言】，目标语种设为【中文简体】，然后文本框里输入”I love you. 我爱你。”，你看看翻译结果是什么。

以下是我这边出来的翻译结果。注意看，这段中英文混合的文本被谷歌识别成了中文。考虑到你可能看不到图片，我这里告诉你谷歌翻译的翻译结果——翻译结果仍然是”I love you. 我爱你。”

<img width="497" alt="截屏2022-09-17 18 22 24" src="https://user-images.githubusercontent.com/5035625/190852057-85b47535-335d-4998-a07e-1fb27a366217.png">


网页全文翻译的原理是将网页里的所有文本合并成了一段文本交给了翻译服务，如果想要解决十几个语种的翻译问题，那就不能将文本合并起来、而是一句一句的翻译，但这样一来，一个网页就会需要成百上千次的翻译服务调用，但这些翻译服务不允许短时间内频繁调用，会出现 429 错误。

”不管什么语种全丢给谷歌官方，保证目标输出为中文就行了”，这话说起来很简单，但是该怎么做？黑进谷歌翻译的服务器改它们的代码吗 :joy:

我目前能想到的就是通过改变源语种来解决中英文混合的情况。看起来你很自信你能解决这个问题，请教一下我该怎么解决十几个语种的情况。

**Comment by families** [comment]
> @families
> 
> > 怎么选目标语种？
> 
> 在设置页可以设置
> 
> > 不能设置成源语种为自动检测，目标语种为中文吗？
> 
> 这就是默认设置，但是这种设置还是会出现在中英文混合的页面中英译英的问题，所以需要手动将源语种选择为英语
> 
> > 就不能把检测语种这个直接交给谷歌，百度这些官方服务器识别吗？不管什么语种全丢给谷歌官方，保证目标输出为中文就行了，这才是重点功能。
> 
> 你似乎很自信的判断这是个很简单的问题。我给你解释一下这个问题的前因后果，你教一下我该怎么办吧。
> 
> 你所说的本来就是默认设置——源语种默认为自动检测，翻译结果默认为中文。但是，**这些翻译服务不支持多语种的翻译**，即使将源语种设为了“自动检测”，它们也只会把所有文本识别为同一个语种，即无论一段文本里有多少个语种，都只会全部当作其中的一种来处理，这才是出现多语言混合页面问题的主要原因。
> 
> 你可以自己试一下，在 https://translate.google.cn 里，将源语种设为【检测语言】，目标语种设为【中文简体】，然后文本框里输入”I love you. 我爱你。”，你看看翻译结果是什么。
> 
> 以下是我这边出来的翻译结果。注意看，这段中英文混合的文本被谷歌识别成了中文。考虑到你可能看不到图片，我这里告诉你谷歌翻译的翻译结果——翻译结果仍然是”I love you. 我爱你。”
> 
> <img alt="截屏2022-09-17 18 22 24" width="497" src="https://user-images.githubusercontent.com/5035625/190852057-85b47535-335d-4998-a07e-1fb27a366217.png">
> 
> 网页全文翻译的原理是将网页里的所有文本合并成了一段文本交给了翻译服务，如果想要解决十几个语种的翻译问题，那就不能将文本合并起来、而是一句一句的翻译，但这样一来，一个网页就会需要成百上千次的翻译服务调用，但这些翻译服务不允许短时间内频繁调用，会出现 429 错误。
> 
> ”不管什么语种全丢给谷歌官方，保证目标输出为中文就行了”，这话说起来很简单，但是该怎么做？黑进谷歌翻译的服务器改它们的代码吗 😂
> 
> 我目前能想到的就是通过改变源语种来解决中英文混合的情况。看起来你很自信你能解决这个问题，请教一下我该怎么解决十几个语种的情况。


   你好，看了你介绍的网页全文翻译的原理，让我明白了对于3个及以上语种的页面想要一步到位翻译成中文确实比较棘手，目前没想到更好的方法解决此问题，只是有个小想法大概说一下，有没有必要得由你自己评估一下：
   我看插件能够在双语模式下给译文加上虚线边框，是否能够在鼠标悬浮在某一个边框内时，在边框区域的左上角出现一个按钮，点一下后，一键将该边框内的译文所对应的原文再次单独打包发送给谷歌等服务器翻译一遍，并将返回的新译文替换掉之前边框内的老译文，能够使用鼠标配合快捷键完成上面操作更好。当然，这只是为了简化一下，避免对于无法正确翻译的语句频繁地手动使用鼠标划词进行翻译。

**Comment by LoopholesInTheHeart** [comment]
刚看到可以在网页手动设置源语言为英语, 并且在网页里测试了确实可以, 
但是感觉和在谷歌翻译页面测试的结果不同? 谷歌翻译页面设置源语言英语不会执行翻译,
