### ISSUE TITLE
希望添加一个highlight的功能

### ISSUE THREAD

**Issue by xpgege** [hcfyapp/crx-selection-translate#970]
## 功能简介
希望能在内置pdf阅读器中添加highlight功能便于标注和做笔记
## 为什么你觉得需要（改进）这个功能？
在阅读文献的过程中，有时候看到重点的部分需要highlight，但是内置pdf阅读器中没有这个功能偶尔感觉很不方便。

最近新添加的维基百科功能也很好用，希望这个插件能越做越好，非常感谢！

**Comment by alex6521** [comment]
十分同意，对于科研狗这一功能很有必要

**Comment by lmk123** [comment]
已加入开发计划当中

**Comment by LI-EM-Rj** [comment]
个人觉得不一定要在划词翻译pdf阅读器里内置标注功能；主要是edge自带的pdf阅读器内无法触发已设置的快捷翻译，个人觉得只要改进edge自带阅读器内的翻译体验就好

**Comment by lmk123** [comment]
@LI-EM-Rj 浏览器自带阅读器是受到浏览器保护的，扩展程序没法获取你在自带阅读器里划选的文本，所以只有以下两种方式可以使用：

- 划选文本后，打开右键菜单并选择“翻译这段文本”
- 划选文本后复制，然后使用快捷键打开独立翻译窗口

这两个方法都比较不方便，但是受限于浏览器的保护，所以也没法进一步改进翻译体验了。

**Comment by lmk123** [comment]
即将发布的 v9.1.0 已支持添加标注与划线，并且可以导出带有标注和划线的 PDF。
